"""Row 36 — accessibility trees, and the decisions a navigator makes on them.

The state is a page as an accessibility tree, rendered as JSON. That is the shape a
browser harness already has: roles and names, not pixels and not raw HTML, which is an
order of magnitude fewer tokens and carries the semantics a click decision needs.

Three question families, each a decision a navigator actually makes:

    click_target     the goal and the page -> which control advances toward it
    goal_reached     is the goal already satisfied here, or is another hop needed
    field_for_value  a value to enter -> which field takes it

The pages are generated rather than captured, for two reasons. The navigation tier of
the Decision Index benchmark is scored on a Wikipedia link graph, so training on real pages
from the same web would contaminate the thing it measures. And a generator can hold out
whole *layout families*, which is the split that told us anything about rule transfer:
holding out individual pages leaks, because pages of one layout are near-duplicates of each
other.

`HELDOUT_LAYOUTS` never enter training. They are built from the same controls as the
trained layouts and differ only in how those controls are arranged, so a drop on them
is a failure to generalise over structure rather than a missing widget. `DEV_LAYOUTS` are
a second, disjoint pair of arrangements built the same way, held out of training *and* of
test, for `devreal`: the split that selects checkpoints and fits T then measures transfer
over layout the way test does, without reading test's layouts.

Option counts are drawn wide on purpose. 63 % of the rest of the corpus is binary, and a
page is the natural place to learn that a choice can have eighty candidates.

Pages are built to *fit the state budget*. `ship_v4.sh` trains at `--max-state-tokens
2304`, and `packing.Packer` truncates a long state from the tail, keeping the head. A page
whose gold control sits past the cut is an example whose evidence the model never sees --
it teaches guessing, and it depresses the held-out-layout reading for a reason that has
nothing to do with structure. Measured on the first build, 13 % of `click` lost its gold
control that way. So the tree is rendered compactly and `build_page` narrows the record
count until the rendered state fits `MAX_STATE_CHARS`. The ceiling on option count is
therefore what a page can *show*, not what a draw can name.
"""

from __future__ import annotations

import hashlib
import json
import random
from typing import Iterator

from lod.phrasings import PhrasingBank
from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/browser.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/browser.py"
ROW = 36

TRAINED_LAYOUTS = ("search_results", "article", "settings_form", "nav_menu", "data_table")
HELDOUT_LAYOUTS = ("wizard", "modal_dialog", "paginated_table")
# held out of train and test; the dev split's own unseen arrangements of trained roles
DEV_LAYOUTS = ("tabbed_panels", "accordion")
LAYOUTS = TRAINED_LAYOUTS + HELDOUT_LAYOUTS + DEV_LAYOUTS

TOPICS = ("billing", "shipping", "account", "security", "reports", "inventory",
          "messages", "calendar", "devices", "integrations", "audit", "payroll",
          "contracts", "suppliers", "tickets", "releases", "budgets", "permissions")
NOUNS = ("invoice", "order", "profile", "password", "export", "shipment", "thread",
         "event", "printer", "webhook", "entry", "payslip", "contract", "supplier",
         "ticket", "release", "budget", "role", "mailbox", "dashboard")
# Site names are compounds, so a page of eighty records can name eighty sites without
# numbering them. It used to be twelve cities, then "<city> <i>" -- and `i` was the
# record's position on the page, so a goal naming "Calder Bay 13" would have given its
# answer away by index. (`_click_target`'s substring guard happened to drop every such
# goal, which in turn meant a Site goal on a page wider than twelve records always pointed
# into the first twelve.) No prefix is a prefix of another and no suffix of another, so no
# site name is a substring of a different one.
SITE_HEADS = ("Ash", "Birch", "Cold", "Dun", "Elm", "Fair", "Green", "Hart", "Iron",
              "Kings", "Lark", "Mill", "North", "Oak", "Red", "Stan", "West", "Wood")
SITE_TAILS = ("ford", "wick", "moor", "field", "bury", "ton", "gate", "haven", "mere",
              "ley", "stead", "well")
SITES = tuple(h + t for h in SITE_HEADS for t in SITE_TAILS)
# Owners are drawn without replacement from 19 x 40 names, so no two records on a page
# share one. With ten owners drawn with replacement, a goal could only name an owner who
# was unique on the page, and "pick a record whose Owner nobody else has" -- a reader who
# never looks at the value -- scored 0.49 on Owner goals against a 0.14 chance.
SURNAMES = ("Walsh", "Nkemdi", "Aaltonen", "Okonkwo", "Bergqvist", "Duval", "Marchetti",
            "Oyelaran", "Fairbairn", "Halvorsen", "Achterberg", "Brennan", "Castellano",
            "Dimitrov", "Esposito", "Fonseca", "Gallagher", "Haddad", "Iwasaki", "Jaramillo",
            "Kowalczyk", "Lindqvist", "Mbeki", "Nakamura", "Ostrowski", "Petrakis",
            "Quinlan", "Rautio", "Sandoval", "Takahashi", "Umarov", "Varga", "Whitlock",
            "Xiong", "Yilmaz", "Zielinski", "Abernethy", "Bhattacharya", "Cavanagh",
            "Delacroix")
OWNERS = tuple(f"{c}. {n}" for n in SURNAMES for c in "ABCDEFGHJKLMNPRSTVW")
# Not "open": every control is labelled "Open <ref>", so a goal naming Status 'open' matched
# every record to a case-blind reader (4.4 % of click questions).
STATUSES = ("active", "pending", "settled", "on hold", "cancelled", "escalated")

# One pool of page titles for every layout. Titles used to name the layout -- "Billing
# wizard", "Search results for billing", "Billing table", "Billing settings" -- and the
# goal of `goal_reached` describes the layout, so "does a title word occur in the goal"
# scored 0.81 on that question against a 0.50 chance, and it would have carried straight
# over to the held-out layouts ("X wizard", "X log") without reading any structure.
TITLE_FORMS = ("{T}", "{T} | Console", "Console / {T}", "{T} workspace", "{T} overview")


def _title(rng: random.Random, topic: str) -> str:
    return rng.choice(TITLE_FORMS).format(T=topic.title())


def _rng(seed: int, salt: str) -> random.Random:
    return random.Random(f"{seed}:{salt}")


def _node(role: str, name: str, **kw) -> dict:
    n = {"role": role, "name": name}
    n.update(kw)
    return n


def _slugify(text: str) -> str:
    return "".join(c.lower() if c.isalnum() else "-" for c in text).strip("-")


# ---- layouts -----------------------------------------------------------------
# Each returns (tree, controls). `controls` is the flat list of clickable nodes in
# document order; the question families index into it, so a layout only has to say
# what is on the page and where.

def _entries(rng: random.Random, n: int, topic: str) -> list[dict]:
    """n records, each an opaque control plus the attributes that identify it.

    The control label carries a reference number and nothing else. What distinguishes one
    record from another lives in sibling nodes, so a goal that names an attribute cannot
    be answered by matching the goal against the option list.
    """
    refs = rng.sample(range(1000, 9999), n)
    sites = rng.sample(SITES, n)
    owners = rng.sample(OWNERS, n)
    # Whether a record's control leads or trails its attributes, drawn once per page. Every
    # layout used to put the control last, so "the first link after the named value in the
    # serialised state" picked the gold on 100 % of `click` questions, held-out layouts
    # included (measured by a shortcut audit) -- a reader that never finds the
    # record's container scored what one that does scores, and the held-out split measured
    # nothing about arrangement. Now that proxy is right on trailing pages and wrong on
    # leading ones, and only the container says which control is the record's.
    lead = rng.random() < 0.5
    out = []
    for i in range(n):
        out.append({
            "attrs": {"Site": sites[i], "Owner": owners[i],
                      "Status": rng.choice(STATUSES), "Count": str(rng.randrange(1, 500))},
            "control": _node("link", f"Open {refs[i]}", href=f"/{topic}/{refs[i]}"),
            "noun": rng.choice(NOUNS),
            "lead": lead,
        })
    return out


def _with_control(e: dict, nodes: list[dict]) -> list[dict]:
    """A record's children: its attribute nodes, with the control before or after them."""
    return [e["control"], *nodes] if e["lead"] else [*nodes, e["control"]]


def _links(rng: random.Random, n: int, topic: str) -> list[dict]:
    return [e["control"] for e in _entries(rng, n, topic)]


def _describe(e: dict) -> str:
    return f"{e['noun']} for {e['attrs']['Owner']}, {e['attrs']['Status']}"


def _search_results(rng, topic, entries):
    items = [_node("listitem", "", children=_with_control(e, [
        _node("heading", e["attrs"]["Site"], level=3),
        _node("paragraph", _describe(e))])) for e in entries]
    return _node("document", _title(rng, topic), children=[
        _node("heading", f"{len(entries)} found", level=1),
        _node("region", topic, children=[_node("list", topic, children=items)])])


def _article(rng, topic, entries):
    body = [_node("heading", f"About {topic}", level=1),
            _node("paragraph", f"This page describes how {topic} works in the console.")]
    for i, e in enumerate(entries):
        # Unnamed: a group named after the Site above a heading naming it again put the
        # value a goal names on the page twice (8 % of click questions, with modal_dialog).
        # Leading, the control is the heading's link; trailing, the paragraph's. Nested
        # either way, so the page's length does not say which (a bare leading control made
        # leading pages ~14 characters a record shorter, and the length bucket alone
        # predicted the gold's side of the value at 0.67).
        if e["lead"]:
            kids = [_node("heading", e["attrs"]["Site"], level=2, children=[e["control"]]),
                    _node("paragraph", _describe(e))]
        else:
            kids = [_node("heading", e["attrs"]["Site"], level=2),
                    _node("paragraph", _describe(e), children=[e["control"]])]
        body.append(_node("group", "", children=kids))
    return _node("document", _title(rng, topic), children=body)


def _settings_form(rng, topic, entries):
    # No `value: ""`: an absent value is an empty field, and at eighty fields the empty
    # strings cost ~400 characters of the state budget.
    fields = [_node("textbox", f"{e['noun'].title()} {i}") for i, e in enumerate(entries)]
    title = _title(rng, topic)
    return _node("document", title, children=[
        _node("heading", title, level=1),
        _node("tablist", "panels", children=[
            _node("tab", "General", selected=True), _node("tab", "Advanced")]),
        _node("form", topic, children=fields + [_node("button", "Save changes")]),
        _node("dialog", "Discard changes?", modal=False, children=[
            _node("button", "Keep editing")])])


def _nav_menu(rng, topic, entries):
    groups, per = [], max(1, len(entries) // 3)
    for g in range(0, len(entries), per):
        kids = [_node("menuitem", e["attrs"]["Site"], children=_with_control(e, [
            _node("paragraph", _describe(e))])) for e in entries[g:g + per]]
        groups.append(_node("menu", rng.choice(TOPICS).title(), children=kids))
    return _node("document", _title(rng, topic), children=[
        _node("navigation", "main", children=groups)])


def _data_table(rng, topic, entries):
    cols = ["Site", "Owner", "Status", "Count"]
    cols = ["Action", *cols] if entries and entries[0]["lead"] else [*cols, "Action"]
    head = _node("row", "", children=[_node("columnheader", h) for h in cols])
    rows = [_node("row", "", children=_with_control(e, [
        _node("cell", e["attrs"]["Site"]), _node("cell", e["attrs"]["Owner"]),
        _node("cell", e["attrs"]["Status"]), _node("cell", e["attrs"]["Count"])]))
        for e in entries]
    return _node("document", _title(rng, topic), children=[
        _node("region", topic, children=[
            _node("table", topic, children=[head] + rows)])])


def _wizard(rng, topic, entries):  # held out
    steps = [_node("tab", f"Step {i + 1}", selected=(i == 1)) for i in range(3)]
    items = [_node("group", e["attrs"]["Site"], children=_with_control(e, [
        _node("paragraph", _describe(e))])) for e in entries]
    return _node("document", _title(rng, topic), children=[
        _node("tablist", "steps", children=steps),
        _node("group", "body", children=items),
        _node("button", "Back"), _node("button", "Next")])


def _modal_dialog(rng, topic, entries):  # held out
    # `group`, not `list`/`listitem`: this layout used to build items byte-identical to
    # `_search_results`' -- heading, paragraph, link, inside a list -- so a modal page
    # satisfied "a list of search results" as well as its own content string. 296 of
    # `browser_goal_modal_dialog`'s 4,000 questions in an earlier build were labelled `no`
    # for a goal the page did in fact show. `listitem` is now unique to `_search_results`.
    items = [_node("group", "", children=_with_control(e, [
        _node("heading", e["attrs"]["Site"], level=3),
        _node("paragraph", _describe(e))])) for e in entries]
    # The paragraph behind the dialog used to read "The page behind the dialog is inert.",
    # which is the goal string's own words; `modal: true` is what says so.
    return _node("document", _title(rng, topic), children=[
        _node("paragraph", f"This page describes how {topic} works in the console."),
        _node("dialog", "Choose a destination", modal=True, children=[
            _node("heading", "Choose a destination", level=2),
            _node("group", "destinations", children=items),
            _node("button", "Cancel")])])


def _paginated_table(rng, topic, entries):  # held out
    # Every `ATTRS` entry has to be on the page. This layout rendered Site and Owner only,
    # so a quarter of `browser_click_paginated_table` (972 of 4,000 in an earlier build)
    # asked for the record whose Status was some value the tree never showed -- an example
    # whose answer the state does not contain, on the held-out side, where it is read as a
    # failure to generalise over layout.
    per, pages = max(1, len(entries) // 3), []
    for i in range(0, len(entries), per):
        rows = [_node("row", "", children=_with_control(e, [
            _node("cell", e["attrs"]["Site"]), _node("cell", e["attrs"]["Owner"]),
            _node("cell", e["attrs"]["Status"])])) for e in entries[i:i + per]]
        pages.append(_node("region", f"Page {len(pages) + 1}",
                           children=[_node("table", topic, children=rows)]))
    return _node("document", _title(rng, topic), children=pages + [
        _node("navigation", "pagination", children=[
            _node("button", "Previous"), _node("button", "Next")])])


def _sections(rng, topic, entries) -> list[tuple[str, list[dict]]]:
    """The records split into two to four named sections, named after distinct topics.
    No topic word occurs in a site, an owner or a status, so a section name never
    collides with a value a goal names."""
    k = min(len(entries), rng.randint(2, 4))
    per = -(-len(entries) // k)
    names = [t.title() for t in rng.sample(TOPICS, k)]
    return [(names[i], entries[i * per:(i + 1) * per]) for i in range(k)
            if entries[i * per:(i + 1) * per]]


def _tabbed_panels(rng, topic, entries):  # held out of train and test (dev)
    # One tab per section and one region per tab, named alike: the pairing is what the
    # page shows. The settings form's two tabs and the wizard's steps have no region.
    secs = _sections(rng, topic, entries)
    on = rng.randrange(len(secs))
    tabs = [_node("tab", name, selected=(i == on)) for i, (name, _) in enumerate(secs)]
    panels = [_node("region", name, children=[
        _node("group", "", children=_with_control(e, [
            _node("heading", e["attrs"]["Site"], level=3),
            _node("paragraph", _describe(e))])) for e in recs]) for name, recs in secs]
    return _node("document", _title(rng, topic), children=[
        _node("tablist", "sections", children=tabs), *panels])


def _accordion(rng, topic, entries):  # held out of train and test (dev)
    # A button per section carrying `expanded`, then that section's region. No heading
    # anywhere, so the page is not an article; one or two collapsed sections carry no
    # region, as a real accordion's closed sections do.
    secs = _sections(rng, topic, entries)
    items = [[_node("button", name, expanded=True),
              # the Site is a paragraph beside the control, not the group's name: a name
              # always precedes the children, which put the gold after the value on 0.76
              # of click questions (shortcut audit, "first link after value")
              _node("region", name, children=[
                  _node("group", "", children=_with_control(e, [
                      _node("paragraph", e["attrs"]["Site"]),
                      _node("paragraph", _describe(e))])) for e in recs])]
             for name, recs in secs]
    used = {n for n, _ in secs}
    for name in rng.sample([t.title() for t in TOPICS if t.title() not in used],
                           rng.randint(1, 2)):
        items.insert(rng.randrange(len(items) + 1), [_node("button", name, expanded=False)])
    return _node("document", _title(rng, topic),
                 children=[n for item in items for n in item])


_LAYOUTS = {"search_results": _search_results, "article": _article,
            "settings_form": _settings_form, "nav_menu": _nav_menu,
            "data_table": _data_table, "wizard": _wizard,
            "modal_dialog": _modal_dialog, "paginated_table": _paginated_table,
            "tabbed_panels": _tabbed_panels, "accordion": _accordion}

# What each layout's tree contains, for the content-based goal of `goal_reached`. Each
# string must be true of its own layout and false of every other, so the label is decidable
# from the tree alone -- that is why they name a feature (Back and Next, numbered pages,
# column headers) rather than a container role, which several layouts now share.
LAYOUT_CONTENT = {
    "search_results": "a list of search results",
    "article": "an article with section headings",
    "settings_form": "a settings form with editable fields",
    "nav_menu": "a navigation menu of grouped links",
    "data_table": "a table of records with column headers",
    "wizard": "a multi-step wizard with Back and Next buttons",
    "modal_dialog": "a modal dialog over a page that is inert behind it",
    "paginated_table": "a log table split across numbered pages",
    # at least two regions each named like a tab of a tablist
    "tabbed_panels": "a row of tabs, each with its own panel of records",
    # at least two buttons that carry an expanded state
    "accordion": "an accordion of sections that expand and collapse",
}


def _decoy(of: str, host: str, rng: random.Random, topic: str) -> list[dict]:
    """A near-miss of layout `of`: the words its content string shares with its own page,
    on nodes that do not make the page show it.

    Each content string names features, and on the undecorated pages those features' words
    occurred nowhere else: "the fraction of the goal's words found anywhere in the JSON"
    separated yes from no on **1.000** of the held-out goal questions and 0.89 of the
    trained ones (measured by a shortcut audit). A keyword matcher fitted on the
    trained layouts and applied to the held-out ones scored 0.755 on `paginated_table` --
    where the models swing, 0.69 / 0.75 / 0.54 -- because that page's Next button half-
    matches the wizard's goal. With these fragments a page can carry the words and not the
    structure (a non-modal dialog, a one-page table, a Back *link*), so only reading the
    structure decides. Every fragment is outside `LAYOUT_CONTENT[of]` by the independent
    readers of the domain-14 audit and the tests, and uses only trained roles.
    """
    t = topic.title()
    if of == "search_results":
        return [_node("button", "Show as list", pressed=False)]   # a view toggle, no list
    if of == "article":
        return [_node("heading", t, level=1)]                     # one heading, no sections
    if of == "settings_form":                                     # a form with no fields
        return [_node("form", "Subscription", children=[_node("button", "Unsubscribe")])]
    if of == "nav_menu":                          # a breadcrumb and a collapsed menu button
        return [_node("navigation", "breadcrumb",
                      children=[_node("link", "Home"), _node("link", t)]),
                _node("button", "Menu", expanded=False)]
    if of == "data_table":
        return [_node("button", "Show as table", pressed=False)]  # a view toggle, no table
    if of == "wizard":                                            # no Back button, no steps
        out = [_node("link", f"Back to {t}"), _node("link", "Step-by-step guide")]
        if host != "paginated_table":                             # which has Next already
            out.append(_node("button", "Next"))
        return out
    if of == "modal_dialog":                                      # a dialog, not modal
        return [_node("dialog", "Cookie preferences", modal=False, children=[
            _node("paragraph", "This page uses cookies."), _node("button", "Accept")])]
    if of == "tabbed_panels":                  # tabs with no panel named after either
        return [_node("tablist", "sections", children=[
            _node("tab", "Summary", selected=True), _node("tab", "Details")])]
    if of == "accordion":                      # one expandable control, not sections
        return [_node("button", "Expand all", expanded=False)]
    if of == "paginated_table":                                   # one page, not split
        rows = [_node("row", "", children=[_node("cell", s), _node("cell", rng.choice(STATUSES))])
                for s in rng.sample(SITES, rng.randint(2, 4))]
        return [_node("region", "Page 1 of 1", children=[_node("table", topic, children=rows)])]
    raise KeyError(of)


# Where a near-miss can only carry a goal's words in a *name* -- a view toggle, a menu
# button -- the real page gets the same control, in its true state, at the same rate.
# Otherwise those words would occur in names only on `no` pages, and "a word of the goal
# is in some name on the page" would predict `no` (the domain-14 audit's names-only
# baseline fell from 0.52 to 0.33 without these).
def _chrome(layout: str) -> list[dict]:
    if layout == "search_results":
        return [_node("button", "Show as list", pressed=True)]
    if layout == "data_table":
        return [_node("button", "Show as table", pressed=True)]
    if layout == "nav_menu":
        return [_node("button", "Menu", expanded=True)]
    if layout == "accordion":
        return [_node("button", "Expand all", expanded=True)]
    return []


# How often a `goal_reached` page carries a near-miss fragment. The same on `yes` pages
# (a sibling's fragment, which the goal does not name) as on `no` pages (the fragment of
# the layout the goal names), so the presence of a fragment says nothing on its own. The
# page's own `_chrome` is drawn at the same rate, independently of the label.
DECOY_RATE = 0.9


# `goal_reached`'s distractor pool. A page is contrasted with another layout on its own
# side of the holdout, never across it.
_SIBLINGS = {l: tuple(x for x in group if x != l)
             for group in (TRAINED_LAYOUTS, HELDOUT_LAYOUTS, DEV_LAYOUTS) for l in group}


# Wide on purpose: the rest of the corpus is 63 % binary questions.
WIDTHS = (2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 80)

# The rendered state must survive `packing.Packer` at `ship_v4.sh`'s `--max-state-tokens
# 2304`. Compact JSON of this tree runs 3.0-3.8 characters per Qwen token, so 6,600
# characters is ~2,170 tokens at the worst observed ratio -- inside 2,304 with headroom,
# and a character count needs no tokenizer inside a source module.
MAX_STATE_CHARS = 6600


def build_page(layout: str, rng: random.Random, decoy: str | None = None,
               chrome: bool = False) -> tuple[dict, list[dict], str]:
    """-> (accessibility tree, entries in document order, topic).

    The record count is drawn from `WIDTHS`, then narrowed to the widest value whose
    rendered page fits `MAX_STATE_CHARS`. Narrowing slices `entries`, which keeps every
    surviving record exactly as it was drawn -- sites stay unique, refs stay unique.

    `decoy` names another layout whose near-miss fragment (`_decoy`) is placed among the
    page's top-level nodes, and `chrome` adds the page's own `_chrome`; `goal_reached`
    uses both, `click` neither.
    """
    topic = rng.choice(TOPICS)
    entries = _entries(rng, rng.choice(WIDTHS), topic)
    extra = _decoy(decoy, layout, rng, topic) if decoy else []
    if chrome:
        extra = _chrome(layout) + extra
    at = rng.random()
    while True:
        tree = _LAYOUTS[layout](rng, topic, entries)
        if extra:
            kids = tree["children"]
            i = round(at * len(kids))
            tree["children"] = kids[:i] + extra + kids[i:]
        if len(_state(tree)) <= MAX_STATE_CHARS or len(entries) <= WIDTHS[0]:
            return tree, entries, topic
        narrower = [w for w in WIDTHS if w < len(entries)] or [WIDTHS[0]]
        entries = entries[:narrower[-1]]


# ---- question families -------------------------------------------------------

def _prune(n: dict) -> dict:
    """Drop what costs tokens and carries nothing: an empty accessible name, and `href`,
    which only restates the reference number already in the control's name."""
    out = {"role": n["role"]}
    if n.get("name"):
        out["name"] = n["name"]
    for k, v in n.items():
        if k not in ("role", "name", "children", "href"):
            out[k] = v
    if n.get("children"):
        out["children"] = [_prune(c) for c in n["children"]]
    return out


def _state(tree: dict) -> str:
    return json.dumps(_prune(tree), separators=(",", ":"), ensure_ascii=False)


ATTRS = ("Site", "Owner", "Status")

# Question wording goes through the phrasing bank (`lod/assets/phrasing_specs/d14.json`
# holds the specs). With an empty bank `pick` returns the template unchanged. The
# instructions carry the per-example facts -- the attribute and value, the content
# string, the value and section -- as placeholders, so a phrasing can reword around them
# and never change them.
CLICK_Q = ("d14.click_question", "Which control should the agent activate next?")
CLICK_I = ("d14.click_instructions",
           "Open the record whose {attr} is '{value}'. Pick the control that belongs to "
           "that record.")
GOAL_Q = ("d14.goal_question", "Is the goal already satisfied on this page?")
GOAL_I = ("d14.goal_instructions", "The goal is to reach a page that shows {want}.")
FIELD_Q = ("d14.field_question", "Which field should receive this value?")
FIELD_I = ("d14.field_instructions",
           "The value to enter is '{value}'. It belongs in the {section} section of the "
           "form.")
_BANK: PhrasingBank | None = None


def _phrase(spec: tuple[str, str], key: str, **slots) -> str:
    global _BANK
    if _BANK is None:
        _BANK = PhrasingBank.load()
    template_id, template = spec
    return _BANK.pick(template_id, template, key).format(**slots)


def _click_target(layout: str, rng: random.Random, qid: str) -> Example | None:
    """The goal names an attribute. The control labels are opaque reference numbers, so
    the answer is only reachable by reading which control sits beside that attribute."""
    tree, entries, topic = build_page(layout, rng)
    if len(entries) < 2:
        return None
    attr = rng.choice(ATTRS)
    values = [e["attrs"][attr] for e in entries]
    # Every record's value of the named attribute is distinct, not merely the gold's. When
    # only the gold had to be unique, the gold was the one record whose value nobody else
    # shared, and a reader who ignored the value and picked such a record scored 0.64 on
    # Status goals against a 0.19 chance. Six statuses means a Status goal only lands on a
    # page of six records or fewer with no status repeated; the other two attributes are
    # distinct by construction.
    if len(set(values)) != len(values):
        return None
    gold = rng.randrange(len(values))
    options = [e["control"]["name"] for e in entries]
    if len(set(options)) != len(options):
        return None
    state = _state(tree)
    # THE INVARIANT, enforced here rather than trusted: the goal names an attribute value,
    # so a layout that does not render that attribute makes the question unanswerable from
    # the state. `test_every_layout_renders_every_attribute_a_goal_can_name` is the
    # structural form of the same check; this is the per-example one, and it drops rather
    # than guesses.
    if values[gold] not in state:
        return None
    # A value contained in another record's value ("Oak" in "Oakley") is only unambiguous
    # to a reader who compares whole values. Drop rather than rely on that -- and compare
    # case-blind, which is what caught Status 'open' against every "Open <ref>" control.
    low = values[gold].lower()
    if any(i != gold and (low in v.lower() or v.lower() in low) for i, v in enumerate(values)):
        return None
    if any(low in o.lower() for o in options):
        return None
    key = f"{layout}:{qid}"
    q = Question(
        id=qid, question=_phrase(CLICK_Q, key),
        instructions=_phrase(CLICK_I, key, attr=attr, value=values[gold]),
        options=options,
        # No per-option description: "link labelled 'Open 9391'" restates the option and
        # costs ~10 tokens of the 3,072 total budget each, which at 80 options drives the
        # state budget down from 2,304 to 1,515 and truncates the evidence away.
        target=gold,
        meta={"attr": attr, "value": values[gold]})
    return Example(task=f"browser_click_{layout}", state=state, questions=[q])


def _goal_reached(layout: str, rng: random.Random, qid: str) -> Example | None:
    """The goal describes what the page must contain. Neither the title nor any other
    name on the page says which layout it is (`TITLE_FORMS`); the roles do."""
    reached = rng.random() < 0.5
    if reached:
        want = LAYOUT_CONTENT[layout]
        other = rng.choice(_SIBLINGS[layout])
    else:
        # From this layout's own group, so that every content string appears as `yes` on
        # its own task and as `no` on its siblings in equal measure. Drawing from all
        # eight made the prior a function of which side of the holdout a string lived on:
        # a held-out layout's content only ever appeared in training as a `no`, so a
        # lookup fitted on an earlier build's train split and applied to `testreal_eval`
        # scored **0.1482** -- the shortcut is not merely present, it is inverted at eval.
        # It also keeps training free of the held-out layouts' descriptions entirely, which
        # is what a structural holdout was supposed to mean.
        other = rng.choice([x for x in _SIBLINGS[layout]])
        want = LAYOUT_CONTENT[other]
    # On a `no` page the fragment is the named layout's near-miss; on a `yes` page it is a
    # sibling's, which the goal does not name.
    decoy = other if rng.random() < DECOY_RATE else None
    tree, entries, topic = build_page(layout, rng, decoy=decoy,
                                      chrome=rng.random() < DECOY_RATE)
    key = f"{layout}:{qid}"
    q = Question(
        id=qid, question=_phrase(GOAL_Q, key),
        instructions=_phrase(GOAL_I, key, want=want),
        options=["no", "yes"],
        descriptions=["The page does not show that. Another step is needed",
                      "The page shows that"],
        target=int(reached),
        meta={"want": want})
    return Example(task=f"browser_goal_{layout}", state=_state(tree), questions=[q])


# What a field accepts, and a value of that shape. The kinds are mutually unmistakable on
# sight -- no value of one kind could be read as another -- because deciding *which* kind
# the value is is the first half of the question; finding the field that expects it, in
# the tree, is the second. No word of a kind's name occurs in its values.
_MONTHS = ("January", "February", "March", "April", "May", "June", "July", "August",
           "September", "October", "November", "December")
_DAYS = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
FIELD_KINDS: dict[str, "object"] = {
    "date": lambda rng: f"{rng.randrange(1, 29):02d} {rng.choice(_MONTHS)} 2026",
    "email address": lambda rng: f"{rng.choice(OWNERS).split()[-1].lower()}@example.com",
    "postcode": lambda rng: (f"{rng.choice('ABCDEFGH')}{rng.randrange(1, 99)} "
                             f"{rng.randrange(1, 9)}XT"),
    "phone number": lambda rng: f"01632 9601{rng.randrange(10, 99)}",
    "time of day": lambda rng: f"{rng.randrange(0, 24):02d}:{rng.randrange(0, 60):02d}",
    "amount in GBP": lambda rng: f"£{rng.randrange(1, 9999)}.{rng.randrange(0, 100):02d}",
    "amount in EUR": lambda rng: f"€{rng.randrange(1, 9999)}.{rng.randrange(0, 100):02d}",
    "percentage": lambda rng: f"{rng.randrange(1, 100)}.{rng.randrange(10)}%",
    "web address": lambda rng: (f"https://{rng.choice(TOPICS)}.example.org/"
                                f"{rng.choice(NOUNS)}"),
    "IP address": lambda rng: (f"10.{rng.randrange(256)}.{rng.randrange(256)}."
                               f"{rng.randrange(1, 255)}"),
    "colour code": lambda rng: f"#{rng.randrange(16 ** 6):06x}",
    "weight": lambda rng: f"{rng.randrange(1, 200)}.{rng.randrange(10)} kg",
    "distance": lambda rng: f"{rng.randrange(1, 900)}.{rng.randrange(10)} km",
    "temperature": lambda rng: f"{rng.randrange(-20, 40)} °C",
    "duration": lambda rng: f"{rng.randrange(2, 60)} {rng.choice(('days', 'weeks', 'hours'))}",
    "software version": lambda rng: (f"v{rng.randrange(1, 12)}.{rng.randrange(0, 20)}."
                                     f"{rng.randrange(0, 40)}"),
    "sort code": lambda rng: (f"{rng.randrange(10, 99)}-{rng.randrange(10, 99)}-"
                              f"{rng.randrange(10, 99)}"),
    "file name": lambda rng: (f"{rng.choice(NOUNS)}_{rng.randrange(1, 999)}."
                              f"{rng.choice(('pdf', 'csv', 'xlsx'))}"),
    "day of the week": lambda rng: rng.choice(_DAYS),
    "map coordinates": lambda rng: (f"{rng.uniform(49.9, 58.6):.3f}, "
                                    f"{rng.uniform(-6.0, 1.7):.3f}"),
}
_KIND_NAMES = tuple(FIELD_KINDS)

# A form's fieldsets. None shares a word with a topic, a noun, or another section, so the
# section a goal names occurs once on the page.
FORM_SECTIONS = ("Head office", "Branch office", "Primary contact", "Secondary contact",
                 "Emergency contact", "Returns desk", "Warehouse", "Registered agent")


def _form_shapes(width: int) -> list[tuple[int, int]]:
    """(sections, fields per section) with sections x fields == width, two or more fields
    to a section so the value's kind always matters."""
    return [(s, width // s) for s in range(1, len(FORM_SECTIONS) + 1)
            if width % s == 0 and 2 <= width // s <= len(_KIND_NAMES)]


def _field_for_value(layout: str, rng: random.Random, qid: str) -> Example | None:
    """The value has a *kind*; the goal names a *section*; the tree says which field in
    that section expects that kind. Both halves have to be read off the page.

    Version 1 appended the kind to the gold field's accessible name and to nothing else,
    so the option list read `['Supplier 0', 'Password 1', 'Event 2 date']`: picking the
    one option not shaped `<Noun> <int>` was correct on **2,000 / 2,000** questions of
    an earlier build. Version 2 moved the kinds into the tree -- every field declared one
    of six, the gold's kind exactly once and the others drawn with replacement -- which
    made the gold the only field on the page whose kind was *unique*, so a reader who
    ignored the value and picked a field with a page-unique kind scored **0.68** against a
    0.15 chance (domain-14 audit). Unambiguous and unmarked cannot both hold with six kinds
    on eighty fields. So now every section of the form holds the same set of kinds, in its
    own order: every kind on the page occurs once per section, the value's kind picks a
    field within a section, the named section picks the section, and the gold carries no
    property that the other fields lack.
    """
    if layout != "settings_form":
        return None
    topic = rng.choice(TOPICS)
    tree = _settings_form(rng, topic, [])
    form = next(n for n in tree["children"] if n["role"] == "form")
    save = form["children"]
    widths = [w for w in WIDTHS if _form_shapes(w)]
    width = rng.choice(widths)
    while True:
        n_sec, per = rng.choice(_form_shapes(width))
        kinds = rng.sample(_KIND_NAMES, per)
        sections = rng.sample(FORM_SECTIONS, n_sec)
        boxes, groups = [], []
        for sec in sections:
            order = rng.sample(kinds, per)
            kids = []
            for kind in order:
                kids.append(_node("textbox", f"{rng.choice(NOUNS).title()} {len(boxes)}",
                                  expects=kind))
                boxes.append((sec, kind))
            groups.append(_node("group", sec, children=kids))
        form["children"] = groups + save
        state = _state(tree)
        if len(state) <= MAX_STATE_CHARS or width == widths[0]:
            break
        width = max(w for w in widths if w < width)
    pick = rng.randrange(len(boxes))
    section, kind = boxes[pick]
    value = FIELD_KINDS[kind](rng)
    options = [f"{b['name']}" for g in groups for b in g["children"]]
    if len(set(options)) != len(options) or len(options) != len(boxes):
        return None
    key = f"{layout}:{qid}"
    q = Question(
        id=qid, question=_phrase(FIELD_Q, key),
        instructions=_phrase(FIELD_I, key, value=value, section=section),
        options=options,
        target=pick,
        meta={"value": value, "section": section})
    return Example(task=f"browser_field_{layout}", state=state, questions=[q])


FAMILIES = {"click": _click_target, "goal": _goal_reached, "field": _field_for_value}


def _loader(family: str, layout: str, seed: int):
    make = FAMILIES[family]

    def load(n: int) -> Iterator[Example]:
        made = 0
        for i in range(n * 8):
            if made >= n:
                return
            ex = make(layout, _rng(seed, f"{family}:{layout}:{i}"), f"{family}_{i}")
            if ex is not None:
                made += 1
                yield ex

    return load


def tasks() -> list[RealTask]:
    """Trained layouts go to train; `HELDOUT_LAYOUTS` land in testreal and are never
    trained on, which is what a UI-transfer reading needs; `DEV_LAYOUTS` land in devreal,
    held out of both. A layout is the held-out unit, so the click and goal tasks on one
    layout share its family."""
    out: list[RealTask] = []
    for family in FAMILIES:
        for layout in TRAINED_LAYOUTS:
            # `field` only exists on a form, and a form carries no links for `click`.
            if family == "field" and layout != "settings_form":
                continue
            if family == "click" and layout == "settings_form":
                continue
            out.append(RealTask(
                row=ROW, name=f"browser_{family}_{layout}", licence=LICENCE, url=URL,
                load=_loader(family, layout, 0), real=False, force_split="train",
                family=f"browser_{layout}",
                notes=f"{family} on a {layout} page; code-labelled"))
        for layout in HELDOUT_LAYOUTS:
            if family == "field":
                continue
            out.append(RealTask(
                row=ROW, name=f"browser_{family}_{layout}", licence=LICENCE, url=URL,
                load=_loader(family, layout, 4241), real=False, force_split="testreal",
                family=f"browser_{layout}",
                notes=f"{family} on a {layout} page; NEVER trained on"))
        for layout in DEV_LAYOUTS:
            if family == "field":
                continue
            out.append(RealTask(
                row=ROW, name=f"browser_{family}_{layout}", licence=LICENCE, url=URL,
                load=_loader(family, layout, 4243), real=False, force_split="devreal",
                family=f"browser_{layout}",
                notes=f"{family} on a {layout} page; held out of train and test; a dev "
                      f"structure -- selects checkpoints and fits T"))
    return out
