"""Row 43 -- chess positions as facts (domain 4).

A formal state with no natural-language shortcut, asked about as *facts to compose*
rather than as a search problem.

The distinction is the whole design. "Find the winning move" is search depth, and a
0.6B prefill-only scorer does not do lookahead in one forward pass -- an earlier model
sat at chance on every balanced lichess theme while reporting 0.80 confidence on two of
them, which is the confidently-wrong behaviour this project most wants gone. Training a
scorer to guess a best move teaches exactly that. So every question here is an **exact
lookup over the position, composed two or three deep**, and python-chess derives the
answer definitively:

    attacked     which pieces attack a square
    defended     which pieces of the occupant's own colour attack it
    pinned       an enemy slider attacks it along a line holding its own king
    legal        is this move in `legal_moves`
    gives_check  does this move leave the other king attacked
    material     the usual 1/3/3/5/9 sum
    mobility     how many legal moves the side to move has
    count        how many of a set satisfy a predicate
    extremum     which of several positions, or pieces, maximises one of the above

Nothing else. No evaluation, no "best move", no lookahead past one legal move.

**The holdout is a composition depth, not a sample.** Thirteen families of depth 1 and 2
are trained; five families of depth 3 go to `testreal` and are never trained on. Every
primitive in a held-out family appears alone, or in a two-deep pair, in a trained family
-- `test_chessfacts_source.py` asserts it, primitive by primitive, and names the trained
control each held-out family is paired against. That asks the transfer question worth
asking: not "have you met a discovered check" but "can you compose two lookups you know".
Three more depth-3 families (`DEV_HELDOUT`) go to `devreal`, built the same way and
disjoint from test's, on their own quarter of the trained half of the position pool
(`dev_pool`): the split that selects checkpoints and fits T then measures transfer too.

**The definitions are input, not assumed knowledge.** What "defended" and "pinned" mean
is written into the option criteria and the instructions, the way `rules.py` writes the
rule into its criteria. A model that has to be *told* what a pin is and then apply it to
a board is the bet this corpus is making; a model that has memorised the word `pin` from
lichess theme labels is the thing it is trying not to be.

**Two renderings of the same values.** Each position is emitted as a FEN, as a JSON
square -> piece map, as an ASCII board, or as a combination, drawn independently of the
question. The label is computed from the `chess.Board`, never from the text, so the same
question in another shape is the same question and not a harder exercise in parsing FEN.

**Seeds.** A mix, on purpose. Real lichess puzzle positions are tactically dense and
unusual; positions from random legal playouts are ordinary. A model that only ever sees
tactical positions learns a skewed prior about how often anything is pinned or hanging.
The puzzle half is drawn only from the *trained* half of row 13's puzzle pool
(`lichess._reserved_pool`), and the puzzle's first move -- the opponent move that sets
the puzzle -- is played before the position is used, so no FEN emitted here is a FEN in
any lichess task, reserved or trained. `tests/test_chessfacts_source.py` measures that
overlap and asserts it is zero: row 13 reserves eight themes to `testreal`, and reusing
their positions would leak a held-out eval set into training.

`chess` is imported **inside** the loaders, the way `gefs.py` imports xarray, so
`pytest`, `--help` and every build that does not select row 43 run without the extra.
The build box needs `uv sync --extra chess`.
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass, field
from typing import Any, Callable, Iterator

from lod import sentinel
from lod.schema import Example, Question
from lod.corpus.repositories import raw_store as store
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/chessfacts.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/chessfacts.py"
ROW = 43
DOMAIN = 4

PUZZLE_KEY = "lichess_chess_puzzles"
# Row 43's own, larger puzzle pool: 40,000 puzzles none of which row 13 caches, ChessBench
# positions removed. Random playouts rarely contain a pin, so with 2,000 puzzles the pin
# families were built from 170-280 distinct positions reused 4-7 times each.
POOL_KEY = "lichess_puzzle_pool"

# How many examples one task will ever yield, whatever quota it is handed. 18 tasks at
# this cap is ~18,000 questions, which is the row's share of a 400k budget without the
# source cap having to claw any of it back.
PER_TASK = 1000

# position pool: puzzle-derived first, then random playouts. The pool is then halved by
# a hash of the FEN, and the trained and held-out families draw from different halves --
# see `pool()`.
N_PUZZLE_POSITIONS = 30000     # from `lichess_puzzle_pool` (scripts/fetch_data.py --rows 43)
N_PLAYOUT_POSITIONS = 6000
PLAYOUT_PLIES = (8, 70)

RENDERINGS = ("fen", "map", "both", "ascii")

PIECE_VALUES = {1: 1, 2: 3, 3: 3, 4: 5, 5: 9, 6: 0}   # P N B R Q K
PIECE_WORDS = {1: "pawn", 2: "knight", 3: "bishop", 4: "rook", 5: "queen", 6: "king"}


# ---- primitives, families, and what is held out -------------------------------------

PRIMITIVES = ("attacked", "defended", "pinned", "legal", "gives_check",
              "material", "mobility", "count", "extremum")


@dataclass(frozen=True)
class Family:
    name: str                      # task name *without* the `chessfact_` prefix
    depth: int                     # composition depth: how many lookups deep
    prims: tuple[str, ...]
    boards: int = 1                # how many positions the state carries
    ordinal: bool = False
    control: str = ""              # for a held-out family: the trained family it pairs with
    note: str = ""


TRAINED: tuple[Family, ...] = (
    Family("attacked", 1, ("attacked",),
           note="is the piece on a named square attacked by the enemy"),
    Family("defended", 1, ("defended", "count"), ordinal=True,
           note="how many of its own side defend the piece on a named square"),
    Family("pinned", 1, ("pinned",),
           note="is the piece on a named square pinned against its own king"),
    Family("legal_move", 1, ("legal",),
           note="is this move legal for the side to move"),
    Family("mobility", 1, ("mobility", "count"), ordinal=True,
           note="how many legal moves the side to move has, banded"),
    Family("material", 1, ("material",), ordinal=True,
           note="which side leads on material and by how much, banded"),
    Family("gives_check", 1, ("legal", "gives_check"),
           note="after one legal move, is the other king in check"),
    Family("defended_by_pinned", 2, ("defended", "pinned"),
           note="is the piece on a named square defended by a piece that is itself pinned"),
    Family("hanging_square", 2, ("attacked", "defended"),
           note="which of these squares holds a piece attacked and defended by nobody"),
    Family("most_attacked", 2, ("attacked", "count", "extremum"),
           note="which of these pieces is attacked by the most enemy pieces"),
    Family("most_mobile", 2, ("mobility", "count", "extremum"), boards=4,
           note="which of four positions gives the side to move the most legal moves"),
    Family("material_edge", 2, ("material", "extremum"), boards=4,
           note="which of four positions has the largest material imbalance"),
    Family("after_move_attacked", 2, ("legal", "attacked"),
           note="after one legal move, is a named piece attacked"),
)

HELDOUT: tuple[Family, ...] = (
    Family("discovered_check", 3, ("legal", "gives_check", "attacked"),
           control="gives_check",
           note="after one legal move, is the king checked by the piece that moved, by a "
                "piece that did not move, or not at all"),
    Family("hanging_defender", 3, ("defended", "attacked"),
           control="defended_by_pinned",
           note="is the piece on a named square defended by a piece that is itself "
                "attacked and undefended"),
    Family("most_pinned", 3, ("pinned", "count", "extremum"), boards=4,
           control="most_mobile",
           note="which of four positions has the most pinned pieces"),
    Family("most_hanging", 3, ("attacked", "defended", "count", "extremum"), boards=4,
           control="hanging_square",
           note="which of four positions has the most pieces attacked and undefended"),
    Family("after_move_hanging", 3, ("legal", "attacked", "defended"),
           control="after_move_attacked",
           note="after one legal move, which piece is left attacked and undefended"),
)

# Held out of train *and* test: the dev split's own depth-3 compositions, which select
# checkpoints and fit the temperature. Built exactly as `HELDOUT` is -- every primitive
# trained, each paired with a trained control -- and none is a test family, so dev
# measures transfer to an unseen composition the way test does without reading test.
DEV_HELDOUT: tuple[Family, ...] = (
    Family("after_move_pinned", 3, ("legal", "attacked", "pinned"),
           control="after_move_attacked",
           note="after one legal move, is a named piece pinned against its own king"),
    Family("attacker_hanging", 3, ("attacked", "defended"),
           control="hanging_square",
           note="is the piece on a named square attacked by an enemy piece that is itself "
                "attacked and undefended"),
    Family("most_checks", 3, ("legal", "gives_check", "count", "extremum"), boards=4,
           control="most_mobile",
           note="which of four positions gives the side to move the most checking moves"),
)

FAMILIES = TRAINED + HELDOUT + DEV_HELDOUT
BY_NAME = {f.name: f for f in FAMILIES}


def trained_primitives() -> set[str]:
    return {p for f in TRAINED for p in f.prims}


# ---- glossary: the definitions that go into the state's own instructions -------------
# Every term a question can use is defined here, and only the terms a given question
# actually uses are printed. A model that has to be told what a pin is, and then apply
# it, is the point; a model that recognises the word from a theme label is not.

GLOSSARY = {
    "attacked": ("A piece ATTACKS a square when it could capture an enemy piece standing "
                 "there as a pseudo-legal move -- pawns attack only diagonally forward, "
                 "sliders are blocked by any piece in the way, and whether the capture "
                 "would leave its own king in check does not matter here."),
    "defended": ("A piece on a square is DEFENDED by a piece of the same colour that "
                 "attacks that square. The piece standing there does not defend itself."),
    # deliberately worded without a bare "no": these definitions are printed identically
    # for every option, so a bare "no" in them makes the string "no" present in the text
    # of every yes/no question and pollutes the string-match measurement with a cue that
    # carries nothing.
    "undefended": ("A piece is UNDEFENDED when none of the pieces of its own colour "
                   "attacks the square it stands on."),
    "pinned": ("A piece is PINNED when an enemy queen, rook or bishop attacks it along a "
               "rank, file or diagonal that continues through it to its own king with "
               "nothing else in between, so that moving it off that line would leave its "
               "own king attacked."),
    "legal": ("A move is LEGAL when the piece named can make it under the rules of chess "
              "and the position after it does not leave the mover's own king attacked. "
              "Moves are written in long algebraic form: origin square, destination "
              "square, and a promotion piece letter if the move promotes."),
    "check": ("A king is IN CHECK when an enemy piece attacks the square it stands on."),
    "material": ("MATERIAL counts a pawn as 1, a knight as 3, a bishop as 3, a rook as 5 "
                 "and a queen as 9. Kings are not counted."),
    "mobility": ("A LEGAL MOVE is any move the side to move may play; castling counts as "
                 "one move and each promotion piece counts separately."),
}


def _instructions(*keys: str) -> str:
    return " ".join(GLOSSARY[k] for k in keys)


# ---- question templates -----------------------------------------------------------------
# One per family, registered in `lod/assets/phrasing_specs/d04.json` as
# `d04.chessfact_<family>`. `_ask` reads the wording through the phrasing bank (the
# template itself while the bank has none) and fills the slots. The label never depends
# on the wording: it is computed from the board and the slot values.

TEMPLATES = {
    "attacked": "Is the piece on {square} attacked by any {side} piece?",
    "defended": "How many pieces defend the piece standing on {square}?",
    "pinned": "Is the piece on {square} pinned against its own king?",
    "legal_move": "It is {mover} to move. Is {move} a legal move in this position?",
    "mobility": "How many legal moves does the side to move have?",
    "material": "Counting only the pieces on the board, how do the two material totals "
                "compare?",
    "gives_check": "{mover} plays {move}. Is the {other} king in check in the position "
                   "that follows?",
    "defended_by_pinned": "Is the piece on {square} defended by at least one piece that "
                          "is itself pinned?",
    "hanging_square": "Which of these {side} pieces is attacked by the other side and "
                      "defended by no piece of its own colour?",
    "most_attacked": "Which of these {side} pieces is attacked by the greatest number of "
                     "{other} pieces?",
    "most_mobile": "In which of these positions does the side to move have the greatest "
                   "number of legal moves?",
    "material_edge": "In which of these positions is the gap between the two material "
                     "totals the largest, whichever side is ahead?",
    "after_move_attacked": "{mover} plays {move}. In the position that follows, is the "
                           "piece standing on {square} attacked by any {side} piece? "
                           "Squares are named as they are after the move.",
    "discovered_check": "{mover} plays {move}. In the position that follows, is the "
                        "{other} king in check, and if so which piece is giving it?",
    "hanging_defender": "Is the piece on {square} defended by at least one piece that is "
                        "itself attacked by the other side and defended by nobody?",
    "most_pinned": "In which of these positions is the greatest number of pieces pinned "
                   "against their own king, counting both colours?",
    "most_hanging": "In which of these positions are the most pieces attacked by the "
                    "other side while having no defender of their own colour, counting "
                    "both colours?",
    "after_move_hanging": "{mover} plays {move}. In the position that follows, which of "
                          "these {side} pieces is attacked and has no defender of its own "
                          "colour? Squares are named as they are after the move.",
    "after_move_pinned": "{mover} plays {move}. In the position that follows, is the piece "
                         "standing on {square} pinned against its own king? Squares are "
                         "named as they are after the move.",
    "attacker_hanging": "Is the piece on {square} attacked by at least one enemy piece that "
                        "is itself attacked and defended by nobody?",
    "most_checks": "In which of these positions does the side to move have the greatest "
                   "number of legal moves that give check?",
}

_BANK = None


def _ask(family: str, boards: list, key_extra: str = "", **slots: str) -> str:
    """The question for one record: a bank phrasing of the family's template, filled.

    The key is the record's own identity -- its positions and slot values -- so a rebuild
    picks the same wording and two records of one family usually pick different ones.
    """
    global _BANK
    if _BANK is None:
        from lod.phrasings import PhrasingBank
        _BANK = PhrasingBank.load()
    key = "|".join(b.fen() for b in boards) + "|" + "|".join(
        f"{k}={v}" for k, v in sorted(slots.items())) + "|" + key_extra
    return _BANK.pick(f"d04.chessfact_{family}", TEMPLATES[family], key).format(**slots)


# ---- position pool -------------------------------------------------------------------

_POOL: list[str] | None = None
_POOL_MIX: dict[str, int] = {}


def _reserved_pool(puzzle_id: str) -> bool:
    """Row 13's partition, reproduced so the puzzle half drawn here is the *trained* half.

    `lichess._reserved_pool` is the authority; this is deliberately a copy rather than an
    import, because importing it would couple a generator to a real loader that raises
    when its cache is short. `tests/test_chessfacts_source.py` asserts the two agree on
    every cached puzzle.
    """
    return hashlib.sha256(str(puzzle_id).encode()).digest()[0] % 2 == 1


def _puzzle_positions(limit: int) -> list[str]:
    """FENs from lichess puzzles, from the trained half, after the setup move.

    A lichess puzzle's FEN is the position *before* the opponent's move; the first entry
    of `Moves` is that move, and the puzzle proper starts after it. Playing it is both
    the right position to ask about and the thing that guarantees no FEN emitted by this
    row is a FEN any lichess task states.
    """
    import chess

    key = POOL_KEY if store.has(POOL_KEY) else PUZZLE_KEY
    if not store.has(key):
        return []
    out: list[str] = []
    for raw in store.load(key):
        if len(out) >= limit:
            break
        pid = raw.get("PuzzleId")
        if pid is None or _reserved_pool(pid):
            continue
        fen, moves = raw.get("FEN"), str(raw.get("Moves") or "").split()
        if not fen or not moves:
            continue
        try:
            board = chess.Board(fen)
            board.push(chess.Move.from_uci(moves[0]))
        except (ValueError, AssertionError):
            continue
        if board.is_game_over() or not any(board.legal_moves):
            continue
        out.append(board.fen())
    return out


def _playout_positions(limit: int, seed: int) -> list[str]:
    """Ordinary positions: random legal moves from the start, stopped at a random ply."""
    import chess

    rng = random.Random(seed)
    out: list[str] = []
    while len(out) < limit:
        board = chess.Board()
        plies = rng.randint(*PLAYOUT_PLIES)
        for _ in range(plies):
            moves = list(board.legal_moves)
            if not moves:
                break
            board.push(rng.choice(moves))
        if board.is_game_over() or not any(board.legal_moves):
            continue
        if len(board.piece_map()) < 8:          # a bare endgame has little to ask about
            continue
        out.append(board.fen())
    return out


def _reserved_fen(fen: str) -> bool:
    """Which half of the pool a position belongs to, stable under rebuilds."""
    return hashlib.sha256(fen.encode()).digest()[0] % 2 == 1


def _dev_fen(fen: str) -> bool:
    """A quarter of the *unreserved* half, for `DEV_HELDOUT`. Taken from the trained side
    so that test's half -- and so every testreal state -- is exactly what it was."""
    h = hashlib.sha256(fen.encode()).digest()
    return h[0] % 2 == 0 and h[1] % 4 == 0


def dev_pool() -> list[str]:
    """The dev families' positions: disjoint from `pool(reserved=True)` and from
    `pool(reserved=False)`, for the reason `pool` gives."""
    return [f for f in pool() if _dev_fen(f)]


def pool(reserved: bool | None = None) -> list[str]:
    """The FEN pool. `reserved` selects the held-out half, `False` the trained half
    (less `dev_pool()`, which the dev families draw from).

    **The halves must be disjoint.** Eighteen families asking eighteen questions about
    one pool of positions means a trained task and a held-out task state the same board
    in the same rendering, and `dedup_against_train` -- doing exactly its job -- deletes
    the held-out copy. Measured on the first build of this row: 1,947 of 5,000 testreal
    examples dropped, 39 % of the holdout, silently. `lichess.py` partitions its puzzles
    by `PuzzleId` for the same reason and `base.disjoint_slice` records the same
    accident on three other rows.

    `None` returns everything, for the tests and the contamination audit.
    """
    global _POOL, _POOL_MIX
    if _POOL is None:
        puzzles = _puzzle_positions(N_PUZZLE_POSITIONS)
        plays = _playout_positions(N_PLAYOUT_POSITIONS, seed=43_2026)
        _POOL_MIX = {"puzzle": len(puzzles), "playout": len(plays)}
        merged: list[str] = []
        i = j = 0
        # interleave in proportion, so a task that stops early still sees both kinds
        while i < len(puzzles) or j < len(plays):
            if i < len(puzzles):
                merged.append(puzzles[i]); i += 1
            for _ in range(3):
                if j < len(plays):
                    merged.append(plays[j]); j += 1
        _POOL = merged
    if reserved is None:
        return _POOL
    return [f for f in _POOL if _reserved_fen(f) is reserved and not _dev_fen(f)]


def pool_mix() -> dict[str, int]:
    pool()
    return dict(_POOL_MIX)


def reset_pool() -> None:
    global _POOL, _POOL_MIX
    _POOL, _POOL_MIX = None, {}


# ---- rendering -----------------------------------------------------------------------

def _piece_map(board) -> dict[str, str]:
    import chess

    out = {}
    for sq in sorted(board.piece_map(), key=lambda s: (chess.square_rank(s), chess.square_file(s))):
        p = board.piece_at(sq)
        out[chess.square_name(sq)] = f"{'white' if p.color else 'black'} {PIECE_WORDS[p.piece_type]}"
    return out


def _ascii(board) -> str:
    import chess

    rows = []
    for rank in range(7, -1, -1):
        cells = []
        for file in range(8):
            p = board.piece_at(chess.square(file, rank))
            cells.append(p.symbol() if p else ".")
        rows.append(f"{rank + 1} " + " ".join(cells))
    rows.append("  a b c d e f g h")
    return "\n".join(rows)


def _one(board, shape: str) -> dict[str, Any]:
    """One position as a dict. Every shape carries the same information."""
    import chess

    fields = board.fen().split()
    d: dict[str, Any] = {"side_to_move": "white" if board.turn == chess.WHITE else "black",
                         "castling_rights": fields[2], "en_passant_target": fields[3]}
    if shape in ("fen", "both"):
        d["fen"] = board.fen()
    if shape in ("map", "both"):
        d["pieces"] = _piece_map(board)
    if shape in ("ascii", "both"):
        d["board"] = _ascii(board)
        d["board_key"] = ("upper case is white, lower case is black; "
                          "P pawn N knight B bishop R rook Q queen K king; "
                          "a dot is an empty square")
    return d


def render(boards: list, keys: list[str] | None, shape: str) -> str:
    if keys is None:
        return json.dumps(_one(boards[0], shape), ensure_ascii=False, indent=1)
    return json.dumps({k: _one(b, shape) for k, b in zip(keys, boards)},
                      ensure_ascii=False, indent=1)


# ---- a built question, before it is rendered ------------------------------------------

@dataclass
class Spec:
    """Everything a question is, with the position still a `chess.Board`.

    Keeping this separate from the text is what lets the same values be rendered four
    ways and lets a test assert the target does not move when the rendering does.
    """
    boards: list
    keys: list[str] | None
    question: str
    options: list[str]
    target: int
    descriptions: list[str]
    instructions: str
    meta: dict[str, Any] = field(default_factory=dict)


def _example(spec: Spec, task: str, shape: str, qid: str = "q0") -> Example:
    meta = dict(spec.meta)
    meta["shape"] = shape
    return Example(
        task=task,
        state=render(spec.boards, spec.keys, shape),
        questions=[Question(id=qid, question=spec.question, options=list(spec.options),
                            target=spec.target, meta=meta,
                            instructions=spec.instructions,
                            descriptions=list(spec.descriptions))])


# ---- board helpers --------------------------------------------------------------------

def _defenders(board, sq) -> list[int]:
    p = board.piece_at(sq)
    if p is None:
        return []
    return [a for a in board.attackers(p.color, sq) if a != sq]


def _enemies(board, sq) -> list[int]:
    p = board.piece_at(sq)
    if p is None:
        return []
    return list(board.attackers(not p.color, sq))


def _is_hanging(board, sq) -> bool:
    return bool(_enemies(board, sq)) and not _defenders(board, sq)


def _pclass(piece_type: int) -> int:
    """Coarse piece class for matching keys: pawn, minor, major."""
    return 0 if piece_type == 1 else 1 if piece_type in (2, 3) else 2


# Per-(family, split) tally of accepted answers per shallow-feature key; see `_matched`.
_LEDGER: dict | None = None
_SEEN: dict = {}


def clear_balance() -> None:
    """No tally: builders fall back to per-board matching."""
    global _LEDGER
    _LEDGER = None


def reset_balance() -> None:
    """Start a fresh answer-per-key tally. The loader calls this once per task."""
    global _LEDGER, _SEEN
    _LEDGER = {}
    _SEEN = {}


def _matched(cands, want, rng, per_board: bool = False):
    """Answer-blind shallow features, balanced across the whole task.

    With a tally active (`reset_balance`): take a candidate with label `want` only if
    its key has not already had more `want` answers than the other answer, so every key
    ends with as many yes as no (+-1) across the task and says nothing about the answer.
    A board need not hold both answers under one key, which is what let the keys carry
    every predictive feature without starving the family.

    Without a tally (direct calls, tests): fall back to per-board matching -- a key that
    occurs with both labels on this board, chosen uniformly.

    Without it, the composite families were answerable from partial computations
    (measured by a shortcut audit): `hanging_defender` from "is any defender
    attacked" at 0.82, `defended_by_pinned` from defender count and attack status at
    0.88, `after_move_attacked` from whether the square was attacked BEFORE the move at
    0.91. One earlier model scored 0.993 on held-out `hanging_defender` by riding that cue
    and another 0.139 by riding its opposite -- the family measured which way a model
    leaned, not the composition it is named for.

    `per_board=True` forces per-board matching. The rare compositions need it: a
    `hanging_defender` "no" whose key matches a "yes" needs one defender attacked and a
    DIFFERENT one undefended, which real games barely produce, so the task-wide tally
    refused nearly every "yes" (9 examples in 180,000 boards).

    cands: [(choice, label, key)]. Returns a choice, or None.
    """
    if _LEDGER is not None and not per_board:
        # Every candidate seen counts, taken or not. A key may take a `want` example only
        # when the OTHER answer has been seen under it more often than `want` has been
        # taken: a key that only ever occurs with one answer never contributes. Without
        # that, each such key added one unmatched example, and hundreds of sparse keys
        # summed to a clear correlation (0.688 on defended_by_pinned).
        for _, lab, k in cands:
            _SEEN[(k, bool(lab))] = _SEEN.get((k, bool(lab)), 0) + 1
        w = bool(want)
        ok = [(c, k) for c, lab, k in cands if bool(lab) == w
              and _LEDGER.get((k, w), 0) <= _LEDGER.get((k, not w), 0)
              and _SEEN.get((k, not w), 0) > _LEDGER.get((k, w), 0)]
        if not ok:
            return None
        choice, k = ok[rng.randrange(len(ok))]
        _LEDGER[(k, bool(want))] = _LEDGER.get((k, bool(want)), 0) + 1
        return choice
    yes_keys = {k for _, lab, k in cands if lab}
    no_keys = {k for _, lab, k in cands if not lab}
    shared = sorted(yes_keys & no_keys, key=repr)
    if not shared:
        return None
    key = rng.choice(shared)
    pick = [c for c, lab, k in cands if bool(lab) == bool(want) and k == key]
    return rng.choice(pick)


def _material(board) -> tuple[int, int]:
    w = b = 0
    for _, p in board.piece_map().items():
        v = PIECE_VALUES[p.piece_type]
        if p.color:
            w += v
        else:
            b += v
    return w, b


def _pinned_squares(board, color) -> list[int]:
    return [sq for sq in board.piece_map()
            if board.piece_at(sq).color == color and board.is_pinned(color, sq)]


def _name(board, sq) -> str:
    import chess

    p = board.piece_at(sq)
    return f"{'white' if p.color else 'black'} {PIECE_WORDS[p.piece_type]} on {chess.square_name(sq)}"


def _sq(sq) -> str:
    import chess

    return chess.square_name(sq)


def _shuffled(rng: random.Random, items: list) -> list:
    out = list(items)
    rng.shuffle(out)
    return out


def _place(rng, options, descs, gold_idx) -> tuple[list[str], list[str], int]:
    """Shuffle an option list, carrying its descriptions and its gold index with it."""
    order = list(range(len(options)))
    rng.shuffle(order)
    return ([options[i] for i in order], [descs[i] for i in order],
            order.index(gold_idx))


# ---- family builders -------------------------------------------------------------------
# Each takes the boards it was handed plus an rng and returns a Spec, or None when the
# position cannot answer the question. None is a *drop*, never a guess.

def _b_attacked(boards, rng, want) -> Spec | None:
    board = boards[0]
    # matched on piece class, defenders and pin: "a defended major piece is rarely
    # attacked" predicted this family at 0.655 (measured by a shortcut audit)
    cands = [(sq, bool(_enemies(board, sq)),
              (_pclass(board.piece_at(sq).piece_type), min(len(_defenders(board, sq)), 2),
               board.is_pinned(board.piece_at(sq).color, sq)))
             for sq in board.piece_map() if board.piece_at(sq).piece_type != 6]
    sq = _matched(cands, want, rng)
    if sq is None:
        return None
    who = "white" if not board.piece_at(sq).color else "black"
    return Spec(
        boards=[board], keys=None,
        question=_ask("attacked", [board], square=_sq(sq), side=who),
        options=["no", "yes"],
        descriptions=[f"No {who} piece attacks {_sq(sq)}.",
                      f"At least one {who} piece attacks {_sq(sq)}."],
        instructions=_instructions("attacked"),
        target=int(want), meta={"square": _sq(sq), "n_attackers": len(_enemies(board, sq))})


_COUNT_OPTS = ["defended_by_none", "defended_by_exactly_one", "defended_by_exactly_two",
               "defended_by_three_or_more"]
_COUNT_DESCS = ["No piece of its own colour attacks that square.",
                "Exactly one piece of its own colour attacks that square.",
                "Exactly two pieces of its own colour attack that square.",
                "Three or more pieces of its own colour attack that square."]


def _b_defended(boards, rng, want) -> Spec | None:
    board = boards[0]
    cands = [sq for sq in board.piece_map() if board.piece_at(sq).piece_type != 6]
    buckets: dict[int, list[int]] = {}
    for sq in cands:
        n = min(len(_defenders(board, sq)), 3)
        buckets.setdefault(n, []).append(sq)
    if want not in buckets:     # this position cannot answer the class the task owes
        return None
    sq = rng.choice(buckets[want])
    n = min(len(_defenders(board, sq)), 3)
    return Spec(
        boards=[board], keys=None,
        question=_ask("defended", [board], square=_sq(sq)),
        options=list(_COUNT_OPTS), descriptions=list(_COUNT_DESCS),
        instructions=_instructions("attacked", "defended"),
        target=n, meta={"square": _sq(sq), "n_defenders": len(_defenders(board, sq))})


def _b_pinned(boards, rng, want) -> Spec | None:
    board = boards[0]
    both: list[int] = []
    for color in (True, False):
        both += _pinned_squares(board, color)
    pinned = set(both)
    # matched on piece class, defenders, attacked-ness: a `no` from a back-rank pawn
    # nobody attacks was a freebie (0.632 from shallow features before matching)
    cands = []
    for sq in board.piece_map():
        if board.piece_at(sq).piece_type == 6:
            continue
        ds = _defenders(board, sq)
        cands.append((sq, sq in pinned,
                      (_pclass(board.piece_at(sq).piece_type), min(len(ds), 2),
                       any(_enemies(board, d) for d in ds), bool(_enemies(board, sq)))))
    sq = _matched(cands, want, rng)
    if sq is None:
        return None
    yes = sq in pinned
    return Spec(
        boards=[board], keys=None,
        question=_ask("pinned", [board], square=_sq(sq)),
        options=["no", "yes"],
        descriptions=[f"The piece on {_sq(sq)} is not pinned: no enemy queen, rook or "
                      f"bishop attacks it along a line that continues to its own king.",
                      f"The piece on {_sq(sq)} is pinned: an enemy queen, rook or bishop "
                      f"attacks it along a line that continues to its own king."],
        instructions=_instructions("attacked", "pinned"),
        target=int(yes), meta={"square": _sq(sq)})


def _b_legal_move(boards, rng, want) -> Spec | None:
    import chess

    board = boards[0]
    legal = list(board.legal_moves)
    if not legal:
        return None
    legal_set = {m.uci() for m in legal}
    illegal = []
    # the interesting illegal move is one that is pseudo-legal and leaves the king
    # attacked -- "looks like a move, is not one". Those come first.
    for m in board.pseudo_legal_moves:
        if m.uci() not in legal_set:
            illegal.append(m)
    if not illegal:
        for sq in board.piece_map():
            if board.piece_at(sq).color != board.turn:
                continue
            for to in rng.sample(range(64), 12):
                m = chess.Move(sq, to)
                if sq != to and m.uci() not in legal_set:
                    illegal.append(m)

    def key(m):
        p = board.piece_at(m.from_square)
        return (_pclass(p.piece_type) if p else -1,
                bool(board.attackers(not board.turn, m.to_square)),
                board.is_check(), min(len(legal) // 15, 2), board.gives_check(m),
                board.is_capture(m))
    # matched on piece class and whether the destination is attacked (0.757 from shallow
    # features before matching); a pin stays out of the key -- it is the rule itself
    mv = _matched([(m, True, key(m)) for m in legal] + [(m, False, key(m)) for m in illegal],
                  want, rng)
    if mv is None:
        return None
    ok = mv in legal
    side = "White" if board.turn == chess.WHITE else "Black"
    return Spec(
        boards=[board], keys=None,
        question=_ask("legal_move", [board], mover=side, move=mv.uci()),
        options=["no", "yes"],
        descriptions=[f"{mv.uci()} is not a legal move here.",
                      f"{mv.uci()} is a legal move here."],
        instructions=_instructions("attacked", "legal", "check"),
        target=int(ok), meta={"move": mv.uci()})


_MOB_OPTS = ["fewer_than_15", "from_15_to_24", "from_25_to_34", "35_or_more"]
_MOB_DESCS = ["The side to move has fewer than 15 legal moves.",
              "The side to move has between 15 and 24 legal moves inclusive.",
              "The side to move has between 25 and 34 legal moves inclusive.",
              "The side to move has 35 or more legal moves."]


def _b_mobility(boards, rng, want) -> Spec | None:
    board = boards[0]
    n = board.legal_moves.count()
    band = 0 if n < 15 else 1 if n < 25 else 2 if n < 35 else 3
    if want is not None and band != want:
        return None
    return Spec(
        boards=[board], keys=None,
        question=_ask("mobility", [board]),
        options=list(_MOB_OPTS), descriptions=list(_MOB_DESCS),
        instructions=_instructions("legal", "mobility"),
        target=band, meta={"legal_moves": n})


_MAT_OPTS = ["black_ahead_by_three_or_more", "black_ahead_by_one_or_two", "level",
             "white_ahead_by_one_or_two", "white_ahead_by_three_or_more"]
_MAT_DESCS = ["Black's material total exceeds White's by 3 points or more.",
              "Black's material total exceeds White's by 1 or 2 points.",
              "The two material totals are equal.",
              "White's material total exceeds Black's by 1 or 2 points.",
              "White's material total exceeds Black's by 3 points or more."]


def _b_material(boards, rng, want) -> Spec | None:
    board = boards[0]
    w, b = _material(board)
    d = w - b
    band = 0 if d <= -3 else 1 if d <= -1 else 2 if d == 0 else 3 if d <= 2 else 4
    if want is not None and band != want:
        return None
    return Spec(
        boards=[board], keys=None,
        question=_ask("material", [board]),
        options=list(_MAT_OPTS), descriptions=list(_MAT_DESCS),
        instructions=_instructions("material"),
        target=band, meta={"white": w, "black": b})


def _b_gives_check(boards, rng, want) -> Spec | None:
    import chess

    board = boards[0]
    legal = list(board.legal_moves)
    # matched on piece class, capture, and whether the destination is attacked:
    # "captures onto defended squares give check" predicted this at 0.722
    cands = [(m, board.gives_check(m),
              (_pclass(board.piece_at(m.from_square).piece_type), board.is_capture(m),
               bool(board.attackers(not board.turn, m.to_square)),
               min(len(legal) // 15, 2)))
             for m in legal]
    mv = _matched(cands, want, rng)
    if mv is None:
        return None
    mover = "White" if board.turn == chess.WHITE else "Black"
    other = "Black" if board.turn == chess.WHITE else "White"
    return Spec(
        boards=[board], keys=None,
        question=_ask("gives_check", [board], mover=mover, move=mv.uci(),
                      other=other.lower()),
        options=["no", "yes"],
        descriptions=[f"After {mv.uci()}, no {mover.lower()} piece attacks the square the "
                      f"{other.lower()} king stands on.",
                      f"After {mv.uci()}, at least one {mover.lower()} piece attacks the "
                      f"square the {other.lower()} king stands on."],
        instructions=_instructions("attacked", "legal", "check"),
        target=int(want), meta={"move": mv.uci()})


def _b_defended_by_pinned(boards, rng, want) -> Spec | None:
    """Two hops: the defenders of a square, and whether any of them is pinned.

    Both answers are drawn from squares that *have* a defender, so `no` means "it is
    defended, and none of its defenders is pinned" rather than "nothing defends it".
    """
    board = boards[0]
    cands = []
    for sq in board.piece_map():
        p = board.piece_at(sq)
        if p.piece_type == 6:
            continue
        ds = _defenders(board, sq)
        if not ds:
            continue
        label = any(board.is_pinned(p.color, d) for d in ds)
        # the features that predicted the answer (0.875 before matching), and no more: a
        # seven-part key left ~1 % of boards qualifying and the family repeating them
        key = (min(len(ds), 2), any(_enemies(board, d) for d in ds),
               any(not _defenders(board, d) for d in ds),
               min(len(_enemies(board, sq)), 2), board.turn == p.color,
               board.is_pinned(p.color, sq), _pclass(p.piece_type),
               min(len(board.piece_map()) // 12, 2))
        cands.append((sq, label, key))
    sq = _matched(cands, want, rng)
    if sq is None:
        return None
    return Spec(
        boards=[board], keys=None,
        question=_ask("defended_by_pinned", [board], square=_sq(sq)),
        options=["no", "yes"],
        descriptions=[f"Every piece that defends {_sq(sq)} is free to move; none of them "
                      f"is pinned against its own king.",
                      f"At least one piece that defends {_sq(sq)} is itself pinned "
                      f"against its own king."],
        instructions=_instructions("attacked", "defended", "pinned"),
        target=int(want), meta={"square": _sq(sq), "n_defenders": len(_defenders(board, sq))})


def _b_hanging_square(boards, rng, want, split: str) -> Spec | None:
    """Which listed piece is attacked and undefended -- or none of them.

    Every option is a square that carries a piece of the same colour and appears in the
    state, so "the only option present in the state" is never a signal.
    """
    board = boards[0]
    color = rng.choice([True, False])
    squares = [sq for sq in board.piece_map()
               if board.piece_at(sq).color == color and board.piece_at(sq).piece_type != 6]
    if len(squares) < 5:
        return None
    hang = [sq for sq in squares if _is_hanging(board, sq)]
    safe = [sq for sq in squares if not _is_hanging(board, sq)]
    # the hanging piece occupies one of the k slots when there is one, so the option
    # count is bounded by the *safe* squares available, not by the piece count
    hi = min(7, len(safe) + (1 if want else 0))
    if hi < 4 or (want and not hang):
        return None
    k = rng.randint(4, hi)
    if want:                       # exactly one hanging piece among the options
        chosen = [rng.choice(hang)] + rng.sample(safe, k - 1)
        gold = 0
    else:                          # none of them: the sentinel is the answer
        chosen = rng.sample(safe, k)
        gold = None
    opts = [_sq(s) for s in chosen]
    descs = [f"The {_name(board, s)}." for s in chosen]
    key, desc = sentinel.sample(rng, split)
    opts.append(key)
    descs.append(desc)
    gold_idx = len(opts) - 1 if gold is None else gold
    opts, descs, target = _place(rng, opts, descs, gold_idx)
    side = "white" if color else "black"
    return Spec(
        boards=[board], keys=None,
        question=_ask("hanging_square", [board], side=side, key_extra="|".join(opts)),
        options=opts, descriptions=descs,
        instructions=_instructions("attacked", "defended", "undefended"),
        target=target, meta={"sentinel": gold is None, "n_options": len(opts)})


def _b_most_attacked(boards, rng, want) -> Spec | None:
    """Extremum over an attack map: which listed piece the enemy hits most often."""
    board = boards[0]
    color = rng.choice([True, False])
    squares = [sq for sq in board.piece_map()
               if board.piece_at(sq).color == color and board.piece_at(sq).piece_type != 6]
    if len(squares) < 4:
        return None
    k = rng.randint(4, min(6, len(squares)))
    chosen = rng.sample(squares, k)
    counts = [len(_enemies(board, s)) for s in chosen]
    top = max(counts)
    if top < 1 or counts.count(top) != 1:
        return None                 # a tie has no single answer: drop it
    gold = counts.index(top)
    opts = [_sq(s) for s in chosen]
    descs = [f"The {_name(board, s)}." for s in chosen]
    opts, descs, target = _place(rng, opts, descs, gold)
    side = "white" if color else "black"
    other = "black" if color else "white"
    return Spec(
        boards=[board], keys=None,
        question=_ask("most_attacked", [board], side=side, other=other,
                      key_extra="|".join(opts)),
        options=opts, descriptions=descs,
        instructions=_instructions("attacked"),
        target=target, meta={"counts": sorted(counts, reverse=True)})


_POS_KEYS = ["position_a", "position_b", "position_c", "position_d"]


def _multi(boards, values, question, instr, rng, margin: int,
           desc: Callable[[str], str]) -> Spec | None:
    top = max(values)
    if values.count(top) != 1:
        return None
    rest = sorted(values, reverse=True)[1]
    if top - rest < margin:
        return None                 # a one-move gap is noise, not an extremum
    keys = list(_POS_KEYS[:len(boards)])
    return Spec(
        boards=list(boards), keys=keys,
        question=question, options=list(keys),
        descriptions=[desc(k) for k in keys],
        instructions=instr, target=values.index(top),
        meta={"values": list(values)})


def _b_most_mobile(boards, rng, want) -> Spec | None:
    vals = [b.legal_moves.count() for b in boards]
    return _multi(boards, vals, _ask("most_mobile", boards),
                  _instructions("legal", "mobility"), rng, margin=2,
                  desc=lambda k: f"The position filed under {k}.")


def _b_material_edge(boards, rng, want) -> Spec | None:
    vals = [abs(_material(b)[0] - _material(b)[1]) for b in boards]
    return _multi(boards, vals, _ask("material_edge", boards),
                  _instructions("material"), rng, margin=2,
                  desc=lambda k: f"The position filed under {k}.")


def _b_after_move_attacked(boards, rng, want) -> Spec | None:
    """One legal move, then a lookup on a square the move did not touch.

    The square asked about is never the move's origin or destination. The first version of
    this family asked *which piece is giving check* after the move, and the answer was the
    move's own destination square in every direct check -- so the move written in the
    question contained the gold option verbatim, and the whole family was 100 % solvable
    by copying the last two characters of the move. That is the row 36 failure exactly.
    """
    import chess

    board = boards[0]
    legal = list(board.legal_moves)
    if not legal:
        return None
    rng.shuffle(legal)
    for mv in legal[:20]:
        after = board.copy(stack=False)
        mover = after.turn
        after.push(mv)
        touched = {mv.from_square, mv.to_square}
        cands = [(sq, bool(after.attackers(mover, sq)),
                  # attacked BEFORE the move, and the piece: the answer must not be
                  # readable off the position as given
                  (bool(board.attackers(mover, sq)), after.piece_at(sq).piece_type))
                 for sq in after.piece_map()
                 if sq not in touched and after.piece_at(sq).piece_type != 6
                 and after.piece_at(sq).color != mover]
        sq = _matched(cands, want, rng)
        if sq is None:
            continue
        side = "White" if mover == chess.WHITE else "Black"
        return Spec(
            boards=[board], keys=None,
            question=_ask("after_move_attacked", [board], mover=side, move=mv.uci(),
                          square=_sq(sq), side=side.lower()),
            options=["no", "yes"],
            descriptions=[f"After {mv.uci()}, no {side.lower()} piece attacks {_sq(sq)}.",
                          f"After {mv.uci()}, at least one {side.lower()} piece attacks "
                          f"{_sq(sq)}."],
            instructions=_instructions("attacked", "legal"),
            target=int(want), meta={"move": mv.uci(), "square": _sq(sq)})
    return None


# ---- held out: depth three ---------------------------------------------------------

_DISC_OPTS = ["no_check", "check_by_the_piece_that_moved", "check_by_a_piece_that_did_not_move"]


def _b_discovered_check(boards, rng, want) -> Spec | None:
    """Three hops: play one legal move, take the set of squares attacking the king before
    and after, and ask where the new attacker came from.

    `want` picks the class, so the three classes come out roughly even instead of at
    their natural rate, on which "no check" alone would score about 0.9.
    """
    import chess

    board = boards[0]
    legal = list(board.legal_moves)
    if not legal:
        return None
    rng.shuffle(legal)
    for mv in legal[:60]:
        gives = board.gives_check(mv)
        if want == 0:
            if gives:
                continue
            cls = 0
        else:
            if not gives:
                continue
            after = board.copy(stack=False)
            mover = after.turn
            after.push(mv)
            if board.is_castling(mv):
                continue          # king and rook both move: "the piece that moved" is two
            ksq = after.king(not mover)
            givers = set(after.attackers(mover, ksq))
            cls = 1 if givers == {mv.to_square} else 2
            if cls != want:
                continue
        mover_name = "White" if board.turn == chess.WHITE else "Black"
        other = "black" if board.turn == chess.WHITE else "white"
        return Spec(
            boards=[board], keys=None,
            question=_ask("discovered_check", [board], mover=mover_name, move=mv.uci(),
                          other=other),
            options=list(_DISC_OPTS),
            descriptions=[
                f"After {mv.uci()} no {mover_name.lower()} piece attacks the square the "
                f"{other} king stands on.",
                f"After {mv.uci()} the {other} king is attacked, and the only piece "
                f"attacking it is the one that just moved, standing on {_sq(mv.to_square)}.",
                f"After {mv.uci()} the {other} king is attacked by at least one piece "
                f"other than the one that just moved.",
            ],
            instructions=_instructions("attacked", "legal", "check"),
            target=cls, meta={"move": mv.uci(), "class": cls})
    return None


def _b_hanging_defender(boards, rng, want) -> Spec | None:
    """Three hops: the defenders of a square, and whether any of *them* is attacked and
    itself undefended. Both answers come from squares that have a defender."""
    board = boards[0]
    cands = []
    for sq in board.piece_map():
        if board.piece_at(sq).piece_type == 6:
            continue
        ds = [d for d in _defenders(board, sq) if board.piece_at(d).piece_type != 6]
        if not ds:
            continue
        label = any(_is_hanging(board, d) for d in ds)
        # the partial computations a reader could stop at: some defender attacked, some
        # defender undefended (not necessarily the same one), how busy the square is
        key = (any(_enemies(board, d) for d in ds),
               any(not _defenders(board, d) for d in ds),
               min(len(ds), 2), bool(_enemies(board, sq)))
        cands.append((sq, label, key))
    sq = _matched(cands, want, rng, per_board=True)
    if sq is None:
        return None
    return Spec(
        boards=[board], keys=None,
        question=_ask("hanging_defender", [board], square=_sq(sq)),
        options=["no", "yes"],
        descriptions=[f"Every piece that defends {_sq(sq)} is either unattacked or "
                      f"defended by a piece of its own colour.",
                      f"At least one piece that defends {_sq(sq)} is attacked by the "
                      f"other side and has no defender of its own."],
        instructions=_instructions("attacked", "defended", "undefended"),
        target=int(want), meta={"square": _sq(sq)})


def _b_most_pinned(boards, rng, want) -> Spec | None:
    vals = [len(_pinned_squares(b, True)) + len(_pinned_squares(b, False)) for b in boards]
    return _multi(boards, vals, _ask("most_pinned", boards),
                  _instructions("attacked", "pinned"), rng, margin=1,
                  desc=lambda k: f"The position filed under {k}.")


def _b_most_hanging(boards, rng, want) -> Spec | None:
    def n_hang(b):
        return sum(1 for sq in b.piece_map()
                   if b.piece_at(sq).piece_type != 6 and _is_hanging(b, sq))
    vals = [n_hang(b) for b in boards]
    return _multi(boards, vals, _ask("most_hanging", boards),
                  _instructions("attacked", "defended", "undefended"), rng, margin=2,
                  desc=lambda k: f"The position filed under {k}.")


def _b_after_move_hanging(boards, rng, want, split: str) -> Spec | None:
    """Three hops: one legal move, then attacked-and-undefended over the listed squares."""
    board = boards[0]
    legal = list(board.legal_moves)
    if not legal:
        return None
    rng.shuffle(legal)
    for mv in legal[:40]:
        after = board.copy(stack=False)
        mover = after.turn
        after.push(mv)
        color = not mover                      # ask about the side that did not move
        squares = [sq for sq in after.piece_map()
                   if after.piece_at(sq).color == color
                   and after.piece_at(sq).piece_type != 6]
        if len(squares) < 5:
            continue
        hang = [sq for sq in squares if _is_hanging(after, sq)]
        safe = [sq for sq in squares if not _is_hanging(after, sq)]
        hi = min(7, len(safe) + (1 if want else 0))
        if hi < 4 or (want and not hang):
            continue
        k = rng.randint(4, hi)
        if want:
            chosen = [rng.choice(hang)] + rng.sample(safe, k - 1)
            gold = 0
        else:
            chosen = rng.sample(safe, k)
            gold = None
        opts = [_sq(s) for s in chosen]
        descs = [f"The {_name(after, s)} (named as it stands after the move)."
                 for s in chosen]
        key, desc = sentinel.sample(rng, split)
        opts.append(key)
        descs.append(desc)
        gold_idx = len(opts) - 1 if gold is None else gold
        opts, descs, target = _place(rng, opts, descs, gold_idx)
        side = "White" if mover else "Black"
        them = "black" if mover else "white"
        return Spec(
            boards=[board], keys=None,
            question=_ask("after_move_hanging", [board], mover=side, move=mv.uci(),
                          side=them, key_extra="|".join(opts)),
            options=opts, descriptions=descs,
            instructions=_instructions("attacked", "defended", "undefended", "legal"),
            target=target, meta={"move": mv.uci(), "sentinel": gold is None})
    return None


# ---- held out of train and test: the dev split's depth three ----------------------------

def _b_after_move_pinned(boards, rng, want) -> Spec | None:
    """Three hops: one legal move, then whether a piece the move did not touch now stands
    on a line from an enemy slider to its own king. Matched on whether it was pinned
    BEFORE the move, so the answer cannot be read off the position as given."""
    import chess

    board = boards[0]
    legal = list(board.legal_moves)
    if not legal:
        return None
    rng.shuffle(legal)
    for mv in legal[:30]:
        after = board.copy(stack=False)
        mover = after.turn
        after.push(mv)
        touched = {mv.from_square, mv.to_square}
        moved = (board.piece_at(mv.from_square).piece_type, board.gives_check(mv))
        cands = []
        for sq in after.piece_map():
            p = after.piece_at(sq)
            if sq in touched or p.piece_type == 6:
                continue
            # the move's piece and whether it checks, and the square's attackers before
            # it: without them (side, pinned-before, moving piece) read 0.69 and
            # (attackers, pinned-before, gives check) 0.68 against a ~0.57 noise floor
            # (shortcut-audit features)
            cands.append((sq, after.is_pinned(p.color, sq),
                          (board.is_pinned(p.color, sq), p.color == mover,
                           _pclass(p.piece_type), bool(after.attackers(not p.color, sq)),
                           min(len(board.attackers(not p.color, sq)), 2), moved)))
        sq = _matched(cands, want, rng)
        if sq is None:
            continue
        side = "White" if mover == chess.WHITE else "Black"
        return Spec(
            boards=[board], keys=None,
            question=_ask("after_move_pinned", [board], mover=side, move=mv.uci(),
                          square=_sq(sq)),
            options=["no", "yes"],
            descriptions=[f"After {mv.uci()}, the piece on {_sq(sq)} is not pinned: no "
                          f"enemy queen, rook or bishop attacks it along a line that "
                          f"continues to its own king.",
                          f"After {mv.uci()}, the piece on {_sq(sq)} is pinned: an enemy "
                          f"queen, rook or bishop attacks it along a line that continues "
                          f"to its own king."],
            instructions=_instructions("attacked", "pinned", "legal"),
            target=int(want), meta={"move": mv.uci(), "square": _sq(sq)})
    return None


def _b_attacker_hanging(boards, rng, want) -> Spec | None:
    """Three hops, `hanging_defender` turned round: the *attackers* of a square, and
    whether any of them is attacked and itself undefended. Both answers come from squares
    that are attacked; a square attacked by a king is skipped, so "piece" never has to
    decide whether a king can hang."""
    board = boards[0]
    cands = []
    for sq in board.piece_map():
        if board.piece_at(sq).piece_type == 6:
            continue
        atk = _enemies(board, sq)
        if not atk or any(board.piece_at(a).piece_type == 6 for a in atk):
            continue
        label = any(_is_hanging(board, a) for a in atk)
        # the partial computations a reader could stop at, as in `hanging_defender`, and
        # the square's own piece, side and defenders: without those three (piece, side to
        # move, defenders) read 0.62 against a 0.54 noise floor
        key = (any(_enemies(board, a) for a in atk),
               any(not _defenders(board, a) for a in atk),
               min(len(atk), 2), min(len(_defenders(board, sq)), 2),
               board.piece_at(sq).piece_type, board.piece_at(sq).color == board.turn)
        cands.append((sq, label, key))
    sq = _matched(cands, want, rng)
    if sq is None:
        return None
    return Spec(
        boards=[board], keys=None,
        question=_ask("attacker_hanging", [board], square=_sq(sq)),
        options=["no", "yes"],
        descriptions=[f"Every enemy piece that attacks {_sq(sq)} is either unattacked or "
                      f"defended by a piece of its own colour.",
                      f"At least one enemy piece that attacks {_sq(sq)} is attacked by "
                      f"the other side and has no defender of its own."],
        instructions=_instructions("attacked", "defended", "undefended"),
        target=int(want), meta={"square": _sq(sq), "n_attackers": len(_enemies(board, sq))})


def _n_checks(board) -> int:
    return sum(1 for m in board.legal_moves if board.gives_check(m))


# Checking moves grow with legal moves, so "the most mobile position" -- the trained
# control's answer -- named the gold on 0.387 of 300 questions against a 0.25 chance.
# Keeping only half of the draws where it does brings that to about chance, so the
# family cannot be answered by the control it is paired with.
KEEP_MOBILE_GOLD = 0.5


def _b_most_checks(boards, rng, want) -> Spec | None:
    vals = [_n_checks(b) for b in boards]
    spec = _multi(boards, vals, _ask("most_checks", boards),
                  _instructions("attacked", "legal", "check"), rng, margin=1,
                  desc=lambda k: f"The position filed under {k}.")
    if spec is None:
        return None
    mob = [b.legal_moves.count() for b in boards]
    if mob.count(max(mob)) == 1 and mob.index(max(mob)) == spec.target \
            and rng.random() >= KEEP_MOBILE_GOLD:
        return None
    return spec


BUILDERS: dict[str, Callable] = {
    "attacked": _b_attacked,
    "defended": _b_defended,
    "pinned": _b_pinned,
    "legal_move": _b_legal_move,
    "mobility": _b_mobility,
    "material": _b_material,
    "gives_check": _b_gives_check,
    "defended_by_pinned": _b_defended_by_pinned,
    "hanging_square": _b_hanging_square,
    "most_attacked": _b_most_attacked,
    "most_mobile": _b_most_mobile,
    "material_edge": _b_material_edge,
    "after_move_attacked": _b_after_move_attacked,
    "discovered_check": _b_discovered_check,
    "hanging_defender": _b_hanging_defender,
    "most_pinned": _b_most_pinned,
    "most_hanging": _b_most_hanging,
    "after_move_hanging": _b_after_move_hanging,
    "after_move_pinned": _b_after_move_pinned,
    "attacker_hanging": _b_attacker_hanging,
    "most_checks": _b_most_checks,
}

# how many classes a family's builder balances over, when it takes a `want`
CLASSES = {
    "attacked": 2, "defended": 4, "pinned": 2, "legal_move": 2, "mobility": 4,
    "material": 5, "gives_check": 2, "defended_by_pinned": 2,
    "after_move_attacked": 2, "discovered_check": 3, "hanging_defender": 2,
    "after_move_pinned": 2, "attacker_hanging": 2,
    # 4, not 2: the builder only tests `want` for truth, so three draws in four ask for a
    # hanging piece and the sentinel is the answer a quarter of the time rather than half
    # -- about the share a 5-to-8-option question would give any one option. An earlier
    # build shipped a sentinel that was correct whenever it was present and the model
    # answered it at p = 1.0; the sentinel audit still calls 0.51 too high.
    "hanging_square": 4, "after_move_hanging": 4,
}
# families whose builder draws a sentinel wording and therefore needs the split
WANTS_SPLIT = ("hanging_square", "after_move_hanging")


def build(name: str, boards: list, rng: random.Random, want, split: str) -> Spec | None:
    fn = BUILDERS[name]
    if name in WANTS_SPLIT:
        return fn(boards, rng, want, split)
    return fn(boards, rng, want)


# ---- loaders -----------------------------------------------------------------------

def _loader(fam: Family, split: str, seed: int):
    def load(n: int) -> Iterator[Example]:
        import chess                                     # noqa: F401  (fails loudly here)

        fens = dev_pool() if fam in DEV_HELDOUT else pool(reserved=fam in HELDOUT)
        if not fens:
            raise RuntimeError(
                "chessfacts: the position pool is empty. Random playouts need nothing but "
                "python-chess, so an empty pool means `import chess` succeeded and the "
                "generator still produced nothing -- do not ship this row silently.")
        rng = random.Random(int.from_bytes(
            hashlib.sha256(f"{seed}:{fam.name}".encode()).digest()[:8], "big"))
        # Walk the pool in this family's own shuffled order. The pool is built in a fixed
        # 1 puzzle : 3 playout pattern, and the requested answer alternates no/yes, so a
        # sequential walk tied the answer to the KIND of position: tactical puzzles went
        # to one answer, quiet playouts to the other -- a shortcut underneath every
        # per-board check (found through defended_by_pinned).
        fens = fens[:]
        rng.shuffle(fens)
        reset_balance()
        classes = CLASSES.get(fam.name)
        want_i = 0
        made = 0
        limit = min(n, PER_TASK)
        i = 0
        tries = 0
        # matched sampling (`_matched`) rejects boards where no shallow key carries both
        # answers; the strictest families need ~75 boards per example
        max_tries = limit * 150 + 400
        while made < limit and tries < max_tries:
            tries += 1
            if fam.boards == 1:
                # a random board per attempt, not the next one: cycling a pool whose few
                # qualifying boards recur in a fixed order made each of them land on the
                # same answer every cycle under the no/yes alternation
                boards = [chess.Board(fens[rng.randrange(len(fens))])]
                i += 1
            else:
                boards = [chess.Board(fens[(i + j * 977) % len(fens)])
                          for j in range(fam.boards)]
                # the pool is interleaved, so slot j always drew from the same stratum
                # and `position_d` was the answer 5 times in 60. Shuffle the slots.
                rng.shuffle(boards)
                i += 1
            want = None if classes is None else want_i % classes
            spec = build(fam.name, boards, rng, want, split)
            if spec is None:
                continue
            if classes is not None:
                want_i += 1
            shape = RENDERINGS[made % len(RENDERINGS)]
            yield _example(spec, f"chessfact_{fam.name}", shape, qid=fam.name)
            made += 1
        # the tally belongs to this task only; a direct builder call made after a loader
        # (tests, audits) must not inherit it
        clear_balance()
    return load


def tasks() -> list[RealTask]:
    """Thirteen trained families of depth 1 and 2, five held-out families of depth 3 in
    `testreal`, and three more depth-3 families in `devreal`, disjoint from both.

    Every task is forced to a split. Leaving the held-out side to `split_of`'s hash is
    how `rules.py` lost nineteen of twenty-four intended eval tasks back into `train`.
    """
    out: list[RealTask] = []
    for fam in TRAINED:
        out.append(RealTask(
            row=ROW, name=f"chessfact_{fam.name}", licence=LICENCE, url=URL,
            load=_loader(fam, "train", seed=430),
            ordinal=fam.ordinal, real=False, force_split="train",
            notes=f"depth {fam.depth} [{'+'.join(fam.prims)}]: {fam.note}; "
                  f"python-chess-labelled, trained"))
    for fam in HELDOUT:
        out.append(RealTask(
            row=ROW, name=f"chessfact_{fam.name}", licence=LICENCE, url=URL,
            load=_loader(fam, "eval", seed=4307),
            ordinal=fam.ordinal, real=False, force_split="testreal",
            notes=f"depth {fam.depth} [{'+'.join(fam.prims)}]: {fam.note}; "
                  f"python-chess-labelled, NEVER trained on -- paired against the "
                  f"trained chessfact_{fam.control}"))
    for fam in DEV_HELDOUT:
        out.append(RealTask(
            row=ROW, name=f"chessfact_{fam.name}", licence=LICENCE, url=URL,
            load=_loader(fam, "eval", seed=4311),
            ordinal=fam.ordinal, real=False, force_split="devreal",
            notes=f"depth {fam.depth} [{'+'.join(fam.prims)}]: {fam.note}; "
                  f"python-chess-labelled; held out of train and test; a dev structure -- "
                  f"selects checkpoints and fits T; paired against the trained "
                  f"chessfact_{fam.control}"))
    return out
