"""Row 47 -- rules as random compositions, held out by composition and by depth.

Row 33 (`rules.py` over `grammar.py`) showed that primitives compose when the model has
seen the combination: trained rule forms 0.978, held-out forms 0.598, and cross-record
comparison at chance (0.267). But it trains a fixed list of thirteen combinations, holds
out six, never goes past depth two, renders states two ways and words each primitive one
way. A model can learn thirteen templates. This row is built so that it cannot.

**Primitives** (every one trained on its own, at depth 1):

    cmp      a numeric field against a constant   >  <  >=  <=  (and =, != on small counts)
    eq       a categorical field = / != a value
    range    a numeric field inside / outside [lo, hi] (inclusive)
    member   a categorical field in / not in a set
    fref     a field against its limit in the SAME record   (`weight` vs `weight_limit`)
    pref     a field against a bound held in ANOTHER record, the policy / limits record
    all any none atleast   a quantifier over every record shown, of one of the six above
    agg      count / sum / mean / min / max over the records, against a constant
    cross    this record against another: a named record, the max / min, a rank position

**Connectives**: `and`, `or` (2-3 children), `not`, `implies`, `xor` (exactly one of 2-3).

**The split is taken over the signature.** A tree's signature is its operator structure
over primitive kinds, commutative children sorted (`and(cmp,or(agg,member))`). Depth 1
(one primitive) always trains. Depth 2-3 signatures are hashed 80/10/10 into train /
devreal / testreal; every depth-4 signature is hashed 50/50 into devreal / testreal and
never trains. What dev and test hold out is therefore *compositions and depths*, never
primitives: a miss there is a failure to compose things the model has met.

**Paraphrase is held out too.** Every piece of rule text comes from a template bank
(`BANKS`); about a quarter of each bank's templates never reach training. Half of each
dev/test question is worded with held-out templates wherever the bank has one, and
`meta.tpl` says which half a question is in, so dev measures paraphrase transfer beside
composition transfer.

**Labels are computed, balanced clause-first** (the lesson of the v24 audit of row 33:
one clause decided 87-94 % of held-out combinations, and a primitive's constant could be
skipped 81-90 % of the time). The answer each task owes (`no` or `yes`, whichever it has
emitted less) is chosen first; then a truth pattern over the tree's leaves giving that
answer, weighted so a pattern where some single leaf is decisive is ten times as likely
as one where none is; then each leaf is *built* to have its truth, by placing its constant
just either side of the value it reads (the side drawn independently of where the value
sits in its range), or by setting the values its own fields hold. So no leaf, no field and
no constant-free reading of a leaf carries the answer beyond what the tree's structure
gives it, and a shortcut audit measures that.

**Seven state formats**: JSON, YAML, prose, a markdown table, CSV, `key: value` blocks,
and path-flattened lines (`lod.serialize.flatten_paths`). The records of a state always
carry the same fields as each other (row 33's domain-2 audit found records with different
key sets were a tell nobody chose).

**Question shapes**: mostly yes/no, the rule as the `yes` description and its negation as
the `no`; about a third are routing questions (two to four rules as options, exactly one
true). A few questions list a sentinel option (`lod.sentinel`), at rates set so the row
passes the sentinel audit (`lod.corpus.services.audit`) on its own (see
`P_NOUL_SENTINEL`). When the sentinel is the answer, either no rule holds or a field the
rule reads has been removed from the state -- only a field whose absence leaves the rule
truly undecided -- with `meta.abstain = True`.
"""

from __future__ import annotations

import csv
import copy
import hashlib
import io
import itertools
import json
import random
import re
from dataclasses import dataclass, replace
from typing import Iterator

import yaml

from lod import sentinel
from lod.schema import Example, Question
from lod.serialize import flatten_paths
from lod.corpus.services.sources.real.base import RealTask
from lod.corpus.services.sources.synth.records import DOMAINS as BASE_DOMAINS
from lod.corpus.services.sources.synth.records import (
    Domain,
    Enum,
    Num,
    _label,
    _ref,
    as_prose,
    make_record,
)

ROW = 47
LICENCE = "generated by lod/corpus/services/sources/synth/compose.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/compose.py"

MAX_DEPTH = 4
MAX_LEAVES = 6
ROUTE_MAX_LEAVES = 4
N_RECORDS = (3, 6)
P_ROUTE = 0.35            # share of questions that are routing (pick the rule that holds)
P_SECOND = 0.45           # chance an example carries a second question
# ---- the sentinel, held to the corpus's own statistics -------------------------------
# The sentinel audit replays `lod.training.data.augment_criteria`, which puts its own
# sentinel on ~40 % of every *eligible* choice question (>= 3 options, one-hot target), and
# scores what a model learns from all of them together. An earlier build listed a
# sentinel on 80 % of this row's choice questions and made it the answer 42 % of the time
# (yes/no/sentinel is always three options), so "yes / no / X -> X is plausible" was a
# prior worth learning. The rates below put the row inside the six acceptance bars on its
# own: sentinel on <= a third of choice questions, right about one time in six, its arity
# matched to the questions without one.
#
# What that costs is abstention volume: at P(right | listed) ~0.17 and a share <= 0.34,
# at most ~6 % of choice questions -- about 2 % of this row -- can abstain.
P_NOUL_SENTINEL = 0.04    # a yes/no question lists a sentinel (and becomes a choice question)
P_NOUL_ABSTAIN = 0.22     # ... which is the answer (a field the rule needs is removed)
# routing forms: two rules, no sentinel (never eligible for the augmentation, so it
# carries none there either); three rules, no sentinel (the augmentation's); a sentinel of
# its own beside two rules. Every question that can carry a sentinel therefore has exactly
# three options, with one or without: the audit's arity comparison is equal by
# construction. Four-rule routes, drawn 40 % of the time, left it at the mercy of
# sampling -- 0.06-0.07 total variation on a split of ~100-200 plain questions (bar 0.05).
ROUTE_FORMS = (("two", 0.60), ("plain", 0.25), ("sentinel", 0.15))
P_ROUTE_SENT_RIGHT = 0.22  # "sentinel": it is the answer ...
P_NONE_APPLY = 0.40        # ... because no rule holds (else a field is removed)
P_INDIRECT = 0.50         # rules that name fields by what they record, not by key
P_POLICY_DISTRACTOR = 0.35
P_DROP_DISTRACTOR = 0.20  # each field no rule reads is left out of a state this often
P_EQ = 0.10               # a constant placed exactly on the value, where the op allows it
P_NONCRITICAL = 0.10      # weight of a leaf-truth pattern no single flip would change
P_TIGHT = 0.15            # a constant placed within 2 % of the range of its value
NEAR = 0.08               # otherwise 2-8 %. A constant sits on the owed side of its value,
                          # so its own position leaks the side by about the mean gap; at
                          # 3.5-15 % "a low bar and the rule says greater" read `cmp` 0.60
CLUSTER = 0.10            # numeric fields of a state drawn within +/- 10 % of a centre
TRIES = 24

FORMATS = ("json", "yaml", "prose", "table", "csv", "kv", "paths")
RECORD_KINDS = ("cmp", "eq", "range", "member", "fref", "pref")
QUANT_KINDS = ("all", "any", "none", "atleast")
KINDS = RECORD_KINDS + QUANT_KINDS + ("agg", "cross")
AGG_FNS = ("count", "sum", "mean", "min", "max")
CROSS_MODES = ("named", "extreme", "rank")
OPS = ("and", "or", "not", "implies", "xor")
COMMUTATIVE = ("and", "or", "xor")
OP_WEIGHTS = {"and": 0.30, "or": 0.28, "not": 0.14, "implies": 0.13, "xor": 0.15}
SPLITS = ("train", "devreal", "testreal")


# ==== domains =========================================================================
# `records.DOMAINS` carries one measured/limit pair per domain. A rule that compares a
# field with its own limit is the commonest shape a real policy has ("over its weight
# limit", "past its SLA"), so each domain gains two more pairs here -- as new fields of
# this module's own copy of the domain, leaving row 33's records untouched.

@dataclass(frozen=True)
class CDomain:
    dom: Domain
    plural: str
    coll: str                          # the state's key for the list of records
    pairs: tuple[tuple[str, str], ...]  # (measured, limit), both fields of one record

    @property
    def noun(self) -> str:
        return self.dom.noun

    @property
    def idf(self) -> str:
        return self.dom.ids[0]

    def num(self, name: str) -> Num:
        return next(f for f in self.dom.nums if f.name == name)

    @property
    def limits(self) -> set[str]:
        return {b for _, b in self.pairs}

    @property
    def meas(self) -> list[Num]:
        """Numeric fields a constant is compared with: every number but the limits."""
        return [f for f in self.dom.nums if f.name not in self.limits]

    @property
    def enums(self) -> list[Enum]:
        return list(self.dom.enums)


_EXTRA = {
    "shipment": ("shipments", "shipments", (
        (Num("transit_allowance_days", 1, 21, " days", label="transit allowance",
             gloss="the longest transit its service allows"), "transit_days"),
        (Num("insured_value_usd", 15, 4200, " USD", label="insured value",
             gloss="how much the shipment is insured for"), "declared_value_usd"))),
    "sensor": ("sensor readings", "readings", (
        (Num("humidity_limit_pct", 5, 99, " %", label="humidity limit",
             gloss="the highest humidity its site tolerates"), "humidity_pct"),
        (Num("battery_floor_mv", 2400, 4200, " mV", label="battery floor",
             gloss="the lowest battery level it may run at"), "battery_mv"))),
    "incident": ("incident tickets", "tickets", (
        (Num("error_budget_pct", 0, 97, " %", False, label="error budget",
             gloss="the failure rate the service is allowed"), "error_rate_pct"),
        (Num("restart_limit", 0, 14, label="restart limit",
             gloss="how many restarts are allowed before escalation"), "restarts"))),
    "build": ("build jobs", "builds", (
        (Num("allowed_failures", 0, 37, label="allowed failures",
             gloss="how many test failures are tolerated"), "test_failures"),
        (Num("queue_wait_limit_s", 0, 1700, " s", label="queue wait limit",
             gloss="the longest it may wait to start"), "queue_wait_s"))),
    "order": ("purchase orders", "orders", (
        (Num("discount_cap_pct", 0, 45, " %", label="discount cap",
             gloss="the largest discount it may carry"), "discount_pct"),
        (Num("approval_limit_eur", 9, 9800, " EUR", False, label="approval limit",
             gloss="the most it may come to without extra approval"), "line_total_eur"))),
    "vehicle": ("vehicle records", "vehicles", (
        (Num("tyre_pressure_floor_kpa", 140, 340, " kPa", label="tyre pressure floor",
             gloss="the lowest tyre pressure it may run at"), "tyre_pressure_kpa"),
        (Num("idle_limit_minutes", 0, 240, " min", label="idle limit",
             gloss="the longest it may sit idle"), "idle_minutes"))),
}


def _extend(d: Domain) -> CDomain:
    plural, coll, extra = _EXTRA[d.name]
    nums = d.nums + tuple(f for f, _ in extra)
    pairs = tuple((a, b) for a, b, _ in d.pairs) + tuple((a, f.name) for f, a in extra)
    return CDomain(replace(d, nums=nums), plural, coll, pairs)


CDOMAINS: tuple[CDomain, ...] = tuple(_extend(d) for d in BASE_DOMAINS)
# policy keys are `max_<field>` / `min_<field>`; a record field spelled that way would be
# the same name in two places of one state
assert not any(f.name.startswith(("max_", "min_")) for cd in CDOMAINS for f in cd.dom.fields)


# ==== template banks ==================================================================
# Every piece of rule and question text is drawn from here. `{x}` is the subject (a field
# reference or an aggregate), `{c}` the object (a constant, a second field, a bound held
# in the policy record, or another record's value). A template starting `#` only reads
# with a number as its object ("is 9 days or more"); the `#` is stripped.

BANKS: dict[str, tuple[str, ...]] = {
    "q_noul": (
        "Does {noun} {fid} meet the rule?",
        "Should {noun} {fid} be flagged under this rule?",
        "Does the rule hold for {noun} {fid}?",
        "Is the condition satisfied for {noun} {fid}?",
        "Does {noun} {fid} qualify under the rule?",
        "Apply the rule to {noun} {fid}: is it met?",
        "For {noun} {fid}, is the stated condition true?",
        "Is {noun} {fid} caught by this rule?",
    ),
    "q_route": (
        "Which action applies to {noun} {fid}?",
        "Which of these rules does {noun} {fid} fall under?",
        "Route {noun} {fid}: whose condition does it meet?",
        "Which option's condition is true of {noun} {fid}?",
        "Pick the action whose rule {noun} {fid} satisfies.",
        "Under which rule does {noun} {fid} land?",
    ),
    # colon forms: the rule may itself open with "if" (an implication)
    "route_desc": (
        "Choose this when this holds: {r}.",
        "Applies if the following is true: {r}.",
        "Pick this if this is the case: {r}.",
        "Select this when: {r}.",
        "This one fits when the following holds: {r}.",
        "Use this option if: {r}.",
    ),
    "ref_key": ("`{key}`", "the `{key}` field", "the value of `{key}`", "{key}",
                "the `{key}` value", "the `{key}` entry"),
    "ref_label": ("the {label}", "its {label}", "the recorded {label}", "the listed {label}",
                  "the stated {label}"),
    "ref_ind": ("the field that records {gloss}", "the value recording {gloss}",
                "whichever field gives {gloss}", "the entry that tells {gloss}",
                "the figure for {gloss}", "the value that captures {gloss}"),
    # after a determiner ("the average {xb}", "the highest {xb}")
    "ref_ind_bare": ("figure for {gloss}", "value recording {gloss}", "reading of {gloss}",
                     "entry for {gloss}"),
    "gt": ("{x} is greater than {c}", "{x} exceeds {c}", "{x} is above {c}",
           "{x} is more than {c}", "{c} is exceeded by {x}", "{x} is strictly over {c}",
           "{x} comes out higher than {c}"),
    "lt": ("{x} is less than {c}", "{x} is below {c}", "{x} falls short of {c}",
           "{x} is under {c}", "{c} is greater than {x}", "{x} is strictly lower than {c}",
           "{x} comes out lower than {c}"),
    "ge": ("{x} is at least {c}", "{x} is no less than {c}", "#{x} is {c} or more",
           "{x} reaches {c}", "{x} is greater than or equal to {c}", "{x} is not below {c}",
           "{c} is reached or exceeded by {x}"),
    "le": ("{x} is at most {c}", "{x} is no more than {c}", "{x} does not exceed {c}",
           "#{x} is {c} or less", "{x} is less than or equal to {c}", "{x} is not above {c}",
           "{c} is not exceeded by {x}"),
    "eq_num": ("{x} is exactly {c}", "{x} equals {c}", "{x} is equal to {c}",
               "{x} comes to exactly {c}", "{x} is precisely {c}"),
    "ne_num": ("{x} is not {c}", "{x} is anything other than {c}", "{x} differs from {c}",
               "{x} does not equal {c}", "{x} is some number other than {c}"),
    "eq_enum": ("{x} is {c}", "{x} is set to {c}", "{x} reads {c}", "{x} has the value {c}",
                "{c} is the value of {x}", "{x} is recorded as {c}"),
    "ne_enum": ("{x} is not {c}", "{x} is anything other than {c}",
                "{x} is set to something other than {c}", "{x} does not read {c}",
                "{x} is recorded as something besides {c}", "{c} is not the value of {x}"),
    "range_in": ("{x} is between {lo} and {hi} inclusive", "{x} lies within {lo} to {hi}",
                 "{x} is in the range {lo} to {hi}",
                 "{x} is no lower than {lo} and no higher than {hi}",
                 "{x} sits inside the band from {lo} to {hi}",
                 "{x} falls in the closed interval from {lo} to {hi}"),
    "range_out": ("{x} is outside the range {lo} to {hi}", "{x} is below {lo} or above {hi}",
                  "{x} falls outside {lo} to {hi}",
                  "{x} is not between {lo} and {hi} inclusive",
                  "{x} lies outside the band from {lo} to {hi}",
                  "{x} falls outside the closed interval from {lo} to {hi}"),
    "set_in": ("{x} is one of {s}", "{x} is any of {s}", "{x} takes one of the values {s}",
               "{x} appears among {s}", "{x} matches one of {s}",
               "{x} belongs to the set {s}"),
    "set_out": ("{x} is none of {s}", "{x} is not one of {s}",
                "{x} takes a value outside {s}", "{x} is not among {s}",
                "{x} matches none of {s}", "{x} is outside the set {s}"),
    "set_fmt": ("{a} or {b}", "{{{l}}}"),
    "same_rec": ("{x}", "{x} of the same record", "{x} on that same record"),
    "pref_key": ("the `{pkey}` value in the {P} record", "`{pkey}` from the {P} record",
                 "the {P} record's setting `{pkey}`", "the {P} record's `{pkey}`",
                 "the `{pkey}` that the {P} record lists"),
    "pref_label": ("the {plabel} in the {P} record", "the {P} record's {plabel}",
                   "the {plabel} that the {P} record lists", "the {plabel} set by the {P} record"),
    "pref_ind": ("the {bound} the {P} record sets for it", "the {P} record's {bound} for this value",
                 "the {bound} permitted by the {P} record", "the {bound} that the {P} record allows",
                 "the {bound} given for it in the {P} record"),
    "all": ("for every {noun} in the batch, {p}", "{p}, and this holds for each of the {plural}",
            "each of the {plural} satisfies this: {p}", "all of the {plural} are such that {p}",
            "the condition that {p} is met by every {noun}",
            "without exception, for each {noun} listed, {p}"),
    "any": ("for at least one {noun} in the batch, {p}", "some {noun} satisfies this: {p}",
            "there is a {noun} for which {p}", "one or more of the {plural} are such that {p}",
            "the condition that {p} is met by at least one {noun}",
            "for some {noun} listed, {p}"),
    "none": ("for no {noun} in the batch is it true that {p}",
             "none of the {plural} satisfies this: {p}",
             "not a single {noun} is such that {p}", "there is no {noun} for which {p}",
             "the condition that {p} is met by no {noun}",
             "of the {plural}, zero are such that {p}"),
    "atleast": ("for at least {k} of the {plural}, {p}",
                "no fewer than {k} {plural} satisfy this: {p}",
                "{k} or more of the {plural} are such that {p}",
                "the condition that {p} is met by at least {k} {plural}",
                "a minimum of {k} {plural} satisfy this: {p}",
                "at least {k} {plural} in the batch are such that {p}"),
    "fewer": ("for fewer than {k} of the {plural}, {p}",
              "at most {km1} of the {plural} satisfy this: {p}",
              "no more than {km1} {plural} are such that {p}",
              "the condition that {p} is met by fewer than {k} {plural}",
              "under {k} of the {plural} satisfy this: {p}"),
    "agg_sum": ("the total of {x} across all the {plural}", "the sum of {x} over the batch",
                "{x} added up over every {noun}", "the combined {xb} of all the {plural}"),
    "agg_mean": ("the average {xb} across the {plural}", "the mean of {x} over all the {plural}",
                 "{x} averaged over the batch", "the arithmetic mean of {x} across every {noun}"),
    "agg_min": ("the smallest {xb} among the {plural}", "the minimum {xb} in the batch",
                "the lowest {xb} of any {noun}", "the least {xb} found among the {plural}"),
    "agg_max": ("the largest {xb} among the {plural}", "the maximum {xb} in the batch",
                "the highest {xb} of any {noun}", "the greatest {xb} found among the {plural}"),
    "agg_count": ("the number of {plural} for which {x} is {v}",
                  "how many {plural} have {x} equal to {v}",
                  "the count of {plural} with {x} set to {v}",
                  "the number of {plural} for which {x} reads {v}",
                  "the tally of {plural} where {x} is {v}"),
    "self": ("this {noun}", "{noun} {fid}", "the {noun} in question"),
    "cross_obj": ("the same field's value for {noun} {oid}", "that of {noun} {oid}",
                  "{noun} {oid}'s value", "the corresponding figure for {noun} {oid}",
                  "what {noun} {oid} records for it"),
    "ext_hi": ("{self} has the highest {xb} of all the {plural}",
               "{x} is higher for {self} than for any other {noun}",
               "among the {plural}, {self} has the largest {xb}",
               "{self} tops the batch on {x}",
               "no other {noun} matches or beats {self} on {x}"),
    "ext_lo": ("{self} has the lowest {xb} of all the {plural}",
               "{x} is lower for {self} than for any other {noun}",
               "among the {plural}, {self} has the smallest {xb}",
               "{self} sits at the bottom of the batch on {x}",
               "every other {noun} has a higher {xb} than {self}",
               "no other {noun} matches or undercuts {self} on {x}"),
    "ext_hi_neg": ("{self} does not have the highest {xb} of all the {plural}",
                   "some other {noun} has a higher {xb} than {self}",
                   "{self} is not the {noun} with the largest {xb}",
                   "at least one other {noun} beats {self} on {x}",
                   "the maximum {xb} belongs to a {noun} other than {self}"),
    "ext_lo_neg": ("{self} does not have the lowest {xb} of all the {plural}",
                   "some other {noun} has a lower {xb} than {self}",
                   "{self} is not the {noun} with the smallest {xb}",
                   "at least one other {noun} comes in below {self} on {x}",
                   "the minimum {xb} belongs to a {noun} other than {self}"),
    "rank_hi": ("{self} is among the {k} {plural} with the highest {xb}",
                "{self} ranks in the top {k} of the batch by {x}",
                "at most {km1} other {plural} have a higher {xb} than {self}",
                "by {x}, {self} is one of the {k} highest",
                "sorting by {x} from highest, {self} is within the first {k}"),
    "rank_lo": ("{self} is among the {k} {plural} with the lowest {xb}",
                "{self} ranks in the bottom {k} of the batch by {x}",
                "at most {km1} other {plural} have a lower {xb} than {self}",
                "by {x}, {self} is one of the {k} lowest",
                "sorting by {x} from lowest, {self} is within the first {k}"),
    "rank_hi_neg": ("{self} is not among the {k} {plural} with the highest {xb}",
                    "{self} ranks below the top {k} of the batch by {x}",
                    "at least {k} other {plural} have a higher {xb} than {self}",
                    "by {x}, {self} is outside the {k} highest",
                    "sorting by {x} from highest, {self} comes after the first {k}"),
    "rank_lo_neg": ("{self} is not among the {k} {plural} with the lowest {xb}",
                    "{self} ranks above the bottom {k} of the batch by {x}",
                    "at least {k} other {plural} have a lower {xb} than {self}",
                    "by {x}, {self} is outside the {k} lowest",
                    "sorting by {x} from lowest, {self} comes after the first {k}"),
    "and2": ("{a} and {b}", "both {a} and {b}", "{a}, and also {b}", "{a}; in addition, {b}",
             "{a}, together with {b}"),
    "andn": ("all of the following hold: {items}", "each of these is true: {items}",
             "every one of these conditions is met: {items}",
             "the following are all the case: {items}"),
    "or2": ("{a} or {b}", "either {a} or {b}, or both", "{a}, or otherwise {b}",
            "{a}, or else {b} (or both)", "{a} or {b} (either will do)"),
    "orn": ("at least one of the following holds: {items}", "any of these is true: {items}",
            "one or more of these conditions is met: {items}",
            "some of the following is the case: {items}"),
    "not": ("it is not the case that {a}", "it is false that {a}",
            "the following does not hold: {a}", "not so: {a}",
            "it is untrue that {a}"),
    "implies": ("if {a}, then {b}", "whenever {a}, {b}", "{b} in every case where {a}",
                "{a} implies {b}", "{b}, provided that {a}", "in any case where {a}, {b}"),
    "xor2": ("either {a} or {b}, but not both", "exactly one of these holds: {items}",
             "one and only one of these is true: {items}", "{a} or {b}, but not the two together"),
    "xorn": ("exactly one of the following holds: {items}",
             "one and only one of these is true: {items}",
             "precisely one of these conditions is met: {items}",
             "a single one, and no more, of these holds: {items}"),
    "xor_neg": ("the number of the following that hold is not exactly one: {items}",
                "either none or more than one of these holds: {items}",
                "it is not the case that exactly one of these holds: {items}",
                "zero, or at least two, of these are true: {items}"),
    "neg_wrap": ("it is not the case that {a}", "the following does not hold: {a}",
                 "it is false that {a}", "this rule is not met: {a}",
                 "the opposite of this holds: {a}"),
}

MARKERS = (lambda i: f"({i + 1})", lambda i: f"({chr(97 + i)})",
           lambda i: f"({('i', 'ii', 'iii', 'iv')[i]})")
ACTIONS = ("escalate", "hold", "release", "review", "reroute", "archive", "expedite",
           "audit", "approve", "quarantine")


def _heldout_templates() -> dict[str, frozenset[str]]:
    """A quarter of each bank (rounded, at least one where a bank has three or more),
    chosen by a hash of the template so the choice never moves when a bank grows
    elsewhere. Never drawn in training."""
    out = {}
    for name, tpls in BANKS.items():
        k = max(1, round(len(tpls) / 4)) if len(tpls) >= 3 else 0
        ranked = sorted(tpls, key=lambda t: hashlib.sha256(f"{name}|{t}".encode()).digest())
        out[name] = frozenset(ranked[:k])
    return out


HELDOUT_TEMPLATES = _heldout_templates()


# ==== signatures and the split ========================================================
# A skeleton is a nested tuple: a leaf is its kind string, a node is (op, *children).

def sig_of(sk) -> str:
    if isinstance(sk, str):
        return sk
    op, *kids = sk
    parts = [sig_of(k) for k in kids]
    if op in COMMUTATIVE:
        parts.sort()
    return f"{op}({','.join(parts)})"


def depth_of(sk) -> int:
    return 1 if isinstance(sk, str) else 1 + max(depth_of(k) for k in sk[1:])


def leaves_of(sk) -> list[str]:
    return [sk] if isinstance(sk, str) else [x for k in sk[1:] for x in leaves_of(k)]


def ops_of(sk) -> list[str]:
    return [] if isinstance(sk, str) else [sk[0]] + [o for k in sk[1:] for o in ops_of(k)]


def split_of_sig(sig: str, depth: int) -> str:
    """Depth 1 trains. Depth 2-3: 80/10/10 by hash. Depth 4: dev/test only, 50/50."""
    if depth <= 1:
        return "train"
    h = int.from_bytes(hashlib.sha256(f"compose:{sig}".encode()).digest()[:8], "big") % 100
    if depth <= 3:
        return "train" if h < 80 else ("devreal" if h < 90 else "testreal")
    return "devreal" if h < 50 else "testreal"


def sample_skeleton(rng: random.Random, depth: int, parent: str | None = None):
    """A random tree of exactly `depth`. An associative op never nests in itself (the
    flat n-ary form is used instead, so one composition has one signature), and `not`
    never wraps `not`."""
    if depth == 1:
        return rng.choice(KINDS)
    ops = [o for o in OPS if not (o == parent and o in ("and", "or", "xor", "not"))]
    op = rng.choices(ops, weights=[OP_WEIGHTS[o] for o in ops])[0]
    if op == "not":
        return ("not", sample_skeleton(rng, depth - 1, "not"))
    arity = 2 if op == "implies" or rng.random() < 0.8 else 3
    main = rng.randrange(arity)
    kids = []
    for i in range(arity):
        d = depth - 1 if i == main else (1 if rng.random() < 0.6 else rng.randint(1, depth - 1))
        kids.append(sample_skeleton(rng, d, op))
    return (op, *kids)


def skeleton_for(rng: random.Random, split: str, depth: int, max_leaves: int = MAX_LEAVES):
    for _ in range(4000):
        sk = sample_skeleton(rng, depth)
        if len(leaves_of(sk)) <= max_leaves and split_of_sig(sig_of(sk), depth) == split:
            return sk
    raise RuntimeError(f"no depth-{depth} skeleton lands in {split}")


# ==== evaluation ======================================================================

def _cmp(a: float, op: str, b: float) -> bool:
    eps = 1e-9
    if op == ">":
        return a > b + eps
    if op == "<":
        return a < b - eps
    if op == ">=":
        return a >= b - eps
    if op == "<=":
        return a <= b + eps
    if op == "==":
        return abs(a - b) <= eps
    if op == "!=":
        return abs(a - b) > eps
    raise ValueError(op)


NEG_OP = {">": "<=", "<=": ">", "<": ">=", ">=": "<", "==": "!=", "!=": "=="}
OP_BANK = {">": "gt", "<": "lt", ">=": "ge", "<=": "le", "==": "eq_num", "!=": "ne_num"}


@dataclass
class State:
    cd: CDomain
    recs: list[dict]
    focus: int
    policy: dict
    pname: str

    @property
    def fid(self) -> str:
        return self.recs[self.focus][self.cd.idf]

    def snapshot(self):
        return copy.deepcopy(self.recs), dict(self.policy)

    def restore(self, snap) -> None:
        self.recs, self.policy = copy.deepcopy(snap[0]), dict(snap[1])

    def as_obj(self) -> dict:
        obj = {self.cd.coll: self.recs}
        if self.policy:
            obj[self.pname] = self.policy
        return obj


class Leaf:
    """A primitive. `spec` is JSON-serialisable and is all an independent evaluator
    needs; `reads` names every field (and `policy:<key>`) the leaf looks at."""

    def __init__(self, kind: str, spec: dict, reads: set[str]):
        self.kind, self.spec, self.reads = kind, spec, reads

    def value(self, st: State) -> bool | None:
        return eval_leaf(self.spec, st.as_obj(), st.cd.coll, st.pname, st.cd.idf, st.fid)


def _atom(spec: dict, rec: dict, policy: dict | None) -> bool | None:
    """A record-level primitive on one record; None when a field it reads is absent."""
    k = spec["k"]
    if k == "cmp":
        v = rec.get(spec["f"])
        return None if v is None else _cmp(v, spec["op"], spec["c"])
    if k == "eq":
        v = rec.get(spec["f"])
        return None if v is None else ((v == spec["v"]) == (spec["op"] == "=="))
    if k == "range":
        v = rec.get(spec["f"])
        if v is None:
            return None
        return (spec["lo"] - 1e-9 <= v <= spec["hi"] + 1e-9) == spec["inside"]
    if k == "member":
        v = rec.get(spec["f"])
        return None if v is None else ((v in spec["vals"]) == spec["inside"])
    if k == "fref":
        a, b = rec.get(spec["a"]), rec.get(spec["b"])
        return None if a is None or b is None else _cmp(a, spec["op"], b)
    if k == "pref":
        v = rec.get(spec["f"])
        c = (policy or {}).get(spec["key"])
        return None if v is None or c is None else _cmp(v, spec["op"], c)
    raise ValueError(k)


def eval_leaf(spec: dict, obj: dict, coll: str, pname: str, idf: str, fid) -> bool | None:
    recs = obj[coll]
    policy = obj.get(pname)
    focus = next(r for r in recs if r.get(idf) == fid)
    k = spec["k"]
    if k in RECORD_KINDS:
        return _atom(spec, focus, policy)
    if k in QUANT_KINDS:
        vals = [_atom(spec["phi"], r, policy) for r in recs]
        t, u = vals.count(True), vals.count(None)
        need = {"all": len(vals), "any": 1, "none": 1, "atleast": spec.get("n", 1)}[k]
        if t >= need:
            res = True
        elif t + u < need:
            res = False
        else:
            return None
        return (not res) if k == "none" else res
    if k == "agg":
        if spec["fn"] == "count":
            vals = [r.get(spec["f"]) for r in recs]
            if any(v is None for v in vals):
                return None
            a = sum(v == spec["v"] for v in vals)
        else:
            vals = [r.get(spec["f"]) for r in recs]
            if any(v is None for v in vals):
                return None
            a = {"sum": lambda x: round(sum(x), 6), "mean": lambda x: sum(x) / len(x),
                 "min": min, "max": max}[spec["fn"]](vals)
        return _cmp(a, spec["op"], spec["c"])
    if k == "cross":
        f = spec["f"]
        if any(r.get(f) is None for r in recs):
            return None
        mine = focus[f]
        if spec["mode"] == "named":
            other = next(r for r in recs if r.get(idf) == spec["other"])
            return _cmp(mine, spec["op"], other[f])
        others = [r[f] for r in recs if r is not focus]
        beat = sum((v > mine) if spec["hi"] else (v < mine) for v in others)
        if spec["mode"] == "extreme":
            return beat == 0
        return beat < spec["n"]
    raise ValueError(k)


def eval_tree(tree, st: State) -> bool | None:
    """Kleene three-valued evaluation. Exact here because no field is read by two leaves
    of one tree (`Build.avoid`), so the unknowns are independent."""
    if isinstance(tree, Leaf):
        return tree.value(st)
    op, kids = tree[0], tree[1:]
    vals = [eval_tree(k, st) for k in kids]
    return _combine(op, vals)


def _combine(op: str, vals: list) -> bool | None:
    if op == "not":
        return None if vals[0] is None else not vals[0]
    if op == "and":
        if False in vals:
            return False
        return None if None in vals else True
    if op == "or":
        if True in vals:
            return True
        return None if None in vals else False
    if op == "implies":
        a, b = vals
        return _combine("or", [None if a is None else not a, b])
    if op == "xor":
        t, u = vals.count(True), vals.count(None)
        if t >= 2:
            return False
        if u:
            return None
        return t == 1
    raise ValueError(op)


def spec_of(tree) -> dict:
    if isinstance(tree, Leaf):
        return tree.spec
    return {"op": tree[0], "kids": [spec_of(k) for k in tree[1:]]}


def tree_leaves(tree) -> list[Leaf]:
    return [tree] if isinstance(tree, Leaf) else [x for k in tree[1:] for x in tree_leaves(k)]


def _sk_eval(sk, it) -> bool:
    if isinstance(sk, str):
        return next(it)
    return _combine(sk[0], [_sk_eval(k, it) for k in sk[1:]])


def patterns(sk, want: bool) -> list[tuple[tuple[bool, ...], float]]:
    """Every leaf-truth assignment giving `want`, weighted 1 when flipping some single
    leaf would change the answer, `P_NONCRITICAL` when none would."""
    n = len(leaves_of(sk))
    out = []
    for pat in itertools.product((False, True), repeat=n):
        if _sk_eval(sk, iter(pat)) is not want:
            continue
        crit = any(_sk_eval(sk, iter(pat[:i] + (not pat[i],) + pat[i + 1:])) is not want
                   for i in range(n))
        out.append((pat, 1.0 if crit else P_NONCRITICAL))
    return out


# ==== building leaves that have a given truth =========================================

def _rnd(integral: bool, x: float):
    return int(round(x)) if integral else round(x, 1)


def _gap(span: float, rng: random.Random) -> float:
    if rng.random() < P_TIGHT:
        return rng.uniform(0.005, 0.02) * span
    return rng.uniform(0.02, NEAR) * span


def _side(v, lo, hi, span, integral, below: bool, rng, min_gap: float = 0.0):
    """A constant strictly below (or above) `v`, inside [lo, hi], or None."""
    step = 1 if integral else 0.1
    d = max(_gap(span, rng), min_gap, step)
    room = (v - lo) if below else (hi - v)
    if room < max(step, min_gap):
        return None
    if d > room:
        d = rng.uniform(max(step, min_gap), room)
    c = _rnd(integral, v - d if below else v + d)
    if below and c >= v:
        c = _rnd(integral, v - step)
    if not below and c <= v:
        c = _rnd(integral, v + step)
    if c < lo - 1e-9 or c > hi + 1e-9:
        return None
    return c


def place(v, op, t, lo, hi, span, integral, rng, allow_eq=True, min_gap=0.0):
    """A constant `c` in [lo, hi] with `(v op c) is t`, or None. The side of `v` it sits
    on is fixed by (op, t); how far is drawn, so neither `c` nor `v` alone says which."""
    # which relations of c to v give the truth owed
    rel = {(">", True): "lt", (">", False): "ge", (">=", True): "le", (">=", False): "gt",
           ("<", True): "gt", ("<", False): "le", ("<=", True): "ge", ("<=", False): "lt",
           ("==", True): "eq", ("==", False): "ne", ("!=", True): "ne", ("!=", False): "eq"}
    r = rel[(op, t)]
    if r == "eq" or (r in ("le", "ge") and allow_eq and rng.random() < P_EQ):
        if r == "eq" and not allow_eq:
            return None
        c = _rnd(integral, v)
        return c if _cmp(v, op, c) is t else None
    if r == "ne":
        # equality ops live on small counts: a near miss, one or two either side
        c = v + rng.choice((-2, -1, 1, 2))
        return c if lo <= c <= hi and _cmp(v, op, c) is t else None
    below = r in ("lt", "le")
    c = _side(v, lo, hi, span, integral, below, rng, min_gap)
    if c is None or _cmp(v, op, c) is not t:
        return None
    return c


class Build:
    """Construction context for one example: which fields a tree has already used (a
    field is read by at most one leaf per tree, so evaluation stays exact) and which are
    frozen (read by an earlier tree of the same state, so nothing may change them)."""

    def __init__(self, st: State, rng: random.Random, frozen: set[str]):
        self.st, self.rng, self.frozen = st, rng, frozen
        self.avoid: set[str] = set()

    def pick(self, pool, mutate: bool = False, extra=lambda f: True):
        c = [f for f in pool if f.name not in self.avoid
             and not (mutate and f.name in self.frozen) and extra(f)]
        return self.rng.choice(c) if c else None


def _numops(f: Num) -> list[str]:
    ops = [">", "<", ">=", "<="]
    if f.integral and f.hi - f.lo <= 40:
        ops += ["==", "!="]
    return ops


def _vals(st: State, name: str) -> list:
    return [r[name] for r in st.recs]


def _count_const(vals, op, m, f: Num, rng) -> float | None:
    """A constant making exactly `m` of `vals` satisfy `v op c`."""
    n = len(vals)
    asc = sorted(vals)
    step = 1 if f.integral else 0.1
    span = f.hi - f.lo
    upward = op in (">", ">=")
    for _ in range(8):
        if m in (0, n):
            anchor = asc[-1] if (upward == (m == 0)) else asc[0]
            c = place(anchor, op, m == n, f.lo, f.hi, span, f.integral, rng, allow_eq=False)
        else:
            lo_v, hi_v = (asc[n - m - 1], asc[n - m]) if upward else (asc[m - 1], asc[m])
            if hi_v - lo_v < step - 1e-9:
                return None
            c = _rnd(f.integral, rng.uniform(lo_v, hi_v))
        # never a value some record holds: rounding an interior constant onto one only
        # happens when the count is strictly between 0 and n, so "the rule's number is in
        # the state" separated `none` from its negation (0.60)
        if (c is not None and sum(_cmp(v, op, c) for v in vals) == m
                and all(abs(v - c) > 1e-9 for v in vals)):
            return c
    return None


def _choose_m(q: str, k: int, n: int, t: bool, rng) -> int:
    """How many records satisfy the inner rule. Mostly one step from the boundary, so
    every record has to be read; never 0 or n where the answer does not force it, so the
    focus record can take the side `_focus_side` gives it."""
    near = rng.random() < 0.7
    if q == "all":
        return n if t else (n - 1 if near else rng.randint(1, n - 1))
    if q == "any":
        return (1 if near else rng.randint(1, n - 1)) if t else 0
    if q == "none":
        return 0 if t else (1 if near else rng.randint(1, n - 1))
    if t:
        return k if near or k >= n - 1 else rng.randint(k + 1, n - 1)
    return k - 1 if near or k <= 2 else rng.randint(1, k - 2)


def _focus_side(q: str, m: int, n: int, rng) -> bool:
    """Whether the focus record satisfies the inner rule, chosen so that it says nothing
    about the answer. The question names a record, and a reader who applies the inner
    rule to that record alone answered `all` / `any` / `none` / `atleast` 0.69-0.71 when
    the satisfying records were drawn at random. Where the answer forces the focus's
    side (every record satisfies an `all` that holds), it takes that side in every
    question of the kind; otherwise a coin (`atleast`)."""
    if m == 0:
        return False
    if m == n:
        return True
    if q == "all":
        return True
    if q in ("any", "none"):
        return False
    return rng.random() < 0.5


def _enum_fmt(vals) -> list:
    return sorted(vals)


def build_atom_focus(kind: str, t: bool, b: Build) -> Leaf | None:
    """A record-level primitive about the focus record, true iff `t`."""
    st, rng, cd = b.st, b.rng, b.st.cd
    rec = st.recs[st.focus]
    if kind == "cmp":
        f = b.pick(cd.meas)
        if f is None:
            return None
        op = rng.choice(_numops(f))
        c = place(rec[f.name], op, t, f.lo, f.hi, f.hi - f.lo, f.integral, rng)
        if c is None:
            return None
        return Leaf("cmp", {"k": "cmp", "f": f.name, "op": op, "c": c}, {f.name})
    if kind == "eq":
        e = b.pick(cd.enums)
        if e is None:
            return None
        op = rng.choice(("==", "!="))
        same = (op == "==") == t
        # The value named when it is NOT this record's is one another record holds, so
        # the value appears in the state either way: drawn from the whole enum, "the
        # value the rule names is nowhere in the state" answered `eq` with its op 0.73.
        others = [x for x in e.values if x != rec[e.name]]
        held = [x for x in others
                if any(r[e.name] == x for i, r in enumerate(st.recs) if i != st.focus)]
        v = rec[e.name] if same else rng.choice(held or others)
        return Leaf("eq", {"k": "eq", "f": e.name, "op": op, "v": v}, {e.name})
    if kind == "range":
        f = b.pick(cd.meas)
        if f is None:
            return None
        inside = rng.random() < 0.5
        lohi = _range_for(f, [rec[f.name]], int(t == inside), rng)
        if lohi is None:
            return None
        return Leaf("range", {"k": "range", "f": f.name, "lo": lohi[0], "hi": lohi[1],
                              "inside": inside}, {f.name})
    if kind == "member":
        e = b.pick(cd.enums, extra=lambda e: len(e.values) >= 3)
        if e is None:
            return None
        inside = rng.random() < 0.5
        k = rng.randint(2, len(e.values) - 1)
        others = [x for x in e.values if x != rec[e.name]]
        held = [x for x in others
                if any(r[e.name] == x for i, r in enumerate(st.recs) if i != st.focus)]
        # One anchor the state holds (this record's value, or a value another record
        # holds), then the rest from the same-sized pool either way: the other values
        # minus one held value. With the pool one held value richer when the set
        # contained this record's value, "most of the listed values are in the state"
        # read `member` with its direction 0.62.
        h = rng.choice(held or others)
        pool = [x for x in others if x != h]
        first = rec[e.name] if t == inside else h
        vals = [first] + rng.sample(pool, k - 1)
        return Leaf("member", {"k": "member", "f": e.name, "vals": _enum_fmt(vals),
                               "inside": inside}, {e.name})
    if kind == "fref":
        pairs = [(a, l) for a, l in cd.pairs if a not in b.avoid and l not in b.avoid
                 and l not in b.frozen]
        if not pairs:
            return None
        a, l = rng.choice(pairs)
        fa, fl = cd.num(a), cd.num(l)
        op = rng.choice((">", "<", ">=", "<="))
        c = place(rec[a], op, t, fl.lo, fl.hi, fl.hi - fl.lo, fl.integral, rng)
        if c is None:
            return None
        rec[l] = c
        return Leaf("fref", {"k": "fref", "a": a, "b": l, "op": op}, {a, l})
    if kind == "pref":
        f = b.pick(cd.meas, extra=lambda f: not any(
            f"policy:{bd}_{f.name}" in b.frozen | b.avoid for bd in ("max", "min")))
        if f is None:
            return None
        bound = rng.choice(("max", "min"))
        op = rng.choice((">", "<=") if bound == "max" else ("<", ">="))
        c = place(rec[f.name], op, t, f.lo, f.hi, f.hi - f.lo, f.integral, rng)
        if c is None:
            return None
        key = f"{bound}_{f.name}"
        st.policy[key] = c
        return Leaf("pref", {"k": "pref", "f": f.name, "key": key, "op": op},
                    {f.name, f"policy:{key}"})
    raise ValueError(kind)


def _range_for(f: Num, vals: list, m_inside: int, rng) -> tuple | None:
    """[lo, hi] holding exactly `m_inside` of `vals`, with no value on an edge.

    The band is placed anywhere in the field's range and kept if it holds the owed
    count, as `rules._leaf` learned to: built around the values instead (a window over
    them, or a gap between them), where the band sits said whether it held the value --
    "a band near the middle, and the rule says inside" answered `range` 0.66. The
    window construction below is only the fallback for counts the uniform draw rarely
    hits among clustered values."""
    step = 1 if f.integral else 0.1
    asc = sorted(vals)
    n = len(asc)
    span = f.hi - f.lo
    wlo = 0.10 if n == 1 else 0.03
    for _ in range(80):
        w = rng.uniform(wlo, 0.4) * span
        lo = _rnd(f.integral, rng.uniform(f.lo, f.hi - w))
        hi = _rnd(f.integral, lo + w)
        if hi <= lo or any(abs(v - lo) < step - 1e-9 or abs(v - hi) < step - 1e-9
                           for v in vals):
            continue
        if sum(lo <= v <= hi for v in vals) == m_inside:
            return lo, hi
    for _ in range(20):
        if m_inside == 0:
            gaps = [(f.lo - 0.0, asc[0])] + list(zip(asc, asc[1:])) + [(asc[-1], f.hi)]
            gaps = [(a, b) for a, b in gaps if b - a >= 3 * step]
            if not gaps:
                return None
            a, b = rng.choice(gaps)
            lo = _rnd(f.integral, rng.uniform(a + step, b - step))
            w = rng.uniform(0.05, 0.4) * span
            hi = _rnd(f.integral, min(lo + w, b - step))
            if hi < lo:
                continue
        else:
            i = rng.randint(0, n - m_inside)
            j = i + m_inside - 1
            left = asc[i - 1] if i > 0 else max(f.lo - 0.0, asc[0] - 0.4 * span)
            right = asc[j + 1] if j + 1 < n else min(f.hi, asc[-1] + 0.4 * span)
            if asc[i] - left < 2 * step and i > 0:
                continue
            if right - asc[j] < 2 * step and j + 1 < n:
                continue
            lo = _rnd(f.integral, rng.uniform(left + (step if i > 0 else 0), asc[i] - step))
            hi = _rnd(f.integral, rng.uniform(asc[j] + step, right - (step if j + 1 < n else 0)))
            if lo > asc[i] - step + 1e-9 or hi < asc[j] + step - 1e-9:
                continue
        inside = sum(lo <= v <= hi for v in vals)
        if inside == m_inside and lo < hi and all(abs(v - lo) >= step - 1e-9 and
                                                  abs(v - hi) >= step - 1e-9 for v in vals):
            return lo, hi
    return None


def build_quant(q: str, t: bool, b: Build) -> Leaf | None:
    st, rng, cd = b.st, b.rng, b.st.cd
    n = len(st.recs)
    k = rng.randint(2, n - 1) if q == "atleast" else 0
    m = _choose_m(q, k, n, t, rng)
    inner = rng.choice(RECORD_KINDS)
    extra = {"n": k} if q == "atleast" else {}
    fo = st.focus
    focus_in = _focus_side(q, m, n, rng)
    rest = [i for i in range(n) if i != fo]
    rng.shuffle(rest)
    chosen = set(rest[: m - 1]) | {fo} if focus_in else set(rest[:m])
    if inner in ("cmp", "pref"):
        f = b.pick(cd.meas, mutate=True, extra=(lambda f: True) if inner == "cmp" else (
            lambda f: not any(f"policy:{bd}_{f.name}" in b.frozen | b.avoid
                              for bd in ("max", "min"))))
        if f is None:
            return None
        if inner == "cmp":
            op = rng.choice((">", "<", ">=", "<="))
        else:
            bound = rng.choice(("max", "min"))
            op = rng.choice((">", "<=") if bound == "max" else ("<", ">="))
        c = _count_const(_vals(st, f.name), op, m, f, rng)
        if c is None:
            return None
        if inner == "cmp":
            phi = {"k": "cmp", "f": f.name, "op": op, "c": c}
            reads = {f.name}
        else:
            key = f"{bound}_{f.name}"
            st.policy[key] = c
            phi = {"k": "pref", "f": f.name, "key": key, "op": op}
            reads = {f.name, f"policy:{key}"}
    elif inner == "range":
        f = b.pick(cd.meas, mutate=True)
        if f is None:
            return None
        inside = rng.random() < 0.5
        lohi = _range_for(f, _vals(st, f.name), m if inside else n - m, rng)
        if lohi is None:
            return None
        phi = {"k": "range", "f": f.name, "lo": lohi[0], "hi": lohi[1], "inside": inside}
        reads = {f.name}
    elif inner in ("eq", "member"):
        e = b.pick(cd.enums, mutate=True,
                   extra=lambda e: len(e.values) >= (3 if inner == "member" else 2))
        if e is None:
            return None
        if inner == "eq":
            op = rng.choice(("==", "!="))
            v = rng.choice(e.values)
            yes_set, no_set = ([v], [x for x in e.values if x != v])
            if op == "!=":
                yes_set, no_set = no_set, yes_set
            phi = {"k": "eq", "f": e.name, "op": op, "v": v}
        else:
            inside = rng.random() < 0.5
            kk = rng.randint(2, len(e.values) - 1)
            s = sorted(rng.sample(list(e.values), kk))
            in_s, out_s = s, [x for x in e.values if x not in s]
            yes_set, no_set = (in_s, out_s) if inside else (out_s, in_s)
            phi = {"k": "member", "f": e.name, "vals": s, "inside": inside}
        for i, r in enumerate(st.recs):
            r[e.name] = rng.choice(yes_set if i in chosen else no_set)
        reads = {e.name}
    else:  # fref
        pairs = [(a, l) for a, l in cd.pairs if a not in b.avoid and l not in b.avoid
                 and l not in b.frozen]
        if not pairs:
            return None
        a, l = rng.choice(pairs)
        fl = cd.num(l)
        op = rng.choice((">", "<", ">=", "<="))
        for i, r in enumerate(st.recs):
            c = place(r[a], op, i in chosen, fl.lo, fl.hi, fl.hi - fl.lo, fl.integral, rng)
            if c is None:
                return None
            r[l] = c
        phi = {"k": "fref", "a": a, "b": l, "op": op}
        reads = {a, l}
    # a threshold or band decides which records satisfy by their values: move the focus
    # record to the side `_focus_side` chose by swapping its value with a record on the
    # other side (the count, and so the answer, is unchanged)
    if inner in ("cmp", "pref", "range"):
        fname = phi["f"]
        sat = [bool(_atom(phi, r, st.policy)) for r in st.recs]
        if sat[fo] != focus_in:
            swap = [i for i in range(n) if i != fo and sat[i] == focus_in]
            if not swap:
                return None
            j = rng.choice(swap)
            st.recs[fo][fname], st.recs[j][fname] = st.recs[j][fname], st.recs[fo][fname]
    return Leaf(q, {"k": q, "phi": phi, **extra}, reads)


def build_agg(t: bool, b: Build) -> Leaf | None:
    st, rng, cd = b.st, b.rng, b.st.cd
    n = len(st.recs)
    fn = rng.choice(AGG_FNS)
    op = rng.choice((">", "<", ">=", "<="))
    if fn == "count":
        e = b.pick(cd.enums, mutate=True)
        if e is None:
            return None
        v = rng.choice(e.values)
        cnt = rng.randint(0, n)
        idx = list(range(n))
        rng.shuffle(idx)
        for i, r in enumerate(st.recs):
            r[e.name] = v if i in idx[:cnt] else rng.choice([x for x in e.values if x != v])
        # a constant both answers are possible for, whatever the count: never ">= 0"
        lo, hi = {">": (0, n - 1), ">=": (1, n), "<": (1, n), "<=": (0, n - 1)}[op]
        c = place(cnt, op, t, lo, hi, n, True, rng)
        if c is None:
            return None
        return Leaf("agg", {"k": "agg", "fn": "count", "f": e.name, "v": v, "op": op,
                            "c": c}, {e.name})
    f = b.pick(cd.meas)
    if f is None:
        return None
    vals = _vals(st, f.name)
    span = f.hi - f.lo
    if fn == "sum":
        a = round(sum(vals), 6)
        lo, hi, sp, integral = f.lo * n, f.hi * n, span * n ** 0.5, f.integral
    elif fn == "mean":
        a = sum(vals) / n
        lo, hi, sp, integral = f.lo, f.hi, span, False
    else:
        a = min(vals) if fn == "min" else max(vals)
        lo, hi, sp, integral = f.lo, f.hi, span, f.integral
    exact = fn in ("min", "max")
    c = place(a, op, t, lo, hi, sp, integral, rng, allow_eq=exact,
              min_gap=0 if exact else max(0.015 * sp, 0.2))
    if c is None:
        return None
    return Leaf("agg", {"k": "agg", "fn": fn, "f": f.name, "op": op, "c": c}, {f.name})


def build_cross(t: bool, b: Build) -> Leaf | None:
    st, rng, cd = b.st, b.rng, b.st.cd
    n = len(st.recs)
    mode = rng.choice(CROSS_MODES)
    f = b.pick(cd.meas, mutate=True)
    if f is None:
        return None
    fo = st.focus
    if mode == "named":
        other = rng.choice([i for i in range(n) if i != fo])
        op = rng.choice((">", "<", ">=", "<="))
        c = place(st.recs[fo][f.name], op, t, f.lo, f.hi, f.hi - f.lo, f.integral, rng)
        if c is None:
            return None
        st.recs[other][f.name] = c
        return Leaf("cross", {"k": "cross", "mode": "named", "f": f.name,
                              "other": st.recs[other][cd.idf], "op": op}, {f.name})
    vals = _vals(st, f.name)
    if len(set(vals)) < n:
        return None                              # a tie makes rank and extreme ambiguous
    hi = rng.random() < 0.5
    order = sorted(range(n), key=lambda i: -vals[i] if hi else vals[i])   # rank 1 first
    if mode == "extreme":
        # a false case is mostly the runner-up, which is above the others' mean as the
        # leader is: "above average, so the highest" read `extreme` 0.64 otherwise
        r = 1 if t else (2 if rng.random() < 0.85 else rng.randint(2, n))
        spec = {"k": "cross", "mode": "extreme", "f": f.name, "hi": hi}
    else:
        k = rng.randint(2, n - 1)
        if t:
            r = k if rng.random() < 0.8 else rng.randint(1, k)
        else:
            r = k + 1 if rng.random() < 0.8 else rng.randint(k + 1, n)
        spec = {"k": "cross", "mode": "rank", "f": f.name, "hi": hi, "n": k}
    j = order[r - 1]
    st.recs[fo][f.name], st.recs[j][f.name] = st.recs[j][f.name], st.recs[fo][f.name]
    if mode == "rank":
        # likewise for a rank: "above the others' mean" is a coin, whatever the answer
        mine = st.recs[fo][f.name]
        others = [r[f.name] for i, r in enumerate(st.recs) if i != fo]
        if ((mine > sum(others) / len(others)) == hi) != (rng.random() < 0.5):
            return None
    if mode == "extreme" and not t:
        # the leader is always on the rule's side of the others' mean; so must the focus
        # be when it is not the leader, or "above average" reads the answer
        mine = st.recs[fo][f.name]
        others = [r[f.name] for i, r in enumerate(st.recs) if i != fo]
        if (mine > sum(others) / len(others)) != hi:
            return None
    return Leaf("cross", spec, {f.name})


def build_leaf(kind: str, t: bool, b: Build) -> Leaf | None:
    if kind in RECORD_KINDS:
        lf = build_atom_focus(kind, t, b)
    elif kind in QUANT_KINDS:
        lf = build_quant(kind, t, b)
    elif kind == "agg":
        lf = build_agg(t, b)
    else:
        lf = build_cross(t, b)
    if lf is None or lf.value(b.st) is not t:
        return None
    return lf


def _assemble(sk, it):
    if isinstance(sk, str):
        return next(it)
    return (sk[0], *[_assemble(k, it) for k in sk[1:]])


def build_tree(sk, want: bool, st: State, rng: random.Random, frozen: set[str]):
    """A tree of shape `sk` answering `want`, built leaf by leaf (see the module doc), or
    None. The state is left as the successful build set it, or as it was."""
    pats = patterns(sk, want)
    if not pats:
        return None
    kinds = leaves_of(sk)
    for _ in range(TRIES):
        pat = rng.choices([p for p, _ in pats], weights=[w for _, w in pats])[0]
        snap = st.snapshot()
        b = Build(st, rng, frozen)
        leaves = []
        for kind, t in zip(kinds, pat):
            lf = None
            for _ in range(6):
                lf = build_leaf(kind, t, b)
                if lf is not None:
                    break
            if lf is None:
                break
            b.avoid |= lf.reads
            leaves.append(lf)
        else:
            tree = _assemble(sk, iter(leaves))
            # later leaves may only touch fields no earlier leaf reads, so every leaf
            # still has its truth; checked rather than trusted
            if (all(lf.value(st) is t for lf, t in zip(leaves, pat))
                    and eval_tree(tree, st) is want):
                return tree
        st.restore(snap)
    return None


# ==== records =========================================================================

def make_state(cd: CDomain, rng: random.Random, n: int) -> State:
    """`n` records of one domain. Every measured number is drawn around a centre shared
    by the state, so where a value ranks among the records says nothing about where it
    sits in its range; every limit is drawn near its own reading, either side."""
    recs = [make_record(cd.dom, rng) for _ in range(n)]
    for f in cd.meas:
        span = f.hi - f.lo
        c = rng.uniform(f.lo + CLUSTER * span, f.hi - CLUSTER * span)
        for r in recs:
            r[f.name] = _rnd(f.integral, min(f.hi, max(f.lo, c + rng.uniform(-CLUSTER, CLUSTER) * span)))
    for a, l in cd.pairs:
        fl = cd.num(l)
        for r in recs:
            v = _side(r[a], fl.lo, fl.hi, fl.hi - fl.lo, fl.integral, rng.random() < 0.5, rng)
            for below in (True, False):
                if v is None:
                    v = _side(r[a], fl.lo, fl.hi, fl.hi - fl.lo, fl.integral, below, rng)
            if v is not None:
                r[l] = v
    seen = set()
    for r in recs:
        while r[cd.idf] in seen:
            r[cd.idf] = _ref(rng)
        seen.add(r[cd.idf])
        for it in cd.dom.items:
            if not r[it.name] and rng.random() < 0.5:
                r[it.name] = sorted(rng.sample(it.pool, rng.randint(1, min(it.hi, len(it.pool)))))
    pname = rng.choice(("policy", "limits", "thresholds", "rulebook"))
    return State(cd, recs, rng.randrange(n), {}, pname)


def _policy_distractors(st: State, rng: random.Random, k: int, exclude: set[str]) -> None:
    """Settings no rule reads. Never for a field a rule reads, and never re-adding a
    setting an abstention removed."""
    free = [f for f in st.cd.meas if f.name not in exclude
            and f"max_{f.name}" not in st.policy and f"min_{f.name}" not in st.policy]
    for f in rng.sample(free, min(k, len(free))):
        vals = _vals(st, f.name) if all(f.name in r for r in st.recs) else [f.lo, f.hi]
        mid = sum(vals) / len(vals)
        v = mid + rng.uniform(-0.25, 0.25) * (f.hi - f.lo)
        st.policy[f"{rng.choice(('max', 'min'))}_{f.name}"] = _rnd(
            f.integral, min(f.hi, max(f.lo, v)))


# ==== rendering the state =============================================================

def _cell(v) -> str:
    if isinstance(v, list):
        return ", ".join(v) if v else "none"
    return str(v)


def _plabel(cd: CDomain, key: str) -> str:
    bound, name = key.split("_", 1)
    f = cd.num(name)
    return f"{'maximum' if bound == 'max' else 'minimum'} {_label(f.name, f.label)}"


def render_state(st: State, fmt: str) -> str:
    cd = st.cd
    obj = st.as_obj()
    if fmt == "json":
        return json.dumps(obj, indent=2, ensure_ascii=False)
    if fmt == "yaml":
        # block style or one flow mapping per record, drawn from the state itself so the
        # render stays a function of the state
        flow = None if int(hashlib.md5(st.fid.encode()).hexdigest(), 16) % 2 else False
        return yaml.safe_dump(obj, sort_keys=False, allow_unicode=True,
                              default_flow_style=flow, width=1000).rstrip()
    if fmt == "paths":
        return flatten_paths(obj)
    keys = list(st.recs[0])
    pol = list(st.policy.items())
    if fmt == "prose":
        out = [f"There are {len(st.recs)} {cd.plural} in this batch."]
        out += [as_prose(cd.dom, r) for r in st.recs]
        if pol:
            parts = []
            for k, v in pol:
                unit = cd.num(k.split("_", 1)[1]).unit
                parts.append(f"a {_plabel(cd, k)} of {v}{unit}")
            out.append(f"The {st.pname} record sets " + "; ".join(parts) + ".")
        return "\n\n".join(out)
    if fmt == "table":
        lines = ["| " + " | ".join(keys) + " |", "|" + "---|" * len(keys)]
        lines += ["| " + " | ".join(_cell(r[k]) for k in keys) + " |" for r in st.recs]
        text = f"{cd.coll}:\n\n" + "\n".join(lines)
        if pol:
            text += (f"\n\n{st.pname}:\n\n| setting | value |\n|---|---|\n" +
                     "\n".join(f"| {k} | {v} |" for k, v in pol))
        return text
    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf, lineterminator="\n")
        w.writerow(keys)
        for r in st.recs:
            w.writerow([";".join(r[k]) if isinstance(r[k], list) else r[k] for k in keys])
        text = f"# {cd.coll}\n" + buf.getvalue().rstrip()
        if pol:
            buf = io.StringIO()
            w = csv.writer(buf, lineterminator="\n")
            w.writerow(["setting", "value"])
            w.writerows(pol)
            text += f"\n\n# {st.pname}\n" + buf.getvalue().rstrip()
        return text
    if fmt == "kv":
        blocks = []
        for i, r in enumerate(st.recs, 1):
            blocks.append(f"[{cd.noun} {i}]\n" + "\n".join(f"{k}: {_cell(v)}" for k, v in r.items()))
        if pol:
            blocks.append(f"[{st.pname}]\n" + "\n".join(f"{k}: {v}" for k, v in pol))
        return "\n\n".join(blocks)
    raise ValueError(fmt)


# ==== rendering the rule ==============================================================

class Renderer:
    """Everything a rule's wording depends on, for one question.

    `heldout` is None in training (held-out templates are never drawn), True for a
    dev/test question worded with held-out templates wherever a bank has them, False for
    one worded with trained templates only. The field-reference templates are drawn once
    per question, so one rule names its fields one way."""

    def __init__(self, st: State, fmt: str, mode: str, rng: random.Random,
                 heldout: bool | None):
        self.st, self.cd, self.rng = st, st.cd, rng
        self.shape = "label" if fmt == "prose" else "key"
        self.mode, self.heldout = mode, heldout
        self.fixed: dict[str, str] = {}
        self.used_heldout = False

    def pick(self, bank: str, numeric: bool = True, fixed: bool = False) -> str:
        if fixed and bank in self.fixed:
            return self.fixed[bank]
        tpls = [t for t in BANKS[bank] if numeric or not t.startswith("#")]
        held = HELDOUT_TEMPLATES[bank]
        seen = [t for t in tpls if t not in held]
        new = [t for t in tpls if t in held]
        pool = new if (self.heldout and new) else seen
        t = self.rng.choice(pool)
        if t in held:
            self.used_heldout = True
        t = t.lstrip("#")
        if fixed:
            self.fixed[bank] = t
        return t

    # -- names ------------------------------------------------------------------------
    def ref(self, name: str, bare: bool = False) -> str:
        """How the rule names a field. `bare` is the form that follows a determiner
        ("the average `transit_days`", not "the average the `transit_days` field")."""
        f = next(x for x in self.cd.dom.fields if x.name == name)
        if self.mode == "indirect" and getattr(f, "gloss", ""):
            unit = getattr(f, "unit", "").strip()
            t = self.pick("ref_ind_bare" if bare else "ref_ind", fixed=True)
            # the unit, which also keeps "how heavy the shipment is is greater" apart
            return t.format(gloss=f.gloss) + (f" (in {unit})" if unit else "")
        if self.shape == "key":
            return f"`{f.name}`" if bare else self.pick("ref_key", fixed=True).format(key=f.name)
        lab = _label(f.name, getattr(f, "label", ""))
        return lab if bare else self.pick("ref_label", fixed=True).format(label=lab)

    def const(self, name: str, v) -> str:
        f = next(x for x in self.cd.dom.fields if x.name == name)
        return f"{v}{getattr(f, 'unit', '')}"

    def self_(self) -> str:
        return self.pick("self", fixed=True).format(noun=self.cd.noun, fid=self.st.fid)

    def cmp(self, x: str, op: str, c: str, numeric: bool = True) -> str:
        return self.pick(OP_BANK[op], numeric).format(x=x, c=c)

    def set_(self, vals) -> str:
        t = self.pick("set_fmt")
        vals = list(vals)
        return t.format(a=", ".join(vals[:-1]), b=vals[-1], l=", ".join(vals))

    # -- leaves -----------------------------------------------------------------------
    def atom(self, s: dict, pol: bool) -> str:
        k = s["k"]
        if k == "cmp":
            op = s["op"] if pol else NEG_OP[s["op"]]
            return self.cmp(self.ref(s["f"]), op, self.const(s["f"], s["c"]))
        if k == "eq":
            op = s["op"] if pol else NEG_OP[s["op"]]
            return self.pick("eq_enum" if op == "==" else "ne_enum").format(
                x=self.ref(s["f"]), c=s["v"])
        if k == "range":
            inside = s["inside"] == pol
            return self.pick("range_in" if inside else "range_out").format(
                x=self.ref(s["f"]), lo=self.const(s["f"], s["lo"]),
                hi=self.const(s["f"], s["hi"]))
        if k == "member":
            inside = s["inside"] == pol
            return self.pick("set_in" if inside else "set_out").format(
                x=self.ref(s["f"]), s=self.set_(s["vals"]))
        if k == "fref":
            op = s["op"] if pol else NEG_OP[s["op"]]
            other = self.pick("same_rec").format(x=self.ref(s["b"]))
            return self.cmp(self.ref(s["a"]), op, other, numeric=False)
        if k == "pref":
            op = s["op"] if pol else NEG_OP[s["op"]]
            bound = "maximum" if s["key"].startswith("max_") else "minimum"
            if self.mode == "indirect":
                c = self.pick("pref_ind").format(bound=bound, P=self.st.pname)
            elif self.shape == "key":
                c = self.pick("pref_key").format(pkey=s["key"], P=self.st.pname)
            else:
                c = self.pick("pref_label").format(plabel=_plabel(self.cd, s["key"]),
                                                   P=self.st.pname)
            return self.cmp(self.ref(s["f"]), op, c, numeric=False)
        raise ValueError(k)

    def leaf(self, s: dict, pol: bool) -> str:
        k, cd = s["k"], self.cd
        common = {"noun": cd.noun, "plural": cd.plural}
        if k in RECORD_KINDS:
            return self.atom(s, pol)
        if k in QUANT_KINDS:
            # the negation of a quantifier is its dual: not all = some fail, not any =
            # none, not none = some, not at-least-k = fewer-than-k
            if k == "all":
                bank, inner = ("all", True) if pol else ("any", False)
            elif k == "any":
                bank, inner = ("any", True) if pol else ("none", True)
            elif k == "none":
                bank, inner = ("none", True) if pol else ("any", True)
            else:
                bank, inner = ("atleast" if pol else "fewer"), True
            n = s.get("n", 1)
            return self.pick(bank).format(p=self.atom(s["phi"], inner), k=n, km1=n - 1,
                                          **common)
        if k == "agg":
            op = s["op"] if pol else NEG_OP[s["op"]]
            if s["fn"] == "count":
                x = self.pick("agg_count").format(x=self.ref(s["f"]), v=s["v"], **common)
                return self.cmp(x, op, str(s["c"]))
            x = self.pick(f"agg_{s['fn']}").format(x=self.ref(s["f"]),
                                                    xb=self.ref(s["f"], bare=True), **common)
            return self.cmp(x, op, self.const(s["f"], s["c"]))
        if k == "cross":
            x = self.ref(s["f"])
            if s["mode"] == "named":
                op = s["op"] if pol else NEG_OP[s["op"]]
                c = self.pick("cross_obj").format(noun=cd.noun, oid=s["other"])
                return self.cmp(x, op, c, numeric=False)
            hl = "hi" if s["hi"] else "lo"
            bank = ("ext_" if s["mode"] == "extreme" else "rank_") + hl + ("" if pol else "_neg")
            n = s.get("n", 1)
            return self.pick(bank).format(self=self.self_(), x=x, xb=self.ref(s["f"], bare=True),
                                          k=n, km1=n - 1, **common)
        raise ValueError(k)

    # -- trees ------------------------------------------------------------------------
    def _items(self, texts: list[str], level: int) -> str:
        mk = MARKERS[min(level, len(MARKERS) - 1)]
        return "; ".join(f"{mk(i)} {t}" for i, t in enumerate(texts))

    def _wrap(self, tree, text: str) -> str:
        # a quantifier carries a clause of its own ("some build job satisfies this: A"),
        # so under a connective it is bracketed too, or "..., together with B" reads as
        # part of the quantified clause
        if isinstance(tree, Leaf) and tree.kind not in QUANT_KINDS:
            return text
        return f"[{text}]"

    def _nary(self, op: str, kids_text: list[str], kids, level: int) -> str:
        wrapped = [self._wrap(k, t) for k, t in zip(kids, kids_text)]
        if len(wrapped) == 2:
            t = self.pick(f"{op}2")
            if "{items}" in t:
                return t.format(items=self._items(wrapped, level))
            # "`mount` is duct or wall or [...]": a leaf with its own and/or, joined by
            # a bare and/or, is bracketed like a subtree
            wrapped = [f"[{w}]" if not w.startswith("[") and
                       re.search(r"\b(and|or)\b", w) else w for w in wrapped]
            return t.format(a=wrapped[0], b=wrapped[1])
        return self.pick(f"{op}n").format(items=self._items(wrapped, level))

    def rule(self, tree, level: int = 0) -> str:
        if isinstance(tree, Leaf):
            return self.leaf(tree.spec, True)
        op, kids = tree[0], list(tree[1:])
        if op == "not":
            return self.pick("not").format(a=self._wrap(kids[0], self.rule(kids[0], level + 1)))
        if op == "implies":
            a, b = (self._wrap(k, self.rule(k, level + 1)) for k in kids)
            return self.pick("implies").format(a=a, b=b)
        texts = [self.rule(k, level + 1) for k in kids]
        return self._nary(op, texts, kids, level)

    def negation(self, tree, level: int = 0) -> str:
        """The rule's complement pushed down to the leaves (De Morgan), so the `no`
        description is a rule in its own right rather than the `yes` one with a prefix."""
        if isinstance(tree, Leaf):
            return self.leaf(tree.spec, False)
        op, kids = tree[0], list(tree[1:])
        if op == "not":
            return self.rule(kids[0], level)
        if op in ("and", "or"):
            dual = "or" if op == "and" else "and"
            texts = [self.negation(k, level + 1) for k in kids]
            return self._nary(dual, texts, kids, level)
        if op == "implies":
            a = self._wrap(kids[0], self.rule(kids[0], level + 1))
            nb = self._wrap(kids[1], self.negation(kids[1], level + 1))
            t = self.pick("and2")
            return t.format(items=self._items([a, nb], level)) if "{items}" in t \
                else t.format(a=a, b=nb)
        wrapped = [self._wrap(k, self.rule(k, level + 1)) for k in kids]   # xor
        return self.pick("xor_neg").format(items=self._items(wrapped, level))

    def negated_rule(self, tree) -> str:
        if isinstance(tree, Leaf) or self.rng.random() < 0.5:
            return self.negation(tree)
        return self.pick("neg_wrap").format(a=f"[{self.rule(tree)}]")


def _sentence(text: str) -> str:
    text = text.strip()
    if text[:1].isalpha():
        text = text[0].upper() + text[1:]
    return text if text.endswith(".") else text + "."


# ==== questions and examples ==========================================================

@dataclass
class Plan:
    split: str
    depths: tuple[int, ...]
    formats: tuple[str, ...]
    sentinel_split: str      # which half of the sentinel wording space to draw from


TRACE: list | None = None     # set to a list to capture (question, state, trees) triples


def _drop_for_abstain(st: State, tree, others: set[str], rng: random.Random) -> str | None:
    """Remove one field the tree reads -- from every record, or the policy key -- such
    that the tree's answer is no longer determined. None (and nothing removed) when no
    field can go without deciding the rule anyway."""
    # sorted: `reads` is a set of strings, whose order follows PYTHONHASHSEED, and the
    # corpus must be the same from one process to the next
    cands = [r for lf in tree_leaves(tree) for r in sorted(lf.reads) if r not in others]
    rng.shuffle(cands)
    for name in cands:
        snap = st.snapshot()
        if name.startswith("policy:"):
            st.policy.pop(name.split(":", 1)[1], None)
        else:
            for r in st.recs:
                r.pop(name, None)
        if name != st.cd.idf and eval_tree(tree, st) is None:
            return name
        st.restore(snap)
    return None


def _meta_tree(tree, sk) -> dict:
    lv = tree_leaves(tree)
    return {"sig": sig_of(sk), "depth": depth_of(sk), "leaves": len(lv),
            "kinds": [lf.kind for lf in lv],
            "inner": [lf.spec["phi"]["k"] for lf in lv if lf.kind in QUANT_KINDS],
            "ops": sorted(set(ops_of(sk))), "tree": spec_of(tree)}


class Loader:
    def __init__(self, name: str, plan: Plan, seed: int):
        self.name, self.plan, self.seed = name, plan, seed

    def __call__(self, n: int) -> Iterator[Example]:
        h = hashlib.sha256(f"{self.seed}:{self.name}".encode()).digest()
        rng = random.Random(int.from_bytes(h[:8], "big"))
        bal = [0, 0]
        made = 0
        i = 0
        while made < n:
            cd = CDOMAINS[i % len(CDOMAINS)]
            i += 1
            if i > 20 * n + 100:
                raise RuntimeError(f"{self.name}: {made} of {n} examples after {i} draws")
            ex = self.example(cd, rng, bal)
            if ex is not None:
                made += 1
                yield ex

    def example(self, cd: CDomain, rng: random.Random, bal: list[int]) -> Example | None:
        plan = self.plan
        fmt = rng.choice(plan.formats)
        st = make_state(cd, rng, rng.randint(*N_RECORDS))
        mode = "indirect" if rng.random() < P_INDIRECT else "direct"
        frozen: set[str] = set()
        built = []                    # (kind, payload) per question
        n_q = 2 if rng.random() < P_SECOND else 1
        eff = list(bal)
        for qi in range(n_q):
            depth = rng.choice(plan.depths)
            if rng.random() < P_ROUTE:
                got = self._route(st, rng, frozen, depth)
            else:
                got = self._noul(st, rng, frozen, depth, eff)
            if got is None:
                if qi == 0:
                    return None
                break
            built.append(got)
        # abstention: at most one question per example loses a field it needs
        reads_by_q = [set().union(*[lf.reads for t in trees for lf in tree_leaves(t)])
                      for _, _, trees, *_ in built]
        for qi, b in enumerate(built):
            if b[0] == "noul" and b[3]["sentinel"] and b[3]["abstain_wanted"]:
                others = set().union(*[r for j, r in enumerate(reads_by_q) if j != qi]) \
                    if len(reads_by_q) > 1 else set()
                dropped = _drop_for_abstain(st, b[2][0], others, rng)
                b[3]["abstain"] = dropped
                break
            if b[0] == "route" and b[3]["sentinel"] and b[3]["abstain_wanted"]:
                others = set().union(*[r for j, r in enumerate(reads_by_q) if j != qi]) \
                    if len(reads_by_q) > 1 else set()
                gold_tree = b[2][b[3]["gold"]]
                others |= set().union(*[lf.reads for j, t in enumerate(b[2])
                                        if j != b[3]["gold"] for lf in tree_leaves(t)])
                dropped = _drop_for_abstain(st, gold_tree, others, rng)
                b[3]["abstain"] = dropped
                break
        # policy record: where a rule reads it, plus distractor settings; sometimes present
        # when nothing reads it, so its presence says nothing about the rule
        read_all = set().union(*reads_by_q)
        if st.policy or rng.random() < P_POLICY_DISTRACTOR:
            _policy_distractors(st, rng, rng.randint(1, 3), read_all)
        for f in cd.dom.fields:
            if f.name != cd.idf and f.name not in read_all and rng.random() < P_DROP_DISTRACTOR:
                for r in st.recs:
                    r.pop(f.name, None)
        # every question re-evaluated on the final state: nothing after its build may
        # have moved its answer
        qs = []
        for qi, b in enumerate(built):
            q = self._question(qi, b, st, fmt, mode, rng)
            if q is None:
                return None
            qs.append(q)
        for b in built:
            if b[0] == "noul" and not b[3].get("abstain"):
                bal[int(b[3]["want"])] += 1
        ex = Example(state=render_state(st, fmt), questions=qs, task=self.name)
        if TRACE is not None:
            for q, b in zip(qs, built):
                TRACE.append((q, copy.deepcopy(st), b[2], fmt, mode))
        return ex

    # -- builders ---------------------------------------------------------------------
    def _noul(self, st, rng, frozen, depth, eff):
        want = eff[1] < eff[0] if eff[0] != eff[1] else rng.random() < 0.5
        for _ in range(8):
            sk = skeleton_for(rng, self.plan.split, depth)
            tree = build_tree(sk, want, st, rng, frozen)
            if tree is not None:
                frozen |= set().union(*[lf.reads for lf in tree_leaves(tree)])
                sent = rng.random() < P_NOUL_SENTINEL
                eff[int(want)] += 1       # an earlier question of this example counts too
                info = {"want": want, "sentinel": sent,
                        "abstain_wanted": sent and rng.random() < P_NOUL_ABSTAIN}
                return ("noul", [sk], [tree], info)
        return None

    def _route(self, st, rng, frozen, depth):
        form = rng.choices([f for f, _ in ROUTE_FORMS], weights=[w for _, w in ROUTE_FORMS])[0]
        sent = form == "sentinel"
        if form == "two":
            k = 2
        elif form == "plain":
            k = 3
        else:
            k = 2            # + the sentinel: three options, as every plain one has
        right = sent and rng.random() < P_ROUTE_SENT_RIGHT
        none_apply = right and rng.random() < P_NONE_APPLY
        abstain_wanted = right and not none_apply
        gold = None if none_apply else rng.randrange(k)
        sks, trees = [], []
        local = set(frozen)
        snap = st.snapshot()
        for j in range(k):
            d = depth if j == 0 else rng.randint(max(1, depth - 1), depth)
            if self.plan.split != "train" and d == 1:
                d = depth
            tree = None
            for _ in range(8):
                sk = skeleton_for(rng, self.plan.split, d, ROUTE_MAX_LEAVES)
                tree = build_tree(sk, j == gold, st, rng, local)
                if tree is not None:
                    break
            if tree is None:
                st.restore(snap)
                return None
            local |= set().union(*[lf.reads for lf in tree_leaves(tree)])
            sks.append(sk)
            trees.append(tree)
        frozen |= local
        info = {"gold": gold, "sentinel": sent, "abstain_wanted": abstain_wanted,
                "none_apply": none_apply, "k": k}
        return ("route", sks, trees, info)

    # -- questions --------------------------------------------------------------------
    def _question(self, qi, b, st, fmt, mode, rng) -> Question | None:
        kind, sks, trees, info = b
        heldout = None if self.plan.split == "train" else rng.random() < 0.5
        R = Renderer(st, fmt, mode, rng, heldout)
        cd = st.cd
        meta_common = {"format": fmt, "mode": mode, "split": self.plan.split,
                       "focus": st.fid, "coll": cd.coll, "policy": st.pname,
                       "domain": cd.dom.name, "qshape": kind}
        skey = sdesc = None
        if info["sentinel"]:
            skey, sdesc = sentinel.sample(rng, self.plan.sentinel_split)
        if kind == "noul":
            tree, sk = trees[0], sks[0]
            val = eval_tree(tree, st)
            abstain = bool(info.get("abstain"))
            if abstain != (val is None) or (not abstain and val is not info["want"]):
                return None
            opts = ["no", "yes"]
            desc = [_sentence(R.negated_rule(tree)), _sentence(R.rule(tree))]
            target = [0.0, 0.0] if abstain else [float(not val), float(val)]
            text = R.pick("q_noul").format(noun=cd.noun, fid=st.fid)
            meta = {**meta_common, **_meta_tree(tree, sk)}
            if skey is not None:
                pos = rng.randrange(3)
                opts.insert(pos, skey)
                desc.insert(pos, sdesc)
                target.insert(pos, 1.0 if abstain else 0.0)
                meta["sentinel"] = pos
            if abstain:
                meta.update(abstain=True, reason="field_not_in_state",
                            missing=info["abstain"])
            meta["tpl"] = "train" if heldout is None else ("heldout" if R.used_heldout else "seen")
            return Question(f"q{qi}", text, opts, target, meta, None, desc)
        # routing
        k = info["k"]
        vals = [eval_tree(t, st) for t in trees]
        gold = info["gold"]
        abstain = bool(info.get("abstain"))
        if abstain:
            if vals[gold] is not None or any(v is not False for j, v in enumerate(vals)
                                             if j != gold):
                return None
        elif gold is None:
            if any(v is not False for v in vals):
                return None
        elif vals[gold] is not True or any(v is not False for j, v in enumerate(vals)
                                           if j != gold):
            return None
        keys = rng.sample(ACTIONS, k)
        keys_by_tree = list(keys)
        desc = [_sentence(R.pick("route_desc").format(r=R.rule(t)).rstrip(".")) for t in trees]
        target = [1.0 if (j == gold and not abstain) else 0.0 for j in range(k)]
        sigs = [sig_of(s) for s in sks]
        meta = {**meta_common, "sigs": sigs, "depths": [depth_of(s) for s in sks],
                "depth": max(depth_of(s) for s in sks),
                "sig": sigs[gold] if gold is not None else sigs[0],
                "kinds": [lf.kind for t in trees for lf in tree_leaves(t)],
                "inner": [lf.spec["phi"]["k"] for t in trees for lf in tree_leaves(t)
                          if lf.kind in QUANT_KINDS],
                "ops": sorted({o for s in sks for o in ops_of(s)}),
                "trees": [spec_of(t) for t in trees], "leaves": sum(len(tree_leaves(t)) for t in trees)}
        if skey is not None:
            pos = rng.randrange(k + 1)
            keys.insert(pos, skey)
            desc.insert(pos, sdesc)
            target.insert(pos, 1.0 if (abstain or gold is None) else 0.0)
            meta["sentinel"] = pos
            meta["trees"].insert(pos, None)
            if gold is None:
                meta["none_apply"] = True
        if abstain:
            meta.update(abstain=True, reason="field_not_in_state", missing=info["abstain"],
                        undecided=keys.index(keys_by_tree[gold]))
        meta["tpl"] = "train" if heldout is None else ("heldout" if R.used_heldout else "seen")
        text = R.pick("q_route").format(noun=cd.noun, fid=st.fid)
        return Question(f"q{qi}", text, keys, target, meta, None, desc)


# ==== tasks ===========================================================================

def task_plans() -> list[tuple[str, Plan, str]]:
    """(task name, plan, family). Train: one task per (depth 1-3, format). Dev and test:
    one task per depth bucket (2-3, 4), formats mixed. With equal per-task quotas that is
    21 : 2 : 2, the 30k / 3k / 3k the row is sized for."""
    out = []
    for d in (1, 2, 3):
        for fmt in FORMATS:
            out.append((f"compose_train_d{d}_{fmt}", Plan("train", (d,), (fmt,), "train"),
                        f"compose_train_d{d}"))
    for split, tag in (("devreal", "dev"), ("testreal", "test")):
        for bucket, depths in (("d23", (2, 3)), ("d4", (4,))):
            out.append((f"compose_{tag}_{bucket}", Plan(split, depths, FORMATS, "eval"),
                        f"compose_{split}_{bucket}"))
    return out


def tasks() -> list[RealTask]:
    out = []
    for name, plan, family in task_plans():
        out.append(RealTask(
            row=ROW, name=name, licence=LICENCE, url=URL,
            load=Loader(name, plan, 0), soft=True, real=False,
            per_example_options=True, force_split=plan.split, family=family,
            notes=(f"compositional rules, split {plan.split}, depth {plan.depths}, "
                   f"formats {','.join(plan.formats)}; code-labelled")))
    return out


__all__ = ["tasks", "task_plans", "sig_of", "split_of_sig", "sample_skeleton",
           "eval_leaf", "BANKS", "HELDOUT_TEMPLATES", "KINDS", "OPS", "FORMATS",
           "flatten_paths"]
