"""Row 39 -- entity resolution (domain 17).

Two records, or one record and a roster of forty: are these one entity or two? The
corruption that built the pair decides the label, and the *matching policy* -- what
counts as the same entity, which field settles it, what a missing field means -- is
written into the criteria, the way `rules.py` writes the rule into the criteria.

**The trap this module is built around.** Corrupt a matched pair by one character and
leave unmatched pairs as two unrelated records, and edit distance solves the task: you
have a string-similarity benchmark wearing a reasoning benchmark's clothes. So both
halves are built the other way round.

- Matched pairs are driven *apart* on the surface: transliterated surnames, `SURNAME,
  Given` order, a nickname, initials, a married name, a new address, the date written
  three ways.
- Unmatched pairs are pulled *together*: a father and a son at one address, twins, a
  namesake in a large city, two branches of one company, parts I and II of one paper.

`_similarity_baseline` in the tests measures what is left: the best accuracy any
threshold on character similarity can reach, maximised over the threshold *and* over the
direction of the comparison, so a merely inverted signal counts as solved too.

**The policy is the program.** Three clauses, the same shape for each record type:

  1. If both records carry the strong identifier -- national insurance number,
     registration number, DOI -- it settles the question by itself. It is recorded
     reliably, so only its punctuation and case vary.
  2. If at least one record lacks it, fall back to the date both records carry -- date of
     birth, date of incorporation, year of publication -- together with the name.
  3. Address, telephone, employer, sector, venue and the record key never decide
     anything. People move, companies re-register an office, a paper is re-typeset.

A field present in only one record is not evidence either way, which is why clause 2 has
a hole in it: when neither the identifier nor the fallback date is in *both* records, the
records genuinely do not settle the question. Those pairs are drawn one-entity exactly
half the time and carry the soft target `[0.5, 0.5]`. That is the true conditional
probability under the generating distribution, not manufactured softness.

**What is held out.** Fourteen atomic corruption operations, and families that combine
them. Twenty-two families are trained, six are reserved whole to `testreal`, five more
(`DEV_FAMILIES`) whole to `devreal`, and every operation inside a reserved family appears
alone in a trained one -- the `rule_transfer` pattern. Dev's five share no composition with
test's six, so selecting a checkpoint on them never reads a structure test measures.
`("translit", "reorder")` is read against trained `("translit", "punct")` and `("reorder",
"drop")`; `("surname_change", "relocate")` against `("surname_change", "phone_style")` and
`("abbrev", "relocate")`.

**Why no LLM call.** `entityres_` is in `PROTECTED_PREFIXES`, so the enricher never sees
these tasks -- it must not, because it keys on `(task, option keys)` and a roster's option
keys are per example. Field formatting, field order and the question stem are therefore
varied in code, deterministically and from a seed. The question stems below were drafted
as paraphrases and then fixed here as literals: the model proposes wording, code owns
everything else, and here the wording is frozen at review time rather than at build time.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from datetime import date, timedelta
from typing import Iterator

from lod.schema import Example, Question
from lod import sentinel
from lod.phrasings import PhrasingBank
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/entityres.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/entityres.py"
ROW = 39
DOMAIN = 17

TODAY = date(2026, 6, 1)

# ---- name material -------------------------------------------------------------------
# Given names are grouped: every spelling inside a group is the same given name, so
# `Robert`/`Bob`/`R.` reconcile and `Alice`/`Amelia` do not. The group's first entry is
# the formal form and the rest are what a second clerk wrote down.
GIVEN: tuple[tuple[str, ...], ...] = (
    ("Robert", "Bob", "Rob", "Bobby"),
    ("Elizabeth", "Liz", "Beth", "Eliza"),
    ("William", "Bill", "Will", "Billy"),
    ("Margaret", "Peggy", "Maggie", "Meg"),
    ("Richard", "Rick", "Rich", "Ricky"),
    ("Katherine", "Kate", "Katie", "Kath"),
    ("James", "Jim", "Jamie", "Jimmy"),
    ("Patricia", "Pat", "Trish", "Patty"),
    ("Michael", "Mike", "Mick", "Micky"),
    ("Jennifer", "Jen", "Jenny", "Jenni"),
    ("Charles", "Charlie", "Chuck", "Chas"),
    ("Anthony", "Tony", "Ant"),
    ("Theodore", "Ted", "Teddy", "Theo"),
    ("Susan", "Sue", "Suzy", "Susie"),
    ("Alexander", "Alex", "Sasha", "Xander"),
    ("Francisco", "Paco", "Pancho", "Fran"),
    ("Giuseppe", "Beppe", "Peppe"),
    ("Ekaterina", "Katya", "Katerina"),
    ("Wilhelmina", "Mina", "Willa"),
    ("Nikolaos", "Nikos", "Nick"),
    ("Abigail", "Abby", "Gail"),
    ("Dorothy", "Dot", "Dolly", "Dora"),
    ("Ibrahim", "Ibo", "Brahim"),
    ("Yevgeniya", "Zhenya", "Eugenia"),
    ("Amelia", "Amy", "Millie"),
    ("Sebastian", "Seb", "Baz"),
    ("Harriet", "Hattie", "Hetty"),
    ("Constance", "Connie", "Cora"),
    ("Bartholomew", "Bart", "Tolly"),
    ("Priyanka", "Priya", "Pri"),
    ("Olusegun", "Segun", "Olu"),
    ("Thandiwe", "Thandi", "Tandy"),
)

# (canonical surname, other romanisations of the same surname). Every variant inside a
# tuple is one surname; two tuples are two surnames, whatever they look like.
SURNAME: tuple[tuple[str, ...], ...] = (
    ("Müller", "Mueller", "Muller"),
    ("Kowalczyk", "Kowalchyk", "Kowalcik"),
    ("Nguyễn", "Nguyen", "Nguyn"),
    ("Özdemir", "Ozdemir", "Oezdemir"),
    ("Šimunović", "Simunovic", "Shimunovich"),
    ("Ó Súilleabháin", "O'Sullivan", "O Suilleabhain"),
    ("Dmitriev", "Dmitriyev", "Dmitrijev"),
    ("Zhāng", "Zhang", "Chang"),
    ("Ahmadí", "Ahmadi", "Ahmady"),
    ("Björnsson", "Bjornsson", "Bjoernsson"),
    ("Håkansson", "Hakansson", "Haakansson"),
    ("Wójcik", "Wojcik", "Voycik"),
    ("Çelik", "Celik", "Chelik"),
    ("García-Ortega", "Garcia-Ortega", "Garcia Ortega"),
    ("Đukić", "Dukic", "Djukic"),
    ("Λεωνίδου", "Leonidou", "Leonidhou"),
    ("Розанов", "Rozanov", "Rosanoff"),
    ("Fitzgerald", "FitzGerald", "Fitz-Gerald"),
    ("Oyelaran", "Oyelaaran", "Oyelarran"),
    ("Krishnamurthy", "Krishnamoorthy", "Krishnamurti"),
    ("Van der Berg", "van den Berg", "Vanderberg"),
    ("Silva-Reis", "Silva Reis", "SilvaReis"),
    ("Mäkinen", "Makinen", "Maekinen"),
    ("Petrović", "Petrovic", "Petrovich"),
    ("Sørensen", "Sorensen", "Soerensen"),
    ("Chaudhary", "Choudhary", "Chowdhary"),
    ("Abdurrahman", "Abdul Rahman", "Abd-al-Rahman"),
    ("Lindqvist", "Lindkvist", "Lindquist"),
    ("Kaczmarek", "Katchmarek", "Kachmarek"),
    ("Yamashita", "Yamasita", "Yamas'ita"),
)

STREETS = ("Larch Avenue", "Kestrel Road", "Marlow Street", "Ember Lane",
           "Cobalt Terrace", "Hollow Way", "Pivot Street", "Garnet Crescent",
           "Juniper Road", "Onyx Avenue", "Birch Close", "Flint Street",
           "Nimbus Drive", "Delta Road", "Indigo Walk", "Axle Street",
           "Saint Ambrose Road", "Quarry Mount Avenue")
CITIES = ("Norday", "Caldmere", "Brastol", "Pellgate", "Umberfell", "Vellim",
          "Ostrivka", "Kirn", "Tern Hollow", "Ashen Reach", "Cray Basin",
          "Salt Marrow", "Draymouth", "Holtby", "Wexbridge", "Carrowmore")
POSTAL = ("NR", "CM", "BR", "PG", "UF", "VL", "OS", "KN", "TH", "AR", "CB", "SM")
EMPLOYERS = ("Harbourway Logistics", "Tessera Ceramics", "Ridgeway Grid Metering",
             "Kestrel Marine Survey", "Northline Cold Storage", "Vellim Seed Genetics",
             "Brastol Textile Dyeing", "Caldmere Precision Casting",
             "Pellgate Isotope Assay", "Umberfell Hydrographic Charting")
COMPANY_HEADS = ("Harbourway", "Tessera", "Ridgeway", "Kestrel", "Northline", "Marlow",
                 "Garnet", "Juniper", "Onyx", "Flint", "Nimbus", "Cobalt", "Ember",
                 "Birch", "Larch", "Axle", "Pivot", "Hollow")
COMPANY_MIDS = ("Logistics", "Ceramics", "Metering", "Marine Survey", "Cold Storage",
                "Seed Genetics", "Textile Dyeing", "Precision Casting", "Isotope Assay",
                "Hydrographic Charting", "Grid Services", "Freight")
COMPANY_TAILS = ("Limited", "Holdings Limited", "Group Limited", "Incorporated",
                 "Corporation", "and Partners Limited", "Trading Company Limited")
SECTORS = ("freight logistics", "seed genetics", "ceramic tooling", "marine survey",
           "textile dyeing", "grid metering", "cold storage", "precision casting",
           "hydrographic charting", "isotope assay")
TITLE_A = ("Adaptive", "Robust", "Sparse", "Hierarchical", "Distributed", "Bounded",
           "Stochastic", "Incremental", "Compositional", "Differentiable", "Federated",
           "Contrastive")
TITLE_B = ("scheduling", "calibration", "retrieval", "segmentation", "alignment",
           "quantisation", "routing", "reconstruction", "annotation", "summarisation",
           "clustering", "attribution")
TITLE_C = ("under distribution shift", "for low-resource settings", "at scale",
           "with partial supervision", "in streaming data", "on noisy records",
           "without a reference model", "for tabular corpora")
VENUES = ("Journal of Applied Metrology", "Proceedings of the Conference on Record "
          "Linkage", "Transactions on Data Engineering", "International Workshop on "
          "Provenance", "Annals of Statistical Computing", "Symposium on Information "
          "Integration", "Review of Quantitative Methods")

# ---- the matching policy, as criteria -------------------------------------------------

ID_FIELD = {"person": "national_insurance_no", "company": "registration_number",
            "publication": "doi"}
DATE_FIELD = {"person": "date_of_birth", "company": "incorporated_on",
              "publication": "year_published"}
NOUN = {"person": "person", "company": "company", "publication": "publication"}
ID_NAME = {"person": "the national insurance number",
           "company": "the registration number",
           "publication": "the DOI"}
DATE_NAME = {"person": "the date of birth", "company": "the date of incorporation",
             "publication": "the year of publication"}
NOUN_PL = {"person": "people", "company": "companies",
           "publication": "publications"}
NEVER = {
    "person": "The postal address, the telephone number, the employer and the record key",
    "company": "The registered office, the telephone number, the sector and the record "
               "key",
    "publication": "The venue, the volume, the page range and the record key",
}
# Clause 3 is the part of the policy that does the work, and it is different for each
# record type: a company has no nickname and a paper has no maiden name.
SAME_NAME = {
    "person": "Two names are the same name when one can be reached from the other by a "
              "shortened or familiar form (`Bob` for `Robert`), initials, a reversed "
              "`SURNAME, Given` ordering, another romanisation of the same name, an "
              "abbreviation, a change of letter case or punctuation, or a single slip "
              "of the keyboard. A surname changed on marriage counts only when {id} "
              "confirms it.",
    "company": "Two names are the same name when one can be reached from the other by "
               "an abbreviation (`Ltd` for `Limited`, `&` for `and`), another "
               "romanisation, a change of letter case or punctuation, or a single slip "
               "of the keyboard. A different legal suffix is a different name: "
               "`Holdings Limited` where the other record says `Limited` is not the "
               "same company unless {id} says so.",
    "publication": "Two titles are the same title when one can be reached from the "
                   "other by an abbreviation, a change of letter case or punctuation, "
                   "or a single slip of the keyboard, and the first author is the same "
                   "person under the same allowances -- initials, a reversed "
                   "`SURNAME, Given` ordering, another romanisation. A part number is "
                   "part of the title: `Part II` where the other record says `Part I` "
                   "is a different publication.",
}


# What else, besides spacing, punctuation and case, the identifier's dress may vary by.
# A DOI is written bare, after `doi:` or as a `https://doi.org/` link, and `norm_id`
# strips all three. Without saying so, clause 1 read literally ("only its spacing,
# punctuation and letter case vary") calls `doi:10.1234/x` and `10.1234/x` two DOIs:
# measured on the current generator, 273 of 4,293 resolved pairs (6.4 %, every one a
# publication) flip under that literal reading.
ID_DRESS = {"person": "", "company": "",
            "publication": ", and it may be written bare, after `doi:`, or as a "
                           "`https://doi.org/` link"}


def policy(rt: str) -> str:
    """The matching policy, in full. This is the program the question asks to execute."""
    return (
        f"Matching policy for {NOUN[rt]} records, to be applied in order.\n"
        f"1. When both records carry {ID_NAME[rt]}, it settles the question on its own. "
        f"It is recorded reliably; only its spacing, punctuation and letter case vary "
        f"between systems{ID_DRESS[rt]}.\n"
        f"2. When at least one record does not carry it, fall back to {DATE_NAME[rt]}. "
        f"Dates written with slashes or dots are day first, so 07/04/1983 is the "
        f"seventh of April. If the two are different dates, the records are two "
        f"different {NOUN_PL[rt]}. If they are the same date, the names decide.\n"
        f"3. {SAME_NAME[rt].format(id=ID_NAME[rt])}\n"
        f"4. {NEVER[rt]} never decide anything: they change while the {NOUN[rt]} stays "
        f"the same.\n"
        f"5. A field that appears in only one of the two records is not evidence either "
        f"way. When neither {ID_NAME[rt]} nor {DATE_NAME[rt]} appears in both records, "
        f"nothing in them settles the question."
    )


OPT_ONE, OPT_TWO = "one_entity", "two_entities"

DESC = {
    "person": (
        "Two separate people happen to have been recorded here.",
        "One person, written down twice by two systems that disagree about how to spell "
        "and lay out what they hold.",
    ),
    "company": (
        "Two separate companies happen to have been recorded here.",
        "One company, written down twice by two systems that disagree about how to "
        "spell and lay out what they hold.",
    ),
    "publication": (
        "Two separate publications happen to have been recorded here.",
        "One publication, written down twice by two systems that disagree about how to "
        "spell and lay out what they hold.",
    ),
}

# `decisive`: which clause of the policy carries the pair. The last three are named by
# the policy as things that never decide, so they are never the answer -- they measure
# whether the criteria were read.
DECISIVE_OPTIONS = ("strong_identifier", "fallback_date", "names_alone",
                    "postal_address", "contact_number", "record_key")


def decisive_descriptions(rt: str) -> list[str]:
    return [
        f"Both records carry {ID_NAME[rt]}, so clause 1 settles the pair and nothing "
        f"else is consulted.",
        f"At least one record is missing {ID_NAME[rt]}, but both carry {DATE_NAME[rt]}, "
        f"so clause 2 carries the pair.",
        f"Neither {ID_NAME[rt]} nor {DATE_NAME[rt]} appears in both records, so only "
        f"the names can be compared and clause 5 applies.",
        "The two records are placed at the same address.",
        "The two records give the same telephone number.",
        "The two records were filed under keys drawn from one series.",
    ]


# ---- question stems ------------------------------------------------------------------
# Drafted as paraphrases and frozen here, so the wording varies without any build-time
# call that could touch a target.
PAIR_STEMS = (
    "Do these two records describe one {noun} or two?",
    "Applying the policy below, how many distinct {noun}s appear in these two records?",
    "Two systems supplied the records above. Are they a single {noun} recorded twice?",
    "Under the stated policy, should these two records be merged into one {noun}?",
    "A deduplication pass has to decide about the pair above. What is the verdict?",
    "Read both records against the policy. One {noun}, or two?",
    "The records above arrived from separate registries. Do they refer to the same "
    "{noun}?",
    "Decide, using the policy given, whether the pair above is a duplicate.",
)
ROSTER_STEMS = (
    "Which entry in the roster is the same {noun} as the query record?",
    "The query record has to be checked against the roster. Which entry, if any, does it "
    "match under the policy?",
    "Applying the policy, which roster entry and the query record describe one {noun}?",
    "One entry of the roster may be the query record filed a second time. Which?",
    "Point at the roster entry that resolves to the same {noun} as the query.",
    "Which roster entry, if any, should the query record be merged with under the policy?",
)
DECISIVE_STEMS = (
    "Which clause of the policy decides this pair?",
    "Under the policy, what carries the decision for the two records above?",
    "Which part of these records settles the policy's decision for this pair?",
    "The policy is applied in order. Where does it stop for this pair?",
)
PAIRWISE_FOLLOWUP = (
    "And entry {key} on its own: is it the query record again, or a different {noun}?",
    "Take entry {key} by itself. Same {noun} as the query, or not?",
    "Considering only entry {key} and the query record: one {noun}, or two?",
)


# ---- field formatting ----------------------------------------------------------------

_MONTHS = ("January", "February", "March", "April", "May", "June", "July", "August",
           "September", "October", "November", "December")


def fmt_date(d: date, style: str) -> str:
    if style == "iso":
        return d.isoformat()
    if style == "dmy_slash":
        return f"{d.day:02d}/{d.month:02d}/{d.year}"
    if style == "dmy_dot":
        return f"{d.day:02d}.{d.month:02d}.{d.year}"
    if style == "long":
        return f"{d.day} {_MONTHS[d.month - 1]} {d.year}"
    if style == "short":
        return f"{d.day:02d} {_MONTHS[d.month - 1][:3]} {d.year}"
    return f"{_MONTHS[d.month - 1]} {d.day}, {d.year}"  # "us_long"


DATE_STYLES = ("iso", "dmy_slash", "dmy_dot", "long", "short", "us_long")

_ISO = re.compile(r"^(\d{4})-(\d{2})-(\d{2})$")
_NUM = re.compile(r"^(\d{1,2})[/.](\d{1,2})[/.](\d{4})$")
_LONG = re.compile(r"^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$")
_USL = re.compile(r"^([A-Za-z]+)\s+(\d{1,2}),\s*(\d{4})$")


def parse_date(text: str) -> tuple[int, int, int]:
    """Any style this module writes, back to (y, m, d). Numeric forms are day first,
    which is the convention the policy states rather than one the reader must guess."""
    s = str(text).strip()
    if s.isdigit() and len(s) == 4:            # a publication year
        return (int(s), 0, 0)
    m = _ISO.match(s)
    if m:
        return (int(m[1]), int(m[2]), int(m[3]))
    m = _NUM.match(s)
    if m:
        return (int(m[3]), int(m[2]), int(m[1]))
    m = _LONG.match(s)
    if m:
        return (int(m[3]), _month(m[2]), int(m[1]))
    m = _USL.match(s)
    if m:
        return (int(m[3]), _month(m[1]), int(m[2]))
    raise ValueError(f"unparsable date {text!r}")


def _month(word: str) -> int:
    w = word[:3].lower()
    for i, name in enumerate(_MONTHS, start=1):
        if name[:3].lower() == w:
            return i
    raise ValueError(f"unknown month {word!r}")


def fmt_nino(digits: str, letter: str, prefix: str, style: str) -> str:
    d = digits
    if style == "spaced":
        return f"{prefix} {d[0:2]} {d[2:4]} {d[4:6]} {letter}"
    if style == "tight":
        return f"{prefix}{d}{letter}"
    if style == "dashed":
        return f"{prefix}-{d[0:2]}-{d[2:4]}-{d[4:6]}-{letter}"
    return f"{prefix.lower()} {d[0:2]} {d[2:4]} {d[4:6]} {letter.lower()}"  # "lower"


NINO_STYLES = ("spaced", "tight", "dashed", "lower")


def fmt_regno(prefix: str, digits: str, style: str) -> str:
    if style == "spaced":
        return f"{prefix} {digits[:3]} {digits[3:]}"
    if style == "tight":
        return f"{prefix}{digits}"
    if style == "dashed":
        return f"{prefix}-{digits[:3]}-{digits[3:]}"
    return f"{prefix.lower()}{digits}"


REGNO_STYLES = ("spaced", "tight", "dashed", "lower")


def fmt_doi(suffix: str, style: str) -> str:
    if style == "bare":
        return f"10.{suffix}"
    if style == "prefixed":
        return f"doi:10.{suffix}"
    if style == "url":
        return f"https://doi.org/10.{suffix}"
    return f"10.{suffix.upper()}"


DOI_STYLES = ("bare", "prefixed", "url", "upper")


def norm_id(text: str) -> str:
    """Identifiers compare after their punctuation, case and URL dress are removed."""
    s = str(text).strip().lower()
    for lead in ("https://doi.org/", "http://doi.org/", "doi:", "doi "):
        if s.startswith(lead):
            s = s[len(lead):]
    return re.sub(r"[^0-9a-z]", "", s)


def fmt_phone(area: str, body: str, style: str) -> str:
    if style == "intl":
        return f"+44 {area} {body[:4]} {body[4:]}"
    if style == "bracket":
        return f"(0{area}) {body[:4]} {body[4:]}"
    if style == "plain":
        return f"0{area} {body[:4]} {body[4:]}"
    if style == "tight":
        return f"0{area}{body}"
    return f"+44-{area}-{body[:4]}-{body[4:]}"


PHONE_STYLES = ("intl", "bracket", "plain", "tight", "dashed")

ABBREV = {"Street": "St", "Road": "Rd", "Avenue": "Ave", "Lane": "Ln", "Drive": "Dr",
          "Crescent": "Cres", "Terrace": "Terr", "Close": "Cl", "Saint": "St",
          "Mount": "Mt", "Limited": "Ltd", "Incorporated": "Inc",
          "Corporation": "Corp", "Holdings": "Hldgs", "Company": "Co",
          "and": "&", "Proceedings": "Proc", "International": "Intl",
          "Journal": "J.", "Transactions": "Trans.", "Conference": "Conf.",
          "Symposium": "Symp.", "Workshop": "Wkshp", "Annals": "Ann.",
          "Review": "Rev.", "Quantitative": "Quant.", "Applied": "Appl."}


def abbreviate(text: str) -> str:
    out = [ABBREV.get(w, w) for w in str(text).split(" ")]
    return " ".join(out)


def depunct(text: str) -> str:
    return re.sub(r"[-'’.]", "", str(text))


def typo(text: str, rng: random.Random) -> str:
    """One keyboard slip: a transposition, a doubling, a drop or a neighbour."""
    s = str(text)
    idx = [i for i, c in enumerate(s) if c.isalnum()]
    if len(idx) < 3:
        return s
    i = rng.choice(idx[1:-1])
    kind = rng.choice(("swap", "double", "drop", "sub"))
    if kind == "swap" and i + 1 < len(s):
        return s[:i] + s[i + 1] + s[i] + s[i + 2:]
    if kind == "double":
        return s[:i] + s[i] + s[i:]
    if kind == "drop":
        return s[:i] + s[i + 1:]
    near = "qwertyuiopasdfghjklzxcvbnm"
    return s[:i] + rng.choice(near) + s[i + 1:]


# ---- records --------------------------------------------------------------------------
# Every record carries hidden `_` keys: the entity it belongs to and the canonical name
# behind whatever surface the corruption left. Nothing under `_` is ever rendered; they
# are how `verdict` reaches the policy's notion of "the same name" without having to
# reverse-engineer it out of the strings.

RECORD_TYPES = ("person", "company", "publication")


def _postcode(rng: random.Random) -> str:
    return f"{rng.choice(POSTAL)}{rng.randrange(1, 20)} {rng.randrange(1, 9)}" \
           f"{rng.choice('ABDEFGHJLNPQRSTUWXYZ')}{rng.choice('ABDEFGHJLNPQRSTUWXYZ')}"


def _address(rng: random.Random) -> dict:
    return {"street": f"{rng.randrange(1, 220)} {rng.choice(STREETS)}",
            "city": rng.choice(CITIES), "postcode": _postcode(rng)}


def _key(rng: random.Random) -> str:
    return f"{rng.choice('ABCDEFGHJKLMNPQRSTVWXYZ')}{rng.randrange(100000, 999999)}"


def new_person(rng: random.Random) -> dict:
    g = rng.randrange(len(GIVEN))
    s = rng.randrange(len(SURNAME))
    dob = date(rng.randrange(1938, 2006), rng.randrange(1, 13), rng.randrange(1, 29))
    addr = _address(rng)
    return {
        "_type": "person", "_entity": _key(rng),
        "_given": g, "_surname": s, "_married": None,
        "_dob": dob,
        "_nino": (f"{rng.randrange(100000, 999999)}",
                  rng.choice("ABCD"),
                  rng.choice("ABCEGHJKLMNOPRSTWXYZ") + rng.choice("ABCEGHJKLMNPRSTWXYZ")),
        "_phone": (f"{rng.randrange(11, 99)}", f"{rng.randrange(1000000, 9999999)}"),
        "_address": addr,
        "_employer": rng.choice(EMPLOYERS),
        "_record_key": f"P-{rng.randrange(10000, 99999)}",
        "_style": {},
    }


def new_company(rng: random.Random) -> dict:
    head, mid = rng.choice(COMPANY_HEADS), rng.choice(COMPANY_MIDS)
    inc = date(rng.randrange(1962, 2024), rng.randrange(1, 13), rng.randrange(1, 29))
    return {
        "_type": "company", "_entity": _key(rng),
        "_head": head, "_mid": mid, "_tail": rng.choice(COMPANY_TAILS),
        "_dob": inc,
        "_regno": (rng.choice(("SC", "NI", "OC", "FC")), f"{rng.randrange(100000, 999999)}"),
        "_phone": (f"{rng.randrange(11, 99)}", f"{rng.randrange(1000000, 9999999)}"),
        "_address": _address(rng),
        "_sector": rng.choice(SECTORS),
        "_record_key": f"C-{rng.randrange(10000, 99999)}",
        "_style": {},
    }


def new_publication(rng: random.Random) -> dict:
    authors = []
    for _ in range(rng.randint(2, 4)):
        authors.append((rng.randrange(len(GIVEN)), rng.randrange(len(SURNAME))))
    year = rng.randrange(1996, 2026)
    return {
        "_type": "publication", "_entity": _key(rng),
        "_title": (rng.choice(TITLE_A), rng.choice(TITLE_B), rng.choice(TITLE_C)),
        "_part": None,
        "_authors": authors,
        "_dob": date(year, 1, 1), "_year": year,
        "_doi": f"{rng.randrange(1000, 9999)}/jml.{year}.{rng.randrange(1000, 9999)}",
        "_venue": rng.choice(VENUES),
        "_volume": rng.randrange(1, 60), "_pages": rng.randrange(1, 900),
        "_record_key": f"B-{rng.randrange(10000, 99999)}",
        "_style": {},
    }


NEW = {"person": new_person, "company": new_company, "publication": new_publication}


def name_key(rec: dict) -> tuple:
    """What the policy means by "the same name", reached without parsing the surface.

    Case, punctuation, initials, nicknames, romanisation, abbreviation and a single
    keyboard slip are all listed in clause 3 as renderings of one name, and none of them
    moves this key. A marriage name and a different given name do move it -- which is
    exactly the pair of cases clause 3 refuses to reconcile without the identifier.
    """
    t = rec["_type"]
    if t == "person":
        return ("person", rec["_given"], rec["_married"] if rec["_married"] is not None
                else rec["_surname"])
    if t == "company":
        return ("company", rec["_head"], rec["_mid"], rec["_tail"])
    return ("publication", rec["_title"], rec["_part"], tuple(rec["_authors"][:1]))


# ---- rendering -------------------------------------------------------------------------

def _given_text(rec: dict, rng: random.Random) -> str:
    style = rec["_style"].get("given", "full")
    group = GIVEN[rec["_given"]]
    if style == "full":
        return group[0]
    if style == "nickname":
        return group[rec["_style"].get("nick_i", 1) % len(group)]
    return group[0][0] + "."                                  # "initial"


def _surname_text(rec: dict) -> str:
    idx = rec["_married"] if rec["_married"] is not None else rec["_surname"]
    variants = SURNAME[idx]
    return variants[rec["_style"].get("translit", 0) % len(variants)]


def person_name(rec: dict, rng: random.Random) -> str:
    given, sur = _given_text(rec, rng), _surname_text(rec)
    order = rec["_style"].get("order", "given_first")
    if order == "surname_first":
        text = f"{sur.upper()}, {given}"
    elif order == "surname_plain":
        text = f"{sur} {given}"
    else:
        text = f"{given} {sur}"
    return _finish(text, rec, "name")


def company_name(rec: dict) -> str:
    return _finish(f"{rec['_head']} {rec['_mid']} {rec['_tail']}", rec, "name")


def publication_title(rec: dict) -> str:
    a, b, c = rec["_title"]
    text = f"{a} {b} {c}" + (f", Part {rec['_part']}" if rec["_part"] else "")
    return _finish(text, rec, "name")


def author_list(rec: dict, rng: random.Random) -> list[str]:
    out = []
    order = rec["_style"].get("order", "given_first")
    initials = rec["_style"].get("given") == "initial"
    for g, s in rec["_authors"]:
        sur = SURNAME[s][rec["_style"].get("translit", 0) % len(SURNAME[s])]
        given = GIVEN[g][0][0] + "." if initials else GIVEN[g][0]
        out.append(f"{sur.upper()}, {given}" if order == "surname_first"
                   else f"{given} {sur}")
    # The keyboard slip lands on ONE string. Every author used to share the title's
    # `name` slot, so one `typo` op put a slip in the title and another in every author
    # with the same seed -- two slips in what the policy reads (title, first author)
    # where clause 3 allows "a single slip of the keyboard". A reader holding the policy
    # to the letter called 45 % of `typo`-family publication duplicates two works.
    return [_finish(x, rec, "name", slot="author" if i == 0 else "author_rest")
            for i, x in enumerate(out)]


def _finish(text: str, rec: dict, kind: str, slot: str | None = None) -> str:
    """Case, punctuation, abbreviation and the keyboard slip, applied to a rendered
    string rather than to the record, so they never move `name_key`. `slot` is where a
    `typo` may land; it defaults to `kind`."""
    st = rec["_style"]
    if st.get("abbrev") and kind in ("name", "street", "venue"):
        text = abbreviate(text)
    if st.get("punct") and kind == "name":
        text = depunct(text)
    if st.get("case") == "upper":
        text = text.upper()
    elif st.get("case") == "lower":
        text = text.lower()
    if st.get("typo_field") == (slot or kind):
        seed = st.get("typo_seed", 0)
        slipped = typo(text, random.Random(seed))
        if kind == "name":
            # A slip that happens to spell another real name is not a slip to a reader:
            # `OZDEMIR, Rick` with its R turned to M reads as Michael, not as Richard
            # mistyped. Re-draw the slip, deterministically, until it spells nothing new.
            for k in range(1, 16):
                if not (_tokens(slipped) - _tokens(text)) & KNOWN_NAME_TOKENS:
                    break
                slipped = typo(text, random.Random(seed + k))
        text = slipped
    return text


def _tokens(text: str) -> set[str]:
    return set(depunct(text).lower().replace(",", " ").split())


KNOWN_NAME_TOKENS = frozenset(
    tok for grp in GIVEN + SURNAME for form in grp for tok in _tokens(form))


def surface(rec: dict, rng: random.Random) -> dict:
    """The record as it is actually written down. Hidden keys never appear."""
    t, st = rec["_type"], rec["_style"]
    ds = st.get("date", "iso")
    out: dict = {}
    if t == "person":
        out["full_name"] = person_name(rec, rng)
        if "date_of_birth" not in st.get("dropped", ()):
            out["date_of_birth"] = fmt_date(rec["_dob"], ds)
        if "national_insurance_no" not in st.get("dropped", ()):
            d, letter, prefix = rec["_nino"]
            out["national_insurance_no"] = fmt_nino(d, letter, prefix,
                                                    st.get("id", "spaced"))
        a = rec["_address"]
        out["address"] = _finish(a["street"], rec, "street")
        out["city"] = a["city"]
        out["postcode"] = a["postcode"]
        out["telephone"] = fmt_phone(*rec["_phone"], st.get("phone", "plain"))
        out["employer"] = _finish(rec["_employer"], rec, "employer")
        out["record_key"] = rec["_record_key"]
    elif t == "company":
        out["legal_name"] = company_name(rec)
        if "incorporated_on" not in st.get("dropped", ()):
            out["incorporated_on"] = fmt_date(rec["_dob"], ds)
        if "registration_number" not in st.get("dropped", ()):
            out["registration_number"] = fmt_regno(*rec["_regno"], st.get("id", "spaced"))
        a = rec["_address"]
        out["registered_office"] = _finish(a["street"], rec, "street")
        out["city"] = a["city"]
        out["postcode"] = a["postcode"]
        out["sector"] = rec["_sector"]
        out["telephone"] = fmt_phone(*rec["_phone"], st.get("phone", "plain"))
        out["record_key"] = rec["_record_key"]
    else:
        out["title"] = publication_title(rec)
        out["authors"] = author_list(rec, rng)
        if "year_published" not in st.get("dropped", ()):
            out["year_published"] = str(rec["_year"])
        if "doi" not in st.get("dropped", ()):
            out["doi"] = fmt_doi(rec["_doi"], st.get("id", "bare"))
        out["venue"] = _finish(rec["_venue"], rec, "venue")
        out["volume"] = str(rec["_volume"])
        out["pages"] = f"{rec['_pages']}-{rec['_pages'] + rng.randrange(3, 22)}"
        out["record_key"] = rec["_record_key"]
    order = list(out)
    rng.shuffle(order)
    return {k: out[k] for k in order}


# ---- corruption operations --------------------------------------------------------------
# An operation writes into `_style` or into a non-deciding field. None of them moves
# `_entity`, and none of them moves `name_key` except `surname_change` (a married surname,
# or a company re-registered under another legal suffix), which is only ever drawn where
# the identifier is in both records to confirm it.

OP_TYPES = {
    "typo": RECORD_TYPES, "case": RECORD_TYPES, "abbrev": RECORD_TYPES,
    "initial": ("person", "publication"), "nickname": ("person",),
    "reorder": ("person", "publication"), "date_style": RECORD_TYPES,
    "translit": RECORD_TYPES, "punct": RECORD_TYPES,
    "phone_style": ("person", "company"), "drop": RECORD_TYPES,
    "relocate": ("person", "company"), "surname_change": ("person", "company"),
    "id_style": RECORD_TYPES,
}
OPS = tuple(OP_TYPES)

# `year_published` has no styles to vary, so `date_style` is a no-op on publications; it
# is still a legal member of a publication family, it simply does nothing there.
TYPO_FIELDS = {"person": ("name", "street", "employer"),
               "company": ("name", "street"),
               "publication": ("name", "author", "venue")}   # title, first author, venue
DROPPABLE = {"person": ("employer", "telephone"),
             "company": ("sector", "telephone"),
             "publication": ("volume", "pages")}


def apply_op(op: str, rec: dict, rng: random.Random) -> None:
    t, st = rec["_type"], rec["_style"]
    if t not in OP_TYPES[op]:
        return
    if op == "typo":
        st["typo_field"] = rng.choice(TYPO_FIELDS[t])
        st["typo_seed"] = rng.randrange(1 << 30)
    elif op == "case":
        st["case"] = rng.choice(("upper", "lower"))
    elif op == "abbrev":
        st["abbrev"] = True
    elif op == "initial":
        st["given"] = "initial"
    elif op == "nickname":
        st["given"] = "nickname"
        st["nick_i"] = rng.randrange(1, 4)
    elif op == "reorder":
        st["order"] = rng.choice(("surname_first", "surname_plain"))
    elif op == "date_style":
        st["date"] = rng.choice([s for s in DATE_STYLES if s != st.get("date")])
    elif op == "translit":
        st["translit"] = rng.randrange(1, 3)
    elif op == "punct":
        st["punct"] = True
    elif op == "phone_style":
        st["phone"] = rng.choice(PHONE_STYLES)
    elif op == "drop":
        st.setdefault("dropped", set()).add(rng.choice(DROPPABLE[t]))
    elif op == "relocate":
        rec["_address"] = _address(rng)
    elif op == "surname_change":
        if t == "company":
            # The company's version of a married name: re-registered under another legal
            # suffix. Clause 3 names exactly this ("`Holdings Limited` where the other
            # record says `Limited` is not the same company unless the registration
            # number says so"), and until this existed no company duplicate ever changed
            # its name, so "the names differ -> two companies" was never wrong, even
            # where the policy says the registration number decides.
            rec["_tail"] = rng.choice([x for x in COMPANY_TAILS if x != rec["_tail"]])
        else:
            cur = rec["_surname"]
            rec["_married"] = rng.choice([i for i in range(len(SURNAME)) if i != cur])


TRAINED_FAMILIES: tuple[tuple[str, ...], ...] = (
    ("typo",), ("case",), ("abbrev",), ("initial",), ("nickname",), ("reorder",),
    ("date_style",), ("translit",), ("punct",), ("phone_style",), ("drop",),
    ("relocate",), ("surname_change",), ("id_style",),
    ("typo", "case"), ("nickname", "date_style"), ("abbrev", "relocate"),
    ("translit", "punct"), ("initial", "id_style"), ("reorder", "drop"),
    ("surname_change", "phone_style"), ("typo", "abbrev", "date_style"),
)

# Never trained on. Every operation inside these appears alone in TRAINED_FAMILIES, so a
# drop here is a failure to compose operations the model has, not a failure to recognise
# an operation it has never met. Each is read against a trained neighbour:
# translit+reorder against translit+punct and reorder+drop; surname_change+relocate
# against surname_change+phone_style and abbrev+relocate.
#
# Two of the original six were trained families in disguise, and are replaced.
# `("nickname", "initial", "date_style")`: `initial` overwrites the given-name style
# `nickname` just set, and `date_style` changes nothing `vary_against` had not already
# changed, so on a person it *was* `("initial",)`. `("date_style", "phone_style",
# "drop")` was `("drop",)` for the same reason. See `NULL_OPS`.
HELDOUT_FAMILIES: tuple[tuple[str, ...], ...] = (
    ("translit", "reorder"),
    ("nickname", "reorder", "typo"),
    ("surname_change", "relocate"),
    ("translit", "typo", "punct"),
    ("abbrev", "id_style", "case"),
    ("drop", "case", "nickname"),
)

# Held out of train *and* test: the dev split's own unseen compositions, so checkpoint
# selection and the temperature read transfer without reading a family test measures.
# Same rule as `HELDOUT_FAMILIES` -- every operation appears alone in a trained family,
# and `combos` keeps a (record type, family) only where it composes at least two
# operations no trained family composes -- and no dev family does to any record type
# what a held-out one does (`test_dev_families_are_disjoint_from_trained_and_heldout`).
DEV_FAMILIES: tuple[tuple[str, ...], ...] = (
    ("initial", "relocate"),
    ("typo", "relocate"),
    ("case", "reorder"),
    ("abbrev", "translit", "drop"),
    ("punct", "surname_change"),
)
DEV_NOTE = "held out of train and test; a dev structure -- selects checkpoints and fits T"


def slug(family: tuple[str, ...]) -> str:
    return "_".join(family)


# An operation that does not apply to a record type is a no-op on it: a company has no
# nickname, a year of publication has no format to vary. That matters for the held-out
# families and not much else -- `("nickname", "initial", "date_style")` over a company
# record *is* `("date_style",)`, which is trained, so scoring it as held-out would be
# scoring a trained family under a held-out name.
# A company name has no romanisation to vary (`company_name` never reads `translit`), so
# `("translit",)` over a company was a baseline pair filed under a corruption's name.
NO_EFFECT = {("publication", "date_style"), ("company", "translit")}


def effective(family: tuple[str, ...], rt: str) -> tuple[str, ...]:
    return tuple(op for op in family
                 if rt in OP_TYPES[op] and (rt, op) not in NO_EFFECT)


# Operations that change nothing a baseline pair does not already vary. Every record gets
# its own random date, identifier and telephone style (`randomise_style`), and
# `vary_against` forces the date and identifier styles of the two records apart in every
# pair and every roster entry. Re-drawing one of those styles is therefore a draw from
# the distribution the baseline already has: the singleton families still train (as
# pairs that differ in formatting only), but a held-out family is not new because it
# contains one of these.
NULL_OPS = frozenset({"date_style", "id_style", "phone_style"})


def substantive(family: tuple[str, ...], rt: str) -> frozenset[str]:
    """The operations of `family` that actually move a `rt` record off the baseline."""
    eff = set(effective(family, rt)) - NULL_OPS
    if "initial" in eff:
        eff.discard("nickname")      # `initial` overwrites the given-name style
    return frozenset(eff)


def combos(rtypes: tuple[str, ...], families: tuple[tuple[str, ...], ...],
           heldout: bool) -> tuple[tuple[str, tuple[str, ...]], ...]:
    """The (record type, family) pairs a task may draw, with the degenerate ones gone.

    A held-out (record type, family) is kept only when what it does to that record type
    is a combination of at least two operations that no trained family does."""
    out = []
    for rt in rtypes:
        trained = {substantive(f, rt) for f in TRAINED_FAMILIES}
        for f in families:
            eff = effective(f, rt)
            if not eff:
                continue
            if heldout:
                sub = substantive(f, rt)
                if eff in TRAINED_FAMILIES or len(sub) < 2 or sub in trained:
                    continue
            out.append((rt, f))
    if not out:
        raise ValueError(f"no usable family for {rtypes}")
    return tuple(out)


def apply_family(family: tuple[str, ...], rec: dict, rng: random.Random) -> None:
    for op in family:
        if op == "id_style":
            rec["_style"]["id"] = rng.choice(
                {"person": NINO_STYLES, "company": REGNO_STYLES,
                 "publication": DOI_STYLES}[rec["_type"]])
        else:
            apply_op(op, rec, rng)


def randomise_style(rec: dict, rng: random.Random) -> None:
    """The baseline formatting of a record, before any corruption. Two records of two
    different systems disagree about formatting whether or not they are the same entity,
    so this runs on every record, not only on corrupted ones."""
    st = rec["_style"]
    st["date"] = rng.choice(DATE_STYLES)
    st["id"] = rng.choice({"person": NINO_STYLES, "company": REGNO_STYLES,
                           "publication": DOI_STYLES}[rec["_type"]])
    st["phone"] = rng.choice(PHONE_STYLES)


# ---- the policy, executed ---------------------------------------------------------------

def verdict(a: dict, b: dict) -> tuple[str | None, str]:
    """Run the policy over the two records. -> (option key or None, decisive clause).

    `None` is clause 5: the records do not settle it. The label the corpus carries is
    this function's output, never the construction that produced the pair -- so a
    corruption that accidentally destroyed the evidence is caught here rather than
    shipped with a label the state does not support.
    """
    t = a["_type"]
    idf, datef = ID_FIELD[t], DATE_FIELD[t]
    sa, sb = a["_surf"], b["_surf"]
    if idf in sa and idf in sb:
        same = norm_id(sa[idf]) == norm_id(sb[idf])
        return (OPT_ONE if same else OPT_TWO), "strong_identifier"
    if datef in sa and datef in sb:
        if parse_date(sa[datef]) != parse_date(sb[datef]):
            return OPT_TWO, "fallback_date"
        return (OPT_ONE if name_key(a) == name_key(b) else OPT_TWO), "fallback_date"
    return None, "names_alone"


def materialise(rec: dict, rng: random.Random) -> dict:
    rec["_surf"] = surface(rec, rng)
    return rec


NAME_FIELD = {"person": "full_name", "company": "legal_name",
              "publication": "title"}


def _surface_name(rec: dict) -> tuple:
    """The deciding name as a *reader* sees it: case and punctuation folded away, and
    for a publication the first author beside the title."""
    surf = rec["_surf"]
    out = [depunct(str(surf.get(NAME_FIELD[rec["_type"]], ""))).lower().strip()]
    if rec["_type"] == "publication":
        authors = surf.get("authors") or [""]
        out.append(depunct(str(authors[0])).lower().strip())
    return tuple(out)


def _evidence(query: dict, cand: dict) -> tuple:
    """What the policy actually reads off the two surfaces, as a hashable tuple.

    `verdict` compares hidden indices, so it separates `Theodore Ozdemir` from
    `Thandiwe Ozdemir` even when both records write `T. Ozdemir` and carry the same date
    of birth. A reader cannot, and four rosters in an earlier build have two defensible
    answers for exactly that reason. Two candidates that present the same evidence must
    therefore carry the same verdict. The fold is exact-string after case and punctuation,
    which catches the collisions that actually occur; it does not claim to enumerate every
    rendering the policy calls one name.
    """
    t = query["_type"]
    idf, datef = ID_FIELD[t], DATE_FIELD[t]
    sq, sc = query["_surf"], cand["_surf"]
    if idf in sq and idf in sc:
        return ("id", norm_id(sq[idf]), norm_id(sc[idf]))
    if datef in sq and datef in sc:
        return ("date", parse_date(sq[datef]), parse_date(sc[datef]),
                _surface_name(query), _surface_name(cand))
    return ("unresolved",)


def roster_is_ambiguous(query: dict, cands: list[dict], verdicts: list) -> bool:
    seen: dict[tuple, object] = {}
    for c, v in zip(cands, verdicts):
        e = _evidence(query, c)
        if e in seen and seen[e] != v:
            return True
        seen[e] = v
    return False


def one_slip(x: str, y: str) -> bool:
    """Damerau-Levenshtein distance of at most one: the policy's "single slip"."""
    if x == y:
        return True
    if abs(len(x) - len(y)) > 1:
        return False
    if len(x) == len(y):
        d = [i for i in range(len(x)) if x[i] != y[i]]
        return len(d) == 1 or (len(d) == 2 and d[1] == d[0] + 1
                                and x[d[0]] == y[d[1]] and x[d[1]] == y[d[0]])
    if len(x) > len(y):
        x, y = y, x
    return any(y[:i] + y[i + 1:] == x for i in range(len(y)))


def _shown_given(g: int, rec: dict, author: bool) -> str:
    """The given name as the record writes it, before case, punctuation or a slip."""
    st = rec["_style"].get("given", "full")
    if st == "initial":
        return GIVEN[g][0][0] + "."
    if author or st == "full":
        return GIVEN[g][0]
    return GIVEN[g][rec["_style"].get("nick_i", 1) % len(GIVEN[g])]


def _givens_confusable(ga: int, ta: str, gb: int, tb: str) -> bool:
    """Two *different* given names that clause 3's allowances would reconcile.

    `T.` is the initial of Theodore and of Thandiwe; `Mick` (Michael) is one slip from
    `Nick` (Nikolaos) and `Rick` (Richard). A twin written `T. Ozdemir` beside a
    `Theodore Ozdemir` with the same date of birth is one person under the policy as
    written, whatever the generator knows about her; so is `ZHĀNG, Mick` beside
    `Richard Zhāng`, by way of `Rick` and one slip."""
    if ga == gb:
        return False
    if ta.endswith(".") and ta[0] == GIVEN[gb][0][0]:
        return True
    if tb.endswith(".") and tb[0] == GIVEN[ga][0][0]:
        return True
    return (any(one_slip(ta.lower(), f.lower()) for f in GIVEN[gb])
            or any(one_slip(tb.lower(), f.lower()) for f in GIVEN[ga]))


def names_confusable(a: dict, b: dict) -> bool:
    """True when the hidden names differ but the written ones are reconcilable."""
    t = a["_type"]
    if t == "person":
        sur_a = a["_married"] if a["_married"] is not None else a["_surname"]
        sur_b = b["_married"] if b["_married"] is not None else b["_surname"]
        if sur_a != sur_b:
            return False
        return _givens_confusable(a["_given"], _shown_given(a["_given"], a, False),
                                  b["_given"], _shown_given(b["_given"], b, False))
    if t == "publication":
        if a["_title"] != b["_title"] or a["_part"] != b["_part"]:
            return False
        (ga, sa), (gb, sb) = a["_authors"][0], b["_authors"][0]
        if sa != sb:
            return False
        return _givens_confusable(ga, _shown_given(ga, a, True),
                                  gb, _shown_given(gb, b, True))
    return False


def pair_is_unreadable(a: dict, b: dict) -> bool:
    """True when clause 2 falls through to the names and the policy's own allowances make
    two different entities read as one name: the same written name, or an initial or a
    one-slip spelling that reaches the other's given name. Nothing in the state supports
    a `two_entities` label there, so the draw is discarded rather than shipped."""
    t = a["_type"]
    idf, datef = ID_FIELD[t], DATE_FIELD[t]
    sa, sb = a["_surf"], b["_surf"]
    if idf in sa and idf in sb:
        return False
    if not (datef in sa and datef in sb):
        return False
    if parse_date(sa[datef]) != parse_date(sb[datef]):
        return False
    if name_key(a) == name_key(b):
        return False
    return _surface_name(a) == _surface_name(b) or names_confusable(a, b)


# ---- pair construction -------------------------------------------------------------------

MODES = ("id", "date", "none")


def _force_mode(rec_a: dict, rec_b: dict, mode: str, rng: random.Random) -> None:
    """Make the records carry exactly what the mode says they carry."""
    t = rec_a["_type"]
    idf, datef = ID_FIELD[t], DATE_FIELD[t]
    for r in (rec_a, rec_b):
        r["_style"].setdefault("dropped", set()).discard(idf)
        r["_style"]["dropped"].discard(datef)
    if mode == "id":
        return
    if mode == "date":
        rng.choice((rec_a, rec_b))["_style"]["dropped"].add(idf)
        if rng.random() < 0.35:
            rng.choice((rec_a, rec_b))["_style"]["dropped"].add(idf)
        return
    for r in (rec_a, rec_b):
        r["_style"]["dropped"].add(idf)
    rng.choice((rec_a, rec_b))["_style"]["dropped"].add(datef)
    if rng.random() < 0.4:
        for r in (rec_a, rec_b):
            r["_style"]["dropped"].add(datef)


def vary_against(base: dict, other: dict, rng: random.Random) -> None:
    """Make `other` write its identifier and its date in a different style from `base`.

    Applied to every pair, whatever its label, and to every roster entry against the
    query. Without it a quarter of the identifier-mode pairs render the deciding field
    as the *same string* in both records, and `state.count(gold)` solves them.
    """
    styles = {"person": NINO_STYLES, "company": REGNO_STYLES,
              "publication": DOI_STYLES}[base["_type"]]
    if other["_style"].get("id") == base["_style"].get("id"):
        other["_style"]["id"] = rng.choice([x for x in styles
                                            if x != base["_style"].get("id")])
    if other["_style"].get("date") == base["_style"].get("date"):
        other["_style"]["date"] = rng.choice([x for x in DATE_STYLES
                                              if x != base["_style"].get("date")])


def drift(rec: dict, rng: random.Random) -> None:
    """Move what the policy says never decides: a new number, a new job, a new address.

    Clause 4 is only worth stating if it is exercised. It is also what stops matched
    pairs sitting at a high character similarity: without it the duplicate shares its
    address, telephone and employer with the original word for word, and a similarity
    threshold reads a duplicate off those three fields alone.
    """
    t = rec["_type"]
    if t in ("person", "company") and rng.random() < 0.6:
        rec["_phone"] = (f"{rng.randrange(11, 99)}", f"{rng.randrange(1000000, 9999999)}")
    if t == "person" and rng.random() < 0.45:
        rec["_employer"] = rng.choice(EMPLOYERS)
    if t == "company" and rng.random() < 0.3:
        rec["_sector"] = rng.choice(SECTORS)
    if t in ("person", "company") and rng.random() < 0.45:
        rec["_address"] = _address(rng)
    if t == "publication":
        if rng.random() < 0.5:
            rec["_venue"] = rng.choice(VENUES)
        if rng.random() < 0.6:
            rec["_volume"] = rng.randrange(1, 60)
            rec["_pages"] = rng.randrange(1, 900)


def copy_entity(rec: dict, rng: random.Random) -> dict:
    out = dict(rec)
    out["_style"] = {}
    out["_address"] = dict(rec["_address"]) if "_address" in rec else None
    if out["_address"] is None:
        out.pop("_address")
    out["_authors"] = list(rec["_authors"]) if "_authors" in rec else None
    if out["_authors"] is None:
        out.pop("_authors")
    # A fresh key, drawn like any other record's. The duplicate's key used to be
    # `(original + 7717) % 90000 + 10000`: a fixed function of the original's that no
    # near miss or filler ever satisfied, so "the keys are 7717 apart" labelled 100 % of
    # resolved pairs (measured by a shortcut audit) with clause 4 saying the
    # record key never decides.
    out["_record_key"] = f"{rec['_record_key'][:2]}{rng.randrange(10000, 99999)}"
    return out


# The fields clause 4 says never decide, per record type. A duplicate starts with all of
# them and `drift` moves some; a near miss does the same (`near_miss`), so whether two
# records share a telephone, an address or an employer carries no information about the
# label. It used to: every near miss kept the original's telephone ("one household, one
# line") and employer, while a duplicate drifted its telephone 60 % of the time, so a
# telephone that differed meant one entity on 100 % of the pairs where it happened.
SOFT_FIELDS = {"person": ("_phone", "_address", "_employer"),
               "company": ("_phone", "_address", "_sector"),
               "publication": ("_venue", "_volume", "_pages")}


def share_then_drift(src: dict, other: dict, rng: random.Random) -> None:
    for f in SOFT_FIELDS[src["_type"]]:
        v = src[f]
        other[f] = dict(v) if isinstance(v, dict) else v
    drift(other, rng)


NEAR = {
    "person": ("household", "twin", "namesake", "sibling"),
    "company": ("branch", "successor", "rename_clash"),
    "publication": ("series", "homonym", "preprint"),
}


# The near miss that keeps the *name* the same: a namesake, a branch trading under the
# identical name, the preprint of the same paper. Every other kind changes the name
# (a different given name, a different legal suffix, a part number or another first
# author). Drawn uniformly, those were two in three of the unmatched pairs, and a matched
# pair almost never changes its name, so "same name -> one entity" -- reading neither the
# identifier nor the date -- scored 0.83 on resolved pairs against a majority of 0.51.
# Half of the near misses now keep the name, so the name stops standing in for clauses 1
# and 2.
SAME_NAME_NEAR = {"person": "namesake", "company": "branch", "publication": "preprint"}
P_SAME_NAME_NEAR = 0.5


# The near misses that keep the date and change the name. Under clause 2 a pair is one
# entity only when the date AND the name agree, so the two single steps should each be
# right about as often: with same-name near misses always on another date and a person's
# other near misses mostly on another date too, "same date -> one entity" scored 0.83-0.87
# on date-mode pairs against 0.74 for the name. In date mode the name-changing near miss
# is now the same-date kind most of the time.
SAME_DATE_NEAR = {"person": "twin", "company": "rename_clash", "publication": "series"}
P_SAME_DATE_NEAR = 0.7


def near_kind(rt: str, rng: random.Random, mode: str | None = None) -> str:
    if rng.random() < P_SAME_NAME_NEAR:
        return SAME_NAME_NEAR[rt]
    if mode == "date" and rng.random() < P_SAME_DATE_NEAR:
        return SAME_DATE_NEAR[rt]
    return rng.choice([k for k in NEAR[rt] if k != SAME_NAME_NEAR[rt]])


def near_miss(rec: dict, kind: str, rng: random.Random) -> dict:
    """A *different* entity that looks as much like `rec` as the world allows."""
    t = rec["_type"]
    other = NEW[t](rng)
    other["_entity"] = _key(rng)
    # What clause 4 says never decides is shared exactly as a duplicate shares it: all of
    # it, then `drift`. A household, a branch or a preprint still often sits at the same
    # address or under the same switchboard -- as often as a duplicate does, no more.
    share_then_drift(rec, other, rng)
    if t == "person":
        other["_surname"] = rec["_surname"]
        if kind == "household":                            # a parent and a child
            other["_given"] = rng.choice([i for i in range(len(GIVEN))
                                          if i != rec["_given"]])
            shift = rng.randrange(18, 42) * 365
            other["_dob"] = rec["_dob"] - timedelta(days=shift)
        elif kind == "twin":                               # same roof, same day
            other["_given"] = rng.choice([i for i in range(len(GIVEN))
                                          if i != rec["_given"]])
            other["_dob"] = rec["_dob"]
        elif kind == "sibling":
            other["_given"] = rng.choice([i for i in range(len(GIVEN))
                                          if i != rec["_given"]])
            other["_dob"] = rec["_dob"] - timedelta(days=rng.randrange(400, 1400))
            d, letter, prefix = rec["_nino"]               # consecutive registrations
            other["_nino"] = (f"{(int(d) + rng.choice((-1, 1))) % 1000000:06d}",
                              letter, prefix)
        else:                                              # namesake in a large city
            other["_given"] = rec["_given"]
            other["_dob"] = date(rng.randrange(1938, 2006), rng.randrange(1, 13),
                                 rng.randrange(1, 29))
    elif t == "company":
        other["_head"], other["_mid"] = rec["_head"], rec["_mid"]
        if kind == "branch":                               # two branches, one name
            other["_tail"] = rec["_tail"]
            other["_dob"] = rec["_dob"] + timedelta(days=rng.randrange(400, 5000))
        elif kind == "successor":                          # X Ltd and X Holdings Ltd
            other["_tail"] = rng.choice([x for x in COMPANY_TAILS if x != rec["_tail"]])
            other["_dob"] = rec["_dob"] + timedelta(days=rng.randrange(900, 7000))
        else:                                              # same office, same day
            other["_tail"] = rng.choice([x for x in COMPANY_TAILS if x != rec["_tail"]])
            other["_dob"] = rec["_dob"]
    else:
        if kind == "series":                               # Part I and Part II
            other["_title"] = rec["_title"]
            other["_authors"] = list(rec["_authors"])
            # Only a record not yet written down may gain its `Part I`. A roster query is
            # materialised before its near misses are drawn, so setting it there moved
            # the query's hidden name away from what its surface says: `verdict` then
            # called the query's own duplicate `two_entities` and the roster was redrawn
            # -- silently, every time a publication roster matched by date also drew a
            # `series` distractor.
            if rec["_part"] is None and "_surf" not in rec:
                rec["_part"] = "I"
            other["_part"] = "II"
            other["_year"] = rec["_year"]
            other["_dob"] = date(other["_year"], 1, 1)
        elif kind == "homonym":                            # one title, other authors
            other["_title"] = rec["_title"]
            other["_year"] = rec["_year"]
            other["_dob"] = date(other["_year"], 1, 1)
        else:                                              # preprint and journal version
            other["_title"] = rec["_title"]
            other["_authors"] = list(rec["_authors"])
            other["_year"] = rec["_year"] + rng.randrange(1, 4)
            other["_dob"] = date(other["_year"], 1, 1)
    return other


# Clause 1 is only worth stating if it is ever needed. Without these, a pair in which
# both records carry the identifier always had the date and the name agreeing with it --
# duplicates never disagreed about a date, and no near miss shared both name and date --
# so "skip clause 1, read the date and the name" scored 0.93-0.96 on identifier-mode
# pairs (only `surname_change` ever separated the two readings;
# measured by a shortcut audit). Now, in that share of identifier-mode pairs,
# clauses 2 and 3 read the other way from clause 1: a duplicate whose second system keyed
# the date wrong, or a namesake / same-named branch / preprint on the same date under
# another identifier. Only the identifier gets these right, which is what clause 1 says.
# Outside identifier mode such a pair is not drawn: clause 2 would read it the other way
# and `verdict` would refuse it.
P_ID_CONFLICT = 0.45


def miskey_date(rec: dict, rng: random.Random) -> None:
    """One system keyed the date wrong: day and month swapped, a day or a year off."""
    d = rec["_dob"]
    if rec["_type"] == "publication":
        rec["_year"] = rec["_year"] + rng.choice((-1, 1))
        rec["_dob"] = date(rec["_year"], 1, 1)
        return
    kinds = ["days", "year"] + (["swap"] if d.day <= 12 and d.day != d.month else [])
    kind = rng.choice(kinds)
    if kind == "swap":
        rec["_dob"] = date(d.year, d.day, d.month)
    elif kind == "year":
        rec["_dob"] = date(d.year + rng.choice((-10, -1, 1, 10)), d.month, d.day)
    else:
        rec["_dob"] = d + timedelta(days=rng.choice((-1, 1)) * rng.randrange(1, 30))


def same_date_as(rec: dict, src: dict) -> None:
    rec["_dob"] = src["_dob"]
    if rec["_type"] == "publication":
        rec["_year"] = src["_year"]


def build_pair(rt: str, family: tuple[str, ...], want: str, mode: str,
               rng: random.Random) -> tuple[dict, dict] | None:
    """One pair. `want` is the label being aimed at; the label shipped is `verdict`'s.

    Returns None when the draw did not land on `want` -- the caller redraws rather than
    relabelling, which is what keeps the corruption in charge of the label.
    """
    a = NEW[rt](rng)
    randomise_style(a, rng)
    conflict = mode == "id" and rng.random() < P_ID_CONFLICT
    if want == OPT_ONE:
        b = copy_entity(a, rng)
        randomise_style(b, rng)
        drift(b, rng)
        apply_family(family, b, rng)
        if "surname_change" in family and mode != "id":
            return None                        # clause 3: unconfirmable without the id
        if conflict:
            miskey_date(b, rng)
    else:
        b = near_miss(a, SAME_NAME_NEAR[rt] if conflict else near_kind(rt, rng, mode),
                      rng)
        if conflict:
            same_date_as(b, a)
        randomise_style(b, rng)
        # the noise sits on both halves, so "the messy one is the duplicate" is not a tell
        apply_family(family, rng.choice((a, b)), rng)
        if "surname_change" in family and mode != "id":
            return None
    _force_mode(a, b, mode, rng)
    vary_against(a, b, rng)
    materialise(a, rng)
    materialise(b, rng)
    if pair_is_unreadable(a, b):
        return None
    got, _ = verdict(a, b)
    if mode == "none":
        return (a, b) if got is None else None
    return (a, b) if got == want else None


def draw_pair(rt: str, family: tuple[str, ...], want: str, mode: str,
              rng: random.Random, tries: int = 40) -> tuple[dict, dict]:
    for _ in range(tries):
        got = build_pair(rt, family, want, mode, rng)
        if got is not None:
            return got
    # every family has at least one mode it always lands in; `id` is it
    for _ in range(tries):
        got = build_pair(rt, family, want, "id", rng)
        if got is not None:
            return got
    raise RuntimeError(f"could not build a {want} {rt} pair for {slug(family)}")


# ---- states ------------------------------------------------------------------------------

def render_pair(a: dict, b: dict, shape: str, rng: random.Random) -> str:
    if shape == "json":
        return json.dumps({"record_from_system_a": a["_surf"],
                           "record_from_system_b": b["_surf"]}, indent=2,
                          ensure_ascii=False)
    return (f"Record from system A. {_prose(a)}\n\n"
            f"Record from system B. {_prose(b)}")


def _prose(rec: dict) -> str:
    parts = []
    for k, v in rec["_surf"].items():
        label = k.replace("_", " ")
        text = ", ".join(v) if isinstance(v, list) else v
        parts.append(f"{label}: {text}")
    return "; ".join(parts) + "."


def _row(rec: dict, columns: tuple[str, ...], compact: bool = False) -> str:
    cells = []
    for c in columns:
        if compact and isinstance(rec["_surf"].get(c), list):
            # forty full author lists do not fit the state budget, and the policy only
            # ever reads the first author
            names = rec["_surf"][c]
            cells.append(names[0] + (" et al." if len(names) > 1 else ""))
            continue
        if c not in rec["_surf"]:
            # a blank cell would read as an empty value, and an empty value that matched
            # another empty value would be clause 1 firing on nothing
            cells.append("(not recorded)")
            continue
        v = rec["_surf"][c]
        cells.append("; ".join(v) if isinstance(v, list) else str(v))
    return " | ".join(cells)


TABLE_COLUMNS = {
    "person": ("full_name", "date_of_birth", "national_insurance_no", "address", "city",
               "postcode", "telephone", "employer", "record_key"),
    "company": ("legal_name", "incorporated_on", "registration_number",
                "registered_office", "city", "postcode", "sector", "telephone",
                "record_key"),
    "publication": ("title", "authors", "year_published", "doi", "venue", "volume",
                    "pages", "record_key"),
}


def render_roster(query: dict, keys: list[str], cands: list[dict], shape: str) -> str:
    rt = query["_type"]
    if shape == "json":
        return json.dumps({"query": query["_surf"],
                           "roster": {k: c["_surf"] for k, c in zip(keys, cands)}},
                          indent=2, ensure_ascii=False)
    # forty rows of nine columns is 3,600 tokens, over `ship_v4.sh --max-state-tokens`.
    # A wide roster drops the columns clause 4 says never decide anyway.
    compact = len(cands) > 12
    cols = NARROW_COLUMNS[rt] if compact else TABLE_COLUMNS[rt]
    head = "entry | " + " | ".join(c.replace("_", " ") for c in cols)
    lines = [f"Query record: {_prose(query)}", "", "Roster.", head,
             "-" * min(len(head), 90)]
    lines += [f"{k} | {_row(c, cols, compact)}" for k, c in zip(keys, cands)]
    return "\n".join(lines)


NARROW_COLUMNS = {
    "person": ("full_name", "date_of_birth", "national_insurance_no", "address", "city"),
    "company": ("legal_name", "incorporated_on", "registration_number", "city"),
    "publication": ("title", "authors", "year_published", "doi"),
}

ROSTER_SIZES = (6, 8, 8, 10, 12, 12, 16, 20, 24, 28, 32, 40)


def roster_keys(n: int, rng: random.Random) -> list[str]:
    stem = rng.choice(("e", "r", "c", "x"))
    return [f"{stem}{i:02d}" for i in range(1, n + 1)]


# ---- examples ------------------------------------------------------------------------------

# Every stem is a registered template (`lod/assets/phrasing_specs/d17.json`), so a frozen
# phrasing bank can widen the wording later. The template is drawn from `rng` exactly as
# before; the bank's choice among its wordings is keyed on the rendered state, so a
# rebuild picks the same wording for the same record. With an empty bank `pick` hands the
# template back unchanged.
STEM_POOLS = {"pair": PAIR_STEMS, "roster": ROSTER_STEMS, "decisive": DECISIVE_STEMS,
              "pairwise": PAIRWISE_FOLLOWUP}
_BANK: PhrasingBank | None = None


def _bank() -> PhrasingBank:
    global _BANK
    if _BANK is None:
        _BANK = PhrasingBank.load()
    return _BANK


def template_id(kind: str, i: int) -> str:
    return f"d17.{kind}_{i}"


def _stem(kind: str, rng: random.Random, state: str, **kw) -> str:
    pool = STEM_POOLS[kind]
    template = rng.choice(pool)
    key = hashlib.sha1(f"{kind}\x00{state}".encode("utf-8")).hexdigest()[:16]
    return _bank().pick(template_id(kind, pool.index(template)), template, key).format(**kw)


def pair_example(rt: str, family: tuple[str, ...], rng: random.Random,
                 task: str) -> Example:
    mode = _draw_mode(rng)
    want = OPT_ONE if rng.random() < 0.5 else OPT_TWO
    a, b = draw_pair(rt, family, want, mode, rng)
    got, clause = verdict(a, b)
    shape = "json" if rng.random() < 0.5 else "prose"
    options = [OPT_TWO, OPT_ONE]
    if got is None:
        # clause 5. Drawn one-entity exactly half the time, so 0.5 is the real rate.
        target: list[float] = [0.5, 0.5]
        meta = {"family": slug(family), "record_type": rt, "clause": clause,
                "mode": mode, "unresolved": True}
    else:
        target = [1.0, 0.0] if got == OPT_TWO else [0.0, 1.0]
        meta = {"family": slug(family), "record_type": rt, "clause": clause,
                "mode": mode}
    state = render_pair(a, b, shape, rng)
    q = Question("pair", _stem("pair", rng, state, noun=NOUN[rt]), options, target, meta,
                 policy(rt), list(DESC[rt]))
    return Example(state=state, questions=[q], task=task)


def _draw_mode(rng: random.Random) -> str:
    r = rng.random()
    return "id" if r < 0.36 else ("date" if r < 0.70 else "none")


def decisive_example(rt: str, family: tuple[str, ...], rng: random.Random,
                     task: str) -> Example:
    mode = _draw_mode(rng)
    want = OPT_ONE if rng.random() < 0.5 else OPT_TWO
    a, b = draw_pair(rt, family, want, mode, rng)
    _, clause = verdict(a, b)
    shape = "json" if rng.random() < 0.5 else "prose"
    options = list(DECISIVE_OPTIONS)
    target = [1.0 if o == clause else 0.0 for o in options]
    state = render_pair(a, b, shape, rng)
    q = Question("decisive", _stem("decisive", rng, state), options, target,
                 {"family": slug(family), "record_type": rt, "mode": mode},
                 policy(rt), decisive_descriptions(rt))
    return Example(state=state, questions=[q], task=task)


# The share of distractors written down without the identifier. `_force_mode` drops it
# from the twin in about two date-mode rosters in three, and nothing else ever lacked
# it, so in a roster whose query carries the identifier the one row reading `(not
# recorded)` was the answer: "pick the only entry missing a key field" scored 0.41-0.45
# against a chance of 0.07 (measured by a shortcut audit). A distractor
# without its identifier falls to clause 2 against the query, which is the clause the
# roster should exercise anyway. Set near the twin's own rate of missing it (~0.4).
P_DISTRACTOR_NO_ID = 0.4


def _maybe_drop_id(c: dict, rng: random.Random) -> None:
    if rng.random() < P_DISTRACTOR_NO_ID:
        c["_style"].setdefault("dropped", set()).add(ID_FIELD[c["_type"]])


def roster_example(rt: str, family: tuple[str, ...], rng: random.Random,
                   task: str, heldout: bool = False) -> Example:
    """One query, `n` candidates, several of them near misses. Sometimes nothing matches.

    Every query/candidate pair is checked against the policy before the example is
    emitted: exactly one candidate may resolve to the query, and no other may be
    unresolvable, or the roster has more than one defensible answer.
    """
    n = rng.choice(ROSTER_SIZES)
    # `has_match` and `offer_none` together set P(the sentinel is the answer | it is on
    # the list). At 0.78 / 0.25 that was 0.22 / 0.415 = 0.530 in an earlier build -- seven
    # times the 1/n a roster entry gets, and nearly three times the 0.188 the corpus
    # audit reports. "If a `none` option is offered, take it" is then a rule worth 53 %
    # of the rosters that carry one, which is an earlier model's sentinel failure in slow
    # motion. Offering it almost always, and leaving fewer rosters without a match, puts it
    # at 0.14 / 0.914 = 0.153 -- close to the corpus figure and far enough above 1/n that
    # never taking it is not free either.
    has_match = rng.random() < 0.86
    offer_none = (not has_match) or rng.random() < 0.90
    for _ in range(30):
        query = NEW[rt](rng)
        randomise_style(query, rng)
        materialise(query, rng)
        cands: list[dict] = []
        if has_match:
            twin = copy_entity(query, rng)
            randomise_style(twin, rng)
            drift(twin, rng)
            apply_family(family, twin, rng)
            tmode = ("id" if "surname_change" in family
                     else rng.choice(("id", "date", "date")))
            if tmode == "id" and rng.random() < P_ID_CONFLICT:
                miskey_date(twin, rng)             # only the identifier finds it
            _force_mode(query, twin, tmode, rng)
            materialise(query, rng)
            materialise(twin, rng)
            vary_against(query, twin, rng)
            materialise(twin, rng)
            if verdict(query, twin)[0] != OPT_ONE:
                continue
            cands.append(twin)
        n_near = min(n - len(cands), rng.randint(2, max(2, n // 3)))
        # The roster's version of `P_ID_CONFLICT`: when the query carries its identifier,
        # one near miss may carry the query's name *and* its date under another
        # identifier. Without it the entry with the query's date and the closest name
        # was the answer on 0.80-0.85 of rosters, clause 1 unread.
        query_has_id = ID_FIELD[rt] not in query["_style"].get("dropped", ())
        conflict = query_has_id and rng.random() < P_ID_CONFLICT
        for j in range(n_near):
            clash = conflict and j == 0
            c = near_miss(query, SAME_NAME_NEAR[rt] if clash else near_kind(rt, rng), rng)
            if clash:
                same_date_as(c, query)
            randomise_style(c, rng)
            if rng.random() < 0.5:
                apply_family(family, c, rng)
            if not clash:
                _maybe_drop_id(c, rng)
            vary_against(query, c, rng)
            materialise(c, rng)
            cands.append(c)
        while len(cands) < n:
            c = NEW[rt](rng)
            randomise_style(c, rng)
            _maybe_drop_id(c, rng)
            vary_against(query, c, rng)
            materialise(c, rng)
            cands.append(c)
        verdicts = [verdict(query, c)[0] for c in cands]
        if verdicts.count(OPT_ONE) != (1 if has_match else 0):
            continue
        if None in verdicts:
            continue
        if roster_is_ambiguous(query, cands, verdicts):
            continue
        if any(pair_is_unreadable(query, c) for c in cands):
            continue
        rng.shuffle(cands)
        keys = roster_keys(n, rng)
        shape = "json" if n <= 8 and rng.random() < 0.5 else "table"
        state = render_roster(query, keys, cands, shape)
        # The "nothing here matches" option is drawn from `lod.sentinel`, not written
        # out. A fixed wording here repeated 1,402 times in an earlier build and failed
        # `sentinel_audit`'s max-exact-repeat bar of 50 -- the same memorisable-string
        # failure an earlier model shipped with, where one phrase became perfectly
        # predictive. `sentinel.sample` draws from a 24,804-string grammar and keeps a
        # hashed 20 % of the space out of training, so `sentinel_wordings` can read
        # unseen wordings here too.
        none_key, none_desc = sentinel.sample(
            rng, split="eval" if heldout else "train")
        if none_key in keys:                       # never collide with a roster label
            none_key = f"{none_key}_x"
        options = keys + ([none_key] if offer_none else [])
        gold = next((k for k, c in zip(keys, cands)
                     if verdict(query, c)[0] == OPT_ONE), none_key)
        if gold == none_key and not offer_none:
            continue
        target = [1.0 if o == gold else 0.0 for o in options]
        descs = [f"The roster entry filed under {k}." for k in keys]
        if offer_none:
            descs.append(none_desc)
        qs = [Question("roster", _stem("roster", rng, state, noun=NOUN[rt]), options,
                       target, {"family": slug(family), "record_type": rt,
                                "roster_size": n, "has_match": has_match},
                       policy(rt), descs)]
        if rng.random() < 0.28:
            # a contrastive second question over the same sequence: one entry, on its
            # own. Drawn from the matching entry half the time when there is one, or the
            # follow-up is a constant `two_entities` and teaches nothing.
            #
            # The entry is drawn UNIFORMLY from the eligible ones, not taken as the first
            # of them. `next(...)` handed back candidate 0 for every `two_entities`
            # follow-up and the twin's (shuffled, so uniform) position for every
            # `one_entity` one, and the question stem names the entry: in an earlier build
            # entry `?01` is `two_entities` 95 % of the time and every entry from `?03`
            # up is `one_entity` 100 % of the time, so 94.2 % of the 2,769 follow-ups are
            # answerable from the question stem alone with the state unread.
            want_one = has_match and rng.random() < 0.5
            eligible = [i for i, c in enumerate(cands)
                        if (verdict(query, c)[0] == OPT_ONE) == want_one]
            idx = rng.choice(eligible) if eligible else None
            if idx is not None:
                v, clause = verdict(query, cands[idx])
                qs.append(Question(
                    "pairwise", _stem("pairwise", rng, state, key=keys[idx],
                                      noun=NOUN[rt]),
                    [OPT_TWO, OPT_ONE], [1.0, 0.0] if v == OPT_TWO else [0.0, 1.0],
                    {"family": slug(family), "record_type": rt, "clause": clause,
                     "entry": keys[idx]}, policy(rt), list(DESC[rt])))
        return Example(state=state, questions=qs, task=task)
    return pair_example(rt, family, rng, task)


# ---- tasks -------------------------------------------------------------------------------

def _loader(kind: str, rtypes: tuple[str, ...], families: tuple[tuple[str, ...], ...],
            task: str, seed: int):
    heldout = families is HELDOUT_FAMILIES
    # dev families are filtered like held-out ones, but draw the roster's abstention wording
    # from the sentinel's train half: its eval half is test's (`sentinel_wordings`) to read
    pool = combos(rtypes, families, heldout or families is DEV_FAMILIES)
    def load(n: int) -> Iterator[Example]:
        h = hashlib.sha256(f"entityres:{seed}:{task}:{kind}".encode()).digest()
        rng = random.Random(int.from_bytes(h[:8], "big"))
        for i in range(n):
            rt, family = pool[i % len(pool)]
            if kind == "pair":
                yield pair_example(rt, family, rng, task)
            elif kind == "decisive":
                yield decisive_example(rt, family, rng, task)
            else:
                yield roster_example(rt, family, rng, task, heldout)
    return load


def tasks() -> list[RealTask]:
    """Trained families in `train`, with a fresh-seed twin of each kind in `devreal`;
    `HELDOUT_FAMILIES` in `testreal` and `DEV_FAMILIES` in `devreal`, each over pairs and
    rosters, neither ever trained on and disjoint from each other.

    Family: every task over `TRAINED_FAMILIES` is `entityres_trained`, so a twin is never
    counted as held out; the held-out pair and roster share `entityres_heldout`, and the
    dev pair and roster `entityres_dev`.
    """
    out: list[RealTask] = []
    for rt in RECORD_TYPES:
        out.append(RealTask(
            row=ROW, name=f"entityres_pair_{rt}", licence=LICENCE, url=URL,
            load=_loader("pair", (rt,), TRAINED_FAMILIES, f"entityres_pair_{rt}", 11),
            soft=True, real=False, family="entityres_trained", force_split="train",
            notes=f"{rt} pairs, trained corruption families; code-labelled"))
        out.append(RealTask(
            row=ROW, name=f"entityres_roster_{rt}", licence=LICENCE, url=URL,
            load=_loader("roster", (rt,), TRAINED_FAMILIES,
                         f"entityres_roster_{rt}", 12),
            real=False, per_example_options=True, family="entityres_trained", force_split="train",
            notes=f"{rt} rosters of 6-40 entries; high distractor density"))
    out.append(RealTask(
        row=ROW, name="entityres_decisive", licence=LICENCE, url=URL,
        load=_loader("decisive", RECORD_TYPES, TRAINED_FAMILIES,
                     "entityres_decisive", 13),
        real=False, family="entityres_trained", force_split="train",
        notes="which clause of the matching policy carries the pair"))
    out.append(RealTask(
        row=ROW, name="entityres_pair_eval", licence=LICENCE, url=URL,
        load=_loader("pair", RECORD_TYPES, TRAINED_FAMILIES, "entityres_pair_eval", 907),
        soft=True, real=False, family="entityres_trained", force_split="devreal",
        notes="trained families, examples never trained on"))
    out.append(RealTask(
        row=ROW, name="entityres_roster_eval", licence=LICENCE, url=URL,
        load=_loader("roster", RECORD_TYPES, TRAINED_FAMILIES,
                     "entityres_roster_eval", 908),
        real=False, per_example_options=True, family="entityres_trained", force_split="devreal",
        notes="trained families, rosters never trained on"))
    out.append(RealTask(
        row=ROW, name="entityres_heldout_pair", licence=LICENCE, url=URL,
        load=_loader("pair", RECORD_TYPES, HELDOUT_FAMILIES,
                     "entityres_heldout_pair", 7717),
        soft=True, real=False, family="entityres_heldout", force_split="testreal",
        notes="corruption families NEVER trained on; every operation inside them is"))
    out.append(RealTask(
        row=ROW, name="entityres_heldout_roster", licence=LICENCE, url=URL,
        load=_loader("roster", RECORD_TYPES, HELDOUT_FAMILIES,
                     "entityres_heldout_roster", 7718),
        real=False, per_example_options=True, family="entityres_heldout", force_split="testreal",
        notes="held-out families over rosters; the transfer question at cardinality"))
    out.append(RealTask(
        row=ROW, name="entityres_dev_pair", licence=LICENCE, url=URL,
        load=_loader("pair", RECORD_TYPES, DEV_FAMILIES, "entityres_dev_pair", 5501),
        soft=True, real=False, family="entityres_dev", force_split="devreal",
        notes="corruption families in neither train nor test; " + DEV_NOTE))
    out.append(RealTask(
        row=ROW, name="entityres_dev_roster", licence=LICENCE, url=URL,
        load=_loader("roster", RECORD_TYPES, DEV_FAMILIES, "entityres_dev_roster", 5502),
        real=False, per_example_options=True, family="entityres_dev",
        force_split="devreal",
        notes="dev-held families over rosters; " + DEV_NOTE))
    return out
