"""Row 35 — entity facts with every attribute randomised.

The failure this exists to stop is the model answering from the backbone's memory rather
than from the state. A question about Manchester's population is answerable without
reading the record; a question about Varnhold Kestrel's is not, because Varnhold Kestrel
does not exist and its attributes were drawn a moment ago.

Each fact is presented in **three** states, which is the whole point:

    supported        the record carries the attribute, with this value        -> yes
    refuted          the record carries the attribute, with another value     -> no
    not in context   the record carries the entity but not that attribute     -> abstain

The third is the one that is usually got wrong. Labelling it `no` teaches "absent means
false", which is exactly the confidently-wrong behaviour the confidence head exists to
prevent, and it is why the shipped model answers a caller's out-of-scope question with a
clean 0.83 instead of an abstention. It carries no score target and supervises confidence
toward 0. The record is never empty in that case either, and the dropped attribute is
**backfilled** with the unused attribute of the *same value type*, so the not-in-context
record carries exactly as many attributes as its supported/refuted twins -- and exactly as
many values of the claim's type. Length is not the tell either: a length-only classifier
cannot beat the majority baseline (`tests/test_synth_sources.py`, domain 6).

The claimed value must be *bound* to the attribute, not merely found. With one attribute
per value type (the row as first shipped: eight attributes, eight types), "the claimed
value occurs anywhere in the record" separated supported from refuted, and supported
from not-in-context -- the pair `unseen_entity_abstention` measures -- 1.000 on every
split, with no attribute lookup at all. Every value type now has three attributes
(`TYPES`); the record always carries two of the asked attribute's type (the asked one and a
MATE) and never the third, which is the backfill. On a DECOY triple the refuted and the
not-in-context twins both claim the value the record gives the mate: in the record, under
another attribute. The value-anywhere cue is then right on 1 - DECOY/2 of the scored
questions, and "how many values of the claim's type does the record hold" is 2 in every
twin. A shortcut audit measures both.

Entity names are partitioned by a hash of the name, so the entities
`unseen_entity_abstention` is measured on were never trained on -- and the held-out
quarter is itself split in two, so the devreal twin the gate is selected against shares
no name with the testreal task it is scored on.
"""

from __future__ import annotations

import hashlib
import json
import random
from typing import Iterator

from lod.phrasings import PhrasingBank
from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/entities.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/entities.py"
ROW = 35

_A = ("Var", "Kes", "Hol", "Mar", "Ald", "Bren", "Cor", "Dun", "Elv", "Fen",
      "Gal", "Hask", "Ives", "Jorn", "Kelm", "Lund", "Morr", "Neth", "Oss", "Pell")
_B = ("nhold", "trel", "loway", "bury", "stead", "wick", "mere", "ford", "gate",
      "combe", "thorpe", "garth", "haven", "ridge", "shaw", "dale")
# Widened from 12 to 16 when the held-out quarter was split in two (see
# `entity_split`): halving the eval pool had taken `entity_fact_unseen` from 478
# distinct names per 2,000 examples to 343. Adding suffixes only *adds* names -- every
# name that already existed hashes to the bucket it always did -- so the train
# partition is unchanged by this.
_C = ("Group", "Institute", "Works", "Collective", "Foundation", "Consortium",
      "Laboratory", "Union", "Trust", "Society", "Company", "Office",
      "Partnership", "Bureau", "Syndicate", "Association")

PLACES = ("Ostrivka", "Caldmere", "Tern Hollow", "Brastol", "Ashen Reach", "Vellim",
          "Norday", "Pellgate", "Cray Basin", "Umberfell", "Salt Marrow", "Kirn")
SECTORS = ("freight logistics", "seed genetics", "ceramic tooling", "marine survey",
           "textile dyeing", "grid metering", "cold storage", "precision casting",
           "hydrographic charting", "isotope assay")
STATUSES = ("active", "dissolved", "merged", "dormant", "in administration")
CHARTERS = ("charter_a", "charter_b", "charter_c", "charter_d")

# The third case is not one of the two options, and nothing else in the question says so:
# both descriptions assert the record *has* the attribute, which is false for every
# `not_in_context` example. `grounding.py` -- the other half of domain 6 -- has always
# carried this sentence; row 35 shipped 2,758 abstention questions in an earlier
# build without it, so the one case the row exists to teach was the one case the prompt
# did not name.
INSTRUCTION = ("Answer from the record above and nothing else. If the record does not "
               "give this attribute at all, the claim is not in context.")


def _name(rng: random.Random) -> str:
    return f"{rng.choice(_A)}{rng.choice(_B)} {rng.choice(_C)}"


# The question template, registered in `lod/assets/phrasing_specs/d06.json`; the wording
# is drawn per record from the phrasing bank (the template itself while the bank is empty).
Q_ID = "d06.entity_fact"
Q_TEMPLATE = "According to the record above, is this claim correct: {claim}?"
_BANK: PhrasingBank | None = None


def _phrasing(key: str) -> str:
    global _BANK
    if _BANK is None:
        _BANK = PhrasingBank.load()
    return _BANK.pick(Q_ID, Q_TEMPLATE, key)


def entity_split(name: str) -> str:
    """`train`, `unseen` or `unseen_dev`, by a hash of the name.

    `unseen_entity_abstention` reads `unseen` (testreal) and its devreal twin reads
    `unseen_dev`. The held-out quarter is split in two rather than shared: both eval tasks
    used to draw from one `unseen` pool with different seeds, and in an earlier build that
    left **242 of ~480 entity names in both `entity_fact_unseen` and
    `entity_fact_unseen_dev`** -- so selecting a checkpoint on devreal was selecting on
    half the names the gate then scored. The `train` bucket is untouched by this split: a
    name that hashed to `train` before still does.
    """
    h = int.from_bytes(hashlib.sha256(name.encode()).digest()[:8], "big")
    if (h % 100) >= 25:
        return "train"
    return "unseen_dev" if (h // 100) % 2 else "unseen"


# Three attributes per value type. The first of each is one of the eight the row
# started with; the other two exist so that a value of that type can sit in the record
# under an attribute other than the one the claim names. None of the three says anything
# about the other two -- a company's largest site is not its headquarters, the sector it
# sells to is not the one it operates in, a rival's standing is not its own -- so a
# claim about one is never settled by another, only matched or not matched by it.
TYPES = {
    "year": ("founded_in", "listed_in", "rebranded_in"),
    "count": ("employees", "shareholders", "contractors"),
    "place": ("headquartered_in", "largest_site_in", "first_office_in"),
    "sector": ("sector", "sells_to", "buys_from"),
    "standing": ("status", "rival_standing", "supplier_standing"),
    "org": ("parent_organisation", "largest_customer", "main_competitor"),
    "class": ("charter_class", "supplier_requirement", "partner_requirement"),
    "code": ("registry_number", "tax_number", "licence_number"),
}
TYPE_OF = {a: t for t, attrs in TYPES.items() for a in attrs}
ATTRS = tuple(a for attrs in TYPES.values() for a in attrs)


def _parent(rng: random.Random, split: str | None, entity: str | None) -> str:
    """An organisation's name (parent, customer, competitor): from the entity's own hash
    bucket, never itself.

    Parent names used to be drawn from the whole name space, so a held-out name turned up
    as somebody's parent in training: 48 of 407 `entity_fact_unseen` names (11.8 %) and
    50 of 429 `entity_fact_unseen_dev` names appeared verbatim in 2,000 train states, and
    3 in 2,000 unseen records named the entity as its own parent.
    """
    for _ in range(400):
        name = _name(rng)
        if name != entity and (split is None or entity_split(name) == split):
            return name
    raise RuntimeError(f"no parent name in bucket {split!r}")


# Share of triples whose refuted and not-in-context twins claim the mate's value. The
# rest keep a value the record does not hold anywhere, so "absent from the record" is
# still seen in both cases rather than becoming the not-in-context tell by itself.
DECOY = 0.8
_YEARS = (1780, 2024)
_COUNTS = (6, 48000)


def _value(attr: str, rng: random.Random, split: str | None = None,
           entity: str | None = None):
    t = TYPE_OF[attr]
    if t == "year":
        return rng.randrange(*_YEARS)
    if t == "count":
        return rng.randrange(*_COUNTS)
    if t == "place":
        return rng.choice(PLACES)
    if t == "sector":
        return rng.choice(SECTORS)
    if t == "standing":
        return rng.choice(STATUSES)
    if t == "org":
        return _parent(rng, split, entity)
    if t == "class":
        return rng.choice(CHARTERS)
    return f"{rng.randrange(10, 99)}-{rng.randrange(1000, 9999)}"


def _fresh(attr: str, taken, rng: random.Random, split: str | None = None,
           entity: str | None = None):
    """A value of `attr`'s type unlike every value in `taken` (numbers >= 4 apart)."""
    for _ in range(400):
        v = _value(attr, rng, split, entity)
        if isinstance(v, int):
            if all(abs(v - t) >= 4 for t in taken):
                return v
        elif v not in taken:
            return v
    raise RuntimeError(f"no fresh value for {attr} beside {taken!r}")


def _phrase(attr: str, value) -> str:
    return {
        "founded_in": f"was founded in {value}",
        "listed_in": f"was first listed in {value}",
        "rebranded_in": f"was last rebranded in {value}",
        "employees": f"employs {value} people",
        "shareholders": f"has {value} shareholders",
        "contractors": f"engages {value} contractors",
        "headquartered_in": f"is headquartered in {value}",
        "largest_site_in": f"has its largest site in {value}",
        "first_office_in": f"opened its first office in {value}",
        "sector": f"operates in {value}",
        "sells_to": f"sells mainly to {value} firms",
        "buys_from": f"buys mainly from {value} firms",
        "status": f"has the status {value}",
        "rival_standing": f"faces a main rival that is {value}",
        "supplier_standing": f"relies on a supplier that is {value}",
        "parent_organisation": f"has {value} as its parent organisation",
        "largest_customer": f"counts {value} as its largest customer",
        "main_competitor": f"names {value} as its main competitor",
        "charter_class": f"holds charter class {value}",
        "supplier_requirement": f"requires its suppliers to hold {value}",
        "partner_requirement": f"partners only with holders of {value}",
        "registry_number": f"has registry number {value}",
        "tax_number": f"has tax number {value}",
        "licence_number": f"has licence number {value}",
    }[attr]


def _render(name: str, rec: dict, shape: str) -> str:
    if shape == "json":
        return json.dumps({"entity": name, **rec}, indent=2)
    items = list(rec.items())
    parts = [f"{name} {_phrase(items[0][0], items[0][1])}"]
    parts += [f"It {_phrase(k, v)}" for k, v in items[1:]]
    return ". ".join(parts) + "."


def _question(name: str, attr: str, value, case: str, key: str = "",
              decoy: bool = False) -> Question:
    claim = f"{name} {_phrase(attr, value)}"
    meta = {"case": case, "attr": attr, "claim": claim, "decoy": decoy}
    if case == "not_in_context":
        target, meta = None, {**meta, "abstain": True, "reason": "attribute_absent"}
    else:
        target = [0.0, 1.0] if case == "supported" else [1.0, 0.0]
    return Question(
        attr,
        _phrasing(key or claim).format(claim=claim),
        ["no", "yes"], target, meta, INSTRUCTION,
        ["The record gives this attribute a different value.",
         "The record gives this attribute exactly this value."])


def _loader(split: str, seed: int, shapes=("json", "prose")):
    def load(n: int) -> Iterator[Example]:
        h = hashlib.sha256(f"entities:{split}:{seed}".encode()).digest()
        rng = random.Random(int.from_bytes(h[:8], "big"))
        made = 0
        while made < n:
            name = _name(rng)
            if entity_split(name) != split:
                continue
            asked = rng.choice(ATTRS)
            kind = TYPE_OF[asked]
            # the asked type is carried twice (asked + mate) and its third attribute is
            # held back for the not-in-context backfill
            mate, spare = rng.sample([a for a in TYPES[kind] if a != asked], 2)
            chosen = [asked, mate]
            for t in rng.sample([t for t in TYPES if t != kind], rng.randint(4, 5)):
                # other types once or twice, so "two of a type" is not the asked one's mark
                chosen += rng.sample(TYPES[t], 2 if rng.random() < 0.2 else 1)
            rng.shuffle(chosen)
            taken: dict[str, list] = {}
            rec = {}
            for a in chosen:
                rec[a] = _fresh(a, taken.get(TYPE_OF[a], []), rng, split, name)
                taken.setdefault(TYPE_OF[a], []).append(rec[a])
            shape = rng.choice(shapes)
            decoy = rng.random() < DECOY
            # the refuted value: the mate's (in the record, not as this attribute), or one
            # the record holds nowhere
            refuted = rec[mate] if decoy else _fresh(asked, taken[kind], rng, split, name)
            # not in context: drop the asked attribute, backfill the held-back third of
            # its type with a value neither the asked attribute nor the refuted claim had
            # -- so a non-decoy claim of rec[asked] is absent from the record entirely
            absent_rec = {k: v for k, v in rec.items() if k != asked}
            absent_rec[spare] = _fresh(spare, taken[kind] + [refuted], rng, split, name)
            # re-shuffle key order so "the backfilled attribute is always last" is not
            # itself a new positional tell
            items = list(absent_rec.items())
            rng.shuffle(items)
            absent_rec = dict(items)
            variants = (
                ("supported", rec, rec[asked]),
                ("refuted", rec, refuted),
                ("not_in_context", absent_rec, rec[mate] if decoy else rec[asked]),
            )
            for case, body, claimed in variants:
                if made >= n:
                    break
                q = _question(name, asked, claimed, case, key=f"{split}:{seed}:{made}",
                              decoy=decoy and case != "supported")
                # the three cases are twins; val must take all of them or none
                q.meta["group"] = f"{name}\x1f{asked}"
                yield Example(state=_render(name, body, shape), questions=[q],
                              task=f"entity_fact_{split}")
                made += 1
    return load


def tasks() -> list[RealTask]:
    """One task per entity bucket (`entity_split`). The held-out unit is the bucket, so
    each task names its bucket as its family: the default (`family_of` strips a trailing
    `_dev`) would have put `entity_fact_unseen_dev` in `entity_fact_unseen`'s family, and
    the devood selection would then have read the dev half of `unseen_entity_abstention`
    as sharing test's entities,
    which by construction it does not."""
    return [
        RealTask(row=ROW, name="entity_fact_train", licence=LICENCE, url=URL,
                 load=_loader("train", 0), real=False, force_split="train",
                 family="entity_fact:train_entities",
                 notes="randomised attributes; supported / refuted / not-in-context"),
        RealTask(row=ROW, name="entity_fact_unseen", licence=LICENCE, url=URL,
                 load=_loader("unseen", 41), real=False, force_split="testreal",
                 family="entity_fact:unseen_entities",
                 notes="entities never trained on -- the unseen_entity_abstention gate reads this"),
        RealTask(row=ROW, name="entity_fact_unseen_dev", licence=LICENCE, url=URL,
                 load=_loader("unseen_dev", 42), real=False, force_split="devreal",
                 family="entity_fact:unseen_dev_entities",
                 notes="entities never trained on, and disjoint from entity_fact_unseen; "
                       "held out of train and test; a dev structure -- selects "
                       "checkpoints and fits T"),
    ]
