"""Row 51 -- long-context reading with the evidence at a controlled depth (domain 25).

The model trained on states of at most 2,304 tokens while its backbone reads 32,768
positions. The final runs raise the state budget to ~30k tokens, and this row is the long
tail that has to teach the model to *use* evidence anywhere in a long state, not merely
to tolerate length. Every question here is decided by one record, line, section or clause
(or a handful of them) placed at a depth the generator chooses, inside a state of 2k-30k
Qwen3 tokens that is otherwise distractor.

Two kinds of state:

    records   many records of one `records.py` domain (the `compose.py` extension of it,
              values clustered per state as `compose.make_state` draws them), rendered in
              one of `compose.FORMATS`, 15 to ~1,500 records depending on format and field
              subset. Families:
                lookup  does record <id> satisfy a 1-2 clause rule?        (yes/no)
                cross   which of 2-4 named records has the highest/lowest <field>?
                pick    which of 4-5 named records meets every one of 3 requirements?
                        (a catalog in the state, not in the options: an option is a bare id)
                scan    how many records carry <field> = <value>? (1-5, every hit placed by the depth law)
    documents distractor-heavy text with one relevant piece:
                log     the final status of one job among thousands of log lines
                config  one setting of one service section in a long config file
                policy  who signs off a request under one clause of a long policy

**Code owns the target.** Every answer is computed from the records or pieces the
generator placed, and re-evaluated against the final state before an example is emitted.

**Near-miss decoys.** A lookup target has two decoy records whose ids differ from it by
one or two digits; log jobs, config sections and policy clauses have the same, and a cross
question has a near-twin of one option holding a value that would win. A decoy's answer
is drawn independently of the target's -- forced opposite, "find the twin and flip it"
would be a shortcut a prefix reader could use half the time -- so approximate
retrieval ("the record that looks like birch-4417") is right only at chance.

**Depth.** The state length is log-uniform over [2,500, 29,000] tokens. With probability
`P_ANY_DEPTH` the evidence depth is uniform over the whole state; otherwise it is uniform
over the part past the first `PREFIX_TOKENS` (2,304, the old state budget), because a
question whose answer sits in a short prefix teaches nothing a 2k model does not already
do. `meta.gen = {depth_tokens, state_tokens, depth_frac, n_records, family, ...}` is
measured with the Qwen3 tokenizer on the final state, not estimated.

**Held out by structure.** Record families hold out whole domains (`order` -> devreal,
`vehicle` -> testreal: unseen field names, nouns and value ranges); document families hold
out whole formats (log `bracket` and policy `markdown` -> devreal, config `toml` and policy
`legal` -> testreal). Every task is `force_split` and is its own `family`.
A shortcut audit measures the shortcuts; `scripts/build_corpus.py probes`
builds the controlled length x depth grid from the devreal structures.
"""

from __future__ import annotations

import copy
import hashlib
import json
import math
import random
import re
from bisect import bisect_right
from dataclasses import dataclass, field
from typing import Iterator

from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask
from lod.corpus.services.sources.synth import compose as C
from lod.corpus.services.sources.synth.records import DOMAINS as BASE_DOMAINS
from lod.corpus.services.sources.synth.records import Enum, Num, _label, field_ref

ROW = 51
LICENCE = "generated by lod/corpus/services/sources/synth/longctx.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/longctx.py"
TOKENIZER = "Qwen/Qwen3-0.6B-Base"

PREFIX_TOKENS = 2304          # the budget the model was trained at before this row
MIN_TOKENS = 2500              # every state has room past the old prefix
MAX_TOKENS = 29000            # target; the hard cap below leaves room for "State:\n"
HARD_CAP = 29800
P_ANY_DEPTH = 0.15
QUESTIONS_PER_EXAMPLE = 2
# examples per task (each carries QUESTIONS_PER_EXAMPLE questions): 21 train tasks
# x 210 x 2 = 8.8k training questions (beside ~6.4k from longdocs); 12 held-out tasks
# x 60 x 2 = 1.4k
CAP = {"train": 210, "devreal": 60, "testreal": 60}

RECORD_FAMILIES = ("lookup", "cross", "pick", "scan")
DOC_FAMILIES = ("log", "config", "policy")
DOMAIN_SPLIT = {"shipment": "train", "sensor": "train", "incident": "train",
                "build": "train", "order": "devreal", "vehicle": "testreal"}
DOC_FORMATS = {
    "log": (("syslog", "train"), ("jsonl", "train"), ("bracket", "devreal")),
    "config": (("ini", "train"), ("yaml", "train"), ("toml", "testreal")),
    "policy": (("numbered", "train"), ("markdown", "devreal"), ("legal", "testreal")),
}
CDOMS = {d.name: C._extend(d) for d in BASE_DOMAINS}
# scan counts start at one: with zero allowed, "no hit in what I read, so none" is right
# for every zero-count question whatever its depth -- a prefix reader's free 20 %
COUNT_WORDS = ("one", "two", "three", "four", "five")


# ==== tokens ==========================================================================

_TOK = None


def tokenizer():
    """The backbone's tokenizer from a local cache (the default HF cache, then the shared
    one HF_HOME points at), so a build never needs the network."""
    global _TOK
    if _TOK is None:
        from transformers import AutoTokenizer
        errs = []
        for kw in ({},):
            try:
                _TOK = AutoTokenizer.from_pretrained(TOKENIZER, local_files_only=True, **kw)
                break
            except Exception as e:  # noqa: BLE001 - try the next cache location
                errs.append(e)
        if _TOK is None:
            raise RuntimeError(f"no local {TOKENIZER} tokenizer: {errs}")
    return _TOK


def token_starts(text: str) -> list[int]:
    """Start character of every token of `text` (Qwen3, no special tokens)."""
    enc = tokenizer()(text, add_special_tokens=False, return_offsets_mapping=True)
    return [a for a, _ in enc["offset_mapping"]]


def n_tokens(text: str) -> int:
    return len(tokenizer()(text, add_special_tokens=False)["input_ids"])


def token_at(starts: list[int], char: int) -> int:
    """Index of the token that contains character `char`."""
    return max(0, bisect_right(starts, char) - 1)


# ==== sampling lengths and depths =====================================================

def sample_length(rng: random.Random) -> int:
    return int(math.exp(rng.uniform(math.log(MIN_TOKENS), math.log(MAX_TOKENS))))


def sample_depth(rng: random.Random, length: int) -> float:
    """Depth as a fraction of the state. Past the old 2,304-token prefix unless the
    state is too short to have a past, or the P_ANY_DEPTH draw says anywhere."""
    lo = PREFIX_TOKENS + 100
    if rng.random() < P_ANY_DEPTH or length < lo + 400:
        return rng.random()
    return rng.uniform(lo, length) / length


def _seed(*parts) -> int:
    return int.from_bytes(hashlib.sha256(":".join(map(str, parts)).encode()).digest()[:8], "big")


def _near_id(ident: str, taken: set[str], rng: random.Random) -> str:
    """`birch-4417` -> `birch-4471` / `birch-4917`: one or two digits moved."""
    word, num = ident.rsplit("-", 1)
    for _ in range(200):
        d = list(num)
        if rng.random() < 0.5:
            i, j = rng.sample(range(len(d)), 2)
            d[i], d[j] = d[j], d[i]
        else:
            i = rng.randrange(1, len(d))
            d[i] = rng.choice([c for c in "0123456789" if c != d[i]])
        cand = f"{word}-{''.join(d)}"
        if cand != ident and cand not in taken:
            return cand
    raise RuntimeError("no near id")


def _id_pattern(ident: str) -> re.Pattern:
    return re.compile(r"(?<![\w-])" + re.escape(ident) + r"(?![\w-])")


# ==== record rules ====================================================================

OPWORD = {">": "above", "<": "below", ">=": "at least", "<=": "at most"}


def eval_leaf(leaf: dict, rec: dict) -> bool:
    k = leaf["kind"]
    if k == "cmp":
        return C._cmp(rec[leaf["field"]], leaf["op"], leaf["value"])
    if k == "fref":
        return rec[leaf["field"]] > rec[leaf["limit"]]
    if k == "eq":
        return rec[leaf["field"]] == leaf["value"]
    raise ValueError(k)


def eval_rule(rule: dict, rec: dict) -> bool:
    vals = [eval_leaf(l, rec) for l in rule["leaves"]]
    return all(vals) if rule["op"] == "and" else any(vals)


def _gap(f: Num, rng: random.Random) -> float:
    span = f.hi - f.lo
    g = rng.uniform(0.02, 0.08) * span
    return max(1.0, round(g)) if f.integral else max(0.1, round(g, 1))


def _rnd(f: Num, x: float):
    return int(round(x)) if f.integral else round(x, 1)


def _make_leaf(cd, rec: dict, truth: bool, rng: random.Random, avoid: set[str]) -> dict:
    """A leaf that `rec` satisfies iff `truth`, built by placing its constant (cmp) or by
    setting the record's own fields (fref, eq)."""
    kinds = ["cmp", "cmp", "fref", "eq"]
    rng.shuffle(kinds)
    for kind in kinds:
        if kind == "cmp":
            fs = [f for f in cd.meas if f.name not in avoid]
            if not fs:
                continue
            f = rng.choice(fs)
            op = rng.choice(list(OPWORD))
            v, g = rec[f.name], _gap(f, rng)
            up = (op in (">", ">=")) != truth       # constant above the value?
            c = _rnd(f, v + g if up else v - g)
            if not f.lo <= c <= f.hi:
                op = {">": "<", "<": ">", ">=": "<=", "<=": ">="}[op]
                up = not up
                c = _rnd(f, v + g if up else v - g)
            leaf = {"kind": "cmp", "field": f.name, "op": op, "value": c}
        elif kind == "fref":
            ps = [(a, l) for a, l in cd.pairs if a not in avoid and l not in avoid]
            if not ps:
                continue
            a, l = rng.choice(ps)
            fl = cd.num(l)
            g = _gap(fl, rng)
            rec[l] = _rnd(fl, rec[a] - g if truth else rec[a] + g)
            leaf = {"kind": "fref", "field": a, "limit": l}
        else:
            es = [e for e in cd.enums if e.name not in avoid]
            if not es:
                continue
            e = rng.choice(es)
            if truth:
                val = rec[e.name]
            else:
                val = rng.choice([x for x in e.values if x != rec[e.name]])
            leaf = {"kind": "eq", "field": e.name, "value": val}
        if eval_leaf(leaf, rec) == truth:
            return leaf
    raise RuntimeError("no leaf")


def force_leaf(cd, rec: dict, leaf: dict, truth: bool, rng: random.Random) -> None:
    """Set `rec`'s fields so `leaf` evaluates to `truth` (the constant stays put)."""
    k = leaf["kind"]
    if k == "cmp":
        f = cd.num(leaf["field"])
        g = _gap(f, rng)
        up = (leaf["op"] in (">", ">=")) == truth   # value above the constant?
        rec[f.name] = _rnd(f, leaf["value"] + g if up else leaf["value"] - g)
    elif k == "fref":
        fl = cd.num(leaf["limit"])
        g = _gap(fl, rng)
        rec[fl.name] = _rnd(fl, rec[leaf["field"]] - g if truth else rec[leaf["field"]] + g)
    else:
        e = next(x for x in cd.enums if x.name == leaf["field"])
        rec[e.name] = leaf["value"] if truth else rng.choice(
            [x for x in e.values if x != leaf["value"]])
    assert eval_leaf(leaf, rec) == truth


def _pattern(op: str, n: int, want: bool, rng: random.Random) -> list[bool]:
    if n == 1:
        return [want]
    if op == "and":
        if want:
            return [True] * n
        p = [True] * n
        p[rng.randrange(n)] = False
        if rng.random() < 0.2:
            p = [False] * n
        return p
    if not want:
        return [False] * n
    p = [False] * n
    p[rng.randrange(n)] = True
    if rng.random() < 0.2:
        p = [True] * n
    return p


def leaf_text(cd, leaf: dict, shape: str, mode: str) -> str:
    f = next(x for x in cd.dom.fields if x.name == leaf["field"])
    ref = field_ref(f, shape, mode)
    if leaf["kind"] == "cmp":
        return f"{ref} is {OPWORD[leaf['op']]} {leaf['value']}{f.unit}"
    if leaf["kind"] == "fref":
        return f"{ref} is above {field_ref(cd.num(leaf['limit']), shape, mode)}"
    return f"{ref} is {leaf['value']}"


def rule_text(cd, rule: dict, shape: str, mode: str) -> str:
    parts = [leaf_text(cd, l, shape, mode) for l in rule["leaves"]]
    return f" {rule['op']} ".join(parts)


def rule_fields(rule: dict) -> set[str]:
    out = set()
    for l in rule["leaves"]:
        out.add(l["field"])
        if l["kind"] == "fref":
            out.add(l["limit"])
    return out


# ==== record states ===================================================================

@dataclass
class RecState:
    cd: object
    fmt: str
    recs: list[dict]
    keep: list[str]                   # the fields rendered; questions read only these
    used: set[int] = field(default_factory=set)
    scan_fields: set[str] = field(default_factory=set)
    starts: list[int] = field(default_factory=list)   # token starts of the first render
    pos: list[int] = field(default_factory=list)      # char offset of each record's id

    def render(self) -> str:
        keys = [self.cd.idf] + [k for k in self.recs[0] if k in self.keep]
        recs = [{k: r[k] for k in keys} for r in self.recs]
        st = C.State(self.cd, recs, 0, {}, "policy")
        return C.render_state(st, self.fmt)


def _keep_fields(cd, rng: random.Random) -> list[str]:
    """A random field subset that still lets every family ask its questions: two
    measured numbers, two categorical fields, one measured/limit pair."""
    meas = [f.name for f in cd.meas]
    enums = [e.name for e in cd.enums]
    a, l = rng.choice(cd.pairs)
    # nested randint: small subsets are commoner, so compact records (and so states of
    # many hundreds of records) are too
    keep = set(rng.sample(meas, rng.randint(2, rng.randint(2, len(meas)))))
    keep |= set(rng.sample(enums, rng.randint(2, rng.randint(2, len(enums)))))
    keep |= {a, l}
    rest = [f.name for f in cd.dom.fields if f.name not in keep]
    keep |= set(rng.sample(rest, rng.randint(0, rng.randint(0, len(rest)))))
    return sorted(keep)


def _record_state(cd, fmt: str, length: int, rng: random.Random) -> tuple[RecState, str, list[int]]:
    """Records of `cd` rendered in `fmt` to about `length` tokens: -> (state, text,
    token starts). Three passes at most: estimate tokens per record from a 2- and a
    12-record render, then rescale the record count on the measured total."""
    keep = _keep_fields(cd, rng)
    trial = RecState(cd, fmt, C.make_state(cd, rng, 12).recs, keep)
    t12 = n_tokens(trial.render())
    trial.recs = trial.recs[:2]
    t2 = n_tokens(trial.render())
    per = max(5.0, (t12 - t2) / 10)
    over = max(0.0, t2 - 2 * per)
    n = max(4, int((length - over) / per))
    for _ in range(3):
        rs = RecState(cd, fmt, C.make_state(cd, rng, n).recs, keep)
        text = rs.render()
        starts = token_starts(text)
        total = len(starts)
        if abs(total - length) <= 0.05 * length and total <= HARD_CAP:
            break
        n = max(4, int(n * (length - over) / max(1.0, total - over)))
    return rs, text, starts


def _positions(text: str, idents: list[str]) -> list[int]:
    return [_id_pattern(i).search(text).start() for i in idents]


def _choose_index(rs: RecState, starts: list[int], pos_chars: list[int], depth_tok: float,
                  rng: random.Random) -> int:
    toks = [token_at(starts, c) for c in pos_chars]
    free = [i for i in range(len(rs.recs)) if i not in rs.used]
    return min(free, key=lambda i: (abs(toks[i] - depth_tok), rng.random()))


def _like_target(rs: RecState, rng: random.Random, k: int, exclude: set[int]) -> list[int]:
    """k more option records placed by the same depth law as the target. Uniform
    positions would put the target (past the old prefix 85 % of the time) later than its
    rivals, and "the option that appears last" would find it."""
    out: list[int] = []
    total = len(rs.starts)
    for _ in range(k):
        rs.used |= set(exclude) | set(out)
        i = _choose_index(rs, rs.starts, rs.pos, sample_depth(rng, total) * total, rng)
        out.append(i)
    return out


def _free(rs: RecState, rng: random.Random, k: int, exclude: set[int] = frozenset()) -> list[int]:
    free = [i for i in range(len(rs.recs)) if i not in rs.used and i not in exclude]
    return rng.sample(free, k)


def _q_lookup(rs: RecState, t: int, rng: random.Random, split: str, qid: str) -> tuple[Question, list[int]]:
    cd = rs.cd
    rec = rs.recs[t]
    want = rng.random() < 0.5
    op = rng.choice(("and", "or"))
    n = 1 if rng.random() < 0.5 else 2
    pat = _pattern(op, n, want, rng)
    leaves, avoid = [], {f.name for f in cd.dom.fields} - set(rs.keep)
    for truth in pat:
        leaf = _make_leaf(cd, rec, truth, rng, avoid)
        leaves.append(leaf)
        avoid |= rule_fields({"leaves": [leaf]})
    rule = {"op": op, "leaves": leaves}
    assert eval_rule(rule, rec) == want
    decoys = _free(rs, rng, 2, {t})
    taken = {r[cd.idf] for r in rs.recs}
    for d in decoys:
        drec = rs.recs[d]
        drec[cd.idf] = _near_id(rec[cd.idf], taken, rng)
        taken.add(drec[cd.idf])
        # a decoy's answer is a fair coin, independent of the target's: forcing it
        # opposite would make "find the near-twin, flip its answer" a shortcut
        dwant = rng.random() < 0.5
        for leaf, truth in zip(leaves, _pattern(op, n, dwant, rng)):
            force_leaf(cd, drec, leaf, truth, rng)
        assert eval_rule(rule, drec) == dwant
    shape = "label" if rs.fmt == "prose" else "json"
    mode = rng.choice(("direct", "indirect"))
    text = rule_text(cd, rule, shape, mode)
    q = Question(
        id=qid,
        question=f"Does the {cd.noun} {rec[cd.idf]} meet this condition: {text}?",
        options=["no", "yes"], target=int(want),
        meta={"family": "lookup", "rule": rule, "target_id": rec[cd.idf],
              "decoys": [rs.recs[d][cd.idf] for d in decoys]})
    return q, [t] + decoys, [t]


def _q_cross(rs: RecState, t: int, rng: random.Random, split: str, qid: str):
    cd = rs.cd
    f = rng.choice([f for f in cd.meas if f.name in rs.keep])
    k = rng.randint(2, 4)
    others = _like_target(rs, rng, k - 1, {t})
    named = [t] + others
    hi = rng.random() < 0.5
    step = 1.0 if f.integral else 0.1
    # the winner beats the best other by a margin of 1-8 % of the range
    best_other = (max if hi else min)(rs.recs[i][f.name] for i in others)
    g = max(step, _gap(f, rng))
    rs.recs[t][f.name] = _rnd(f, best_other + g if hi else best_other - g)
    win = rs.recs[t][f.name]
    assert all((rs.recs[i][f.name] < win) if hi else (rs.recs[i][f.name] > win) for i in others)
    taken = {r[cd.idf] for r in rs.recs}
    # ...a near-id twin of a random named record (not always the winner's: that would
    # make "the option whose twin is extreme" a shortcut) that would win if read instead
    d = _free(rs, rng, 1, set(named))[0]
    rs.recs[d][cd.idf] = _near_id(rs.recs[rng.choice(named)][cd.idf], taken, rng)
    rs.recs[d][f.name] = _rnd(f, win + g if hi else win - g)
    ids = [rs.recs[i][cd.idf] for i in named]
    order = list(range(k))
    rng.shuffle(order)
    options = [ids[i] for i in order]
    shape = "label" if rs.fmt == "prose" else "json"
    ref = field_ref(f, shape, rng.choice(("direct", "indirect")))
    word = "highest" if hi else "lowest"
    q = Question(
        id=qid,
        question=f"Of the {cd.plural} {', '.join(options[:-1])} and {options[-1]}, which has "
                 f"the {word} value of {ref}?",
        options=options, target=options.index(ids[0]),
        meta={"family": "cross", "field": f.name, "highest": hi, "target_id": ids[0],
              "decoys": [rs.recs[d][cd.idf]]})
    return q, named + [d], named


def _q_pick(rs: RecState, t: int, rng: random.Random, split: str, qid: str):
    cd = rs.cd
    rec = rs.recs[t]
    leaves, avoid = [], {f.name for f in cd.dom.fields} - set(rs.keep)
    for _ in range(3):
        leaf = _make_leaf(cd, rec, True, rng, avoid)
        leaves.append(leaf)
        avoid |= rule_fields({"leaves": [leaf]})
    rule = {"op": "and", "leaves": leaves}
    k = rng.randint(4, 5)
    others = _like_target(rs, rng, k - 1, {t})
    for j, o in enumerate(others):
        fail = j % 3 if j < 3 else rng.randrange(3)
        for li, leaf in enumerate(leaves):
            force_leaf(cd, rs.recs[o], leaf, li != fail, rng)
        assert not eval_rule(rule, rs.recs[o])
    named = [t] + others
    ids = [rs.recs[i][cd.idf] for i in named]
    options = ids[:]
    rng.shuffle(options)
    shape = "label" if rs.fmt == "prose" else "json"
    mode = rng.choice(("direct", "indirect"))
    reqs = "; ".join(leaf_text(cd, l, shape, mode) for l in leaves)
    q = Question(
        id=qid,
        question=f"Which of these {cd.plural} meets every one of these requirements: {reqs}?",
        options=options, target=options.index(ids[0]),
        meta={"family": "pick", "rule": rule, "target_id": ids[0]})
    return q, named, named


def _q_scan(rs: RecState, t: int, rng: random.Random, split: str, qid: str):
    cd = rs.cd
    e = rng.choice([e for e in cd.enums if e.name in rs.keep and e.name not in rs.scan_fields])
    rs.scan_fields.add(e.name)
    val = rng.choice(e.values)
    for r in rs.recs:
        if r[e.name] == val:
            r[e.name] = rng.choice([x for x in e.values if x != val])
    count = rng.randrange(len(COUNT_WORDS)) + 1
    # every hit placed by the same depth law as the target: hits packed before the
    # target made "hits seen in the prefix, scaled up" a count estimate (audit: +0.215)
    extra = _like_target(rs, rng, count - 1, {t})
    hits = [t] + extra
    count = len(hits)
    for i in hits:
        rs.recs[i][e.name] = val
    assert sum(r[e.name] == val for r in rs.recs) == count
    shape = "label" if rs.fmt == "prose" else "json"
    ref = field_ref(e, shape, "direct")
    q = Question(
        id=qid,
        question=f"How many of the {cd.plural} in this state have {ref} {val}?",
        options=list(COUNT_WORDS), target=count - 1,
        meta={"family": "scan", "field": e.name, "value": val,
              "target_id": rs.recs[t][cd.idf],
              "hit_ids": [rs.recs[i][cd.idf] for i in hits]})
    return q, hits, hits


RECORD_Q = {"lookup": _q_lookup, "cross": _q_cross, "pick": _q_pick, "scan": _q_scan}


def record_example(fam: str, dom: str, rng: random.Random, split: str, task: str,
                   lengths: list[int] | None = None, depths: list[float] | None = None,
                   n_q: int = QUESTIONS_PER_EXAMPLE, fmt: str | None = None) -> Example:
    """One records state with `n_q` questions of family `fam`. `length`/`depths` fix the
    state length (tokens) and each question's evidence depth (fraction); the depth check
    passes them, training draws them."""
    cd = CDOMS[dom]
    length = lengths[0] if lengths else sample_length(rng)
    depths = depths or [sample_depth(rng, length) for _ in range(n_q)]
    fmt = fmt or rng.choice(C.FORMATS)
    rs, text, starts = _record_state(cd, fmt, length, rng)
    pos = _positions(text, [r[cd.idf] for r in rs.recs])
    rs.starts, rs.pos = starts, pos
    total = len(starts)
    questions, evid = [], []
    for j, frac in enumerate(depths):
        t = _choose_index(rs, starts, pos, frac * total, rng)
        q, used, ev = RECORD_Q[fam](rs, t, rng, split, f"q{j}")
        rs.used |= set(used)
        questions.append(q)
        evid.append([rs.recs[i][cd.idf] for i in ev])
    text = rs.render()
    while n_tokens(text) > HARD_CAP:
        spare = [i for i in range(len(rs.recs) - 1, -1, -1) if i not in rs.used]
        drop = set(spare[: max(1, len(spare) // 50)])
        rs.recs = [r for i, r in enumerate(rs.recs) if i not in drop]
        rs.used = {i - sum(1 for d in drop if d < i) for i in rs.used}
        text = rs.render()
    # every label re-derived from the final records
    by_id = {r[cd.idf]: r for r in rs.recs}
    for q in questions:
        assert rederive_records(q, list(by_id.values()), cd.idf) == q.target, q.meta
    starts = token_starts(text)
    for q, ev in zip(questions, evid):
        ptoks = [token_at(starts, _id_pattern(i).search(text).start()) for i in ev]
        _set_gen(q, ptoks, len(starts), fam, dom, fmt, n_records=len(rs.recs))
    return Example(state=text, questions=questions, task=task)


def rederive_records(q: Question, recs: list[dict], idf: str) -> int:
    """The target, recomputed from records alone (the tests call this on re-parsed
    states)."""
    m = q.meta
    by_id = {r[idf]: r for r in recs}
    fam = m["family"]
    if fam == "lookup":
        return int(eval_rule(m["rule"], by_id[m["target_id"]]))
    if fam == "pick":
        ok = [i for i, o in enumerate(q.options) if eval_rule(m["rule"], by_id[o])]
        assert len(ok) == 1
        return ok[0]
    if fam == "cross":
        vals = [by_id[o][m["field"]] for o in q.options]
        best = (max if m["highest"] else min)(vals)
        assert vals.count(best) == 1
        return vals.index(best)
    if fam == "scan":
        return sum(r[m["field"]] == m["value"] for r in recs) - 1
    raise ValueError(fam)


def _set_gen(q: Question, ptoks: list[int], total: int, fam: str, variant: str, fmt: str,
             n_records: int) -> None:
    depth = max(ptoks) if ptoks else total
    q.meta["gen"] = {
        "family": fam, "variant": variant, "format": fmt,
        "depth_tokens": depth, "state_tokens": total,
        "depth_frac": round(depth / total, 4) if total else 0.0,
        "evidence_tokens": sorted(ptoks), "n_records": n_records,
    }


# ==== document states =================================================================

WORDS = ("axle", "birch", "cobalt", "delta", "ember", "flint", "garnet",
         "hollow", "indigo", "juniper", "kestrel", "larch", "marlow", "nimbus",
         "onyx", "pivot", "quartz", "rowan", "sable", "tamarack", "umber",
         "vesper", "willow", "yarrow", "zephyr")
SERVICES = ("billing", "search", "ingest", "notifier", "auth", "catalog", "ledger",
            "gateway", "scheduler", "reports", "media", "inventory", "checkout", "profile")
ROLES_SUFFIX = ("api", "worker", "sync", "cache", "proxy", "store", "relay", "export")
FINAL = ("succeeded", "failed", "cancelled", "timed_out")
INTERIM = ("queued", "running", "retrying", "waiting")
STAGES = ("fetch", "build", "test", "package", "upload", "verify", "index")
HOSTS = tuple(f"node-{i}" for i in range(1, 25))


@dataclass
class Doc:
    pieces: list[str]
    sep: str = "\n"
    head: str = ""

    def text_and_offsets(self) -> tuple[str, list[int]]:
        offs, cur, parts = [], len(self.head), [self.head] if self.head else []
        for p in self.pieces:
            offs.append(cur)
            parts.append(p)
            cur += len(p) + len(self.sep)
        body = self.sep.join(self.pieces)
        return self.head + body, offs


def _jid(rng) -> str:
    return f"{rng.choice(WORDS)}-{rng.randrange(1000, 9999)}"


def _ts(base: int, fmt: str) -> str:
    h, rem = divmod(base, 3600)
    m, s = divmod(rem, 60)
    d = 3 + h // 24
    h %= 24
    if fmt == "bracket":
        return f"2026-05-{d:02d} {h:02d}:{m:02d}:{s:02d}"
    return f"2026-05-{d:02d}T{h:02d}:{m:02d}:{s:02d}Z"


def _log_line(fmt: str, ts: str, host: str, job: str | None, stage: str, event: str,
              note: str | None = None) -> str:
    if job is None:
        if fmt == "jsonl":
            return json.dumps({"ts": ts, "host": host, "level": "INFO", "msg": note})
        if fmt == "bracket":
            return f"[{ts}] [INFO] [{host}] {note}"
        return f"{ts} {host} agent[{sum(map(ord, host)) * 37 % 9000 + 1000}]: {note}"
    if fmt == "jsonl":
        return json.dumps({"ts": ts, "host": host, "job": job, "stage": stage, "event": event})
    if fmt == "bracket":
        return f"[{ts}] [{'WARN' if event in ('failed', 'timed_out', 'retrying') else 'INFO'}] [{host}] {job} {stage} -> {event}"
    return f"{ts} {host} scheduler: job={job} stage={stage} status={event}"


NOTES = ("heartbeat ok", "cache hit ratio {:.2f}", "queue depth {}", "gc pause {} ms",
         "disk usage {}%", "rotated log segment {}", "lease renewed for {} s",
         "connection pool size {}", "config reloaded (rev {})", "metrics flushed ({} series)")


def _note(rng) -> str:
    t = rng.choice(NOTES)
    return t.format(rng.random()) if "{:.2f}" in t else t.format(rng.randrange(1, 5000))


def _job_events(rng, final: str) -> list[tuple[str, str]]:
    n = rng.randint(1, 4)
    ev = [("queued", rng.choice(STAGES))]
    for _ in range(n - 1):
        ev.append((rng.choice(INTERIM[1:]), rng.choice(STAGES)))
    ev.append((final, rng.choice(STAGES)))
    return ev


def _log_doc(fmt: str, length: int, depths: list[float], rng: random.Random):
    """Lines of many interleaved jobs. Each question's job has its final status at the
    chosen depth; two near-id decoy jobs end differently; every other job is filler."""
    per = {"syslog": 26, "jsonl": 34, "bracket": 24}[fmt]
    n_lines = max(20, int(length / per))
    # slots: a list of (job, event, stage) or None (a note line)
    slots: list[tuple | None] = [None] * n_lines
    jobs_final: dict[str, str] = {}
    taken: set[str] = set()
    qs = []
    for frac in depths:
        ans = rng.choice(FINAL)
        jid = _jid(rng)
        while jid in taken:
            jid = _jid(rng)
        taken.add(jid)
        target_pos = min(n_lines - 1, int(frac * n_lines))
        dec = []
        for _ in range(2):
            did = _near_id(jid, taken, rng)
            taken.add(did)
            dec.append((did, rng.choice(FINAL)))    # independent of the answer
        qs.append((jid, ans, target_pos, dec))
    # place the question jobs: final at target (or nearest free slot), earlier events before
    placed_final = []
    for jid, ans, tp, dec in qs:
        ev = _job_events(rng, ans)
        free = [i for i in range(n_lines) if slots[i] is None]
        fp = min(free, key=lambda i: (abs(i - tp), i))
        slots[fp] = (jid, ev[-1][0], ev[-1][1])
        earlier = [i for i in range(fp) if slots[i] is None]
        for (e, s), i in zip(ev[:-1], sorted(rng.sample(earlier, min(len(earlier), len(ev) - 1)))):
            slots[i] = (jid, e, s)
        placed_final.append(fp)
        jobs_final[jid] = ans
        for did, dans in dec:
            dev = _job_events(rng, dans)
            free = sorted(rng.sample([i for i in range(n_lines) if slots[i] is None], len(dev)))
            for (e, s), i in zip(dev, free):
                slots[i] = (did, e, s)
            jobs_final[did] = dans
    # filler jobs: runs of 2-5 events spread over the log, and note lines
    free = [i for i in range(n_lines) if slots[i] is None]
    rng.shuffle(free)
    fi = 0
    while fi < len(free) * 0.8:
        fj = _jid(rng)
        if fj in taken:
            continue
        taken.add(fj)
        ev = _job_events(rng, rng.choice(FINAL))
        idx = sorted(free[fi: fi + len(ev)])
        for (e, s), i in zip(ev, idx):
            slots[i] = (fj, e, s)
        if len(idx) == len(ev):
            jobs_final[fj] = ev[-1][0]
        fi += len(ev)
    t0 = rng.randrange(0, 20000)
    lines = []
    for i, sl in enumerate(slots):
        t0 += rng.randint(0, 4)
        ts, host = _ts(t0, fmt), rng.choice(HOSTS)
        if sl is None:
            lines.append(_log_line(fmt, ts, host, None, "", "", _note(rng)))
        else:
            lines.append(_log_line(fmt, ts, host, sl[0], sl[2], sl[1]))
    head = {"syslog": "# scheduler log, all nodes\n", "jsonl": "",
            "bracket": "== job scheduler log ==\n"}[fmt]
    doc = Doc(lines, "\n", head)
    questions = []
    for j, (jid, ans, tp, dec) in enumerate(qs):
        options = list(FINAL)
        questions.append(Question(
            id=f"q{j}", question=f"According to this log, what is the final status of job {jid}?",
            options=options, target=options.index(ans),
            meta={"family": "log", "target_id": jid, "decoys": [d for d, _ in dec]}))
    return doc, questions, [[fp] for fp in placed_final]


def rederive_log(state: str, jid: str, fmt: str) -> str:
    last = None
    pat = _id_pattern(jid)
    for line in state.split("\n"):
        if not pat.search(line):
            continue
        if fmt == "jsonl":
            last = json.loads(line)["event"]
        elif fmt == "bracket":
            last = line.rsplit("-> ", 1)[1]
        else:
            last = line.rsplit("status=", 1)[1]
    return last


CONF_KEYS = {
    "retry_policy": ("exponential", "linear", "fixed", "none"),
    "log_level": ("debug", "info", "warn", "error"),
    "tls_mode": ("strict", "permissive", "disabled"),
    "region": ("eu-west", "us-east", "ap-south", "sa-east"),
    "cache_mode": ("write-through", "write-back", "read-only", "off"),
    "compression": ("gzip", "zstd", "brotli", "none"),
}
CONF_GLOSS = {"retry_policy": "retry policy", "log_level": "log level", "tls_mode": "TLS mode",
              "region": "region", "cache_mode": "cache mode", "compression": "compression"}
CONF_NUMS = ("timeout_ms", "max_connections", "replicas", "queue_size", "port")


def _svc(rng) -> str:
    return f"{rng.choice(SERVICES)}-{rng.choice(ROLES_SUFFIX)}-{rng.randrange(10, 99)}"


def _near_svc(name: str, taken: set[str], rng) -> str:
    for _ in range(100):
        a, b, n = name.split("-")
        r = rng.random()
        if r < 0.4:
            cand = f"{a}-{b}-{n[::-1] if n[::-1] != n else int(n) % 90 + 10}"
        elif r < 0.7:
            cand = f"{a}-{rng.choice([x for x in ROLES_SUFFIX if x != b])}-{n}"
        else:
            cand = f"{a}-{b}-{n}-{rng.choice(('canary', 'legacy', 'staging', 'v2'))}"
        if cand not in taken and cand != name:
            return cand
    raise RuntimeError("no near service")


def _conf_section(fmt: str, name: str, vals: dict) -> str:
    if fmt == "ini":
        return f"[service.{name}]\n" + "\n".join(f"{k} = {v}" for k, v in vals.items())
    if fmt == "yaml":
        return f"  {name}:\n" + "\n".join(f"    {k}: {v}" for k, v in vals.items())
    return f'[services."{name}"]\n' + "\n".join(
        f"{k} = {v}" if isinstance(v, int) else f'{k} = "{v}"' for k, v in vals.items())


def _conf_vals(rng, keys: list[str]) -> dict:
    out = {}
    for k in keys:
        if k in CONF_KEYS:
            out[k] = rng.choice(CONF_KEYS[k])
        else:
            out[k] = rng.randrange(1, 60000)
    return out


def _config_doc(fmt: str, length: int, depths: list[float], rng: random.Random):
    keys = list(CONF_KEYS) + list(CONF_NUMS)
    per = {"ini": 95, "yaml": 95, "toml": 105}[fmt]
    n = max(6, int(length / per))
    taken: set[str] = set()
    names = []
    while len(names) < n:
        s = _svc(rng)
        if s not in taken:
            taken.add(s)
            names.append(s)
    order = keys[:]
    sections = []
    for nm in names:
        ks = [k for k in order if k in CONF_KEYS or rng.random() < 0.7]
        sections.append([nm, _conf_vals(rng, ks)])
    qs, ev = [], []
    used = set()
    for j, frac in enumerate(depths):
        tp = min(n - 1, int(frac * n))
        t = min((i for i in range(n) if i not in used), key=lambda i: (abs(i - tp), i))
        used.add(t)
        key = rng.choice(list(CONF_KEYS))
        ans = rng.choice(CONF_KEYS[key])
        sections[t][1][key] = ans
        for _ in range(2):
            d = rng.choice([i for i in range(n) if i not in used])
            used.add(d)
            sections[d][0] = _near_svc(sections[t][0], taken, rng)
            taken.add(sections[d][0])
            sections[d][1][key] = rng.choice(CONF_KEYS[key])   # independent of the answer
        qs.append((sections[t][0], key, ans, t))
    pieces = []
    for nm, vals in sections:
        sec = _conf_section(fmt, nm, vals)
        if rng.random() < 0.25:
            sec = ("; " if fmt == "ini" else "  # " if fmt == "yaml" else "# ") + \
                f"owner: team-{rng.choice(WORDS)}, last reviewed {rng.randrange(1, 28)} days ago\n" + sec
        pieces.append(sec)
    head = {"ini": "; service configuration\n\n", "yaml": "services:\n",
            "toml": "# service configuration\n\n"}[fmt]
    doc = Doc(pieces, "\n\n" if fmt != "yaml" else "\n", head)
    questions = []
    for j, (nm, key, ans, t) in enumerate(qs):
        options = list(CONF_KEYS[key])
        questions.append(Question(
            id=f"q{j}",
            question=f"In this configuration, which {CONF_GLOSS[key]} is set for the "
                     f"service {nm}?",
            options=options, target=options.index(ans),
            meta={"family": "config", "target_id": nm, "key": key}))
    return doc, questions, [[t] for *_, t in qs]


def rederive_config(state: str, name: str, key: str, fmt: str) -> str:
    head = {"ini": f"[service.{name}]", "yaml": f"  {name}:",
            "toml": f'[services."{name}"]'}[fmt]
    lines = state.split("\n")
    i = lines.index(head)
    for line in lines[i + 1:]:
        s = line.strip()
        if not s or s.startswith("[") or (fmt == "yaml" and not line.startswith("    ")):
            break
        k, _, v = s.replace(":", " =", 1).partition(" = ") if fmt == "yaml" else s.partition(" = ")
        if k.strip() == key:
            return v.strip().strip('"')
    return None


ROLES = ("budget holder", "finance controller", "regional director", "procurement lead",
         "legal counsel", "chief operating officer")
BOILER = (
    "This policy applies to every request for expenditure, whatever its funding source.",
    "Approvals must be recorded in the finance system before a commitment is made.",
    "A request split into smaller requests to avoid a threshold is treated as one request.",
    "Amounts are assessed including tax and before any discount is applied.",
    "Delegated authority may not be further delegated without written consent.",
    "Where two provisions appear to conflict, the more specific provision prevails.",
    "Emergency expenditure may be approved retrospectively within five working days.",
    "Records of approval are retained for seven years.",
    "Currency conversion uses the rate published on the first working day of the month.",
    "Nothing in this policy overrides a statutory requirement.",
)


def _cc(rng) -> str:
    return f"CC-{rng.randrange(1000, 9999)}"


def _clause(fmt: str, num: int, cc: str, thr: int, above: str, below: str) -> str:
    t = f"{thr:,}"
    if fmt == "numbered":
        return (f"4.{num} Spend charged to cost centre {cc} above {t} EUR requires sign-off "
                f"by the {above}; spend at or below {t} EUR requires sign-off by the {below}.")
    if fmt == "markdown":
        return (f"### Cost centre {cc}\n- Threshold: {t} EUR\n- Above the threshold: {above}\n"
                f"- At or below the threshold: {below}")
    return (f"Section 4({num}). Where expenditure is charged to cost centre {cc} and exceeds "
            f"{t} EUR, it shall be approved by the {above}; where it does not exceed {t} EUR, "
            f"it shall be approved by the {below}.")


def _policy_doc(fmt: str, length: int, depths: list[float], rng: random.Random):
    per = {"numbered": 44, "markdown": 42, "legal": 52}[fmt]
    n = max(8, int(length / per * 0.85))
    taken: set[str] = set()
    clauses = []
    while len(clauses) < n:
        cc = _cc(rng)
        if cc in taken:
            continue
        taken.add(cc)
        a, b = rng.sample(ROLES, 2)
        clauses.append([cc, rng.randrange(5, 400) * 100, a, b])
    qs, used = [], set()
    for frac in depths:
        tp = min(n - 1, int(frac * n))
        t = min((i for i in range(n) if i not in used), key=lambda i: (abs(i - tp), i))
        used.add(t)
        cc, thr, a, b = clauses[t]
        above = rng.random() < 0.5
        g = max(100, int(thr * rng.uniform(0.02, 0.15)))
        amount = thr + g if above else thr - g
        if not above and rng.random() < 0.15:
            amount = thr                                   # "at or below" includes it
        ans = a if amount > thr else b
        for _ in range(2):
            d = rng.choice([i for i in range(n) if i not in used])
            used.add(d)
            dcc = "CC-" + _near_id("x-" + cc[3:], {"x-" + c[3:] for c in taken}, rng)[2:]
            taken.add(dcc)
            clauses[d][0] = dcc
            clauses[d][1] = thr
            clauses[d][2], clauses[d][3] = rng.sample(ROLES, 2)   # independent of the answer
        qs.append((cc, amount, ans, t))
    pieces, where = [], []
    for i, (cc, thr, a, b) in enumerate(clauses):
        if rng.random() < 0.18:
            pieces.append(rng.choice(BOILER))
        where.append(len(pieces))
        pieces.append(_clause(fmt, i + 1, cc, thr, a, b))
    head = {"numbered": "EXPENDITURE APPROVAL POLICY\n\n4. Cost centre approvals\n\n",
            "markdown": "# Expenditure approval policy\n\n## Cost centre approvals\n\n",
            "legal": "EXPENDITURE APPROVAL REGULATIONS\n\nPart 4 -- Cost centre approvals\n\n"}[fmt]
    doc = Doc(pieces, "\n\n", head)
    questions = []
    for j, (cc, amount, ans, t) in enumerate(qs):
        options = list(ROLES)
        questions.append(Question(
            id=f"q{j}",
            question=f"A request for {amount:,} EUR is charged to cost centre {cc}. Under "
                     f"this policy, who must sign it off?",
            options=options, target=options.index(ans),
            meta={"family": "policy", "target_id": cc, "amount": amount}))
    return doc, questions, [[where[t]] for *_, t in qs]


def rederive_policy(state: str, cc: str, amount: int, fmt: str) -> str:
    pat = _id_pattern(cc)
    for block in state.split("\n\n"):
        if not pat.search(block):
            continue
        nums = [int(x.replace(",", "")) for x in re.findall(r"(\d[\d,]*) EUR", block)]
        thr = nums[0]
        roles = [r for r in ROLES if r in block]
        # the role named first in the text is the above-threshold one
        roles.sort(key=block.index)
        return roles[0] if amount > thr else roles[1]
    return None


DOC_BUILDERS = {"log": _log_doc, "config": _config_doc, "policy": _policy_doc}


def doc_example(kind: str, fmt: str, rng: random.Random, split: str, task: str,
                lengths: list[int] | None = None, depths: list[float] | None = None,
                n_q: int = QUESTIONS_PER_EXAMPLE) -> Example:
    length = lengths[0] if lengths else sample_length(rng)
    depths = depths or [sample_depth(rng, length) for _ in range(n_q)]
    # the builders estimate tokens per piece; rescale on the measured total until the
    # state is within 6 % of the length asked for (the depth check needs its cells)
    build = length
    for _ in range(5):
        sub = random.Random(rng.random())
        doc, questions, ev = DOC_BUILDERS[kind](fmt, build, depths, sub)
        text, offs = doc.text_and_offsets()
        starts = token_starts(text)
        total = len(starts)
        if total <= HARD_CAP and abs(total - length) <= 0.06 * length:
            break
        build = max(200, int(build * length / total))
    assert total <= HARD_CAP, total
    for q, pieces in zip(questions, ev):
        m = q.meta
        if kind == "log":
            assert FINAL[q.target] == rederive_log(text, m["target_id"], fmt)
        elif kind == "config":
            assert CONF_KEYS[m["key"]][q.target] == rederive_config(text, m["target_id"], m["key"], fmt)
        else:
            assert ROLES[q.target] == rederive_policy(text, m["target_id"], m["amount"], fmt)
        ptoks = [token_at(starts, offs[p]) for p in pieces]
        _set_gen(q, ptoks, total, kind, fmt, fmt, n_records=len(doc.pieces))
    return Example(state=text, questions=questions, task=task)


# ==== tasks ===========================================================================

@dataclass(frozen=True)
class Spec:
    name: str
    kind: str          # "records" | "doc"
    fam: str
    variant: str       # domain name, or doc format
    split: str


def specs() -> list[Spec]:
    out = []
    for fam in RECORD_FAMILIES:
        for dom, split in DOMAIN_SPLIT.items():
            out.append(Spec(f"longctx_{fam}_{dom}", "records", fam, dom, split))
    for kind, fmts in DOC_FORMATS.items():
        for fmt, split in fmts:
            out.append(Spec(f"longctx_{kind}_{fmt}", "doc", kind, fmt, split))
    return out


def make(spec: Spec, rng: random.Random, **kw) -> Example:
    if spec.kind == "records":
        return record_example(spec.fam, spec.variant, rng, spec.split, spec.name, **kw)
    return doc_example(spec.fam, spec.variant, rng, spec.split, spec.name, **kw)


def generate(spec: Spec, n: int, seed_tag: str = "build") -> Iterator[Example]:
    for i in range(min(n, CAP[spec.split])):
        rng = random.Random(_seed(seed_tag, spec.name, i))
        yield make(spec, rng)


def _loader(spec: Spec):
    def load(n: int) -> Iterator[Example]:
        return generate(spec, n)
    return load


def tasks() -> list[RealTask]:
    out = []
    for s in specs():
        out.append(RealTask(
            row=ROW, name=s.name, licence=LICENCE, url=URL, load=_loader(s),
            per_example_options=s.fam in ("cross", "pick"), real=False,
            force_split=s.split, family=s.name,
            notes=f"long-context {s.fam} over {s.variant}; evidence depth recorded in meta.gen"))
    return out
