"""Row 48 -- exact posteriors (domain 22).

Calibration breaks on unseen families (ECE 0.033 familiar against 0.145 unseen) and
forecast transfer collapses (r 0.917 -> 0.425 on unseen forecast families). The loss is
PSR-FT, a cross-entropy against soft targets whose optimum is the true probability, so a
question whose target *is* the true probability teaches calibrated reading directly.
Every question here states a small generative story (urns, coins, dice, a noisy test,
witnesses of stated reliability, a population table, a two-step chain) and an
observation, and asks for the hypothesis or the next outcome. The target is the exact
posterior, computed with `fractions.Fraction` from the numbers the text states; nothing is
estimated, sampled or guessed.

**Six concept families, 26 structural variants.** A variant is one shape of story
(`urn_which_norepl`, `sensor_repeat`, `sources_relay`, ...). Every family trains in two or
three variants; each family also has one variant held out to `devreal` and a different one
held out to `testreal`, so dev and test both measure transfer to an unseen *structure* of a
trained *concept*, and are disjoint from each other and from train (`VARIANTS`). Every
trained variant also has a fresh-seed `_eval` twin in `devreal`, whose `family` is its
trained sibling, for in-structure evaluation.

**The shortcuts are built to lose.** "The hypothesis the prior favours", "the one the
likelihood favours ignoring the prior", "the one the last observation favours", "the
majority of the observations" and "the most reliable source" are each computed for every
draft (`heuristics`), and the loader keeps a draft only while every one of them stays in a
band above chance and well below the exact answer (`Balance`). The same balancer holds the
normalised max-posterior flat over five bins, so targets are neither mostly near-certain
nor mostly near-uniform. A shortcut audit measures the result.

**Numbers in varied formats.** Priors, rates, compositions and reliabilities appear as
counts, percentages, fractions, decimals, "n in N" and occasionally odds, in JSON,
`key: value`, markdown tables or prose, in the state or in the instructions. The format is
drawn per example and recorded in `meta.gen`, with every other generator parameter, so dev
loss can be broken down by parameter.
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter
from dataclasses import dataclass, field
from fractions import Fraction as F
from typing import Callable, Iterator

from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/posterior.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/posterior.py"
ROW = 48
DOMAIN = 22

# variant -> (concept family, split). Every family trains; each has one variant held out
# to dev and a different one to test.
VARIANTS: dict[str, tuple[str, str]] = {
    "urn_which_repl": ("urn", "train"),
    "urn_which_norepl": ("urn", "train"),
    "urn_next_repl": ("urn", "train"),
    "urn_which_polya": ("urn", "devreal"),        # a stated reinforcement rule
    "urn_next_norepl": ("urn", "testreal"),       # predictive x without replacement
    "coin_which": ("dice", "train"),
    "die_which": ("dice", "train"),
    "coin_next": ("dice", "train"),
    "die_next": ("dice", "devreal"),              # predictive over faces
    "coin_nextcount": ("dice", "testreal"),       # predictive over a count of heads
    "sensor_single": ("sensor", "train"),
    "sensor_repeat": ("sensor", "train"),
    "sensor_multi_single": ("sensor", "train"),
    "sensor_mixed": ("sensor", "devreal"),        # several different tests
    "sensor_multi_repeat": ("sensor", "testreal"),  # confusion matrix x several readings
    "sources_2": ("sources", "train"),
    "sources_3": ("sources", "train"),
    "sources_4": ("sources", "devreal"),          # an unseen number of sources
    "sources_relay": ("sources", "testreal"),     # reports passed through an intermediary
    "missing_joint": ("missing", "train"),
    "missing_inverse": ("missing", "train"),
    "missing_either": ("missing", "devreal"),     # the conditioning value is a disjunction
    "missing_two": ("missing", "testreal"),       # two conditionally independent attributes
    "chain_two_step": ("chain", "train"),
    "chain_host": ("chain", "devreal"),           # a Monty-Hall host rule stated explicitly
    "chain_explain": ("chain", "testreal"),       # two causes, one effect (explaining away)
}
FAMILIES = ("urn", "dice", "sensor", "sources", "missing", "chain")
TRAINED = tuple(v for v, (_, s) in VARIANTS.items() if s == "train")
DEV = tuple(v for v, (_, s) in VARIANTS.items() if s == "devreal")
TEST = tuple(v for v, (_, s) in VARIANTS.items() if s == "testreal")

SEED_TRAIN, SEED_TWIN, SEED_DEV, SEED_TEST = 0, 5051, 3131, 7717
# ~26,600 train questions before `carve_val` takes 5 %; 3,000 dev + ~1,500 twins; 3,000 test
MAX_PER_TASK = 1900
MAX_PER_TWIN = 108
MAX_PER_HELDOUT = 500

N_BINS = 5          # normalised max-posterior bins held flat by `Balance`
STALL = 400         # consecutive rejections after which the balancer gives way

# ======================================================================================
# number formatting
# ======================================================================================


def pct(p: F) -> str | None:
    x = p * 100
    if x.denominator == 1:
        return f"{x.numerator}%"
    if (x * 10).denominator == 1:
        return f"{float(x):.1f}%"
    return None


def dec(p: F) -> str | None:
    if (p * 1000).denominator != 1:
        return None
    s = f"{float(p):.3f}".rstrip("0").rstrip(".")
    return s if s else "0"


def frac(p: F) -> str:
    return f"{p.numerator}/{p.denominator}" if p.denominator != 1 else str(p.numerator)


def fmt_p(p: F, style: str) -> str:
    """One probability in one style, always exact (falls back to a fraction)."""
    if style == "pct":
        return pct(p) or frac(p)
    if style == "dec":
        return dec(p) or frac(p)
    if style == "in":
        return f"{p.numerator} in {p.denominator}"
    if style == "odds":
        return f"odds {p.numerator} to {p.denominator - p.numerator}"
    return frac(p)


def norm(ws) -> list[F]:
    s = sum(F(w) for w in ws)
    return [F(w) / s for w in ws]


def grid(rng: random.Random, lo: int, hi: int, den: int) -> F:
    return F(rng.randint(lo, hi), den)


def rate(rng: random.Random, lo: float, hi: float) -> F:
    """A probability on a 1/20 or 1/100 grid (or 1/10), within [lo, hi]."""
    den = rng.choice((20, 20, 100, 10))
    a, b = math.ceil(lo * den), math.floor(hi * den)
    return F(rng.randint(a, max(a, b)), den)


def int_split(rng: random.Random, weights: list[float], total: int) -> list[int]:
    """Integer counts summing to `total`, proportional to `weights` (largest remainder)."""
    s = sum(weights)
    raw = [w * total / s for w in weights]
    out = [int(x) for x in raw]
    rest = total - sum(out)
    order = sorted(range(len(raw)), key=lambda i: -(raw[i] - out[i]) + rng.random() * 1e-9)
    for i in order[:rest]:
        out[i] += 1
    return out


def join_and(xs: list[str]) -> str:
    xs = list(xs)
    if len(xs) <= 1:
        return "".join(xs)
    return ", ".join(xs[:-1]) + " and " + xs[-1]


def plural(n: int, word: str) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {word}s"


NUMBER_WORDS = ("zero", "one", "two", "three", "four", "five", "six", "seven", "eight",
                "nine", "ten", "eleven", "twelve")

# ======================================================================================
# state documents: one set of facts, four renderings
# ======================================================================================

FORMATS = ("json", "kv", "table", "prose")


@dataclass
class Block:
    title: str
    kind: str                      # facts | table | text
    pairs: list = field(default_factory=list)       # facts: [(key, value)]
    header: list = field(default_factory=list)      # table
    rows: list = field(default_factory=list)        # table
    prose: str = ""


class Doc:
    def __init__(self):
        self.blocks: list[Block] = []

    def facts(self, title, pairs, prose):
        self.blocks.append(Block(title, "facts", pairs=list(pairs), prose=prose))

    def table(self, title, header, rows, prose):
        self.blocks.append(Block(title, "table", header=list(header),
                                 rows=[list(r) for r in rows], prose=prose))

    def text(self, title, text):
        self.blocks.append(Block(title, "text", prose=text))

    def render(self, fmt: str, rng: random.Random) -> str:
        if fmt == "json":
            obj = {}
            for b in self.blocks:
                if b.kind == "facts":
                    obj[b.title] = {k: v for k, v in b.pairs}
                elif b.kind == "table":
                    obj[b.title] = [dict(zip(b.header, r)) for r in b.rows]
                else:
                    obj[b.title] = b.prose
            return json.dumps(obj, indent=rng.choice((None, 1, 2)), ensure_ascii=False)
        out = []
        for b in self.blocks:
            if fmt == "prose":
                out.append(b.prose)
            elif b.kind == "text":
                out.append(f"{b.title}: {b.prose}" if fmt == "kv" else b.prose)
            elif b.kind == "facts":
                out.append(f"{b.title}:\n" + "\n".join(f"  {k}: {v}" for k, v in b.pairs))
            elif fmt == "kv":
                lines = []
                for r in b.rows:
                    rest = "; ".join(f"{h}={c}" for h, c in zip(b.header[1:], r[1:]))
                    lines.append(f"  {r[0]}: {rest}")
                out.append(f"{b.title}:\n" + "\n".join(lines))
            else:
                head = "| " + " | ".join(str(h) for h in b.header) + " |"
                sep = "|" + "|".join("---" for _ in b.header) + "|"
                body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in b.rows)
                out.append(f"{b.title}\n{head}\n{sep}\n{body}")
        return "\n\n".join(out)


# ======================================================================================
# drafts, exact posteriors, heuristics
# ======================================================================================


@dataclass
class Draft:
    """One problem before rendering. Hypotheses carry `prior`; every observation j
    carries `liks[j][h]` = P(obs_j | h, obs_<j); `pred[h][o]` maps a hypothesis to the
    outcome asked about (None: the options are the hypotheses themselves)."""
    variant: str
    prior: list[F]
    liks: list[list[F]]
    pred: list[list[F]] | None
    params: dict
    gen: dict
    render: Callable[[random.Random], tuple]    # -> state, question, instructions, options, descriptions
    picks: dict = field(default_factory=dict)   # outcome-level picker heuristics: name -> set
    keep: list[int] | None = None               # outcomes offered as options (default: all)
    shuffle: bool = True
    hyp_heuristics: bool = True                 # per-observation last/majority on hypotheses


def posterior(prior: list[F], liks: list[list[F]]) -> list[F]:
    w = list(prior)
    for lk in liks:
        w = [a * b for a, b in zip(w, lk)]
    s = sum(w)
    if s == 0:
        raise ZeroDivisionError("observations impossible under every hypothesis")
    return [x / s for x in w]


def to_outcomes(dist: list, pred) -> list:
    if pred is None:
        return list(dist)
    n_out = len(pred[0])
    return [sum(dist[h] * pred[h][o] for h in range(len(dist))) for o in range(n_out)]


def exact_target(d: Draft) -> list[F]:
    """The exact posterior over the offered outcomes, in outcome order."""
    t = to_outcomes(posterior(d.prior, d.liks), d.pred)
    if d.keep is not None:
        dropped = sum(t[o] for o in range(len(t)) if o not in d.keep)
        if dropped != 0:
            raise ValueError("an outcome left out of the options carries mass")
        t = [t[o] for o in d.keep]
    return t


def _fnorm(xs) -> list[float]:
    s = float(sum(xs))
    if s <= 0:
        return [1.0 / len(xs)] * len(xs)
    return [float(x) / s for x in xs]


def _argset(xs, tol=1e-12) -> set[int]:
    m = max(xs)
    return {i for i, x in enumerate(xs) if x >= m - tol}


def heuristics(d: Draft) -> dict[str, list[float]]:
    """Every shallow reading of the draft, as a distribution over the offered outcomes.

    prior       -- the hypotheses weighed by the prior only (the evidence ignored)
    likelihood  -- the evidence only (the prior ignored; uniform prior)
    last        -- the last observation alone
    majority    -- one vote per observation, for the hypothesis it favours
    <picks>     -- variant-specific pickers: the most reliable source, the last or most
                   frequent observed outcome, staying with the first door, ...
    """
    k = len(d.prior)
    out: dict[str, list] = {}
    out["prior"] = to_outcomes(_fnorm(d.prior), d.pred)
    lik = [F(1)] * k
    for lk in d.liks:
        lik = [a * b for a, b in zip(lik, lk)]
    out["likelihood"] = to_outcomes(_fnorm(lik), d.pred)
    if d.hyp_heuristics and len(d.liks) >= 2:
        out["last"] = to_outcomes(_fnorm(d.liks[-1]), d.pred)
        votes = [0.0] * k
        for lk in d.liks:
            best = _argset([float(x) for x in lk])
            for h in best:
                votes[h] += 1.0 / len(best)
        out["majority"] = to_outcomes(_fnorm(votes), d.pred)
    n_out = len(out["prior"])
    for name, chosen in d.picks.items():
        if chosen:
            out[name] = [1.0 if o in chosen else 0.0 for o in range(n_out)]
    if d.keep is not None:
        out = {n: [v[o] for o in d.keep] for n, v in out.items()}
    return {n: _fnorm(v) for n, v in out.items()}


def agreement(dist: list[float], target: list[float]) -> float:
    """Expected accuracy of picking uniformly among `dist`'s argmax, scored against the
    argmax set of the exact target."""
    a, t = _argset(dist, 1e-9), _argset(target, 1e-12)
    return len(a & t) / len(a)


def conf_bin(target: list[float]) -> int:
    k = len(target)
    m = (max(target) - 1 / k) / (1 - 1 / k)
    return min(N_BINS - 1, max(0, int(m * N_BINS)))


def band(name: str, k: int) -> tuple[float, float]:
    """The accuracy a heuristic is held to: at least chance, far below the exact answer."""
    c = 1.0 / k
    return c, c + (1 - c) * (0.30 if name == "prior" else 0.42)


class Balance:
    """Keeps a task's max-posterior bins flat, every heuristic inside its band, and the
    answer's outcome index near 1/k (so a fixed option set -- yes/no, heads/tails, a count
    of heads, "neither" -- carries no label prior)."""

    def __init__(self):
        self.n = 0
        self.bins = Counter()
        self.acc: dict[str, list[float]] = {}     # name -> [sum acc, sum lo, sum hi]
        self.gold = Counter()                     # (k, outcome index) -> answers there
        self.gold_n = Counter()                   # k -> questions with k options

    @staticmethod
    def _gold(info):
        t = info["target"]
        g = _argset(t, 1e-12)
        return {i: 1 / len(g) for i in g}

    def violation(self, info) -> float:
        """How far past its limits this draft would push the task (0: it fits)."""
        n1 = self.n + 1
        v = max(0.0, self.bins[info["bin"]] + 1 - (n1 / N_BINS + 2 + 0.02 * n1))
        k = len(info["target"])
        for name, a in info["agree"].items():
            lo, hi = band(name, k)
            s, sl, sh = self.acc.get(name, (0.0, 0.0, 0.0))
            v += 2 * max(0.0, s + a - (sh + hi + 2)) + 2 * max(0.0, (sl + lo - 2) - (s + a))
        n_k = self.gold_n[k] + 1
        for i, w in self._gold(info).items():
            lim = n_k / k + 0.04 * n_k + 2
            v += max(0.0, self.gold[(k, i)] + w - lim)
        return v

    def fits(self, info) -> bool:
        return self.violation(info) == 0

    def add(self, info) -> None:
        self.n += 1
        self.bins[info["bin"]] += 1
        k = len(info["target"])
        for name, a in info["agree"].items():
            lo, hi = band(name, k)
            s, sl, sh = self.acc.get(name, (0.0, 0.0, 0.0))
            self.acc[name] = [s + a, sl + lo, sh + hi]
        for i, w in self._gold(info).items():
            self.gold[(k, i)] += w
        self.gold_n[k] += 1


def assess(d: Draft) -> dict | None:
    try:
        exact = exact_target(d)
    except ZeroDivisionError:
        return None
    target = [float(x) for x in exact]
    if len(target) < 2 or len(target) > 12:
        return None
    heur = heuristics(d)
    return {"exact": exact, "target": target, "heur": heur, "bin": conf_bin(target),
            "agree": {n: agreement(v, target) for n, v in heur.items()}}


# ======================================================================================
# shared wording
# ======================================================================================

ANSWER_LINES = (
    "Give the probability of each option, using exactly the numbers stated.",
    "Answer with a probability for every option, given everything stated.",
    "Assign each option its probability given the information above.",
    "Report how likely each option is, given what is stated and nothing else.",
    "Weigh every option by its exact probability under the stated setup.",
)


STRONG_WEIGHTS = (5, 6, 8, 10, 12, 15, 20, 30, 45, 60, 100, 150)


EXACT_LINES = (
    "Treat every stated rate, share and frequency as exact.",
    "Take each stated frequency, percentage or count ratio as the exact probability.",
    "All stated rates are exact; use them as given.",
    "The frequencies given are the true probabilities, not estimates.",
)


def answer(r: random.Random) -> str:
    return r.choice(EXACT_LINES) + " " + r.choice(ANSWER_LINES)


def draw_weights(rng: random.Random, k: int, uniform_share: float = 0.2,
                 strong: float = 0.35, top: int = 15):
    """Prior weights over k hypotheses: (weights, kind). `strong` is how often one
    hypothesis gets a dominant weight, of up to `top`."""
    if rng.random() < uniform_share:
        return [1] * k, "uniform"
    while True:
        if rng.random() < strong:
            ws = [rng.randint(1, 3) for _ in range(k)]
            ws[rng.randrange(k)] = rng.choice([w for w in STRONG_WEIGHTS if w <= top])
        else:
            ws = [rng.randint(1, 9) for _ in range(k)]
        if len(set(ws)) > 1:
            return ws, "stated"


def pick_truth(rng: random.Random, ws: list, conflict: float = 0.4) -> int:
    """The hidden hypothesis the observations are drawn from. Part of the time it is the
    one the prior likes least, so prior and evidence pull apart; the target does not
    depend on this choice, only which instances get drawn."""
    if rng.random() < conflict:
        lo = min(ws)
        return rng.choice([i for i, w in enumerate(ws) if w == lo])
    return rng.randrange(len(ws))


def prior_block(doc: Doc, rng: random.Random, names: list[str], ws: list[int], kind: str,
                what: str, style: str | None = None, frame: str = "lottery") -> str:
    """Add the prior over `names` to `doc`. -> the style used. `frame` says how a count
    prior is told: `lottery` (the hypothesis was drawn by lot, for urns, coins, doors) or
    `records` (base rates among comparable past cases, for facts about the world)."""
    k = len(names)
    p = norm(ws)
    if kind == "uniform":
        style = "uniform"
        s = rng.choice((
            f"Beforehand each of the {k} is equally likely to be {what}.",
            f"Beforehand no one of the {k} is favoured over another as {what}.",
            f"No option is favoured in advance: each has prior probability 1/{k}.",
        ))
        doc.facts("prior", [("rule", "uniform"), ("each", f"1/{k}")], s)
        return style
    if style is None:
        opts = ["counts", "counts", "pct", "frac", "dec", "ratio"]
        if k == 2:
            opts.append("odds")
        style = rng.choice(opts)
    if style in ("pct", "dec") and not all((pct if style == "pct" else dec)(x) for x in p):
        style = "frac"
    if style == "counts" and frame == "records":
        src = rng.choice(("comparable cases on record", "similar past cases",
                          "earlier cases in the reference set"))
        parts = [f"{w} {'was' if w == 1 else 'were'} {n}" for n, w in zip(names, ws)]
        s = (f"Base rates for {what}: of {sum(ws)} {src}, {join_and(parts)}.")
        doc.facts(f"base rates ({sum(ws)} {src})", list(zip(names, ws)), s)
    elif style == "counts":
        vessel, unit = rng.choice((("a hat", "slip"), ("a bag", "token"),
                                   ("a drum", "ticket"), ("a box", "card")))
        parts = [f"{plural(w, unit)} for {n}" for n, w in zip(names, ws)]
        s = (f"The choice of {what} was made by drawing one {unit} from {vessel} "
             f"holding {join_and(parts)}.")
        doc.facts(f"prior ({unit}s in {vessel})", list(zip(names, ws)), s)
    elif style == "ratio":
        s = (f"Beforehand the odds for {what} were {':'.join(str(w) for w in ws)} "
             f"across {join_and(names)}, in that order.")
        doc.facts("prior (odds ratio)", list(zip(names, [str(w) for w in ws])), s)
    elif style == "odds":
        s = (f"Beforehand the odds of {names[0]} against {names[1]} as {what} were "
             f"{ws[0]} to {ws[1]}.")
        doc.facts("prior", [("odds", f"{names[0]} : {names[1]} = {ws[0]} : {ws[1]}")], s)
    else:
        vals = [fmt_p(x, style) for x in p]
        s = rng.choice((
            f"Prior probability of {what}: " + ", ".join(f"{n} {v}" for n, v in zip(names, vals)) + ".",
            "Before any evidence, " + join_and([f"{n} had probability {v}" for n, v in zip(names, vals)])
            + f" of being {what}.",
        ))
        doc.facts("prior", list(zip(names, vals)), s)
    return style


# ======================================================================================
# family 1: urns
# ======================================================================================

COLOURS = ("red", "blue", "green", "white", "black", "yellow", "orange", "purple")
ITEMS = ("ball", "marble", "bead", "token", "chip")
URN_SETS = (
    ("urn", ["Urn A", "Urn B", "Urn C", "Urn D", "Urn E", "Urn F"]),
    ("bag", ["Bag 1", "Bag 2", "Bag 3", "Bag 4", "Bag 5", "Bag 6"]),
    ("box", ["the oak box", "the tin box", "the glass box", "the clay box", "the cedar box",
             "the steel box"]),
    ("jar", ["the left jar", "the middle jar", "the right jar", "the top-shelf jar",
             "the back jar", "the chipped jar"]),
    ("tub", ["Tub North", "Tub South", "Tub East", "Tub West", "Tub Centre", "Tub Spare"]),
)


def _urn_comp(rng, k, m, lo, hi, distinct_props, peaked=0.0):
    for _ in range(200):
        comps = []
        for _h in range(k):
            while True:
                if rng.random() < peaked:
                    c = [rng.randint(0, 2) for _ in range(m)]
                    c[rng.randrange(m)] = rng.randint(5, 10)
                else:
                    c = [rng.randint(0, 7) for _ in range(m)]
                if lo <= sum(c) <= hi and sum(1 for x in c if x) >= 1:
                    break
            comps.append(c)
        keys = [tuple(norm(c)) if distinct_props else tuple(c) for c in comps]
        if len(set(keys)) == k:
            return comps
    return None


def _urn_draw(rng, variant):
    mode = {"urn_which_repl": "repl", "urn_next_repl": "repl", "urn_which_norepl": "norepl",
            "urn_next_norepl": "norepl", "urn_which_polya": "polya"}[variant]
    query = "next" if "next" in variant else "which"
    k = rng.randint(2, 5) if query == "which" else rng.randint(2, 4)
    m = rng.randint(2, 4)
    lo, hi = (3, 14) if mode == "repl" else (4, 10)
    comps = _urn_comp(rng, k, m, lo, hi, mode == "repl", 0.6 if query == "next" else 0.0)
    if comps is None:
        return None
    totals = [sum(c) for c in comps]
    if mode == "repl":
        n = rng.randint(1, 6) if query == "which" else rng.randint(1, 4)
    elif mode == "polya":
        n = rng.randint(2, 5)
    else:
        n = rng.randint(1, min(5 if query == "which" else 3, min(totals) - 1))
    ws, kind = draw_weights(rng, k, *((0.2, 0.35) if query == "which" else (0.1, 0.7, 150)))
    truth = pick_truth(rng, ws, 0.4 if query == 'which' else 0.7)
    draws, cur = [], list(comps[truth])
    for _ in range(n):
        tot = sum(cur)
        if tot == 0:
            return None
        c = rng.choices(range(m), weights=cur)[0]
        draws.append(c)
        if mode == "norepl":
            cur[c] -= 1
        elif mode == "polya":
            cur[c] += 1
    liks, used = [], [0] * m
    for j, c in enumerate(draws):
        if mode == "repl":
            liks.append([F(comps[h][c], totals[h]) for h in range(k)])
        elif mode == "norepl":
            liks.append([F(max(0, comps[h][c] - used[c]), totals[h] - j) for h in range(k)])
        else:
            liks.append([F(comps[h][c] + used[c], totals[h] + j) for h in range(k)])
        used[c] += 1
    pred, picks = None, {}
    if query == "next":
        if mode == "repl":
            pred = [[F(comps[h][c], totals[h]) for c in range(m)] for h in range(k)]
        else:
            pred = [[F(max(0, comps[h][c] - used[c]), totals[h] - n) for c in range(m)]
                    for h in range(k)]
        cnt = Counter(draws)
        top = max(cnt.values())
        picks = {"last_outcome": {draws[-1]}, "majority_outcome": {c for c in cnt if cnt[c] == top}}
    kind_c, names = rng.choice(URN_SETS)
    names = names[:k]
    colours = rng.sample(COLOURS, m)
    item = rng.choice(ITEMS)
    fmt = rng.choice(FORMATS)
    comp_style = "counts" if mode != "repl" or rng.random() < 0.7 else rng.choice(("pct", "frac"))
    rule_in_instr = rng.random() < 0.5
    seq_style = rng.choice(("list", "numbered", "sentence"))
    gen = {"n_hyp": k, "n_colours": m, "n_obs": n, "prior": kind, "mode": mode,
           "query": query, "fmt": fmt, "comp_style": comp_style, "seq_style": seq_style,
           "rule_in_instr": rule_in_instr, "container": kind_c}
    params = {"comps": comps, "prior": ws, "draws": draws, "mode": mode, "query": query}

    def render(r: random.Random):
        doc = Doc()
        rows, prose = [], []
        for nm, c, t in zip(names, comps, totals):
            if comp_style == "counts":
                rows.append([nm] + [str(x) for x in c])
                parts = [f"{x} {col}" for x, col in zip(c, colours) if x]
                prose.append(f"{nm[0].upper() + nm[1:]} holds {join_and(parts)} "
                             f"{item}{'s' if t != 1 else ''}.")
            else:
                vals = [fmt_p(F(x, t), comp_style) for x in c]
                rows.append([nm] + vals)
                parts = [f"{v} are {col}" for v, col, x in zip(vals, colours, c) if x]
                prose.append(f"Of the {item}s in {nm}, {join_and(parts)}.")
        title = f"contents ({'counts' if comp_style == 'counts' else 'share of ' + item + 's'})"
        doc.table(title, [kind_c] + list(colours), rows, " ".join(prose))
        prior_block(doc, r, names, ws, kind, f"the {kind_c} used")
        rule = {"repl": f"Each {item} is put back and the {kind_c} is shaken before the next draw.",
                "norepl": f"{item[0].upper() + item[1:]}s are not put back: each draw leaves one fewer in the {kind_c}.",
                "polya": f"After each draw the {item} is put back together with one extra {item} "
                         f"of the same colour from a spare supply, so the {kind_c} grows by one "
                         f"each time."}[mode]
        seq = [colours[c] for c in draws]
        if seq_style == "list":
            obs = ", ".join(seq)
        elif seq_style == "numbered":
            obs = "; ".join(f"draw {j + 1}: {s}" for j, s in enumerate(seq))
        else:
            obs = " ".join(f"The {['first', 'second', 'third', 'fourth', 'fifth', 'sixth'][j]} "
                           f"{item} was {s}." for j, s in enumerate(seq))
        story = (f"One {kind_c} was picked as described and {plural(n, item)} "
                 f"{'was' if n == 1 else 'were'} drawn from it one at a time.")
        if not rule_in_instr:
            story += " " + rule
        doc.facts("draws", [("procedure", story), ("observed", obs)],
                  f"{story} Observed: {obs.rstrip('.')}.")
        state = doc.render(fmt, r)
        instr = (rule + " " if rule_in_instr else "") + answer(r)
        if query == "which":
            q = r.choice((f"Which {kind_c} were the {item}s drawn from?",
                          f"From which {kind_c} did the draws come?",
                          f"Which {kind_c} was picked?"))
            opts, descs = list(names), None
        else:
            q = r.choice((f"What colour will the next {item} drawn from the same {kind_c} be?",
                          f"If one more {item} is drawn from that {kind_c}, what colour is it?",
                          f"Predict the colour of the next draw from the same {kind_c}."))
            if mode == "norepl":
                q += f" (The {item}s already drawn stay out.)"
            opts, descs = list(colours), None
        return state, q, instr, opts, descs

    return Draft(variant, norm(ws), liks, pred, params, gen, render, picks=picks,
                 hyp_heuristics=query == "which")


# ======================================================================================
# family 2: coins and dice
# ======================================================================================

COIN_SETS = (
    ["Coin A", "Coin B", "Coin C", "Coin D", "Coin E", "Coin F"],
    ["the silver coin", "the copper coin", "the brass coin", "the bent coin",
     "the worn coin", "the new coin"],
    ["Token 1", "Token 2", "Token 3", "Token 4", "Token 5", "Token 6"],
)
DIE_SETS = (
    ["the red die", "the blue die", "the green die", "the white die"],
    ["Die A", "Die B", "Die C", "Die D"],
    ["the casino die", "the gift-shop die", "the bone die", "the plastic die"],
)


def _coin_draw(rng, variant):
    query = {"coin_which": "which", "coin_next": "next", "coin_nextcount": "count"}[variant]
    k = rng.randint(2, 6) if query == "which" else rng.randint(2, 4)
    den = rng.choice((20, 20, 10, 100))
    edge = max(1, den // 20)
    for _ in range(50):
        biases = []
        for _h in range(k):
            if query != "which" and rng.random() < (0.5 if query == "next" else 0.2):
                # near-certain coins, so a prediction can be confident
                x = rng.randint(edge, max(edge, den // 7))
                biases.append(F(x if rng.random() < 0.5 else den - x, den))
            else:
                biases.append(F(rng.randint(edge, den - edge), den))
        if len(set(biases)) == k:
            break
    else:
        return None
    n = rng.randint(2, 10) if query == "which" else rng.randint(1, 5)
    ws, kind = draw_weights(rng, k, *((0.2, 0.35) if query == "which" else (0.1, 0.7, 150)))
    truth = pick_truth(rng, ws, 0.4 if query == 'which' else 0.7)
    tosses = [1 if rng.random() < biases[truth] else 0 for _ in range(n)]
    liks = [[b if t else 1 - b for b in biases] for t in tosses]
    seq_style = rng.choice(("letters", "words", "counts")) if query != "next" else \
        rng.choice(("letters", "words"))
    pred, picks, shuffle, m_next = None, {}, True, 0
    heads = sum(tosses)
    if query == "next":
        pred = [[b, 1 - b] for b in biases]
        maj = {0} if heads * 2 > n else {1} if heads * 2 < n else {0, 1}
        picks = {"last_outcome": {0 if tosses[-1] else 1}, "majority_outcome": maj}
    elif query == "count":
        m_next = rng.randint(2, 4)
        pred = [[F(math.comb(m_next, x)) * b ** x * (1 - b) ** (m_next - x)
                 for x in range(m_next + 1)] for b in biases]
        fr = F(heads, n)
        plug = [F(math.comb(m_next, x)) * fr ** x * (1 - fr) ** (m_next - x)
                for x in range(m_next + 1)]
        picks = {"plugin": _argset([float(x) for x in plug])}
        shuffle = False
    names = rng.choice(COIN_SETS)[:k]
    fmt = rng.choice(FORMATS)
    bstyle = rng.choice(("pct", "dec", "frac", "in", "odds"))
    gen = {"n_hyp": k, "n_obs": n, "prior": kind, "query": query, "fmt": fmt,
           "bias_style": bstyle, "seq_style": seq_style, "m_next": m_next, "bias_den": den}
    params = {"biases": biases, "prior": ws, "tosses": tosses, "query": query, "m": m_next}

    def render(r: random.Random):
        doc = Doc()
        vals = []
        for b in biases:
            if bstyle == "odds":
                vals.append(f"heads:tails odds {b.numerator}:{b.denominator - b.numerator}")
            elif bstyle == "in":
                vals.append(f"{b.numerator} heads in {b.denominator} tosses on average")
            else:
                vals.append(fmt_p(b, bstyle))
        prose = " ".join(f"{nm[0].upper() + nm[1:]} lands heads with probability {v}."
                         if bstyle not in ("odds", "in") else
                         f"{nm[0].upper() + nm[1:]}: {v}." for nm, v in zip(names, vals))
        doc.table("coins", ["coin", "P(heads)" if bstyle not in ("odds", "in") else "bias"],
                  [[nm, v] for nm, v in zip(names, vals)], prose)
        prior_block(doc, r, names, ws, kind, "the coin tossed")
        if seq_style == "letters":
            obs = "".join("H" if t else "T" for t in tosses) + " (H = heads, T = tails)"
        elif seq_style == "words":
            obs = ", ".join("heads" if t else "tails" for t in tosses)
        else:
            obs = f"{plural(heads, 'head')} and {plural(n - heads, 'tail')} in {n} tosses (order not recorded)"
        story = f"One coin was picked as described and tossed {n} times; tosses are independent."
        doc.facts("tosses", [("procedure", story), ("result", obs)], f"{story} Result: {obs}.")
        state = doc.render(fmt, r)
        instr = answer(r)
        if query == "which":
            q = r.choice(("Which coin was tossed?", "Which coin produced these tosses?",
                          "Which of the coins was picked?"))
            return state, q, instr, list(names), None
        if query == "next":
            q = r.choice(("What will the next toss of the same coin show?",
                          "The same coin is tossed once more. Heads or tails?"))
            return state, q, instr, ["heads", "tails"], None
        q = r.choice((f"The same coin is tossed {m_next} more times. How many heads will those "
                      f"{m_next} tosses show?",
                      f"How many heads will the next {m_next} tosses of the same coin give?"))
        opts = ["no heads"] + [f"exactly {plural(x, 'head')}" for x in range(1, m_next + 1)]
        return state, q, instr, opts, None

    return Draft(variant, norm(ws), liks, pred, params, gen, render, picks=picks,
                 shuffle=shuffle, hyp_heuristics=query == "which")


def _die_faces(rng, f, heavy=0.0):
    if rng.random() < 0.3:
        return [F(1, f)] * f, "fair"
    if rng.random() < heavy:                     # one face dominates
        ws = [1] * f
        ws[rng.randrange(f)] = rng.choice((4, 6, 9, 14, 20, 30, 45))
        return norm(ws), "loaded"
    ws = [rng.randint(1, 3) for _ in range(f)]
    for i in rng.sample(range(f), rng.randint(1, 2)):
        ws[i] = rng.randint(3, 9)
    return norm(ws), "loaded"


def _die_draw(rng, variant):
    query = "which" if variant == "die_which" else "next"
    f = rng.choice((6, 6, 6, 6, 4, 8)) if query == "which" else rng.choice((6, 6, 4, 4))
    k = rng.randint(2, 4)
    for _ in range(50):
        dice = [_die_faces(rng, f, 0.0 if query == "which" else 0.7) for _ in range(k)]
        if len({tuple(p) for p, _ in dice}) == k:
            break
    else:
        return None
    faces = [p for p, _ in dice]
    n = rng.randint(2, 8) if query == "which" else rng.randint(1, 3)
    ws, kind = draw_weights(rng, k, *((0.2, 0.35) if query == "which" else (0.1, 0.7, 150)))
    truth = pick_truth(rng, ws, 0.4 if query == 'which' else 0.7)
    rolls = rng.choices(range(f), weights=[float(x) for x in faces[truth]], k=n)
    liks = [[faces[h][x] for h in range(k)] for x in rolls]
    pred, picks = None, {}
    if query == "next":
        pred = [list(faces[h]) for h in range(k)]
        cnt = Counter(rolls)
        top = max(cnt.values())
        picks = {"last_outcome": {rolls[-1]}, "majority_outcome": {x for x in cnt if cnt[x] == top}}
    names = rng.choice(DIE_SETS)[:k]
    fmt = rng.choice(FORMATS)
    style = rng.choice(("pct", "frac", "dec", "frac"))
    gen = {"n_hyp": k, "n_obs": n, "prior": kind, "query": query, "fmt": fmt, "faces": f,
           "p_style": style, "n_fair": sum(1 for _, t in dice if t == "fair")}
    params = {"faces": faces, "prior": ws, "rolls": rolls, "query": query}

    def render(r: random.Random):
        doc = Doc()
        rows, prose = [], []
        for nm, (p, t) in zip(names, dice):
            rows.append([nm] + [fmt_p(x, style) for x in p])
            if t == "fair":
                prose.append(f"{nm[0].upper() + nm[1:]} is fair: each face has probability "
                             f"{fmt_p(F(1, f), style)}.")
            else:
                prose.append(f"{nm[0].upper() + nm[1:]} is loaded: " + ", ".join(
                    f"face {i + 1} {fmt_p(x, style)}" for i, x in enumerate(p)) + ".")
        doc.table(f"face probabilities ({f}-sided dice)", ["die"] + [f"face {i + 1}" for i in range(f)],
                  rows, " ".join(prose))
        prior_block(doc, r, names, ws, kind, "the die rolled")
        story = f"One die was picked as described and rolled {n} times; rolls are independent."
        obs = ", ".join(str(x + 1) for x in rolls)
        doc.facts("rolls", [("procedure", story), ("faces shown", obs)],
                  f"{story} The faces shown were {obs}.")
        state = doc.render(fmt, r)
        instr = answer(r)
        if query == "which":
            q = r.choice(("Which die was rolled?", "Which die produced these rolls?"))
            return state, q, instr, list(names), None
        q = r.choice(("The same die is rolled once more. Which face comes up?",
                      "What will the next roll of the same die show?"))
        return state, q, instr, [f"a {NUMBER_WORDS[i + 1]}" for i in range(f)], None

    return Draft(variant, norm(ws), liks, pred, params, gen, render, picks=picks,
                 shuffle=query == "which", hyp_heuristics=query == "which")


# ======================================================================================
# family 3: noisy sensors and tests
# ======================================================================================

BINARY_CONTEXTS = (
    {"subject": "the patient", "pop": "patients tested at this clinic", "yes": "infected",
     "no": "not infected", "cond": "has the infection",
     "tests": ["the rapid antigen test", "the PCR test", "the blood panel"],
     "pos": "positive", "neg": "negative"},
    {"subject": "the part", "pop": "parts coming off this line", "yes": "defective",
     "no": "sound", "cond": "is defective",
     "tests": ["the ultrasonic probe", "the X-ray scanner", "the pressure rig"],
     "pos": "flagged", "neg": "clear"},
    {"subject": "the email", "pop": "emails reaching this inbox", "yes": "spam",
     "no": "legitimate", "cond": "is spam",
     "tests": ["the keyword filter", "the sender-reputation check", "the link scanner"],
     "pos": "spam verdict", "neg": "clean verdict"},
    {"subject": "the transaction", "pop": "card transactions at this merchant",
     "yes": "fraudulent", "no": "genuine", "cond": "is fraudulent",
     "tests": ["the velocity rule", "the device-fingerprint model", "the geolocation check"],
     "pos": "alert", "neg": "no alert"},
    {"subject": "the pipe section", "pop": "pipe sections on this network", "yes": "leaking",
     "no": "intact", "cond": "is leaking",
     "tests": ["the acoustic logger", "the pressure-drop sensor", "the tracer-gas sniffer"],
     "pos": "leak signal", "neg": "no signal"},
    {"subject": "the banknote", "pop": "notes handled at this branch", "yes": "counterfeit",
     "no": "genuine", "cond": "is counterfeit",
     "tests": ["the UV lamp", "the magnetic-ink reader", "the watermark check"],
     "pos": "reject", "neg": "accept"},
    {"subject": "the leaf sample", "pop": "samples from this orchard", "yes": "blighted",
     "no": "healthy", "cond": "carries blight",
     "tests": ["the colour-strip test", "the lab culture", "the field spectrometer"],
     "pos": "positive", "neg": "negative"},
)

OPERATORS = ("A. Moreau", "K. Tanaka", "L. Okafor", "S. Brandt", "P. Novak", "R. Iyer")

MULTI_CONTEXTS = (
    {"thing": "bird", "device": "the call-recognition app",
     "classes": ["wren", "robin", "blackbird", "chaffinch", "dunnock", "goldcrest"]},
    {"thing": "defect", "device": "the vision classifier",
     "classes": ["scratch", "dent", "crack", "discoloration", "burr", "warp"]},
    {"thing": "soil", "device": "the handheld soil probe",
     "classes": ["clay", "loam", "sand", "silt", "peat", "chalk"]},
    {"thing": "mineral", "device": "the field spectrometer",
     "classes": ["quartz", "feldspar", "calcite", "mica", "pyrite", "gypsum"]},
    {"thing": "language", "device": "the language detector",
     "classes": ["Danish", "Norwegian", "Swedish", "Dutch", "German", "Icelandic"]},
    {"thing": "fault", "device": "the vibration monitor",
     "classes": ["imbalance", "misalignment", "bearing wear", "looseness", "resonance",
                 "cavitation"]},
)


def _rate_text(p: F, style: str, counts_n: int | None = None) -> str:
    if style == "counts" and counts_n:
        return f"{p * counts_n} of {counts_n}"
    return fmt_p(p, style)


def _binary_sensor_draw(rng, variant):
    ctx = rng.choice(BINARY_CONTEXTS)
    n_tests = {"sensor_single": 1, "sensor_repeat": 1, "sensor_mixed": rng.randint(2, 3)}[variant]
    n = {"sensor_single": 1, "sensor_repeat": rng.randint(2, 5), "sensor_mixed": n_tests}[variant]
    base = rate(rng, 0.02, 0.85)
    tests = []
    for t in range(n_tests):
        se, sp = rate(rng, 0.55, 0.99), rate(rng, 0.55, 0.99)
        tests.append((ctx["tests"][t], se, sp))
    truth = rng.random() < 0.5
    readings = []           # (test index, positive?)
    for j in range(n):
        t = j if variant == "sensor_mixed" else 0
        _, se, sp = tests[t]
        readings.append((t, rng.random() < (se if truth else 1 - sp)))
    liks = []
    for t, pos in readings:
        _, se, sp = tests[t]
        liks.append([se, 1 - sp] if pos else [1 - se, sp])
    fmt = rng.choice(FORMATS)
    style = rng.choice(("pct", "pct", "dec", "frac", "in", "counts"))
    base_style = rng.choice(("pct", "in", "counts", "odds", "dec", "frac"))
    phrase = rng.choice(("sens_spec", "error_rates", "mixed"))
    in_instr = rng.random() < 0.3
    gen = {"n_hyp": 2, "n_obs": n, "n_tests": n_tests, "prior": "stated", "fmt": fmt,
           "rate_style": style, "base_style": base_style, "phrase": phrase,
           "rates_in_instr": in_instr, "context": ctx["subject"]}
    params = {"base": base, "tests": [(se, sp) for _, se, sp in tests],
              "readings": readings}

    def render(r: random.Random):
        doc = Doc()
        N = r.choice((200, 500, 1000, 2000))
        if base_style == "counts" and (base * N).denominator == 1:
            btxt = f"{base * N} of every {N} {ctx['pop']}"
        elif base_style == "odds":
            btxt = f"odds {base.numerator} to {base.denominator - base.numerator}"
        else:
            btxt = fmt_p(base, base_style if base_style != "counts" else "pct")
        pairs, prose = [], []
        pairs.append(("base rate", btxt))
        prose.append(f"Among {ctx['pop']}, the share that {ctx['cond'].replace('is ', 'are ', 1) if ctx['cond'].startswith('is ') else ctx['cond']} "
                     f"is {btxt}." if base_style not in ("counts", "odds") else
                     f"Base rate among {ctx['pop']}: {btxt}.")
        for name, se, sp in tests:
            M = r.choice((20, 50, 100, 200))
            st = style if style != "counts" or ((se * M).denominator == 1 and (sp * M).denominator == 1) else "pct"
            if phrase == "error_rates" or (phrase == "mixed" and r.random() < 0.5):
                a = _rate_text(1 - se, st, M)
                b = _rate_text(1 - sp, st, M)
                pairs.append((f"{name}: false-negative rate", a))
                pairs.append((f"{name}: false-positive rate", b))
                prose.append(f"{name[0].upper() + name[1:]} misses {a} of true cases "
                             f"and wrongly gives '{ctx['pos']}' on {b} of cases that are {ctx['no']}.")
            else:
                a = _rate_text(se, st, M)
                b = _rate_text(sp, st, M)
                pairs.append((f"{name}: sensitivity", a))
                pairs.append((f"{name}: specificity", b))
                prose.append(f"{name[0].upper() + name[1:]} gives '{ctx['pos']}' on {a} of "
                             f"cases that are {ctx['yes']} and '{ctx['neg']}' on {b} of cases "
                             f"that are {ctx['no']}.")
        indep = ("Readings are independent of each other given the true state."
                 if n > 1 else "")
        if in_instr:
            doc.facts("base rate", pairs[:1], prose[0])
            rates_text = " ".join(prose[1:])
        else:
            doc.facts("rates", pairs, " ".join(prose))
            rates_text = ""
        sid = f"{ctx['subject'].split()[-1][:3].upper()}-{r.randint(10000, 99999)}"
        when = f"{r.choice(('Mon', 'Tue', 'Wed', 'Thu', 'Fri'))} {r.randint(6, 18):02d}:{r.choice(('00', '15', '30', '45'))}"
        doc.facts(f"{ctx['subject'].replace('the ', '')} under test",
                  [("id", sid), ("checked", when), ("operator", r.choice(OPERATORS))],
                  f"{ctx['subject'][0].upper() + ctx['subject'][1:]} ({sid}) was checked on "
                  f"{when}.")
        rows = []
        for j, (t, pos) in enumerate(readings):
            rows.append([str(j + 1), tests[t][0], ctx["pos"] if pos else ctx["neg"]])
        rprose = " ".join(f"Reading {j + 1} ({tests[t][0]}): {ctx['pos'] if pos else ctx['neg']}."
                          for j, (t, pos) in enumerate(readings))
        doc.table(f"results for {ctx['subject']}", ["reading", "test", "result"], rows, rprose)
        state = doc.render(fmt, r)
        instr = " ".join(x for x in (rates_text, indep,
                                     answer(r)) if x)
        q = r.choice((f"Is {ctx['subject']} {ctx['yes']} or {ctx['no']}?",
                      f"What is the true state of {ctx['subject']}?",
                      f"Given these results, is {ctx['subject']} {ctx['yes']}?"))
        descs = [f"{ctx['subject']} {ctx['cond']}", None] if r.random() < 0.4 else None
        return state, q, instr, [ctx["yes"], ctx["no"]], descs

    return Draft(variant, [base, 1 - base], liks, None, params, gen, render)


def _confusion(rng, m, N):
    rows = []
    for t in range(m):
        w = [rng.randint(0, 4) for _ in range(m)]
        w[t] = rng.randint(3, 12)
        if sum(w) == 0:
            w[t] = 1
        rows.append([F(x, N) for x in int_split(rng, w, N)])
    return rows


def _multi_sensor_draw(rng, variant):
    ctx = rng.choice(MULTI_CONTEXTS)
    m = rng.randint(3, 6)
    classes = rng.sample(ctx["classes"], m)
    N = rng.choice((20, 20, 50, 100, 40))
    two_devices = variant == "sensor_multi_repeat" and rng.random() < 0.4
    mats = [_confusion(rng, m, N)] + ([_confusion(rng, m, N)] if two_devices else [])
    n = 1 if variant == "sensor_multi_single" else rng.randint(2, 3)
    ws, kind = draw_weights(rng, m)
    truth = pick_truth(rng, ws)
    readings = []
    for j in range(n):
        dv = j % len(mats)
        rep = rng.choices(range(m), weights=[float(x) for x in mats[dv][truth]])[0]
        readings.append((dv, rep))
    liks = [[mats[dv][t][rep] for t in range(m)] for dv, rep in readings]
    fmt = rng.choice(FORMATS)
    style = rng.choice(("counts", "counts", "pct", "frac"))
    gen = {"n_hyp": m, "n_obs": n, "prior": kind, "fmt": fmt, "rate_style": style,
           "n_devices": len(mats), "matrix_total": N, "context": ctx["thing"]}
    params = {"prior": ws, "mats": mats, "readings": readings}
    devnames = [ctx["device"], ctx["device"].replace("the ", "the backup ", 1)]

    def render(r: random.Random):
        doc = Doc()
        for dv, mat in enumerate(mats):
            rows, prose = [], []
            for t in range(m):
                cells = [str(mat[t][x] * N) if style == "counts" else fmt_p(mat[t][x], style)
                         for x in range(m)]
                rows.append([f"truly {classes[t]}"] + cells)
                if style == "counts":
                    prose.append(f"Of {N} tested cases that were truly {classes[t]}, it said "
                                 + ", ".join(f"{classes[x]} {c}" for x, c in enumerate(cells)) + ".")
                else:
                    prose.append(f"When the true {ctx['thing']} is {classes[t]}, it reports "
                                 + ", ".join(f"{classes[x]} with probability {c}"
                                             for x, c in enumerate(cells)) + ".")
            title = (f"{devnames[dv]}: validation counts (rows = truth, columns = reported)"
                     if style == "counts" else
                     f"{devnames[dv]}: P(reported | truth) (rows = truth)")
            doc.table(title, ["truth"] + [f"said {c}" for c in classes], rows,
                      f"Validation of {devnames[dv]}. " + " ".join(prose))
        prior_block(doc, r, classes, ws, kind, f"the {ctx['thing']}", frame="records")
        obs = [(devnames[dv], classes[rep]) for dv, rep in readings]
        doc.table("readings", ["reading", "device", "reported"],
                  [[str(j + 1), d, c] for j, (d, c) in enumerate(obs)],
                  " ".join(f"Reading {j + 1}: {d} reported {c}." for j, (d, c) in enumerate(obs)))
        state = doc.render(fmt, r)
        instr = ("Readings are independent given the true " + ctx["thing"] + ". " if n > 1 else "") \
            + answer(r)
        q = r.choice((f"Which {ctx['thing']} is it really?",
                      f"What is the true {ctx['thing']}?",
                      f"Given the readings, what is the actual {ctx['thing']}?"))
        return state, q, instr, list(classes), None

    return Draft(variant, norm(ws), liks, None, params, gen, render)


# ======================================================================================
# family 4: conflicting sources
# ======================================================================================

SOURCE_CONTEXTS = (
    {"attr": "the town where the painter was born",
     "values": ["Arden", "Belmoor", "Corrin", "Dunmere", "Eskdale", "Farrow", "Glenholm",
                "Hartwell"],
     "srcs": ["the parish register", "a 1920 biography", "the gallery label",
              "a letter from her sister", "the census return"]},
    {"attr": "the colour of the getaway car",
     "values": ["red", "blue", "green", "silver", "black", "white", "yellow", "brown"],
     "srcs": ["Witness Ahn", "Witness Brook", "Witness Castell", "Witness Dray",
              "the traffic camera log"]},
    {"attr": "the ship's home port",
     "values": ["Harwick", "Port Selby", "Tarnmouth", "Oldhaven", "Grest", "Lymford",
                "Kessock", "Wyre"],
     "srcs": ["the harbour ledger", "the insurer's file", "a crew member's diary",
              "the customs stamp", "a newspaper notice"]},
    {"attr": "the supplier of the faulty batch",
     "values": ["Norvik Ltd", "Pellam & Co", "Quarry Works", "Rendal", "Stoke Metals",
                "Tilbury Supply", "Umber Parts", "Vance Group"],
     "srcs": ["the goods-in log", "the shift supervisor", "the invoice scan",
              "the pallet label", "the ERP record"]},
    {"attr": "the horse that won the third race",
     "values": ["Silver Fen", "Quick Marram", "Ashdown Boy", "Moorlight", "Tallow",
                "Red Brae", "Kingfisher", "Old Lantern"],
     "srcs": ["the course announcer", "a bookmaker's slip", "the local paper",
              "a spectator's photo caption", "the steward's notebook"]},
    {"attr": "the original language of the manuscript",
     "values": ["Latin", "Old French", "Middle Dutch", "Catalan", "Occitan", "Old Norse",
                "Middle High German", "Tuscan"],
     "srcs": ["the 1890 catalogue", "a palaeographer's note", "the dealer's invoice",
              "the library index card", "a conference abstract"]},
)
RELAYS = ("the clerk who transcribed it", "a junior assistant", "the translator",
          "the night editor", "an intern")


def _rel_text(r: F, style: str, rng: random.Random) -> str:
    if style == "counts":
        n = rng.choice((10, 20, 40, 50, 100))
        if (r * n).denominator == 1:
            return f"right in {r * n} of {n} past checks"
        style = "pct"
    if style == "odds":
        return f"odds {r.numerator} to {r.denominator - r.numerator} of being right"
    return f"accurate with probability {fmt_p(r, style)}"


def _sources_draw(rng, variant):
    ctx = rng.choice(SOURCE_CONTEXTS)
    m = rng.choice((2, 3, 3, 4, 4, 5, 6, 7, 8))
    values = rng.sample(ctx["values"], m)
    if variant == "sources_relay":
        n = rng.randint(2, 3)
    else:
        n = {"sources_2": 2, "sources_3": 3, "sources_4": 4}[variant]
    floor = 1 / m + 0.05
    rels = [rate(rng, max(0.3, floor), 0.95) for _ in range(n)]
    relays: list[F | None] = [None] * n
    if variant == "sources_relay":
        for j in rng.sample(range(n), rng.randint(1, min(2, n))):
            relays[j] = rate(rng, max(0.5, floor), 0.95)
    ws, kind = draw_weights(rng, m, uniform_share=0.2)
    truth = pick_truth(rng, ws)
    reports = []

    def noisy(v, r):
        if rng.random() < r:
            return v
        return rng.choice([x for x in range(m) if x != v])

    for j in range(n):
        v = noisy(truth, rels[j])
        if relays[j] is not None:
            v = noisy(v, relays[j])
        reports.append(v)
    eff = []
    for j in range(n):
        r = rels[j]
        if relays[j] is not None:
            q = relays[j]
            r = r * q + (1 - r) * (1 - q) / (m - 1)
        eff.append(r)
    liks = [[eff[j] if x == reports[j] else (1 - eff[j]) / (m - 1) for x in range(m)]
            for j in range(n)]
    top = max(rels)
    cnt = Counter(reports)
    mc = max(cnt.values())
    picks = {"reliable": {reports[j] for j in range(n) if rels[j] == top},
             "majority_report": {v for v in cnt if cnt[v] == mc}}
    srcs = rng.sample(ctx["srcs"], n)
    fmt = rng.choice(FORMATS)
    style = rng.choice(("pct", "pct", "dec", "frac", "counts", "odds"))
    gen = {"n_hyp": m, "n_obs": n, "n_sources": n, "prior": kind, "fmt": fmt,
           "rel_style": style, "n_relayed": sum(1 for x in relays if x is not None),
           "n_distinct_reports": len(cnt)}
    params = {"m": m, "rels": rels, "relays": relays, "reports": reports, "prior": ws}

    relayed = variant == "sources_relay"

    def render(r: random.Random):
        doc = Doc()
        doc.facts("candidates", [("values", ", ".join(values))],
                  f"The candidates for {ctx['attr']} are {join_and(values)}.")
        prior_block(doc, r, values, ws, kind, ctx["attr"], frame="records")
        rows, prose = [], []
        for j in range(n):
            rt = _rel_text(rels[j], style, r)
            if relays[j] is None:
                rows.append([srcs[j], rt] + (["direct"] if relayed else []) + [values[reports[j]]])
                prose.append(f"{srcs[j][0].upper() + srcs[j][1:]} ({rt}) gives {values[reports[j]]}.")
            else:
                via = r.choice(RELAYS)
                qt = _rel_text(relays[j], style, r).replace("accurate", "passes it on correctly")
                rows.append([srcs[j], rt, f"via {via} ({qt})", values[reports[j]]])
                prose.append(f"{srcs[j][0].upper() + srcs[j][1:]} ({rt}) is known only through "
                             f"{via}, who {qt.replace('right in', 'relays correctly in')}; the "
                             f"value that reached us is {values[reports[j]]}.")
        doc.table("reports", ["source", "reliability"] + (["channel"] if relayed else [])
                  + ["reported value"], rows,
                  " ".join(prose))
        state = doc.render(fmt, r)
        err = (f"A source that is not accurate names one of the other {m - 1} candidates, "
               f"each equally likely; sources err independently.")
        if variant == "sources_relay":
            err += (" A relay that garbles a value passes on one of the other candidates, each "
                    "equally likely.")
        instr = err + " " + answer(r)
        q = r.choice((f"What is {ctx['attr']}?", f"Which value is true for {ctx['attr']}?",
                      f"Given the reports, what was {ctx['attr']}?"))
        return state, q, instr, list(values), None

    return Draft(variant, norm(ws), liks, None, params, gen, render, picks=picks,
                 hyp_heuristics=True)


# ======================================================================================
# family 5: a missing attribute with a stated prior
# ======================================================================================

MISSING_CONTEXTS = (
    {"record": "customer", "B": "plan",
     "Bv": ["Basic", "Plus", "Pro", "Team", "Business", "Enterprise", "Student", "Family"],
     "A": "signup channel", "Av": ["web", "mobile app", "referral", "partner", "phone"],
     "A2": "region", "A2v": ["North", "South", "East", "West", "Central"],
     "ids": "CUST", "extra": ("last login", ["2 days ago", "last week", "yesterday", "today"])},
    {"record": "vehicle", "B": "fuel type",
     "Bv": ["petrol", "diesel", "hybrid", "electric", "LPG", "plug-in hybrid"],
     "A": "body style", "Av": ["hatchback", "saloon", "estate", "SUV", "van"],
     "A2": "age band", "A2v": ["0-3 years", "4-7 years", "8-12 years", "13+ years"],
     "ids": "VEH", "extra": ("colour", ["grey", "white", "black", "blue", "red"])},
    {"record": "plant specimen", "B": "flower colour",
     "Bv": ["white", "pink", "purple", "yellow", "blue", "red", "orange"],
     "A": "soil type", "Av": ["clay", "loam", "sand", "peat", "chalk"],
     "A2": "altitude band", "A2v": ["lowland", "upland", "montane", "alpine"],
     "ids": "HERB", "extra": ("collector", ["J. Ames", "R. Osei", "T. Lind", "M. Varga"])},
    {"record": "book", "B": "genre",
     "Bv": ["crime", "romance", "history", "science", "fantasy", "poetry", "travel",
            "biography"],
     "A": "format", "Av": ["hardback", "paperback", "ebook", "audiobook"],
     "A2": "shelf section", "A2v": ["front table", "main floor", "basement", "annex"],
     "ids": "ISBN-X", "extra": ("price band", ["under 10", "10-20", "20-40", "over 40"])},
    {"record": "parcel", "B": "carrier",
     "Bv": ["Swiftpost", "ParcelLine", "Northway", "Keel Freight", "Dash", "Orbit Mail"],
     "A": "destination zone", "Av": ["zone 1", "zone 2", "zone 3", "zone 4", "zone 5"],
     "A2": "size class", "A2v": ["small", "medium", "large", "oversize"],
     "ids": "PCL", "extra": ("weight", ["0.4 kg", "1.2 kg", "3 kg", "7.5 kg"])},
    {"record": "employee", "B": "department",
     "Bv": ["finance", "sales", "support", "engineering", "legal", "operations", "marketing"],
     "A": "office", "Av": ["Leeds", "Porto", "Gdansk", "Austin", "Cork"],
     "A2": "contract type", "A2v": ["permanent", "fixed-term", "contractor", "intern"],
     "ids": "EMP", "extra": ("start year", ["2019", "2021", "2022", "2024"])},
)


JOINT_HEAVY = (0, 0, 0, 1, 2, 3, 5, 8, 12, 20, 35, 60, 90)


def _missing_draw(rng, variant):
    ctx = rng.choice(MISSING_CONTEXTS)
    mb = rng.randint(3, min(8, len(ctx["Bv"])))
    ma = rng.randint(2 if variant != "missing_either" else 3, len(ctx["Av"]))
    Bv = rng.sample(ctx["Bv"], mb)
    Av = rng.sample(ctx["Av"], ma)
    A2v = rng.sample(ctx["A2v"], rng.randint(2, len(ctx["A2v"])))
    fmt = rng.choice(FORMATS)
    gen = {"n_hyp": mb, "n_a": ma, "fmt": fmt, "context": ctx["record"]}
    truth = rng.randrange(mb)
    if variant in ("missing_joint", "missing_either"):
        heavy = 0.3 if variant == "missing_joint" else 0.8
        counts = [[rng.choice(JOINT_HEAVY) if rng.random() < heavy else
                   (rng.randint(0, 40) if rng.random() < 0.85 else 0) for _ in range(mb)]
                  for _ in range(ma)]
        col = [sum(counts[a][b] for a in range(ma)) for b in range(mb)]
        if min(col) == 0:
            return None
        prior = [F(c, sum(col)) for c in col]
        cond = [[F(counts[a][b], col[b]) for b in range(mb)] for a in range(ma)]
        pa = [float(cond[a][truth]) for a in range(ma)]
        if sum(pa) == 0:
            return None
        a_obs = rng.choices(range(ma), weights=pa)[0]
        if variant == "missing_either":
            other = rng.choice([a for a in range(ma) if a != a_obs])
            ev = sorted({a_obs, other})
        else:
            ev = [a_obs]
        liks = [[sum(cond[a][b] for a in ev) for b in range(mb)]]
        conds, evidence, kind = [cond], [ev], "table"
        gen.update({"n_obs": 1, "prior": "joint-table", "evidence_size": len(ev)})
        params = {"prior": prior, "conds": conds, "evidence": evidence, "counts": counts}
    else:
        ws, kind = draw_weights(rng, mb, uniform_share=0.1)
        prior = norm(ws)
        n_attr = 2 if variant == "missing_two" else 1
        conds, evidence, liks = [], [], []
        for t in range(n_attr):
            vals = Av if t == 0 else A2v
            M = rng.choice((20, 20, 100, 10))
            cond_t = [[None] * mb for _ in vals]
            for b in range(mb):
                w = [rng.randint(0, 6) for _ in vals]
                if sum(w) == 0:
                    w[rng.randrange(len(vals))] = 1
                cs = int_split(rng, w, M)
                for a in range(len(vals)):
                    cond_t[a][b] = F(cs[a], M)
            pa = [float(cond_t[a][truth]) for a in range(len(vals))]
            a_obs = rng.choices(range(len(vals)), weights=pa)[0]
            conds.append(cond_t)
            evidence.append([a_obs])
            liks.append([cond_t[a_obs][b] for b in range(mb)])
        gen.update({"n_obs": n_attr, "prior": kind})
        params = {"prior": prior, "conds": conds, "evidence": evidence}
    style = rng.choice(("pct", "pct", "frac", "dec"))
    gen["p_style"] = style if variant in ("missing_inverse", "missing_two") else "counts"
    rec_style = rng.choice(("null", "blank", "missing", "unknown"))
    gen["blank_style"] = rec_style

    def render(r: random.Random):
        doc = Doc()
        B, A, A2 = ctx["B"], ctx["A"], ctx["A2"]
        if variant in ("missing_joint", "missing_either"):
            counts = params["counts"]
            rows = [[Av[a]] + [str(counts[a][b]) for b in range(mb)] for a in range(ma)]
            prose = " ".join(f"Among {ctx['record']}s with {A} {Av[a]}: " + ", ".join(
                f"{counts[a][b]} {Bv[b]}" for b in range(mb)) + "." for a in range(ma))
            doc.table(f"{ctx['record']} population: counts by {A} (rows) and {B} (columns)",
                      [A] + Bv, rows, f"Population counts of {ctx['record']}s. " + prose)
        else:
            vals = [fmt_p(x, style) for x in prior]
            doc.facts(f"{B} distribution (all {ctx['record']}s)", list(zip(Bv, vals)),
                      f"Across all {ctx['record']}s, {B} is " + ", ".join(
                          f"{v} {b}" for b, v in zip(Bv, vals)) + ".")
            for t, cond_t in enumerate(conds):
                an, avs = (A, Av) if t == 0 else (A2, A2v)
                rows = [[b] + [fmt_p(cond_t[a][bi], style) for a in range(len(avs))]
                        for bi, b in enumerate(Bv)]
                prose = " ".join(f"Among {Bv[bi]} {ctx['record']}s, {an} is " + ", ".join(
                    f"{avs[a]} {fmt_p(cond_t[a][bi], style)}" for a in range(len(avs))) + "."
                    for bi in range(mb))
                doc.table(f"{an} given {B} (each row sums to 1)", [B] + avs, rows, prose)
        blank = {"null": None, "blank": "", "missing": "(missing)", "unknown": "unknown"}[rec_style]
        rid = f"{ctx['ids']}-{r.randint(1000, 99999)}"
        pairs = [("id", rid)]
        if variant == "missing_either":
            pairs.append((A, f"{Av[evidence[0][0]]} or {Av[evidence[0][1]]} (field smudged)"))
        else:
            pairs.append((A, Av[evidence[0][0]]))
        if variant == "missing_two":
            pairs.append((A2, A2v[evidence[1][0]]))
        pairs.append((ctx["extra"][0], r.choice(ctx["extra"][1])))
        pairs.append((B, blank if fmt == "json" else (blank if blank else "—")))
        r.shuffle(pairs)
        known = [f"{k} {v}" for k, v in pairs if k != B]
        doc.facts(f"{ctx['record']} record", pairs,
                  f"The {ctx['record']} record lists " + join_and(known) + f"; its {B} is not recorded.")
        state = doc.render(fmt, r)
        notes = []
        if variant == "missing_either":
            notes.append(f"The {A} field reads as one of the two values shown; nothing favours "
                         f"either reading beyond the population counts.")
        if variant == "missing_two":
            notes.append(f"Within each {B}, {A} and {A2} are independent.")
        notes.append(f"The record is drawn from the population described, and its {B} is "
                     f"missing for reasons unrelated to its value.")
        instr = " ".join(notes) + " " + answer(r)
        q = r.choice((f"What is this {ctx['record']}'s {B}?",
                      f"Fill in the missing {B}.",
                      f"Which {B} does this {ctx['record']} have?"))
        return state, q, instr, list(Bv), None

    return Draft(variant, list(params["prior"]), liks, None, params, gen, render)


# ======================================================================================
# family 6: chains, host rules, two causes
# ======================================================================================

CHAIN_CONTEXTS = (
    {"A": "the supplier", "Av": ["Aldana", "Birk", "Corvo", "Dahl"],
     "B": "the batch quality", "Bv": ["good", "marginal", "poor"],
     "C": "the inspection result", "Cv": ["pass", "rework", "reject"]},
    {"A": "the season", "Av": ["spring", "summer", "autumn", "winter"],
     "B": "the road surface", "Bv": ["dry", "wet", "icy"],
     "C": "the commute", "Cv": ["on time", "late", "very late"]},
    {"A": "the server", "Av": ["alpha", "bravo", "charlie", "delta"],
     "B": "the network path", "Bv": ["clean", "congested", "flapping"],
     "C": "the request outcome", "Cv": ["fast", "slow", "timeout"]},
    {"A": "the field", "Av": ["north field", "river field", "hill field", "long field"],
     "B": "the pest level", "Bv": ["low", "moderate", "high"],
     "C": "the trap count", "Cv": ["empty", "a few", "many"]},
)


def _cpt_rows(rng, n_from, n_to):
    den = rng.choice((10, 20, 20, 100))
    out = []
    for _ in range(n_from):
        w = [rng.randint(0, 6) for _ in range(n_to)]
        w[rng.randrange(n_to)] += rng.randint(1, 6)
        out.append([F(x, den) for x in int_split(rng, w, den)])
    return out


def _chain_draw(rng, variant):
    ctx = rng.choice(CHAIN_CONTEXTS)
    na = rng.randint(2, 4)
    nb = rng.randint(2, 3)
    nc = rng.randint(2, 3)
    Av, Bv, Cv = ctx["Av"][:na], ctx["Bv"][:nb], ctx["Cv"][:nc]
    ws, kind = draw_weights(rng, na)
    pA = norm(ws)
    pBA = _cpt_rows(rng, na, nb)
    pCB = _cpt_rows(rng, nb, nc)
    query = "A" if rng.random() < 0.65 else "B"
    a = pick_truth(rng, ws)
    b = rng.choices(range(nb), weights=[float(x) for x in pBA[a]])[0]
    wc = [float(x) for x in pCB[b]]
    if sum(wc) == 0:
        return None
    c = rng.choices(range(nc), weights=wc)[0]
    if query == "A":
        prior = pA
        liks = [[sum(pBA[x][y] * pCB[y][c] for y in range(nb)) for x in range(na)]]
    else:
        prior = [sum(pA[x] * pBA[x][y] for x in range(na)) for y in range(nb)]
        liks = [[pCB[y][c] for y in range(nb)]]
    if sum(prior) == 0:
        return None
    fmt = rng.choice(FORMATS)
    style = rng.choice(("pct", "frac", "dec"))
    gen = {"n_hyp": na if query == "A" else nb, "n_obs": 1, "prior": kind, "fmt": fmt,
           "query": query, "p_style": style, "n_a": na, "n_b": nb, "n_c": nc}
    params = {"pA": pA, "pBA": pBA, "pCB": pCB, "c": c, "query": query}

    def render(r: random.Random):
        doc = Doc()
        prior_block(doc, r, Av, ws, kind, ctx["A"], frame="records")
        for title, frm, to, cpt, fn, tn in (
                (f"{ctx['B']} given {ctx['A']}", Av, Bv, pBA, ctx["A"], ctx["B"]),
                (f"{ctx['C']} given {ctx['B']}", Bv, Cv, pCB, ctx["B"], ctx["C"])):
            rows = [[f] + [fmt_p(p, style) for p in cpt[i]] for i, f in enumerate(frm)]
            prose = " ".join(f"When {fn} is {f}, {tn} is " + ", ".join(
                f"{t} with probability {fmt_p(cpt[i][j], style)}" for j, t in enumerate(to)) + "."
                for i, f in enumerate(frm))
            doc.table(title + " (rows sum to 1)", [fn] + list(to), rows, prose)
        doc.facts("observed", [(ctx["C"], Cv[c])], f"Observed: {ctx['C']} was {Cv[c]}.")
        state = doc.render(fmt, r)
        instr = (f"{ctx['C'][0].upper() + ctx['C'][1:]} depends on {ctx['A']} only through "
                 f"{ctx['B']}. " + answer(r))
        if query == "A":
            q = r.choice((f"What was {ctx['A']}?", f"Which was {ctx['A']}?"))
            return state, q, instr, list(Av), None
        q = r.choice((f"What was {ctx['B']}?", f"Which state was {ctx['B']} in?"))
        return state, q, instr, list(Bv), None

    return Draft(variant, prior, liks, None, params, gen, render)


DOOR_SETS = (
    ["Door 1", "Door 2", "Door 3", "Door 4"],
    ["the red box", "the green box", "the blue box", "the gold box"],
    ["the left cup", "the middle cup", "the right cup", "the far-right cup"],
)


def _host_draw(rng, variant):
    nd = rng.choice((3, 3, 4))
    names = rng.choice(DOOR_SETS)[:nd]
    ws, kind = draw_weights(rng, nd, uniform_share=0.15, strong=0.5)
    rule = rng.choice(("random", "weighted", "weighted", "lowest", "highest"))
    hw = [1] * nd
    if rule == "weighted":
        hw = [rng.randint(1, 9) for _ in range(nd)]
        if len(set(hw)) == 1:
            hw[rng.randrange(nd)] += 2
    pick = rng.randrange(nd)
    prize = pick_truth(rng, ws)

    def open_probs(d):
        allowed = [x for x in range(nd) if x != pick and x != d]
        if rule == "lowest":
            return {min(allowed): F(1)}
        if rule == "highest":
            return {max(allowed): F(1)}
        s = sum(hw[x] for x in allowed)
        return {x: F(hw[x], s) for x in allowed}

    po = open_probs(prize)
    opened = rng.choices(list(po), weights=[float(v) for v in po.values()])[0]
    liks = [[open_probs(d).get(opened, F(0)) for d in range(nd)]]
    keep = [x for x in range(nd) if x != opened]
    fmt = rng.choice(FORMATS)
    gen = {"n_hyp": nd, "n_obs": 1, "prior": kind, "fmt": fmt, "host_rule": rule}
    params = {"prior": ws, "pick": pick, "rule": rule, "hw": hw, "opened": opened}

    def render(r: random.Random):
        doc = Doc()
        prior_block(doc, r, names, ws, kind, "the hiding place of the prize")
        if rule == "random":
            rt = "he chooses uniformly at random among them"
        elif rule == "lowest":
            rt = "he always opens the first of them in the order " + ", ".join(names)
        elif rule == "highest":
            rt = "he always opens the last of them in the order " + ", ".join(names)
        else:
            rt = ("he chooses among them in proportion to these weights: "
                  + ", ".join(f"{n} {w}" for n, w in zip(names, hw)))
        host = (f"The host knows where the prize is. He opens exactly one of the other "
                f"{'boxes' if 'box' in names[0] else 'cups' if 'cup' in names[0] else 'doors'} "
                f"that is neither the contestant's choice nor the prize; when more than one "
                f"qualifies, {rt}.")
        doc.facts("host rule", [("rule", host)], host)
        doc.facts("what happened", [("contestant chose", names[pick]), ("host opened", names[opened]),
                                    ("prize behind opened", "no")],
                  f"The contestant chose {names[pick]}. The host then opened {names[opened]}, "
                  f"which was empty.")
        state = doc.render(fmt, r)
        instr = answer(r)
        q = r.choice(("Where is the prize?", "Which one hides the prize?",
                      "Behind which of the unopened ones is the prize?"))
        return state, q, instr, list(names), None

    return Draft(variant, norm(ws), liks, None, params, gen, render,
                 picks={"stay": {pick}}, keep=keep)


EXPLAIN_CONTEXTS = (
    {"c1": "a burst pipe", "c2": "heavy rain", "e": "the cellar is flooded",
     "e_no": "the cellar is dry", "short1": "pipe", "short2": "rain",
     "not1": "no burst pipe", "not2": "no heavy rain"},
    {"c1": "a software bug", "c2": "a network fault", "e": "the nightly job failed",
     "e_no": "the nightly job succeeded", "short1": "bug", "short2": "network",
     "not1": "no software bug", "not2": "no network fault"},
    {"c1": "a pollen spike", "c2": "a cold", "e": "she is sneezing",
     "e_no": "she is not sneezing", "short1": "pollen", "short2": "cold",
     "not1": "no pollen spike", "not2": "no cold"},
    {"c1": "a blown fuse", "c2": "a tripped breaker", "e": "the lights are out",
     "e_no": "the lights are on", "short1": "fuse", "short2": "breaker",
     "not1": "no blown fuse", "not2": "no tripped breaker"},
    {"c1": "a supplier delay", "c2": "a strike at the port", "e": "the shipment is late",
     "e_no": "the shipment is on time", "short1": "supplier", "short2": "strike",
     "not1": "no supplier delay", "not2": "no strike at the port"},
)


def _explain_draw(rng, variant):
    ctx = rng.choice(EXPLAIN_CONTEXTS)
    p1, p2 = rate(rng, 0.05, 0.7), rate(rng, 0.05, 0.7)
    cpt = {}
    for c1 in (1, 0):
        for c2 in (1, 0):
            lo, hi = (0.5, 0.99) if (c1 or c2) else (0.01, 0.3)
            cpt[(c1, c2)] = rate(rng, lo, hi)
    hyps = [(1, 1), (1, 0), (0, 1), (0, 0)]
    prior = [(p1 if a else 1 - p1) * (p2 if b else 1 - p2) for a, b in hyps]
    t1, t2 = rng.random() < 0.5, rng.random() < 0.5
    e = int(rng.random() < cpt[(int(t1), int(t2))])
    if rng.random() < 0.25:
        e = 1 - e
    liks = [[cpt[h] if e else 1 - cpt[h] for h in hyps]]
    c2_known = rng.random() < 0.4
    if c2_known:
        c2v = int(t2)
        liks.append([F(1) if h[1] == c2v else F(0) for h in hyps])
    query = "c1" if c2_known or rng.random() < 0.4 else "joint"
    pred = None if query == "joint" else [[F(1), F(0)] if h[0] else [F(0), F(1)] for h in hyps]
    fmt = rng.choice(FORMATS)
    style = rng.choice(("pct", "frac", "dec", "in"))
    gen = {"n_hyp": 4, "n_obs": len(liks), "prior": "stated", "fmt": fmt, "query": query,
           "effect": e, "c2_known": c2_known, "p_style": style}
    params = {"p1": p1, "p2": p2, "cpt": cpt, "e": e, "c2": int(t2) if c2_known else None,
              "query": query}

    def render(r: random.Random):
        doc = Doc()
        doc.facts("base rates", [(ctx["c1"], fmt_p(p1, style)), (ctx["c2"], fmt_p(p2, style))],
                  f"On a given day, {ctx['c1']} happens with probability {fmt_p(p1, style)} and "
                  f"{ctx['c2']} with probability {fmt_p(p2, style)}, independently.")
        rows = []
        for (a, b) in hyps:
            rows.append(["yes" if a else "no", "yes" if b else "no", fmt_p(cpt[(a, b)], style)])
        prose = " ".join(
            f"With {ctx['c1'] if a else ctx['not1']} and "
            f"{ctx['c2'] if b else ctx['not2']}, the chance that "
            f"{ctx['e']} is {fmt_p(cpt[(a, b)], style)}." for a, b in hyps)
        doc.table(f"P({ctx['e']})", [ctx["c1"], ctx["c2"], "probability"], rows, prose)
        obs = [("effect", ctx["e"] if e else ctx["e_no"])]
        text = f"Today {ctx['e'] if e else ctx['e_no']}."
        if c2_known:
            obs.append((ctx["c2"], "yes" if params["c2"] else "no"))
            text += f" It is known that there was {ctx['c2'] if params['c2'] else ctx['not2']}."
        doc.facts("today", obs, text)
        state = doc.render(fmt, r)
        instr = "The two causes occur independently of each other. " + answer(r)
        if query == "joint":
            q = r.choice(("Which causes were present today?", "What happened today?"))
            opts = [f"both {ctx['short1']} and {ctx['short2']}", f"{ctx['short1']} only",
                    f"{ctx['short2']} only", "neither"]
            descs = [f"{ctx['c1']} and {ctx['c2']}", f"{ctx['c1']}, {ctx['not2']}",
                     f"{ctx['c2']}, {ctx['not1']}", "neither cause occurred"]
            return state, q, instr, opts, descs
        q = f"Was there {ctx['c1']} today?"
        return state, q, instr, ["yes", "no"], None

    return Draft(variant, prior, liks, pred, params, gen, render)


# ======================================================================================
# the loader
# ======================================================================================

DRAW: dict[str, Callable[[random.Random, str], Draft | None]] = {
    "urn_which_repl": _urn_draw, "urn_which_norepl": _urn_draw, "urn_next_repl": _urn_draw,
    "urn_which_polya": _urn_draw, "urn_next_norepl": _urn_draw,
    "coin_which": _coin_draw, "coin_next": _coin_draw, "coin_nextcount": _coin_draw,
    "die_which": _die_draw, "die_next": _die_draw,
    "sensor_single": _binary_sensor_draw, "sensor_repeat": _binary_sensor_draw,
    "sensor_mixed": _binary_sensor_draw,
    "sensor_multi_single": _multi_sensor_draw, "sensor_multi_repeat": _multi_sensor_draw,
    "sources_2": _sources_draw, "sources_3": _sources_draw, "sources_4": _sources_draw,
    "sources_relay": _sources_draw,
    "missing_joint": _missing_draw, "missing_inverse": _missing_draw,
    "missing_either": _missing_draw, "missing_two": _missing_draw,
    "chain_two_step": _chain_draw, "chain_host": _host_draw, "chain_explain": _explain_draw,
}


def _rng(seed: int, salt: str) -> random.Random:
    return random.Random(f"post:{seed}:{salt}")


def emit(d: Draft, info: dict, rng: random.Random, i: int) -> Example:
    state, q, instr, opts, descs = d.render(rng)
    order = list(d.keep) if d.keep is not None else list(range(len(opts)))
    pos = list(range(len(order)))            # positions within the offered outcomes
    if d.shuffle:
        rng.shuffle(pos)
    options = [opts[order[p]] for p in pos]
    target = [info["target"][p] for p in pos]
    descriptions = [descs[order[p]] for p in pos] if descs else None
    fam, split = VARIANTS[d.variant]
    t = info["target"]
    gen = {"family": fam, "variant": d.variant, "n_options": len(options),
           "max_post": round(max(t), 4), "conf_bin": info["bin"], **d.gen}
    return Example(state=state, questions=[Question(
        id=f"{d.variant}_{i}", question=q, instructions=instr, options=options,
        descriptions=descriptions, target=target, meta={"gen": gen})])


def generate(variant: str, seed: int, n: int) -> Iterator[tuple[Draft, dict, Example]]:
    """Up to n balanced (draft, assessment, example) triples for one variant."""
    bal = Balance()
    made = i = stall = 0
    best = None                    # the least-violating draft seen during a stall
    while made < n and i < n * 400:
        i += 1
        rng = _rng(seed, f"{variant}:{i}")
        d = DRAW[variant](rng, variant)
        if d is None:
            continue
        info = assess(d)
        if info is None:
            continue
        v = bal.violation(info)
        if v > 0:
            if best is None or v < best[0]:
                best = (v, d, info, rng, i)
            stall += 1
            if stall < STALL:
                continue
            _, d, info, rng, i_used = best
        else:
            i_used = i
        stall, best = 0, None
        bal.add(info)
        made += 1
        yield d, info, emit(d, info, rng, i_used)


def _loader(variant: str, seed: int, cap: int):
    def load(n: int) -> Iterator[Example]:
        for _, _, ex in generate(variant, seed, min(n, cap)):
            yield ex
    return load


def tasks() -> list[RealTask]:
    """Trained variants to `train` with a fresh-seed `_eval` twin in `devreal` (family =
    the trained sibling); dev-held-out variants to `devreal`; test-held-out variants to
    `testreal`. Held-out variants are never trained on."""
    out: list[RealTask] = []
    for v, (fam, split) in VARIANTS.items():
        name = f"post_{v}"
        common = dict(row=ROW, licence=LICENCE, url=URL, real=False, soft=True,
                      per_example_options=True)
        if split == "train":
            out.append(RealTask(name=name, load=_loader(v, SEED_TRAIN, MAX_PER_TASK),
                                force_split="train", family=name, min_quota=MAX_PER_TASK,
                                notes=f"exact posterior, {fam} family, variant {v}; trained",
                                **common))
            out.append(RealTask(name=f"{name}_eval", load=_loader(v, SEED_TWIN, MAX_PER_TWIN),
                                force_split="devreal", family=name, min_quota=MAX_PER_TWIN,
                                notes=f"in-structure twin of {name} (fresh seed)", **common))
        else:
            seed = SEED_DEV if split == "devreal" else SEED_TEST
            out.append(RealTask(name=name, load=_loader(v, seed, MAX_PER_HELDOUT),
                                force_split=split, family=name, min_quota=MAX_PER_HELDOUT,
                                notes=f"exact posterior, {fam} family, variant {v}; "
                                      f"held out to {split}, NEVER trained on", **common))
    return out
