"""Row 42 -- multi-hop and ranking (domain 20).

The two shapes nothing else in the corpus has, built as **rungs** rather than as more
examples of a shape that already fails.

**Ranking.** An earlier model's rule-transfer report puts the held-out `ranking` family at
0.2667 -- chance, and the worst result in the sweep. Domain 2 diagnosed it exactly: *its
form is different -- compare a field across records rather than evaluate a predicate on
one*. Every trained rule in row 33 evaluates a predicate on a single record, so `ranking`
had no trained parts at all, and adding more ranking rules to row 33 would not have
changed that. So the missing rungs are built here:

    rank_pairwise   of these two records, which ranks higher on X          (trained, 2 options)
    rank_extremum   which of these N ranks highest / lowest / second       (trained, 3-16 options)
    rank_ordering   which of these orderings is correct                    HELD OUT, testreal

`test_relational_source.py` asserts that `rank_ordering` uses no comparison primitive
that `rank_pairwise` and `rank_extremum` do not both already train. Five primitives --
`field`, `ratio`, `mixed_units`, `deviation`, `tiebreak` -- and the comparison rule is
written into the question's `instructions`, the way `rules.py` writes its rule into the
criteria.

**Multi-hop.** Every other domain answers from one record or one passage; nothing asks
the model to follow a reference. Here the state is a universe of five levels of linked
records -- purchase order -> supplier -> certification body -> registry office ->
standards council, and two more chains like it -- and the question names a root and a
number of steps.

    hops 1          one lookup; the trained control                        (trained)
    hops 2, 3       two and three lookups                                  (trained)
    hops 4          four lookups                                           HELD OUT, testreal

The whole universe is rendered whatever the hop count, so a 4-hop question and a 1-hop
question differ **only in the question**. Hop count is the structure being held out, and
nothing else moves with it. It is in `meta.hops`, so a per-hop-count reading needs no
change to the gates.

**The chain is load-bearing by construction, not by hope.** Every stop-early answer is
put in the option list, and it is right exactly as often as any other option -- so a
reader who follows one reference and stops scores **chance**, and so does a reader who
computes the stop-early answer and strikes it out. This used to aim at **zero** (path
marks pairwise distinct; `sameend` wired to agree after one step exactly when the answer
was "no"), and zero is the same shortcut read backwards: the inverted one-hop reader
scored 1.000 on `sameend` and "strike the root's and first hop's marks" 0.87-0.89 on
`lookup`, held-out four hops included (measured by a shortcut audit). The
answer's record is also drawn uniformly among the records some chain reaches, so how
often a record is referenced says nothing either. `tests/test_relational_source.py`
measures both readers.

**The distractors make the wrong hop plausible.** Several suppliers, several certification
bodies, several registry offices; ids are opaque (`kestrel-4471`) and share one pool
across levels, so an option cannot be placed in the chain by the look of its identifier.

Every target is derived by code from the universe. The model's contribution is surface
only -- question stems -- generated once by a one-off generation script,
validated there and pasted here as literals. Two of its seven batches were **dropped
whole** rather than repaired, which is the point of validating at all: the `sameend`
stems put `{noun}` in the wrong grammatical slot ("a chain starting at {a} ... in the
{noun}", which says the chain runs inside a shipment rather than starting at one), and
the fourteen preambles were fourteen paraphrases of "The state <verb>s its records as
...", one memorisable frame rather than fourteen. Those two are hand-written below.
`relational_` is in `PROTECTED_PREFIXES`, so the corpus enricher never rewrites a
question whose wording is part of the task.
"""

from __future__ import annotations

import collections
import hashlib
import json as _json
import random
import re
from dataclasses import dataclass, field as dc_field
from typing import Iterator

from lod import sentinel
from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/relational.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/relational.py"
ROW = 42
DOMAIN = 20

# Row 42 is new and unvalidated. Left alone the build's row budget hands it ~40,000
# questions across 46 tasks; the caps below land it at 22,080, the size budgeted for the
# domain. The `_eval` twins used to be hashed, and the hash sent 15 of 19 to `train` and 4
# to `testreal` and none to `devreal`: the row had no devreal at all, `rank_pairwise` had
# no evaluated draw anywhere, and four *trained* structures sat in testreal beside the
# held-out ones. The twins are now forced to `devreal` at a smaller cap, and the train
# tasks take up the difference so the row keeps its size. With four trained cells moved to
# dev (`DEV_HOP_CELLS`, `DEV_RANK_CELLS`) the sum is 15 * 940 + 15 * 150 + 4 * 480 + 8 *
# 480 = 22,110 -- the 22,080 it was, with 14,100 training questions rather than 15,390.
MAX_PER_TASK = 480            # held-out (testreal and dev-held) tasks, and the default
MAX_PER_TASK_TRAIN = 940
MAX_PER_TASK_DEV = 150

SHAPES = ("json", "table", "prose")

# `ship_v4.sh` trains at `--max-state-tokens 2304` and the packer truncates a long state
# from the *tail*, which in a chain is the level the answer sits on. 2.4 characters per
# token is the lowest ratio measured over every task and every shape with
# `Qwen/Qwen3-0.6B-Base`, so this is a pessimistic token count for the whole state and
# an instance over it is dropped rather than truncated. A first cut at 3.0 chars/token
# left 2 states in 986 over budget.
MAX_STATE_CHARS = int(2304 * 2.4)

TRAINED_HOPS = (1, 2, 3)
HELDOUT_HOPS = (4,)

COMPARATORS = ("field", "ratio", "mixed_units", "deviation", "tiebreak")
TRAINED_RANK_FAMILIES = ("rank_pairwise", "rank_extremum")
HELDOUT_RANK_FAMILIES = ("rank_ordering",)

# The dev split's held-out structures: cells of the trained grids, never trained and
# never tested, which checkpoint selection and the temperature fit read. Test holds out a
# whole *axis value* (four hops, full ordering) and there is no second axis value to hold
# out without holding out a primitive, so dev holds out combinations instead -- a chain
# at a depth it never trains at, a ranking shape on a comparison it never trains with.
# Every value on both sides of each cell still trains: hop 2 on freight and lab, hop 3
# on supply and freight, every chain at two depths; `rank_extremum` on four comparisons,
# `rank_pairwise` on four, and `deviation` and `ratio` under the other ranking shape.
DEV_HOP_CELLS = (("supply", 2), ("lab", 3))            # (chain, hops)
DEV_RANK_CELLS = (("rank_pairwise", "ratio"), ("rank_extremum", "deviation"))
HOP_FAMILIES = ("lookup", "bridge", "sameend")
HOP_FAMILY_SHARE = {"lookup": 0.45, "bridge": 0.35, "sameend": 0.20}

# Sentinel use, for `lookup` only. The wording is drawn from `lod.sentinel`'s
# 24,804-string grammar rather than written out: a fixed wording repeated 1,402 times in
# row 39 failed the sentinel audit's max-exact-repeat bar of 50, which is the
# same memorisable-string failure an earlier model shipped with.
# An earlier build shipped `P_SENTINEL_GOLD = 0.45`, a flat prior. The sentinel option is
# the only one a reader can pick out without following anything -- it is the only option
# absent from the state and the only one carrying a description -- so a flat 0.45 handed a
# state-blind reader 0.442-0.484 against 0.250-0.280 chance on the 30 % of `lookup`
# questions that offered one. The gold share is now `1 / (options + 1)`, i.e. no likelier
# than any other option, and the offer rate is raised so the row still supplies the same
# number of target-absent questions it did before.
P_SENTINEL_OFFERED = 0.55

P_INDIRECT = 0.50          # share of instructions that name no reference field, only what it means


def _rng(seed: int, key: str) -> random.Random:
    h = hashlib.sha256(f"{seed}:{key}".encode()).digest()
    return random.Random(int.from_bytes(h[:8], "big"))


# ======================================================================================
# multi-hop: linked records
# ======================================================================================

@dataclass(frozen=True)
class Attr:
    """One field of a record. `values` non-empty means categorical."""
    name: str
    values: tuple[str, ...] = ()
    lo: int = 0
    hi: int = 0
    unit: str = ""
    label: str = ""

    @property
    def text(self) -> str:
        return self.label or self.name.replace("_", " ")

    def draw(self, rng: random.Random):
        return rng.choice(self.values) if self.values else rng.randint(self.lo, self.hi)


@dataclass(frozen=True)
class Step:
    field: str      # the reference field carried by the record at the level before it
    gloss: str      # what the reference means, with no field name in it


@dataclass(frozen=True)
class Chain:
    name: str
    levels: tuple[str, ...]           # noun per level
    groups: tuple[str, ...]           # the group heading each level gets in the state
    steps: tuple[Step, ...]           # len(levels) - 1
    marks: tuple[Attr, ...]           # carried by every record at every level
    extras: tuple[tuple[Attr, ...], ...]   # per-level distractor field pools


def _mark(name: str, label: str, prefix: str, words: tuple[str, ...]) -> Attr:
    return Attr(name, tuple(f"{prefix}-{w}" for w in words), label=label)


_M1 = ("adze", "brill", "croft", "dunlin", "esker", "fell", "garth", "haugh",
       "inver", "keld", "linn", "moor", "ness", "ogham", "pike", "quoin")
_M2 = ("ash", "bole", "cairn", "delve", "eyot", "flint", "gill", "holt",
       "ing", "kyle", "lade", "mere", "nab", "oxbow", "pell", "rill")

CHAINS: tuple[Chain, ...] = (
    Chain(
        "supply",
        ("purchase order", "supplier", "certification body", "registry office",
         "standards council"),
        ("purchase_orders", "suppliers", "certification_bodies", "registry_offices",
         "standards_councils"),
        (Step("fulfilled_by", "the supplier that fulfils it"),
         Step("audited_by", "the certification body that audits it"),
         Step("listed_by", "the registry office that lists it"),
         Step("overseen_by", "the standards council that oversees it")),
        (_mark("oversight_region", "oversight region", "reg", _M1),
         _mark("escalation_tier", "escalation tier", "esc", _M2)),
        (
            (Attr("line_count", lo=1, hi=24), Attr("currency", ("eur", "gbp", "usd", "sek")),
             Attr("net_days", lo=7, hi=90), Attr("raised_by", ("plant", "central", "field")),
             Attr("revision", lo=0, hi=6)),
            (Attr("staff_headcount", lo=6, hi=900), Attr("sector", ("castings", "polymers", "fasteners", "coatings")),
             Attr("open_claims", lo=0, hi=11), Attr("site_count", lo=1, hi=14),
             Attr("payment_state", ("current", "in_arrears", "on_hold"))),
            (Attr("audits_per_year", lo=1, hi=12), Attr("scope", ("product", "process", "system")),
             Attr("assessor_count", lo=2, hi=60), Attr("lapsed_files", lo=0, hi=9),
             Attr("scheme", ("iso_like", "sector_own", "state_run"))),
            (Attr("filings_held", lo=40, hi=9000), Attr("access", ("public", "on_request", "restricted")),
             Attr("backlog_days", lo=0, hi=180), Attr("office_grade", ("primary", "branch", "satellite")),
             Attr("clerk_count", lo=1, hi=40)),
            (Attr("member_states", lo=2, hi=40), Attr("meets", ("monthly", "quarterly", "twice_yearly")),
             Attr("standards_owned", lo=3, hi=220), Attr("chair_term_years", lo=1, hi=6),
             Attr("funding", ("levy", "subscription", "state"))),
        ),
    ),
    Chain(
        "freight",
        ("shipment", "carrier", "depot", "maintenance contractor", "insurer"),
        ("shipments", "carriers", "depots", "maintenance_contractors", "insurers"),
        (Step("carried_by", "the carrier that moves it"),
         Step("based_at", "the depot the carrier works out of"),
         Step("serviced_by", "the maintenance contractor that services the depot"),
         Step("insured_by", "the insurer that covers the contractor")),
        (_mark("risk_band", "risk band", "risk", _M2),
         _mark("duty_zone", "duty zone", "duty", _M1)),
        (
            (Attr("parcel_count", lo=1, hi=40), Attr("service_level", ("economy", "standard", "express")),
             Attr("transit_days", lo=1, hi=18), Attr("packaging", ("crate", "pallet", "sack", "drum")),
             Attr("declared_kg", lo=2, hi=900)),
            (Attr("fleet_size", lo=4, hi=700), Attr("licence_class", ("national", "regional", "cabotage")),
             Attr("driver_count", lo=6, hi=1400), Attr("night_running", ("nights", "days_only")),
             Attr("mode", ("road", "rail_road", "coastal"))),
            (Attr("bay_count", lo=2, hi=60), Attr("surface", ("concrete", "asphalt", "gravel")),
             Attr("gate_hours", lo=8, hi=24), Attr("yard_hectares", lo=1, hi=30),
             Attr("chill_store", ("chilled", "ambient"))),
            (Attr("engineer_count", lo=2, hi=120), Attr("callout_hours", lo=1, hi=24),
             Attr("rota", ("day", "double_day", "continental")), Attr("van_count", lo=1, hi=45),
             Attr("parts_store", ("on_site", "shared", "none"))),
            (Attr("book_years", lo=2, hi=90), Attr("treaty", ("proportional", "excess_of_loss", "facultative")),
             Attr("branch_count", lo=1, hi=50), Attr("open_files", lo=0, hi=400),
             Attr("rating_house", ("north", "meridian", "crestwell"))),
        ),
    ),
    Chain(
        "lab",
        ("sample", "laboratory", "analyser", "calibration provider", "accreditation body"),
        ("samples", "laboratories", "analysers", "calibration_providers",
         "accreditation_bodies"),
        (Step("processed_by", "the laboratory that processes it"),
         Step("run_on", "the analyser it is run on"),
         Step("calibrated_by", "the calibration provider that calibrates the analyser"),
         Step("accredited_by", "the accreditation body that accredits the provider")),
        (_mark("quality_grade", "quality grade", "grade", _M1),
         _mark("review_cycle", "review cycle", "cyc", _M2)),
        (
            (Attr("aliquots", lo=1, hi=12), Attr("matrix", ("serum", "soil", "effluent", "feed")),
             Attr("hold_hours", lo=1, hi=96), Attr("chain_of_custody", ("sealed", "open", "witnessed")),
             Attr("volume_ml", lo=2, hi=500)),
            (Attr("bench_count", lo=2, hi=40), Attr("shift_pattern", ("day", "two_shift", "round_clock")),
             Attr("analyst_count", lo=3, hi=180), Attr("turnaround_hours", lo=2, hi=120),
             Attr("discipline", ("chemistry", "microbiology", "materials"))),
            (Attr("channels", lo=1, hi=48), Attr("age_years", lo=0, hi=18),
             Attr("throughput_per_hour", lo=4, hi=600), Attr("detector", ("optical", "thermal", "mass")),
             Attr("service_state", ("in_service", "standby", "loan"))),
            (Attr("standards_held", lo=2, hi=90), Attr("visit_weeks", lo=2, hi=52),
             Attr("engineer_count", lo=1, hi=60), Attr("traceable_to", ("national", "regional", "in_house")),
             Attr("mobile_rigs", lo=0, hi=12)),
            (Attr("scope_count", lo=3, hi=300), Attr("assessment_years", lo=1, hi=5),
             Attr("signatory", ("full", "associate", "observer")), Attr("panel_size", lo=3, hi=40),
             Attr("published_register", ("public", "withheld"))),
        ),
    ),
)

CHAINS_BY_NAME = {c.name: c for c in CHAINS}

# One opaque-id pool for every level. A reader must not be able to place a record in the
# chain by the look of its identifier -- `SUP-3` against `CERT-3` would make every
# `bridge` distractor from the wrong level free to discard.
ID_WORDS = ("alder", "brant", "corve", "dunmow", "elver", "fenwick", "girvan", "hollin",
            "irby", "jarrow", "kestrel", "larch", "marlow", "nyland", "orwell", "pendle",
            "quarme", "rowan", "sarn", "tarnock", "ulla", "veryan", "wray", "yarrow",
            "axholme", "breen", "cotham", "dovey", "ember", "flixton", "glaven",
            "hebble", "ilam", "jurby", "kelso", "lugg")


def _unique_ids(rng: random.Random, n: int) -> list[str]:
    out, seen = [], set()
    while len(out) < n:
        word = rng.choice(ID_WORDS)
        ref = f"{word}-{rng.randrange(1000, 9999)}"
        if ref not in seen:
            seen.add(ref)
            out.append(ref)
    return out


@dataclass
class Universe:
    chain: Chain
    width: tuple[int, ...]                     # records per level
    recs: list[list[dict]] = dc_field(default_factory=list)

    @property
    def n_levels(self) -> int:
        return len(self.chain.levels)

    def all_records(self) -> list[tuple[int, dict]]:
        return [(lv, r) for lv, group in enumerate(self.recs) for r in group]

    def by_id(self, rid: str) -> tuple[int, dict]:
        for lv, group in enumerate(self.recs):
            for r in group:
                if r["record_id"] == rid:
                    return lv, r
        raise KeyError(rid)


def make_universe(chain: Chain, rng: random.Random, width_lo: int = 3,
                  width_hi: int = 5, n_extra: int = 3) -> Universe:
    """Records for every level, ids drawn from one pool, extras as distractors.

    Marks and references are left unset: each family assigns them, because what makes a
    chain load-bearing is exactly which values sit where, and that is family-specific.
    """
    width = tuple(rng.randint(width_lo, width_hi) for _ in chain.levels)
    ids = _unique_ids(rng, sum(width))
    uni = Universe(chain, width)
    cut = 0
    for lv, n in enumerate(width):
        group = []
        pool = list(chain.extras[lv])
        rng.shuffle(pool)
        chosen = pool[:n_extra]
        for _ in range(n):
            rec = {"record_id": ids[cut]}
            cut += 1
            for a in chosen:
                rec[a.name] = a.draw(rng)
            group.append(rec)
        uni.recs.append(group)
    return uni


def wire(uni: Universe, rng: random.Random, paths: list[list[int]]) -> None:
    """Set every reference field. `paths` are index sequences that must be honoured.

    A path is a list of record *indices*, one per level, that the references have to
    follow; everything not on a path points somewhere random at the next level.
    """
    chain = uni.chain
    forced: dict[tuple[int, int], int] = {}
    for path in paths:
        for lv in range(len(path) - 1):
            forced[(lv, path[lv])] = path[lv + 1]
    for lv, step in enumerate(chain.steps):
        for i, rec in enumerate(uni.recs[lv]):
            nxt = forced.get((lv, i))
            if nxt is None:
                nxt = rng.randrange(len(uni.recs[lv + 1]))
            rec[step.field] = uni.recs[lv + 1][nxt]["record_id"]


def wire_free(uni: Universe, rng: random.Random) -> None:
    """Every reference field, with no path forced through it.

    This used to force a path and fill the rest at random, so the record a forced chain
    ends on carried one guaranteed reference *plus* its share of the random ones, and
    each of its siblings only the random share. "Pick the option whose record is
    referenced most" found the `bridge` answer 0.60-0.66 of the time against 0.14
    chance, and the `lookup` answer 0.48-0.50 against 0.26, at every hop count including
    the held-out four (measured by a shortcut audit) -- one glance at the level
    before the end, no chain followed. Here the references are drawn with nothing forced, and
    `_free_path` then picks the answer *uniformly among the records some chain reaches*,
    so how often a record is referenced says nothing about which reachable record is the
    answer.

    The records that chains from the first level pass through point at distinct records
    on the next level for as long as the widths allow, and everything else points at
    random. Left fully random, chains merge and the set of records a chain can reach
    shrinks by about a third per level, which leaves a four-hop answer only one or two
    reachable siblings to hide among.
    """
    reach = set(range(len(uni.recs[0])))
    for lv, step in enumerate(uni.chain.steps):
        src, dst = uni.recs[lv], uni.recs[lv + 1]
        live = sorted(reach)
        rng.shuffle(live)
        free = list(range(len(dst)))
        rng.shuffle(free)
        tgt = {i: (free[j] if j < len(free) else rng.randrange(len(dst)))
               for j, i in enumerate(live)}
        for i in range(len(src)):
            if i not in tgt:
                tgt[i] = rng.randrange(len(dst))
        for i, rec in enumerate(src):
            rec[step.field] = dst[tgt[i]]["record_id"]
        reach = {tgt[i] for i in live}


def _reach(uni: Universe, hops: int) -> dict[int, list[int]]:
    """{index at level `hops`: [indices of the first-level records whose chain ends there]}."""
    pos = [{r["record_id"]: i for i, r in enumerate(g)} for g in uni.recs]
    out: dict[int, list[int]] = collections.defaultdict(list)
    for r0, rec in enumerate(uni.recs[0]):
        i = r0
        for k in range(hops):
            i = pos[k + 1][rec[uni.chain.steps[k].field]]
            rec = uni.recs[k + 1][i]
        out[i].append(r0)
    return out


def _free_path(uni: Universe, rng: random.Random, hops: int):
    """Wire freely, draw the answer uniformly among the end-level records some chain
    reaches, and the root uniformly among the roots that reach it.

    Returns (path, the other reachable end records, the unreachable end records). Only
    the reachable ones may stand as distractors: an unreachable record is one nothing on
    the level before points at, which is one glance, not a chain.
    """
    wire_free(uni, rng)
    reach = _reach(uni, hops)
    ends = sorted(reach)
    gold_i = rng.choice(ends)
    root_i = rng.choice(reach[gold_i])
    path = follow(uni, uni.recs[0][root_i]["record_id"], hops)
    live = [uni.recs[hops][i] for i in ends if i != gold_i]
    dead = [r for i, r in enumerate(uni.recs[hops]) if i not in reach]
    return path, live, dead


def follow(uni: Universe, root_id: str, hops: int) -> list[dict]:
    """The record sequence a reader gets by taking `hops` references, exactly."""
    lv, rec = uni.by_id(root_id)
    out = [rec]
    for k in range(hops):
        nxt_id = rec[uni.chain.steps[lv + k].field]
        _, rec = uni.by_id(nxt_id)
        out.append(rec)
    return out


def assign_marks(uni: Universe, rng: random.Random) -> None:
    """Every record gets every mark. Families overwrite the ones that carry the label."""
    for _lv, rec in uni.all_records():
        for m in uni.chain.marks:
            rec[m.name] = rng.choice(m.values)


# ---- rendering ---------------------------------------------------------------------
# Three shapes from one universe: identical values, identical question, identical target.

# Hand-written. The generation script asked for these too and its batch was
# rejected by the diversity check it carries: fourteen sets whose JSON sentence began
# "The state <verb>s its records as ..." is one frame repeated, and one frame repeated
# 22,080 times is the memorisable-surface failure the sentinel grammar exists to avoid.
PREAMBLES = (
    {"json": "The records below are grouped by what they are.",
     "table": "The tables below list the records, grouped by what they are.",
     "prose": "The notes below describe each record in turn."},
    {"json": "Here is the current extract, one group per record type.",
     "table": "Here is the current extract, one table per record type.",
     "prose": "Here is the current extract, written out record by record."},
    {"json": "Extract from the register, grouped by record type.",
     "table": "Extract from the register, tabulated by record type.",
     "prose": "Extract from the register, set out in sentences."},
    {"json": "The following groups hold every record on file.",
     "table": "The following tables hold every record on file.",
     "prose": "The following paragraphs cover every record on file."},
    {"json": "Below is the data as it was exported, grouped by type.",
     "table": "Below is the data as it was exported, laid out as tables.",
     "prose": "Below is the data as it was exported, written out longhand."},
    {"json": "This is what the register holds today, by record type.",
     "table": "This is what the register holds today, one table per type.",
     "prose": "This is what the register holds today, described in order."},
    {"json": "Record groups follow. Nothing has been filtered out.",
     "table": "Record tables follow. Nothing has been filtered out.",
     "prose": "The records follow. Nothing has been filtered out."},
    {"json": "The dump below is complete for the accounts in question.",
     "table": "The tables below are complete for the accounts in question.",
     "prose": "The description below is complete for the accounts in question."},
)

# The first six of each tuple below are hand-written; the rest come from
# deepseek/deepseek-v4.1-flash via a one-off generation script, pasted verbatim.
# They carry no fact and no target -- every id, field and value is drawn by code.
LOOKUP_STEMS = (
    'Start at {noun} {rid} and take all {h} steps. What {mark} is on the record you finish on?',
    'Beginning at {noun} {rid}, follow all {h} steps through. Which {mark} does the record you end at carry?',
    'Take {noun} {rid} and work through all {h} steps, in order. What is the {mark} of the record you land on?',
    'From {noun} {rid}, follow the chain through all {h} steps. Which {mark} is recorded against the final record?',
    'Walk out from {noun} {rid}, taking all {h} steps. What {mark} does the last record in that chain hold?',
    'Trace {noun} {rid} through all {h} steps. Which {mark} is shown on the record at the end of the trace?',
    'After all {h} steps along the chain that begins with the {noun} identified by {rid}, what is the value of {mark} on the record reached?',
    'Starting from the {noun} with identifier {rid} and following the full set of {h} steps, what is the value of {mark} for the resulting record?',
    'What value does {mark} hold on the record arrived at after traversing all {h} steps beginning at the {noun} whose identifier is {rid}?',
    'Upon reaching the record after all {h} steps from the {noun} identified by {rid}, what is the value of {mark}?',
    'Having followed the chain for all {h} steps from the {noun} with identifier {rid}, what is the {mark} value on the final record?',
    'What is the value of {mark} on the record you get to after completing all {h} steps from the {noun} identified by {rid}?',
    'From the {noun} whose identifier is {rid}, after all {h} steps, what does {mark} equal on the record reached?',
    'Starting at the {noun} with identifier {rid}, after taking all {h} steps, what is the value of {mark} on the record you land on?',
    'What value is carried by {mark} on the record obtained after taking all {h} steps of the chain beginning at the {noun} identified by {rid}?',
    'At the end of all {h} steps from the {noun} whose identifier is {rid}, what value does the record have for {mark}?',
    'When you have taken all {h} steps from the {noun} identified by {rid}, what is the value of {mark} on the record you reach?',
    "After completing the chain's {h} steps from the {noun} with identifier {rid}, what is the value associated with {mark} on the landing record?",
    'Beginning with the {noun} whose identifier is {rid}, after following all {h} steps, what is the value of {mark} on the record you arrive at?',
    'What is the value of {mark} on the record reached by taking every step in the chain of {h} steps that starts at the {noun} identified by {rid}?',
)

BRIDGE_STEMS = (
    'Start at {noun} {rid} and take all {h} steps. Which record do you finish on?',
    'Beginning at {noun} {rid}, follow all {h} steps through. Which record do you end at?',
    'Take {noun} {rid} and work through all {h} steps, in order. Which record do you land on?',
    'From {noun} {rid}, follow the chain through all {h} steps. Which record is at the end of it?',
    'Walk out from {noun} {rid}, taking all {h} steps. Which record is the last one in that chain?',
    'Trace {noun} {rid} through all {h} steps. Which record does the trace finish on?',
    'If you start at a {noun} with identifier {rid} and follow all {h} steps of the chain, which record do you land on?',
    'Starting from the {noun} whose identifier is {rid}, after all {h} steps along the chain, which record is reached?',
    'Which record do you arrive at after you take all {h} steps of the chain beginning at the {noun} identified by {rid}?',
    'When you begin at a {noun} identified by {rid} and traverse all {h} steps of the chain, which record do you end up on?',
    'After moving through all {h} steps of the chain that begins at the {noun} with identifier {rid}, which record do you land on?',
    'From the {noun} bearing identifier {rid}, following the chain through all {h} steps, what record do you finish on?',
    'What record results from taking all {h} steps of the chain that starts at the {noun} whose identifier is {rid}?',
    'If the chain starts at the {noun} with identifier {rid}, which record do you reach after all {h} steps?',
    'What record do you land on after going through all {h} steps of the chain that begins at the {noun} with identifier {rid}?',
    'Which record is the endpoint when you start at the {noun} identified by {rid} and complete all {h} steps of the chain?',
    'Upon starting at the {noun} whose identifier is {rid} and following every step in the chain through all {h} steps, which record do you land on?',
    "After you take the chain's full {h} steps from the {noun} with identifier {rid}, which record do you come to?",
    'Starting at the {noun} whose identifier is {rid}, which record do you arrive at after all {h} steps along the chain?',
    'If you begin with the {noun} identified by {rid} and trace the chain for all {h} steps, which record do you land on?',
)

# Hand-written: the model's batch for this family is the one `stem_ok` now rejects.
SAMEEND_STEMS = (
    "After all {h} steps, do {noun} {a} and {noun} {b} finish on records with the same {mark}?",
    "Follow both {noun} {a} and {noun} {b} through all {h} steps. Do the two records you end at share {art} {mark}?",
    "Take {noun} {a} and {noun} {b} through all {h} steps each. Is the {mark} the same at both ends?",
    "Do the chains from {noun} {a} and {noun} {b}, taken all {h} steps, end on the same {mark}?",
    "Walk {noun} {a} and {noun} {b} out through all {h} steps. Do both end on records carrying one and the same {mark}?",
)


_SINGULAR = ((re.compile(r"\ball 1 steps\b"), "the single step"),
             (re.compile(r"\b1 steps\b"), "one step"))


def _article(word: str) -> str:
    """"a escalation tier" shipped 126 times in an earlier build because the hand-written
    `sameend` stem hard-coded the article. Four of the six mark names begin with a
    consonant and two do not, so the article is drawn from the noun rather than written
    into the stem."""
    return "an" if word[:1].lower() in "aeiou" else "a"


def _fill_hop(stem: str, hops: int, **kw) -> str:
    out = stem.format(h=hops, **kw)
    for pat, rep in _SINGULAR:
        out = pat.sub(rep, out)
    return out


def said_hops(text: str) -> int | None:
    """The hop count a filled question states, or None if it states none."""
    m = re.search(r"\b(\d+) steps\b", text)
    if m:
        return int(m.group(1))
    if re.search(r"\bthe single step\b|\bone step\b", text):
        return 1
    return None


# ---- the phrasing bank ---------------------------------------------------------------
# Template ids are `d20.<family>` and are specified in lod/assets/phrasing_specs/d20.json.
# The stem drawn from the literal tuples below is passed as the template, so an empty bank
# returns it unchanged and the rng stream -- and so every corpus built before the bank
# existed -- is untouched. A bank phrasing is used only if, once filled, it still asks the
# same thing: every slot value is in the text, and for a chain the stated hop count is
# the real one. Otherwise the drawn stem is used; a phrasing is never repaired.

_BANK = None


def _bank():
    global _BANK
    if _BANK is None:
        from lod.phrasings import PhrasingBank
        _BANK = PhrasingBank.load()
    return _BANK


def worded(family: str, stem: str, key: str, fill, valid) -> str:
    cand = _bank().pick(f"d20.{family}", stem, key)
    if cand != stem:
        try:
            text = fill(cand)
        except (KeyError, IndexError, ValueError):
            text = None
        if text is not None and valid(text):
            return text
    return fill(stem)


def hop_text(stem: str, hops: int, family: str | None = None, **kw) -> str:
    """Fill a stem, then repair the singular. Every stem writes "{h} steps", so the
    one-hop control would read "take all 1 steps" -- and the control has to read like a
    question somebody would ask or it is not a control."""
    if family is None:
        return _fill_hop(stem, hops, **kw)
    key = f"{family}:{hops}:" + ":".join(str(kw[k]) for k in sorted(kw))
    return worded(
        family, stem, key, lambda st: _fill_hop(st, hops, **kw),
        lambda t: (said_hops(t) == hops and "{" not in t and t.rstrip().endswith("?")
                   and all(str(v) in t for k, v in kw.items() if k != "art")))


def _humanise(field: str) -> str:
    return field.replace("_", " ")


def _fields_of(rec: dict) -> list[str]:
    return [k for k in rec if k != "record_id"]


def render(uni: Universe, shape: str, rng: random.Random) -> str:
    pre = rng.choice(PREAMBLES)[shape]
    chain = uni.chain
    if shape == "json":
        body = _json.dumps({g: uni.recs[lv] for lv, g in enumerate(chain.groups)},
                           indent=2)
    elif shape == "table":
        blocks = []
        for lv, g in enumerate(chain.groups):
            group = uni.recs[lv]
            cols = ["record_id"] + _fields_of(group[0])
            widths = [max(len(c), max(len(str(r[c])) for r in group)) for c in cols]
            head = "  ".join(c.ljust(w) for c, w in zip(cols, widths)).rstrip()
            rows = ["  ".join(str(r[c]).ljust(w) for c, w in zip(cols, widths)).rstrip()
                    for r in group]
            blocks.append(f"{_humanise(g)}\n  " + "\n  ".join([head] + rows))
        body = "\n\n".join(blocks)
    else:
        lines = []
        for lv, noun in enumerate(chain.levels):
            for rec in uni.recs[lv]:
                clauses = [f"{_humanise(k)} {rec[k]}" for k in _fields_of(rec)]
                lines.append(f"The {noun} {rec['record_id']} has "
                             + "; ".join(clauses) + ".")
        body = "\n".join(lines)
    return f"{pre}\n\n{body}"


def steps_block(chain: Chain, hops: int, shape: str, mode: str) -> str:
    """What counts as following a reference, written into the criteria.

    `direct` names the reference field the way the state presents it; `indirect` names
    only what the reference means, so locating it is part of the task. Half and half, the
    way `records.field_ref` splits them for row 33.
    """
    out = []
    for k in range(hops):
        st = chain.steps[k]
        here = chain.levels[k]
        if mode == "indirect":
            out.append(f"  step {k + 1}: from the {here} you are on, go to {st.gloss};")
        elif shape == "prose":
            out.append(f"  step {k + 1}: from the {here} you are on, go to the record "
                       f"named under {_humanise(st.field)};")
        else:
            out.append(f"  step {k + 1}: from the {here} you are on, go to the record "
                       f"whose id is in `{st.field}`;")
    out[-1] = out[-1][:-1] + "."
    return ("Every record names the next one along. Take the steps below strictly in "
            "order, one at a time, and do not skip one:\n" + "\n".join(out))


# ---- the three multi-hop families ---------------------------------------------------
# Each returns (question, instructions, options, descriptions, gold, meta) or None.

def _shuffle(rng: random.Random, options, descs, gold: int):
    order = list(range(len(options)))
    rng.shuffle(order)
    return ([options[i] for i in order], [descs[i] for i in order], order.index(gold))


LOOKUP_COPIES = (2, 2, 3)     # how often each option value is printed in the whole state


def _balance_option_counts(uni: Universe, rng: random.Random, mark: Attr, hops: int,
                           path: list[dict], sibs: list[dict], opts: list[str]) -> bool:
    """Make how often, and where, an option is printed say nothing about which it is.

    `plant` puts each stop-early value on a path record *and* on an end-level sibling, so
    it was printed at least twice, while the answer and the spare distractors were printed
    once plus whatever the random fill added. "Pick the option printed least often"
    scored 0.481-0.500 on `lookup` at 2-4 hops against 0.261 chance (domain-20 audit,
    before this fix) without following a single reference. Balancing the counts alone
    moved the leak rather than closing it: the stop-early values are the only ones
    guaranteed to sit on a level *before* the end, so "drop every option printed before
    the end level" then scored 0.341-0.445.

    So every off-path record outside the end level is refilled here. Each option value is
    printed a number of times drawn from `LOOKUP_COPIES` whatever its role, at least once
    on a level before the end (the stop-early values already are, on the path), and every
    other off-path record takes a value that is not an option. The path and the end level
    -- everything the label depends on -- are left exactly as they were.
    """
    on_path = {id(r) for r in path}
    fixed = on_path | {id(r) for r in sibs}
    free = [(lv, r) for lv, r in uni.all_records() if id(r) not in fixed and lv != hops]
    early = [r for lv, r in free if lv < hops]
    late = [r for lv, r in free if lv > hops]
    rest = [v for v in mark.values if v not in opts]
    have = collections.Counter(r[mark.name] for r in path + sibs)
    early_have = {r[mark.name] for r in path[:hops]}
    rng.shuffle(early)
    first: list[str] = []
    extra: list[str] = []
    for o in opts:
        need_early = o not in early_have
        want = max(rng.choice(LOOKUP_COPIES), have[o] + need_early)
        n_new = want - have[o]
        if need_early:
            first.append(o)
            n_new -= 1
        extra += [o] * n_new
    if len(first) > len(early) or len(first) + len(extra) > len(free) or not rest:
        return False
    for rec, v in zip(early, first):
        rec[mark.name] = v
    spare = early[len(first):] + late
    rng.shuffle(spare)
    for rec, v in zip(spare, extra):
        rec[mark.name] = v
    for rec in spare[len(extra):]:
        rec[mark.name] = rng.choice(rest)
    return True


def _f_lookup(uni: Universe, rng: random.Random, hops: int, heldout: bool):
    """The mark on the record at the end of the chain.

    Three things are arranged rather than hoped for. The stop-early marks -- the root's
    own, and the one a step along -- are put in the option list, so a reader who stops
    early is offered the answer that stopping gives. Every option is *also* carried by a
    record at the level the chain ends on, so knowing which group the answer lives in cuts
    nothing out of the field -- without that, a 4-hop question hands away two of its three
    options to anybody who can count. And the stop-early marks are **not always wrong**:
    each is the answer too, one time in k, because the end record happens to carry the
    same mark.

    That last one is a change. They used to be drawn pairwise distinct, so a reader who
    stopped early scored zero -- and a reader who computed the one-hop mark and *struck it
    out* scored far above chance: with three options, the root's mark, the one-hop mark
    and the answer, striking the two found the answer every time. "Never the root's or
    the first hop's mark" found 0.87-0.89 of `lookup` answers at 2-4 hops against 0.26
    chance, after one step of a four-step chain (measured by a shortcut audit).
    Now an option being a stop-early mark says nothing about whether it is the answer.
    The answer's record is drawn uniformly among the records some chain reaches
    (`_free_path`), and only reachable records carry the distractors.
    """
    chain = uni.chain
    path, live, dead = _free_path(uni, rng, hops)
    if len(live) < 2:
        return None
    mark = rng.choice(chain.marks)
    # The sentinel either replaces the answer or joins the field, and the option count
    # must not say which: an earlier build listed k options when the sentinel was the
    # answer and k + 1 when it was a decoy, so "three options, one of them the sentinel"
    # meant the sentinel was right. Both now list k + 1 -- the answer's slot goes to one
    # more distractor -- which needs k real distractors on hand.
    offer = rng.random() < P_SENTINEL_OFFERED
    k = min(rng.choice((3, 3, 4, 4, 5, 6, 8)), len(live) + (0 if offer else 1))
    m = k + offer                                  # options listed
    # which stop-early marks are offered: the root's and the first hop's, or one of them
    # when the field has room for only one beside the answer
    plant_js = list(range(min(2, hops)))
    rng.shuffle(plant_js)
    plant_js = sorted(plant_js[:k - 1])
    # with probability 1/m for each offered stop-early mark, the end record carries it
    u = rng.random()
    same_as = plant_js[int(u * m)] if u < len(plant_js) / m else None

    pool = list(mark.values)
    rng.shuffle(pool)
    path_vals = pool[:hops + 1]
    if same_as is not None:
        path_vals[hops] = path_vals[same_as]
    gold_val = path_vals[hops]
    for rec, v in zip(path, path_vals):
        rec[mark.name] = v

    # `plant` is what makes the stop-early answers plausible: the root's own mark, and
    # the mark one step along, are carried by (reachable) siblings of the final record.
    rng.shuffle(live)
    rng.shuffle(dead)
    sibs = live + dead
    plant = [path_vals[j] for j in plant_js if j != same_as]
    spare = list(pool[hops + 1:])
    sib_vals = plant + [spare.pop() for _ in range(len(sibs) - len(plant))]
    for rec, v in zip(sibs, sib_vals):
        rec[mark.name] = v
    path_ids = {r["record_id"] for r in path}
    for lv, rec in uni.all_records():
        if lv == hops or rec["record_id"] in path_ids:
            continue
        rec[mark.name] = rng.choice(mark.values)

    wrong = sib_vals[:k - 1]
    if (len(set(sib_vals[:k])) != len(sib_vals[:k]) or gold_val in sib_vals[:k]
            or any(p not in wrong for p in plant)):
        return None

    options = list(wrong) + [gold_val]
    descs: list[str | None] = [None] * len(options)
    gold = len(options) - 1
    meta_extra = {"sentinel": "absent"}
    if offer:
        key, desc = sentinel.sample(rng, split="eval" if heldout else "train")
        if rng.random() < 1.0 / m:
            # the real answer is simply not listed; one more distractor takes its slot
            options = list(sib_vals[:k]) + [key]
            descs = [None] * (len(options) - 1) + [desc]
            gold = len(options) - 1
            meta_extra = {"sentinel": "gold"}
        else:
            options.append(key)
            descs.append(desc)
            meta_extra = {"sentinel": "decoy"}
    if not _balance_option_counts(uni, rng, mark, hops, path, sibs,
                                  [o for o in options if o in mark.values]):
        return None
    options, descs, gold = _shuffle(rng, options, descs, gold)
    root = path[0]
    text = hop_text(rng.choice(LOOKUP_STEMS), hops, "lookup",
                    noun=chain.levels[0], rid=root["record_id"], mark=mark.text)
    return (text, mark, options, descs, gold,
            {"family": "lookup", "mark": mark.name, **meta_extra,
             "root": root["record_id"], "gold_record": path[hops]["record_id"],
             "stop_early": list(path_vals[:hops])})


def _f_bridge(uni: Universe, rng: random.Random, hops: int, heldout: bool):
    """Which record the chain finishes on. Ids are the options, so this is the family
    that carries high cardinality: every record in the universe is a candidate.

    The answer is drawn uniformly among the end-level records some chain reaches, and
    only those stand beside it from the end level (`_free_path`): with a forced path, the
    most-referenced end-level option was the answer 0.60-0.66 of the time against 0.14
    chance."""
    chain = uni.chain
    path, live, _dead = _free_path(uni, rng, hops)
    gold_id = path[hops]["record_id"]
    # not path[0]: "which record do you finish on" is never the one you started from,
    # so the root would be a distractor anybody discards without following anything.
    stop_early = [r["record_id"] for r in path[1:hops]]
    siblings = [r["record_id"] for r in live]
    root_id = path[0]["record_id"]
    elsewhere = [r["record_id"] for lv, r in uni.all_records()
                 if lv != hops and r["record_id"] not in stop_early
                 and r["record_id"] not in (gold_id, root_id)]
    avail = len(stop_early) + len(siblings) + len(elsewhere)
    k = min(rng.choice((3, 4, 5, 6, 8, 10, 12, 16, 20, 24)), avail + 1)
    if k < 3:
        return None
    # The record one step along goes in first and unconditionally: it is the answer a
    # reader who follows one reference and stops would give, and if it is missing from
    # the field that reader scores 1/k instead of nothing.
    wrong: list[str] = list(stop_early[:1])
    rest = stop_early[1:]
    for src in (rest, siblings, elsewhere):
        rng.shuffle(src)
    # round-robin over the rest, so a high-cardinality field is not all from one level
    queues = [rest, siblings, elsewhere]
    while len(wrong) < k - 1 and any(queues):
        for qd in queues:
            if qd and len(wrong) < k - 1:
                wrong.append(qd.pop())
    if len(wrong) < k - 1 or len(set(wrong)) != len(wrong):
        return None
    options = wrong + [gold_id]
    descs = [f"the record filed under {o}" for o in options]
    options, descs, gold = _shuffle(rng, options, descs, len(options) - 1)
    text = hop_text(rng.choice(BRIDGE_STEMS), hops, "bridge",
                    noun=chain.levels[0], rid=path[0]["record_id"])
    return (text, None, options, descs, gold,
            {"family": "bridge", "root": path[0]["record_id"], "gold_record": gold_id,
             "stop_early": list(stop_early),
             "one_hop_record": path[1]["record_id"] if hops >= 1 else None})


def _f_sameend(uni: Universe, rng: random.Random, hops: int, heldout: bool):
    """Two chains: do they end on the same mark?

    The one-hop reader is denied the answer: after one step the two paths carry the same
    mark half the time and different marks half the time, *whatever the answer*.

    It used to be given the opposite of the answer instead -- same mark after one step
    exactly when the answer was `no` -- which made the one-hop reader score zero and so
    made the *inverted* one-hop reader score 1.000 at 2, 3 and the held-out 4 hops
    (measured by a shortcut audit): one step, then say the opposite. The trained
    hop counts taught that rule as well as they taught following. And a `yes` built from
    two different end records puts a repeated mark on the end level while a `no` need
    not, so "does the end level repeat a mark" agreed with the label 0.68-0.69; every
    instance now carries a repeat there.
    """
    chain = uni.chain
    if hops < 1 or min(uni.width[:hops + 1]) < 2:
        return None
    # Every universe carries both kinds of pair, whatever the answer: three chains from
    # three roots, node-disjoint up to the last level, two of which then end on one
    # record and the third elsewhere. The question names the merging pair or the other
    # one. Forcing only the named pair in (the way this used to work) wired two
    # references into one end record exactly when the answer was "same record", so how
    # the end level is referenced -- how many of its records nothing points at, whether
    # any is pointed at twice -- leaned towards the label (0.60-0.62 with a three-feature
    # lookup, measured by a shortcut audit).
    if min(uni.width[:hops]) < 3:
        return None
    a_idx = [rng.randrange(len(g)) for g in uni.recs]
    b_idx, c_idx = [], []
    for lv in range(hops):                       # three chains, node-disjoint
        others = [i for i in range(len(uni.recs[lv])) if i != a_idx[lv]]
        rng.shuffle(others)
        b_idx.append(others[0])
        c_idx.append(others[1])
    b_idx.append(a_idx[hops])                    # b ends on a's record
    c_idx.append(rng.choice([i for i in range(len(uni.recs[hops])) if i != a_idx[hops]]))
    wire(uni, rng, [a_idx, b_idx, c_idx])
    want_same = rng.random() < 0.5
    other = b_idx if want_same and rng.random() < 0.5 else c_idx
    if rng.random() < 0.5:
        a_idx, b_idx = other, a_idx
    else:
        b_idx = other

    mark = rng.choice(chain.marks)
    assign_marks(uni, rng)
    pool = list(mark.values)
    rng.shuffle(pool)
    end_a = uni.recs[hops][a_idx[hops]]
    end_b = uni.recs[hops][b_idx[hops]]
    end_a[mark.name] = pool[0]
    end_b[mark.name] = pool[0] if want_same else pool[1]
    # a repeated mark on the end level, whatever the answer: a `yes` over two different
    # end records has one by construction, so every other instance is given one too
    if not (want_same and end_a is not end_b):
        others = [r for r in uni.recs[hops] if r is not end_a and r is not end_b]
        if not others:
            return None
        tgt = rng.choice(others)
        tgt[mark.name] = rng.choice([r for r in uni.recs[hops] if r is not tgt])[mark.name]
    # after one step: agree or disagree by a coin that knows nothing of the answer
    one_a = uni.recs[1][a_idx[1]]
    one_b = uni.recs[1][b_idx[1]]
    one_same = rng.random() < 0.5
    if hops > 1 and one_a["record_id"] != one_b["record_id"]:
        one_a[mark.name] = pool[2]
        one_b[mark.name] = pool[2] if one_same else pool[3]
    options = ["no", "yes"]
    descs = [f"the two chains end on records with different {mark.text}s",
             f"the two chains end on records carrying the same {mark.text}"]
    text = hop_text(
        rng.choice(SAMEEND_STEMS), hops, "sameend", noun=chain.levels[0],
        a=uni.recs[0][a_idx[0]]["record_id"],
        b=uni.recs[0][b_idx[0]]["record_id"], mark=mark.text,
        art=_article(mark.text))
    return (text, mark, options, descs, int(want_same),
            {"family": "sameend", "mark": mark.name,
             "root": uni.recs[0][a_idx[0]]["record_id"],
             "root_b": uni.recs[0][b_idx[0]]["record_id"],
             "one_hop_same": one_same if hops > 1 else want_same})


_HOP_BUILD = {"lookup": _f_lookup, "bridge": _f_bridge, "sameend": _f_sameend}


def hop_instance(chain: Chain, hops: int, family: str, rng: random.Random,
                 heldout: bool) -> list[Example] | None:
    """One universe, one question, three renderings of the same values."""
    width_hi = 6 if family == "bridge" and rng.random() < 0.5 else 5
    uni = make_universe(chain, rng, 3, width_hi, n_extra=rng.randint(2, 4))
    assign_marks(uni, rng)
    built = _HOP_BUILD[family](uni, rng, hops, heldout)
    if built is None:
        return None
    text, mark, options, descs, gold, meta = built
    if len(set(options)) != len(options):
        return None
    out = []
    for shape in SHAPES:
        mode = "indirect" if rng.random() < P_INDIRECT else "direct"
        instr = steps_block(chain, hops, shape, mode)
        if mark is not None and meta["family"] == "lookup":
            instr += (f"\nThe answer is the {mark.text} recorded on the record you "
                      f"finish on, not on any record you pass through on the way.")
        state = render(uni, shape, rng)
        qmeta = {**meta, "hops": hops, "chain": chain.name, "shape": shape,
                 "mode": mode, "n_records": sum(uni.width)}
        if len(state) > MAX_STATE_CHARS:
            return None
        out.append(Example(state=state, questions=[Question(
            id=f"{meta['family']}_h{hops}_{shape}", question=text, options=list(options),
            target=gold, meta=qmeta, instructions=instr,
            descriptions=list(descs) if any(descs) else None)]))
    return out


# ======================================================================================
# ranking: compare a field across records
# ======================================================================================

@dataclass(frozen=True)
class RankNum:
    name: str
    lo: int
    hi: int
    unit: str = ""
    label: str = ""

    @property
    def text(self) -> str:
        return self.label or self.name.replace("_", " ")


@dataclass(frozen=True)
class RankDomain:
    name: str
    noun: str                       # "depot"
    plural: str
    names: tuple[str, ...]
    nums: tuple[RankNum, ...]
    enums: tuple[Attr, ...]
    ratio: tuple[str, str, str]     # numerator, denominator, what the quotient is called
    mixed: tuple[str, str, tuple[tuple[str, float], ...]]   # field, base unit, (unit, per base)
    deviation: tuple[str, int, int]  # field, target lo, target hi
    tiebreak: tuple[str, bool, str, bool]   # primary, primary_high_wins, secondary, sec_high_wins


RANK_DOMAINS: tuple[RankDomain, ...] = (
    RankDomain(
        "depot", "depot", "depots",
        ("Alder Cross", "Brant Fold", "Corve Wharf", "Dunmow Gate", "Elver Reach",
         "Fenwick Yard", "Girvan Head", "Hollin Bank", "Irby Quay", "Jarrow Mill",
         "Kestrel Row", "Larch End", "Marlow Bar", "Nyland Point", "Orwell Green",
         "Pendle Court"),
        (RankNum("tonnes_handled", 400, 9000, " t"),
         RankNum("cost_eur", 9000, 480000, " EUR"),
         RankNum("throughput_tph", 12, 240, " t/h"),
         RankNum("fill_pct", 34, 99, " %"),
         RankNum("incidents", 0, 9),
         RankNum("audit_score", 41, 99),
         RankNum("staff", 8, 320),
         RankNum("volume_handled", 400, 9000)),
        (Attr("shift_pattern", ("day", "two_shift", "round_clock")),
         Attr("surface", ("concrete", "asphalt", "gravel"))),
        ("cost_eur", "tonnes_handled", "handling cost per tonne"),
        ("volume_handled", "t", (("t", 1.0), ("kg", 1000.0), ("lb", 2204.62))),
        ("fill_pct", 70, 92),
        ("incidents", False, "audit_score", True),
    ),
    RankDomain(
        "vendor", "vendor", "vendors",
        ("Quarme Works", "Rowan Supply", "Sarn Components", "Tarnock Tooling",
         "Ulla Castings", "Veryan Polymers", "Wray Fasteners", "Yarrow Coatings",
         "Axholme Forge", "Breen Optics", "Cotham Seals", "Dovey Motors",
         "Ember Plating", "Flixton Belts", "Glaven Wire", "Hebble Presswork"),
        (RankNum("units_shipped", 800, 90000),
         RankNum("spend_eur", 12000, 940000, " EUR"),
         RankNum("defect_ppm", 20, 4200, " ppm"),
         RankNum("lead_days", 3, 90, " days"),
         RankNum("on_time_pct", 51, 100, " %"),
         RankNum("rating", 30, 99),
         RankNum("open_claims", 0, 14),
         RankNum("consignment_weight", 20, 90000)),
        (Attr("contract_type", ("spot", "framework", "call_off")),
         Attr("region", ("north", "midlands", "south", "overseas"))),
        ("spend_eur", "units_shipped", "spend per unit shipped"),
        ("consignment_weight", "kg", (("kg", 1.0), ("g", 1000.0), ("t", 0.001))),
        ("on_time_pct", 88, 98),
        ("defect_ppm", False, "rating", True),
    ),
    RankDomain(
        "route", "route", "routes",
        ("Ilam Loop", "Jurby Link", "Kelso Spur", "Lugg Crossing", "Adze Cut",
         "Brill Way", "Croft Line", "Dunlin Pass", "Esker Track", "Fell Road",
         "Garth Bend", "Haugh Straight", "Inver Curve", "Keld Ridge", "Linn Bridge",
         "Moor Junction"),
        (RankNum("distance_km", 40, 1400, " km"),
         RankNum("fuel_litres", 12, 900, " L"),
         RankNum("delay_min", 0, 220, " min"),
         RankNum("load_pct", 30, 100, " %"),
         RankNum("stops", 1, 22),
         RankNum("safety_score", 40, 99),
         RankNum("tolls_eur", 0, 340, " EUR"),
         RankNum("leg_distance", 40, 1400)),
        (Attr("road_class", ("motorway", "trunk", "secondary")),
         Attr("corridor", ("east", "west", "alpine", "coastal"))),
        ("fuel_litres", "distance_km", "fuel used per kilometre"),
        ("leg_distance", "km", (("km", 1.0), ("m", 1000.0), ("miles", 0.621371))),
        ("load_pct", 72, 94),
        ("delay_min", False, "safety_score", True),
    ),
)

RANK_BY_NAME = {d.name: d for d in RANK_DOMAINS}

RANK_PREAMBLES = (
    "The figures below are this period's returns.",
    "Here are the returns for the period, one block per entry.",
    "These are the numbers as reported this period.",
    "The period's reported figures are set out below.",
    "Reported figures for the period follow.",
    "Below are the figures each one filed for the period.",
    "The returns filed for the period are reproduced below.",
    "What follows is the filed return for each of them this period.",
)

PAIRWISE_STEMS = (
    'Of {a} and {b}, which one ranks higher under the rule?',
    'Between {a} and {b}, which ranks ahead under this rule?',
    'Which of {a} and {b} comes out in front under the rule below?',
    'Under the rule below, does {a} or {b} rank higher?',
    'Take {a} and {b} only. Which of the two ranks better under the rule?',
    'Under the rule supplied separately, which of {a} and {b} ranks ahead of the other?',
    'According to the rule given elsewhere, which of {a} and {b} is ranked higher than the other?',
    'Applying the separate rule, which of {a} and {b} takes precedence over the other?',
    'When the rule provided apart from this question is applied, which of {a} and {b} is placed ahead of the other?',
    'Given the rule stated separately, which of {a} and {b} ranks above the other?',
    'With the separate rule in mind, which of {a} and {b} outranks the other?',
    'Under the governing rule supplied elsewhere, which of {a} and {b} is the higher-ranked choice over the other?',
    'Following the rule that is not restated here, which of {a} and {b} comes before the other in rank?',
    'If the separate rule is applied, which of {a} and {b} is ranked in the leading position over the other?',
    'Based on the rule presented separately, which of {a} and {b} is ahead in the ordering over the other?',
    'By the rule stated apart from this question, which of {a} and {b} has the higher rank over the other?',
    'Using the rule that appears separately, which of {a} and {b} is ranked better than the other?',
    'As determined by the rule provided elsewhere, which of {a} and {b} is the superior choice in the ranking over the other?',
)

# "second lowest" is ambiguous when the rule itself says "lowest first" -- it reads
# either as second from the bottom of the ranking or as the second-smallest value. The
# position is therefore always named against the ranking, never against the field.
EXTREMUM_STEMS = (
    'Which of these comes {ord} once the rule is applied to them?',
    'Under the rule below, which one comes {ord}?',
    'Which entry comes {ord} once the rule is applied?',
    'Apply the rule below. Which one of them comes {ord}?',
    'Of all of them, which one comes {ord}?',
    'Under the rule supplied separately, which of the listed items is the {ord}?',
    'According to the rule given elsewhere, which among the listed things is the {ord}?',
    'Which of the items on the list is the {ord}, following the rule that appears separately?',
    'With the separate rule in mind, which listed item is the {ord}?',
    'Given the rule provided outside this question, which of the listed options is the {ord}?',
    'Which item from the list is the {ord} when applying the rule stated separately?',
    'Based on the rule set out elsewhere, which of the listed entries is the {ord}?',
    'Using the separate rule, which of these listed items is the {ord}?',
    'Which among the listed options is the {ord} under the rule furnished separately?',
    'Following the rule presented apart from this question, which listed thing is the {ord}?',
    'Which of the listed choices is the {ord} according to the rule provided in a separate place?',
    'By the rule supplied separately, which of the listed items is the {ord}?',
    'Which listed item qualifies as the {ord} under the rule given in a separate location?',
    'Pursuant to the separately given rule, which of the listed things is the {ord}?',
)

ORDERING_STEMS = (
    'Which of these orderings puts them in the right order under the rule?',
    'Under the rule below, which ordering is the correct one?',
    'Which one of these orderings is correct under the rule?',
    'Apply the rule below. Which ordering does it give?',
    'Which of the orderings listed is the one the rule produces?',
    'Which of the candidate orderings offered is correct under the rule supplied separately?',
    'Under the rule given elsewhere, which of the offered candidate orderings is the right choice?',
    'According to the separate rule, which candidate ordering among those offered should be selected?',
    'Which offered candidate ordering satisfies the rule that appears separately from this question?',
    'With the separate rule in mind, which of the candidate orderings presented is the correct selection?',
    'Which candidate ordering from the options offered is correct according to the rule stated elsewhere?',
    'Applying the rule supplied separately, which of these candidate orderings is the correct result?',
    'Which of the offered candidate orderings is right when judged by the rule given independently?',
    'Based on the rule provided elsewhere, which candidate ordering among the offered options is correct?',
    'Which candidate ordering offered should be chosen under the rule that is not repeated here?',
    'Under the separately given rule, which of the offered orderings is the correct candidate?',
    'Which of the candidate orderings offered matches the rule supplied in another place?',
    'Per the rule provided separately, which offered candidate ordering is the correct pick?',
    'Given the rule that stands apart from this question, which of the candidate orderings offered is correct?',
)


def _fmt_num(v: float) -> str:
    """`%g`, not `%.2f`: a factor of 0.001 printed as "0.00" makes the criteria a lie."""
    return f"{v:g}"


@dataclass
class RankInstance:
    domain: RankDomain
    comparator: str
    names: list[str]
    recs: list[dict]
    keys: list[float]           # the comparison key; larger is better, always
    rule: str                   # the criteria text
    direction: str              # "highest" / "lowest", for the question wording
    surface: list[float]        # the number as printed, for the naive-reader distractor
    surface_high_wins: bool

    def order(self) -> list[int]:
        return sorted(range(len(self.recs)), key=lambda i: -self.keys[i])


def _base_record(d: RankDomain, rng: random.Random, name: str) -> dict:
    rec = {"name": name}
    for n in d.nums:
        rec[n.name] = rng.randint(n.lo, n.hi)
    for e in d.enums:
        rec[e.name] = e.draw(rng)
    return rec


RATIO_MIN_GAP = 0.03          # adjacent quotients differ by at least 3 % of the larger
# Share of the surface-number reader's correct answers that are thrown back on the trained
# rungs, for every comparator except `field` (see `_surface_pick`).
P_SURFACE_REJECT = 0.6


def _surface_order(inst: "RankInstance") -> list[int]:
    """What a reader who ignores the rule and sorts the printed number gets. Stable, so a
    tie on the printed number falls back to the order the state lists the records in."""
    n = len(inst.recs)
    return sorted(range(n), key=lambda i: inst.surface[i], reverse=inst.surface_high_wins)


def make_rank_instance(d: RankDomain, comparator: str, n: int,
                       rng: random.Random) -> RankInstance | None:
    names = rng.sample(list(d.names), n)
    recs = [_base_record(d, rng, nm) for nm in names]
    by = {f.name: f for f in d.nums}
    hi_wins = rng.random() < 0.5

    if comparator == "field":
        wide = [x for x in d.nums if x.hi - x.lo + 1 >= n]
        if not wide:
            return None
        f = rng.choice(wide)
        vals = rng.sample(range(f.lo, f.hi + 1), n)
        for rec, v in zip(recs, vals):
            rec[f.name] = v
        keys = [rec[f.name] * (1 if hi_wins else -1) for rec in recs]
        surface = [float(rec[f.name]) for rec in recs]
        rule = (f"Rank the {d.plural} by `{f.name}`, "
                f"{'highest' if hi_wins else 'lowest'} first.")
        direction = "highest" if hi_wins else "lowest"

    elif comparator == "ratio":
        num, den, gloss = d.ratio
        for rec in recs:
            rec[den] = rng.randint(by[den].lo, by[den].hi)
            rec[num] = rng.randint(by[num].lo, by[num].hi)
        keys = [rec[num] / rec[den] * (1 if hi_wins else -1) for rec in recs]
        surface = [float(rec[num]) for rec in recs]
        rule = (f"Rank the {d.plural} by {gloss} -- that is `{num}` divided by `{den}` "
                f"-- {'highest' if hi_wins else 'lowest'} first.")
        direction = f"{'highest' if hi_wins else 'lowest'} on {gloss}"

    elif comparator == "mixed_units":
        fname, base, units = d.mixed
        f = by[fname]
        if f.hi - f.lo + 1 < n:
            return None
        trues = rng.sample(range(f.lo, f.hi + 1), n)
        pers = []
        for rec, t in zip(recs, trues):
            unit, per_base = rng.choice(units)
            rec[fname] = round(t * per_base, 2)
            rec[f"{fname}_unit"] = unit
            pers.append(per_base)
        keys = [rec[fname] / per * (1 if hi_wins else -1)
                for rec, per in zip(recs, pers)]
        surface = [float(rec[fname]) for rec in recs]
        if len({rec[f"{fname}_unit"] for rec in recs}) < 2:
            return None          # one unit throughout is the `field` comparator again
        table = "; ".join(f"1 {base} = {_fmt_num(p)} {u}" for u, p in units if p != 1.0)
        rule = (f"Each {d.noun} reports `{fname}` in whatever unit it uses, given in "
                f"`{fname}_unit` beside it. Convert every figure to {base} before you "
                f"compare anything ({table}), then rank "
                f"{'highest' if hi_wins else 'lowest'} first.")
        direction = f"{'highest' if hi_wins else 'lowest'} once converted to {base}"

    elif comparator == "deviation":
        fname, tlo, thi = d.deviation
        f = by[fname]
        if f.hi - f.lo + 1 < n:
            return None
        target = rng.randint(tlo, thi)
        vals = rng.sample(range(f.lo, f.hi + 1), n)
        for rec, v in zip(recs, vals):
            rec[fname] = v
        keys = [-abs(rec[fname] - target) for rec in recs]
        surface = [float(rec[fname]) for rec in recs]
        hi_wins = True
        rule = (f"Rank the {d.plural} by how close `{fname}` sits to the target of "
                f"{target}{f.unit}: the closest to the target ranks first, whether it is "
                f"over or under. How far above or below makes no difference, only how "
                f"far away.")
        direction = "closest to the target"

    elif comparator == "tiebreak":
        prim, prim_hi, sec, sec_hi = d.tiebreak
        pf, sf = by[prim], by[sec]
        span = list(range(pf.lo, pf.hi + 1))
        if sf.hi - sf.lo + 1 < n:
            return None
        # deliberate ties on the primary field: at least one pair must need the
        # tiebreaker, or the rule's second clause is decoration.
        base_vals = rng.sample(span, min(len(span), max(2, n - 1)))
        vals = [rng.choice(base_vals) for _ in range(n)]
        if len(set(vals)) == n or len(set(vals)) < 2:
            return None
        secs = rng.sample(range(sf.lo, sf.hi + 1), n)
        for rec, v, s in zip(recs, vals, secs):
            rec[prim] = v
            rec[sec] = s
        keys = [(v * (1 if prim_hi else -1)) * 100000
                + (s * (1 if sec_hi else -1))
                for v, s in zip(vals, secs)]
        surface = [float(rec[prim]) for rec in recs]
        hi_wins = prim_hi
        rule = (f"Rank the {d.plural} by `{prim}`, "
                f"{'highest' if prim_hi else 'lowest'} first. Where two of them have the "
                f"same `{prim}`, the one with the "
                f"{'higher' if sec_hi else 'lower'} `{sec}` ranks ahead.")
        direction = f"{'highest' if prim_hi else 'lowest'} on {prim.replace('_', ' ')}"
    else:
        raise ValueError(comparator)

    if len(set(keys)) != n:
        return None
    if comparator == "ratio":
        # A ratio ranking whose two closest quotients sit within 1 % of each other is a
        # three-significant-figure division test, not a ranking test: 6.9 % of the
        # `rank_ordering:ratio` questions hinged on such a pair (domain-20 audit).
        ks = sorted(abs(k) for k in keys)
        if any((b - a) / b < RATIO_MIN_GAP for a, b in zip(ks, ks[1:])):
            return None
    inst = RankInstance(d, comparator, names, recs, keys, rule, direction, surface,
                        hi_wins)
    # `field` is the only comparator whose printed number *is* the key; the proxies must
    # actually differ from the surface reading, or they train nothing new. `tiebreak` is
    # exempt too: its surface reading is its first clause, and the deliberate tie above
    # already makes the second clause decide something. Held to "differ", its ties were
    # resolved *against* the order the state lists the tied records in whenever there was
    # one tie, so "the tied record listed second wins" found the `rank_pairwise` answer
    # 0.58 of the time and `rank_ordering` leaned the same way
    # (measured by a shortcut audit); now the listing says nothing about a tie.
    if comparator not in ("field", "tiebreak"):
        naive = sorted(range(n), key=lambda i: -surface[i] if hi_wins else surface[i])
        if naive == inst.order():
            return None
    return inst


def render_rank(inst: RankInstance, shape: str, rng: random.Random) -> str:
    d, recs = inst.domain, inst.recs
    pre = rng.choice(RANK_PREAMBLES)
    cols = [k for k in recs[0] if k != "name"]
    if shape == "json":
        body = _json.dumps(recs, indent=2)
    elif shape == "table":
        head_cols = ["name"] + cols
        widths = [max(len(c), max(len(str(r[c])) for r in recs)) for c in head_cols]
        lines = ["  ".join(c.ljust(w) for c, w in zip(head_cols, widths)).rstrip()]
        lines += ["  ".join(str(r[c]).ljust(w) for c, w in zip(head_cols, widths)).rstrip()
                  for r in recs]
        body = "\n".join(lines)
    else:
        body = "\n".join(
            f"{r['name']} reports " + "; ".join(f"{_humanise(c)} {r[c]}" for c in cols)
            + "." for r in recs)
    return f"{pre}\n\n{body}"


def _kendall(a: tuple[str, ...], b: tuple[str, ...]) -> int:
    """Adjacent-transposition distance between two orderings of the same names."""
    pos = {x: i for i, x in enumerate(b)}
    return sum(1 for i in range(len(a)) for j in range(i + 1, len(a))
               if pos[a[i]] > pos[a[j]])


ORDINALS = ("first", "second", "third", "fourth", "fifth", "sixth")


def _ordinal_phrase(k: int, low: bool) -> str:
    return (("last in the ranking", "second from last in the ranking") if low
            else ("first in the ranking", "second in the ranking"))[k]


def rank_instance_examples(d: RankDomain, comparator: str, family: str,
                           rng: random.Random, idx: int) -> list[Example] | None:
    if family == "rank_pairwise":
        n = rng.randint(3, 8)
    elif family == "rank_extremum":
        n = rng.choice((3, 4, 5, 6, 8, 10, 12, 16))
    else:
        n = rng.randint(3, 5)
    inst = make_rank_instance(d, comparator, n, rng)
    if inst is None:
        return None
    order = inst.order()

    if family == "rank_pairwise":
        # The pair is chosen, not drawn. Drawn at random, the pair the rule orders one way
        # was ordered the same way by the printed number alone 0.66-0.88 of the time on the
        # four comparisons that are not `field` (domain-20 audit), so the rung taught
        # "compare the number you see" -- which is exactly the naive distractor that
        # `rank_ordering` plants. Half the pairs are now ones the printed number gets
        # wrong; for `tiebreak`, half are pairs tied on the primary field, the only pairs
        # the rule's second clause decides.
        pairs = [(a, b) for a in range(n) for b in range(a + 1, n)]
        surf = _surface_order(inst)
        rank_s = {x: r for r, x in enumerate(surf)}

        def naive_right(a, b):
            if inst.surface[a] == inst.surface[b]:
                return None
            return (rank_s[a] < rank_s[b]) == (inst.keys[a] > inst.keys[b])
        hard = [p for p in pairs if naive_right(*p) is not True]
        easy = [p for p in pairs if naive_right(*p) is True]
        pool = hard if (hard and (rng.random() < 0.5 or not easy)) else easy
        i, j = rng.choice(pool)
        if rng.random() < 0.5:
            i, j = j, i
        options = [inst.names[i], inst.names[j]]
        gold = 0 if inst.keys[i] > inst.keys[j] else 1
        descs = [f"{o}, as reported above" for o in options]
        options, descs, gold = _shuffle(rng, options, descs, gold)
        a_, b_ = inst.names[i], inst.names[j]
        text = worded("rank_pairwise", rng.choice(PAIRWISE_STEMS), f"pw:{idx}:{a_}:{b_}",
                      lambda st: st.format(a=a_, b=b_),
                      lambda t: a_ in t and b_ in t and t.rstrip().endswith("?"))
        meta = {"family": family, "pair": [inst.names[i], inst.names[j]]}

    elif family == "rank_extremum":
        low = rng.random() < 0.35
        k = 0 if rng.random() < 0.72 else 1
        ranked = order if not low else order[::-1]
        gold_i = ranked[k]
        # Same reason as the pairwise choice above: the printed number alone found the
        # asked-for record 0.33-0.58 of the time against 0.14-0.16 chance.
        if comparator != "field":
            surf = _surface_order(inst)
            if (surf if not low else surf[::-1])[k] == gold_i and rng.random() < P_SURFACE_REJECT:
                return None
        options = list(inst.names)
        descs = [f"{o}, as reported above" for o in options]
        gold = options.index(inst.names[gold_i])
        options, descs, gold = _shuffle(rng, options, descs, gold)
        ord_ = _ordinal_phrase(k, low)
        text = worded("rank_extremum", rng.choice(EXTREMUM_STEMS),
                      f"ex:{idx}:{':'.join(inst.names)}",
                      lambda st: st.format(ord=ord_),
                      lambda t: ord_ in t and t.rstrip().endswith("?"))
        meta = {"family": family, "position": k, "from_bottom": low}

    else:                                              # rank_ordering -- held out
        # The option set is built first, around an arbitrary ordering, and the answer is
        # then drawn uniformly from it; the records are *named* afterwards so that the
        # drawn one is the true order. Nothing about where an ordering sits in the field
        # -- central, reversed by another, one swap from most -- can say it is the
        # answer, because the field was shaped before there was an answer.
        #
        # It used to be built outwards from the true order: adjacent swaps of it, swaps
        # of one of those, its reverse, the order the state lists the records in, and the
        # order the printed number gives. So the answer was always the one whose reverse
        # was also offered, and the listed and printed-number orders were always offered
        # and always wrong; "the option whose reverse is also an option" alone scored
        # 0.38 against 0.29 chance, and a lookup over three such features 0.60-0.72,
        # without a record read (measured by a shortcut audit). The Kendall-
        # median repair that followed made it worse in the other direction: the answer
        # was *never* the consensus of the field, so the consensus was a signal to avoid.
        def swapped(p, a):
            q = list(p)
            q[a], q[a + 1] = q[a + 1], q[a]
            return tuple(q)

        base = tuple(rng.sample(list(inst.names), n))
        cands: list[tuple[str, ...]] = [base]

        def add(p):
            if p not in cands:
                cands.append(tuple(p))

        for a in range(n - 1):                         # one adjacent swap
            add(swapped(base, a))
        pivot = swapped(base, rng.randrange(n - 1))    # and swaps of one of those
        for a in range(n - 1):
            add(swapped(pivot, a))
        add(tuple(reversed(base)))
        k = min(rng.choice((2, 3, 4, 4, 5, 6)), len(cands))
        rng.shuffle(cands)
        rows = cands[:k]
        true_perm = rows[rng.randrange(k)]
        # name the records so that the drawn ordering is the true one: the record that
        # ranks r-th under the rule takes the r-th name of `true_perm`
        new_names = list(inst.names)
        for r, i in enumerate(order):
            new_names[i] = true_perm[r]
        inst.names = new_names
        for rec, nm in zip(inst.recs, new_names):
            rec["name"] = nm
        # The printed-number order is never a *wrong* option where the printed number is
        # only a proxy. `make_rank_instance` makes it differ from the true order there,
        # so wherever it was offered it was wrong: a reader who sorts the printed number
        # and strikes that option out gains, and one who sorts it and picks it scores
        # below chance. It is swapped for an unused candidate, or dropped.
        naive = tuple(sorted(inst.names, key=lambda nm: (
            -1 if inst.surface_high_wins else 1) * inst.surface[inst.names.index(nm)]))
        if comparator in SURFACE_PROXY and naive != true_perm and naive in rows:
            rows.remove(naive)
            spare = [c for c in cands[k:] if c != naive]
            if spare:
                rows.append(spare[0])
            if len(rows) < 2:
                return None
        rows = [p for p in rows if p != true_perm] + [true_perm]
        options = [", ".join(p) for p in rows]
        descs = ["; ".join(f"{nm} {ORDINALS[pos]}" for pos, nm in enumerate(p))
                 for p in rows]
        options, descs, gold = _shuffle(rng, options, descs, len(rows) - 1)
        text = worded("rank_ordering", rng.choice(ORDERING_STEMS),
                      f"or:{idx}:{':'.join(inst.names)}", lambda st: st,
                      lambda t: "{" not in t and t.rstrip().endswith("?"))
        # how far the printed-number order sits from the true order, in adjacent swaps
        meta = {"family": family, "n_ranked": n,
                "surface_distance": _kendall(naive, true_perm)}

    instr = (f"{inst.rule}\n"
             f"Nothing else about a {d.noun} counts towards the ranking, and no "
             f"{d.noun} can be placed without comparing it against the others.")
    out = []
    for shape in SHAPES:
        qmeta = {**meta, "comparator": comparator, "domain": d.name, "shape": shape,
                 "n_records": n}
        out.append(Example(state=render_rank(inst, shape, rng), questions=[Question(
            id=f"{family}_{idx}_{shape}", question=text, options=list(options),
            target=gold, meta=qmeta, instructions=instr, descriptions=list(descs))]))
    return out


# ======================================================================================
# loaders and tasks
# ======================================================================================

def _hop_loader(chain_name: str, hops: int, seed: int, cap: int = MAX_PER_TASK):
    chain = CHAINS_BY_NAME[chain_name]
    heldout = hops in HELDOUT_HOPS

    def load(n: int) -> Iterator[Example]:
        n = min(n, cap)
        made = 0
        counts = {f: 0.0 for f in HOP_FAMILIES}
        yes_no = [0, 0]
        i = 0
        while made < n and i < n * 30:
            i += 1
            rng = _rng(seed, f"{chain_name}:{hops}:{i}")
            total = sum(counts.values()) or 1.0
            jitter = random.Random(f"o:{seed}:{i}")
            order = sorted(HOP_FAMILIES,
                           key=lambda f: counts[f] / total - HOP_FAMILY_SHARE[f]
                           + jitter.random() * 0.04)
            for family in order:
                batch = hop_instance(chain, hops, family, rng, heldout)
                if batch is None:
                    continue
                if family == "sameend":
                    g = batch[0].questions[0].target
                    if yes_no[g] > yes_no[1 - g] + 1:
                        continue
                    yes_no[g] += 1
                counts[family] += 1
                made += len(batch)
                yield from batch
                break
    return load


# `rank_ordering` comparisons whose printed number is a proxy for the rule rather than a
# clause of it. On these the loader keeps the printed-number order exactly as often d
# adjacent swaps from the reverse of the true order as d swaps from the true order. Left
# to the draw, the printed number (the numerator of a ratio, a figure in whatever unit,
# the raw value whose distance to a target counts) sorts the records close to the true
# order: once the printed-number order was no longer planted as a wrong option, "the
# option nearest the printed-number order" found 0.47-0.55 of answers against 0.29
# chance, and while it *was* planted, "take that option" scored zero -- a reader was
# rewarded or punished for the very heuristic `rank_pairwise` is balanced to leave at a
# coin flip. (`field` and `tiebreak` are exempt: there the printed number is the rule's
# first clause.) `deviation` keeps a residual this cannot reach: ranking by distance to
# a target orders the records as a V over their values, so some orderings are ruled out
# by the value order alone (a shortcut audit reports it).
SURFACE_PROXY = ("ratio", "mixed_units", "deviation")


def _rank_loader(family: str, comparator: str, seed: int, cap: int = MAX_PER_TASK):
    balance = family in HELDOUT_RANK_FAMILIES and comparator in SURFACE_PROXY

    def load(n: int) -> Iterator[Example]:
        n = min(n, cap)
        made = 0
        i = 0
        concord = collections.Counter()
        while made < n and i < n * 30:
            i += 1
            rng = _rng(seed, f"{family}:{comparator}:{i}")
            d = RANK_DOMAINS[i % len(RANK_DOMAINS)]
            batch = rank_instance_examples(d, comparator, family, rng, i)
            if batch is None:
                continue
            if balance:
                # distance d and its mirror D - d (as near the reverse as d is to the
                # true order) are kept equally common, for each number of records
                m = batch[0].questions[0].meta
                k, D = m["n_ranked"], m["n_ranked"] * (m["n_ranked"] - 1) // 2
                key = (k, m["surface_distance"])
                if concord[key] > concord[(k, D - key[1])]:
                    continue
                concord[key] += 1
            made += len(batch)
            yield from batch
    return load


def tasks() -> list[RealTask]:
    """1-, 2- and 3-hop and the two trained ranking shapes go to `train`, each with a
    fresh-seed `_eval` twin forced to `devreal`. 4-hop and full ordering are `testreal`
    and are never trained on; nothing trained reaches `testreal`, so a testreal number on
    this row is a held-out-structure number and nothing else. `DEV_HOP_CELLS` and
    `DEV_RANK_CELLS` are the dev split's own held-out structures: no train task, no twin,
    no test task.

    The 1-hop tasks are the control the brief asks for: same universes, same renderings,
    same families, one reference followed instead of four. A 4-hop drop read against them
    is a failure to chain, not a failure to read a linked record at all.
    """
    out: list[RealTask] = []
    dev_note = "held out of train and test; a dev structure -- selects checkpoints and fits T"
    for chain in CHAINS:
        for hops in TRAINED_HOPS:
            if (chain.name, hops) in DEV_HOP_CELLS:
                out.append(RealTask(
                    row=ROW, name=f"relational_hop{hops}_{chain.name}", licence=LICENCE,
                    url=URL, load=_hop_loader(chain.name, hops, 6363), real=False,
                    force_split="devreal", per_example_options=True,
                    notes=f"{hops}-hop over the {chain.name} chain; {dev_note}"))
                continue
            for suffix, split, seed, cap in (("", "train", 0, MAX_PER_TASK_TRAIN),
                                             ("_eval", "devreal", 4242, MAX_PER_TASK_DEV)):
                name = f"relational_hop{hops}_{chain.name}{suffix}"
                out.append(RealTask(
                    row=ROW, name=name, licence=LICENCE, url=URL,
                    load=_hop_loader(chain.name, hops, seed, cap), real=False,
                    force_split=split, per_example_options=True,
                    notes=f"{hops}-hop over the {chain.name} chain; code-derived"))
        for hops in HELDOUT_HOPS:
            name = f"relational_hop{hops}_{chain.name}"
            out.append(RealTask(
                row=ROW, name=name, licence=LICENCE, url=URL,
                load=_hop_loader(chain.name, hops, 7717), real=False,
                force_split="testreal", per_example_options=True,
                notes=f"{hops}-hop over the {chain.name} chain; NEVER trained on"))
    for comparator in COMPARATORS:
        for family in TRAINED_RANK_FAMILIES:
            if (family, comparator) in DEV_RANK_CELLS:
                out.append(RealTask(
                    row=ROW, name=f"relational_{family}_{comparator}", licence=LICENCE,
                    url=URL, load=_rank_loader(family, comparator, 6363), real=False,
                    force_split="devreal", per_example_options=True,
                    notes=f"{family} on the {comparator} comparison; {dev_note}"))
                continue
            for suffix, split, seed, cap in (("", "train", 0, MAX_PER_TASK_TRAIN),
                                             ("_eval", "devreal", 4242, MAX_PER_TASK_DEV)):
                name = f"relational_{family}_{comparator}{suffix}"
                out.append(RealTask(
                    row=ROW, name=name, licence=LICENCE, url=URL,
                    load=_rank_loader(family, comparator, seed, cap), real=False,
                    force_split=split, per_example_options=True,
                    notes=f"{family} on the {comparator} comparison; code-derived"))
        for family in HELDOUT_RANK_FAMILIES:
            name = f"relational_{family}_{comparator}"
            out.append(RealTask(
                row=ROW, name=name, licence=LICENCE, url=URL,
                load=_rank_loader(family, comparator, 7717), real=False,
                force_split="testreal", per_example_options=True,
                notes=f"{family} on the {comparator} comparison; NEVER trained on"))
    return out


# ---- the stream a probe should score ---------------------------------------------------

PROBE_SEED = 20260921


def probe_tasks() -> list[RealTask]:
    """Every family again, from a seed no corpus task uses. Nothing registers these.

    Row 33 learned this the expensive way: an earlier rule_transfer probe compared trained
    families against held-out ones by loading the *same* task object the corpus had already
    been written from, and 95.5 % of the states it scored were verbatim in `train.jsonl`.
    The trained-family number it printed was recall of training examples, so the transfer
    gap it reported was an upper bound rather than a measurement.

    These tasks are not returned by `tasks()`, so no split can ever contain them. Point a
    probe at `probe_tasks()` and `hop1/hop2/hop3` against `hop4`, and `rank_pairwise` and
    `rank_extremum` against `rank_ordering`, are both held-out-example comparisons.
    """
    out: list[RealTask] = []
    for chain in CHAINS:
        for hops in TRAINED_HOPS + HELDOUT_HOPS:
            out.append(RealTask(
                row=ROW, name=f"relational_hop{hops}_{chain.name}", licence=LICENCE,
                url=URL, load=_hop_loader(chain.name, hops, PROBE_SEED), real=False,
                force_split=None, per_example_options=True,
                notes="probe only -- never registered, never in a split"))
    for comparator in COMPARATORS:
        for family in TRAINED_RANK_FAMILIES + HELDOUT_RANK_FAMILIES:
            out.append(RealTask(
                row=ROW, name=f"relational_{family}_{comparator}", licence=LICENCE,
                url=URL, load=_rank_loader(family, comparator, PROBE_SEED), real=False,
                force_split=None, per_example_options=True,
                notes="probe only -- never registered, never in a split"))
    return out
