"""Row 41 — scheduling and allocation (domain 19).

Constrained choice where the options interact, so picking one forecloses another. Every
other domain in the corpus scores each option against the state independently, and that
is fine there because the options really are independent. Here "put Ana on Tuesday night"
is only right *because* of what it forecloses on Wednesday, and that is a different shape.

The interaction is structural rather than asserted, and the whole design is one split:

    facts   -> the state.   Who holds which certification, who is away when, which shift
                            needs what. Every one of these is **unary**: it constrains a
                            single (person, shift) pair and nothing else.
    policy  -> the criteria (`instructions`). Every policy rule here is **coupling**: it
                            reads two or more shifts at once.

So every option of every question already passes every check the state alone can make.
Nothing can be eliminated by looking at it on its own; only the criteria discriminate, and
no criterion can be evaluated one shift at a time. `tests/test_scheduling_source.py`
measures that as "local survivors" and requires it to be every option, every time. If that
number ever falls to one the interaction has become decoration and the domain is not
earning its place.

**A solver computes every label.** `feasible_set` enumerates the whole assignment space
exhaustively, so the answer is exact and there is no dependency to add. Instances are
sized so the space stays under `MAX_DOMAIN`; an instance that would be bigger, or whose
answer is not unique, is dropped rather than guessed.

**Seven coupling rule types, two per instance, 21 combinations: 6 held out to test, 4 to
dev.**
`max_shifts` `min_shifts` `rest` `one_per_day` `pair_conflict` `handover` `buddy`.
Every type inside a held-out combination appears in some trained combination, so a drop
on `HELDOUT_COMBOS` (or `DEV_COMBOS`) is a failure to compose two known constraints, not
an unseen one -- the same holdout that told this project something at the `rule_transfer`
gate and at row 36.

**Five families**, all solver-derivable: `pick` (which roster is valid), `culprit` (which
single rule makes the week impossible), `grant` (which pending request can still be
granted), `move` (which other shift must change hands), `feasible` (can it be covered at
all). `feasible`, and `culprit` whenever the week as drawn cannot carry it, are asked of
a *narrowed* copy of the week (more leave, see `narrow`), because a drawn week is almost
always coverable; two combinations (`rest+one_per_day`, `pair_conflict+handover`) are too
loose to carry more than a trace of either.

**The combination has to be what decides.** A held-out pair measures composition only if
neither of its types settles the question alone, and drawn blind most questions were
settled by one: `move` 91 % of the time, a third of `feasible`'s `no`s, and "keep only
the first type's rules" found `pick`'s answer at three times chance
(measured by a shortcut audit). So `move` and `feasible`'s `no` keep only draws
that need both types, `pick` and `grant` split their wrong options between the two
types, and `_balanced` keeps the answer's surface cues (the narrowest shift, the rule
that bites hardest on its own ...) near chance across a task. `move` is the price: few
weeks carry a draw that needs both types, so it is ~3 % of the row, not 15 %.

**Three render shapes** from one instance -- a roster of tables, a calendar of day blocks,
an email thread -- carrying identical facts, identical options and an identical target, so
the shape is a controlled variable rather than a harder task about parsing.
"""

from __future__ import annotations

import itertools
import random
from collections import Counter
from dataclasses import dataclass, field, replace
from typing import Iterator

import numpy as np

from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask

LICENCE = "generated by lod/corpus/services/sources/synth/scheduling.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/scheduling.py"
ROW = 41
DOMAIN = 19

# The enumeration budget. An instance whose assignment space is larger is regenerated,
# which is the alternative to adding a solver dependency: shrink the instance.
MAX_DOMAIN = 12_000

# Row 41 is a new and unvalidated domain. Left alone the build's row budget would hand it
# ~40,000 questions, which is more weight than an unproven addition should take from the
# two domains that carry the corpus. 36 tasks * 560 lands it at ~20,000, the size
# budgeted for it.
MAX_PER_TASK = 560
# Four trained pairs moved to dev (`DEV_COMBOS`) would have cut training from 15 pairs *
# 561 to 11 * 561. The remaining pairs take up the difference, so the row trains on as
# many questions as it did (11 * 765 = 8,415) and only the breadth changes.
MAX_PER_TASK_TRAIN = 765

# ---- the seven coupling rule types ---------------------------------------------------
# Every one of them reads more than one shift. There is deliberately no unary rule type:
# the unary facts are in the state, where they cannot do the discriminating.
RULE_TYPES = ("max_shifts", "min_shifts", "rest", "one_per_day", "pair_conflict",
              "handover", "buddy")

SHORT = {"max_shifts": "mx", "min_shifts": "mn", "rest": "re", "one_per_day": "od",
         "pair_conflict": "pc", "handover": "ho", "buddy": "bu"}

HELDOUT_COMBOS = (
    ("max_shifts", "handover"),
    ("min_shifts", "rest"),
    ("min_shifts", "handover"),
    ("rest", "buddy"),
    ("one_per_day", "pair_conflict"),
    ("pair_conflict", "buddy"),
)
# The dev split's own held-out pairs: never trained, never tested, and what checkpoint
# selection and the temperature fit read. The seven types make only 21 pairs, all of them
# already trained or tested, so there is no new pair to define: four are moved out of
# training instead. Every type still trains in at least two pairs (`min_shifts` and
# `buddy` in two, the rest in three to five), neither loose pair that barely carries
# `feasible` (`rest+one_per_day`, `pair_conflict+handover`) nor `max+min_shifts`, which
# carries none, is among them, and the four were chosen so the one cue a pair set can
# move -- how crowded the week is predicting `feasible` -- stays where it was on both
# sides: in-sample best threshold minus majority, 450 examples a pair, 0.117 on the
# eleven trained pairs and 0.115 on these four, against 0.116 on the fifteen before.
# Triples would have been new structures, but a three-type week is a different
# difficulty class from test's pairs, and dev has to mirror test to steer it. The cost
# is training breadth, 11 trained pairs rather than 15; `MAX_PER_TASK_TRAIN` keeps the
# volume.
DEV_COMBOS = (
    ("min_shifts", "one_per_day"),
    ("min_shifts", "buddy"),
    ("rest", "pair_conflict"),
    ("one_per_day", "buddy"),
)
TRAINED_COMBOS = tuple(
    c for c in itertools.combinations(RULE_TYPES, 2)
    if c not in HELDOUT_COMBOS and c not in DEV_COMBOS)
COMBOS = TRAINED_COMBOS + DEV_COMBOS + HELDOUT_COMBOS

FAMILIES = ("pick", "culprit", "grant", "move", "feasible")
# Roughly the mix wanted; the loader emits whichever eligible family is furthest behind.
FAMILY_SHARE = {"pick": 0.26, "grant": 0.24, "culprit": 0.15, "move": 0.15,
                "feasible": 0.20}
SHAPES = ("roster", "calendar", "email")
# `move`: see `_f_move`. How often the draw the policy-blind guesses score worst on is
# kept, and how often a week on which every draw is a giveaway is kept at all.
MOVE_DEBIAS = 0.9
MOVE_GIVEAWAY = 0.75             # summed tells at or above this make a draw a giveaway
MOVE_GIVEAWAY_KEEP = 0.25
# `_balanced`: how far over the overall answer rate a cue may run before a strict family
# passes the week to another family. 1.0 held every cue to chance but halved `grant` and
# `culprit`; this keeps most of them and the cues within a few points of chance.
CUE_SLACK = 1.2
MOVE_DRAWS = 32                  # draws per week; most are dropped as one-type (`_f_move`)
FEASIBLE_TRIES = 12              # narrowings `_f_feasible` searches for the answer wanted
MOVE_NARROW = 4                  # narrowed copies of the week `_f_move` also searches
# Families that build on a minority of weeks, and how often a week they fail on is skipped
# while they are behind their share (see `_loader`). An earlier build: `culprit` 2.5 % of
# the row. `move` and `grant` joined when their one-type and surface-cue draws started
# being dropped (shortcut audit): a week they pass on otherwise goes to `pick`, which never
# fails. `move` still ends near 3 % of the row: few weeks carry a draw that needs both rule
# types, and none in some combinations.
SCARCE = ("culprit", "feasible", "move", "grant")
SCARCE_SKIP = 0.85

DAYS = ("Mon", "Tue", "Wed", "Thu", "Fri")
PARTS = ("morning", "afternoon", "night")
SKILLS = ("forklift licence", "first aid ticket", "key holder sign-off",
          "night marshal card", "coldstore ticket", "dangerous goods permit")
FIRSTS = ("Ana", "Bo", "Cy", "Dee", "Eli", "Fay", "Gus", "Hana", "Ivo", "Jo",
          "Kit", "Lena", "Moss", "Nia", "Otto", "Pia", "Quinn", "Ravi", "Sol", "Tam")
LASTS = ("Vidal", "Ferrer", "Okorie", "Halvorsen", "Marchetti", "Aaltonen", "Nkemdi",
         "Duval", "Bergqvist", "Oyelaran", "Fairbairn", "Walsh", "Rasmussen", "Iqbal")
SITES = ("Ardenfell depot", "Brightmoor yard", "Calder Bay terminal", "Dunwick works",
         "Eastmere store", "Fallowgate hub", "Greywater plant", "Holmfirth dock")
MONTHS = ("March", "April", "May", "June", "September", "October", "November")
MANAGERS = ("Priya Raman", "Tomas Ek", "Ade Balogun", "Ruth Lindqvist", "Marco Pires")
SCHEDULERS = ("Dana Whyte", "Ken Abara", "Sofia Ruiz", "Neil Ostrom")
HR = ("Val Petrou", "Imani Cole", "Bram de Vries")


# ---- email wording, written by the model ------------------------------------------
# The domain's build plan says the LLM renders the instance. This is
# the whole of what it is allowed to do: 14 thread styles, proposed in one call by
# deepseek/deepseek-v4.1-flash and pasted here verbatim, carrying not one fact and
# not one target. Every shift number, name, certification and absence below them is
# filled in by code, and `sched_` is in PROTECTED_PREFIXES so the corpus enricher
# never gets to touch the criteria -- which in this domain *are* the label.
THREAD_STYLES = (
    {
        'subject': 'Cover needed',
        'shifts': 'Below is the running order of shifts needing cover; the numbers are just the order they appear.',
        'staff': 'This list shows who is available and what each person is signed off to do.',
        'leave': 'The absences below are listed by shift number.',
        'booked': 'The shifts below are already confirmed.',
        'open': 'Nothing is confirmed yet; every shift listed below is still open.',
    },
    {
        'subject': 'Rota gap',
        'shifts': 'Apologies for the short notice, but these shifts need covering and the numbers show the running order.',
        'staff': 'Sorry to chase, but below are the people available and the duties each is signed off to cover.',
        'leave': 'Apologies, the absences below are given by shift number.',
        'booked': 'Thank you to everyone; the shifts below are already confirmed.',
        'open': 'Sorry, but nothing is confirmed yet and every shift listed remains open.',
    },
    {
        'subject': 'Shift cover request',
        'shifts': 'Please note that the numbered shifts below constitute the running order for cover.',
        'staff': 'The following personnel are listed with the duties for which each is signed off.',
        'leave': 'The absences hereunder are specified by shift number.',
        'booked': 'The shifts listed below are hereby confirmed.',
        'open': 'No shifts have been confirmed; all shifts listed below remain open.',
    },
    {
        'subject': 'Urgent cover',
        'shifts': 'Quick one: these shifts need cover and the numbers are the running order.',
        'staff': "Here's who can work and what they're signed off for.",
        'leave': "Who's away is below, listed by shift number.",
        'booked': 'These are the ones already booked.',
        'open': "Nothing's confirmed, so all these are still open.",
    },
    {
        'subject': 'Open shifts',
        'shifts': 'Shifts needing cover, numbered in running order.',
        'staff': 'Available people and their signed-off duties.',
        'leave': 'Absences by shift number.',
        'booked': 'Confirmed shifts below.',
        'open': 'No confirmations. All shifts open.',
    },
    {
        'subject': 'Cover appeal',
        'shifts': 'If you can help, the shifts below need covering and the numbers give the running order.',
        'staff': 'Below are the people who can help and what each is signed off to do.',
        'leave': 'For clarity, the absences below are listed by shift number.',
        'booked': 'A big thank you; the shifts below are already confirmed.',
        'open': 'Nothing is confirmed just yet, so every shift below is still open.',
    },
    {
        'subject': 'Rota shortfall',
        'shifts': 'The numbered list below sets out the running order of shifts requiring cover.',
        'staff': 'Each person below is shown with the duties they are signed off to perform.',
        'leave': 'Absences are recorded below against the relevant shift number.',
        'booked': 'The shifts below have been confirmed in accordance with the rota.',
        'open': 'As no cover is confirmed, every shift listed below remains open.',
    },
    {
        'subject': 'Cover list',
        'shifts': 'Another list, sorry; these shifts need covering and the numbers are the running order.',
        'staff': 'Below are the usual people and what each is signed off to cover.',
        'leave': 'The absences below are given by shift number, as always.',
        'booked': 'These shifts are already booked, at least.',
        'open': 'Still nothing confirmed, so every shift below is open.',
    },
    {
        'subject': 'Staffing gap',
        'shifts': 'These shifts need cover; the numbers below are the running order.',
        'staff': 'Here are the available people and the duties each is signed off for.',
        'leave': 'Absences are given below by shift number.',
        'booked': 'The shifts below are confirmed.',
        'open': 'Nothing is confirmed; all shifts below are open.',
    },
    {
        'subject': 'Cover required',
        'shifts': 'Kindly review the numbered shifts below, which are in running order for cover.',
        'staff': 'Below you will find the people available and the duties each is signed off to undertake.',
        'leave': 'The absences below are respectfully given by shift number.',
        'booked': 'The shifts below have been confirmed and are no longer open.',
        'open': 'No shifts have been confirmed, so all listed below remain open.',
    },
    {
        'subject': 'Shift vacancies',
        'shifts': 'Attention: the numbered shifts below are the running order for cover.',
        'staff': 'The personnel below are listed with the duties they are signed off to carry out.',
        'leave': 'Absences are reported below by shift number.',
        'booked': 'Confirmed shifts are listed below.',
        'open': 'No confirmations received; all shifts below remain open.',
    },
    {
        'subject': 'Cover gap',
        'shifts': 'Right, these shifts need covering and the numbers are just the running order.',
        'staff': "Here's who's about and what they're signed off to do.",
        'leave': "Who's off is below, by shift number.",
        'booked': 'These ones are already booked.',
        'open': 'Nowt confirmed yet, so every shift below is still open.',
    },
    {
        'subject': 'Shift cover',
        'shifts': 'The shifts below need cover, with the numbers showing the running order.',
        'staff': 'This is the list of people and what each is signed off to do.',
        'leave': 'The absences below are listed by shift number.',
        'booked': 'The shifts below are already confirmed.',
        'open': 'Nothing is confirmed yet, so every shift listed is still open.',
    },
    {
        'subject': 'Immediate cover',
        'shifts': 'Immediate action: these shifts need covering and the numbers are the running order.',
        'staff': 'Available staff and their signed-off duties are below.',
        'leave': 'Absences are given below by shift number.',
        'booked': 'The shifts below are confirmed and booked.',
        'open': 'Nothing is confirmed; every shift below is open urgently.',
    },
)


# ---- the instance ---------------------------------------------------------------------

@dataclass
class Instance:
    site: str
    week: str
    days: tuple[str, ...]
    slots: tuple[tuple[int, str, str | None], ...]  # (day index, part, required skill)
    names: tuple[str, ...]                          # display names, distinct
    skills: tuple[tuple[str, ...], ...]             # per person
    away: tuple[tuple[int, ...], ...]               # per person, slot indices
    rules: tuple[dict, ...]
    combo: tuple[str, str]
    allowed: tuple[tuple[int, ...], ...] = field(default=())
    tight: int = 0

    @property
    def n_slots(self) -> int:
        return len(self.slots)

    @property
    def n_staff(self) -> int:
        return len(self.names)

    def day_of(self, s: int) -> int:
        return self.slots[s][0]

    def label(self, s: int) -> str:
        d, part, _ = self.slots[s]
        return f"{self.days[d]} {part}"


def _rng(seed: int, salt: str) -> random.Random:
    return random.Random(f"{seed}:{salt}")


def _display_names(rng: random.Random, n: int) -> tuple[str, ...]:
    firsts = rng.sample(FIRSTS, n)
    lasts = rng.sample(LASTS, n)
    return tuple(f"{f} {l[0]}." for f, l in zip(firsts, lasts))


def _make_rules(rng: random.Random, combo: tuple[str, str], n_slots: int,
                n_staff: int, tight: int) -> tuple[dict, ...] | None:
    """Instantiate the combination's two types. Returns None for a contradictory draw.

    `tight` is 0, 1 or 2 and over-constrains the draw. Left to chance a week is coverable
    about 96 % of the time, so the `no` half of `feasible` starves and `culprit` -- which
    has to start from a week that *is* coverable and then break it -- crowds it out.
    Level 2 puts a ceiling on everyone who has one and a floor under everyone who has one,
    which is usually more staff-days than the week has shifts. The level cycles per
    instance inside every task, so all three land in every split."""
    rules: list[dict] = []
    pairs_used: set[tuple[int, int]] = set()
    # A person with both a floor and a ceiling can be contradictory without any
    # scheduling in it ("at most 1 and at least 2"), which is a reading question, not
    # this domain's question. The two are drawn over disjoint people instead.
    people = list(range(n_staff))
    rng.shuffle(people)
    half = max(2, n_staff // 2)
    pool = {"max_shifts": people[:half], "min_shifts": people[half:] or people[:2]}
    for t in combo:
        if t == "rest":
            rules.append({"t": "rest"})
        elif t == "one_per_day":
            rules.append({"t": "one_per_day"})
        elif t == "max_shifts":
            src = pool["max_shifts"] if "min_shifts" in combo else people
            n = len(src) if tight >= 2 else (min(3, len(src)) if tight else
                                             rng.randint(1, min(3, len(src))))
            for p in rng.sample(src, min(n, len(src))):
                rules.append({"t": "max_shifts", "p": p,
                              "k": 1 if tight else rng.randint(1, 2)})
        elif t == "min_shifts":
            src = pool["min_shifts"] if "max_shifts" in combo else people
            n = min(3, len(src)) if tight >= 2 else (2 if tight else rng.randint(1, 2))
            for p in rng.sample(src, min(n, len(src))):
                rules.append({"t": "min_shifts", "p": p,
                              "k": 2 if tight else rng.randint(1, 2)})
        elif t in ("pair_conflict", "handover", "buddy"):
            n_pairs = 2 if (tight and t != "handover") else (
                rng.randint(1, 2) if t == "pair_conflict" else 1)
            for _ in range(n_pairs):
                # Redraw a pair already taken rather than skip it. Skipping dropped the
                # only `handover` of a `pair_conflict+handover` week whenever the two
                # drew the same people, so 0.7 % of questions labelled with a combination
                # carried one rule type only (domain-19 audit).
                free = [(a, b) for a in range(n_staff) for b in range(n_staff)
                        if a != b and (a, b) not in pairs_used and (b, a) not in pairs_used]
                if not free:
                    break
                a, b = rng.choice(free)
                pairs_used.add((a, b))
                rules.append({"t": t, "a": a, "b": b})
    if len(rules) < 2 or locally_contradictory(rules):
        return None
    if {r["t"] for r in rules} != set(combo):
        return None
    return tuple(rules)


def floor_above_availability(rules, allowed) -> bool:
    """A floor higher than the number of shifts that person can take at all.

    "Hana must cover at least 2 shifts" when Hana is free and certified for one is
    answered by reading Hana's row, not by scheduling -- and it was the whole answer to
    3 % of `feasible` questions and 45 % of `culprit` ones (domain-19 audit)."""
    return any(r["t"] == "min_shifts" and sum(r["p"] in a for a in allowed) < r["k"]
               for r in rules)


def locally_contradictory(rules) -> bool:
    """Two rules that cancel each other without any scheduling in it.

    "At most 1 and at least 2 for Cy" and "keep Cy and Dee apart, and put Cy only on days
    Dee works" are answerable by reading two lines, so a question built on either is a
    reading question wearing this domain's clothes. The first draft of the `culprit`
    builder produced exactly that and it is what reading the generated examples caught.
    """
    kinds: dict[frozenset[int], set[str]] = {}
    for r in rules:
        if r["t"] in ("pair_conflict", "buddy"):
            kinds.setdefault(frozenset((r["a"], r["b"])), set()).add(r["t"])
    if any(len(v) > 1 for v in kinds.values()):
        return True
    lo: dict[int, int] = {}
    hi: dict[int, int] = {}
    for r in rules:
        if r["t"] == "min_shifts":
            lo[r["p"]] = max(lo.get(r["p"], 0), r["k"])
        elif r["t"] == "max_shifts":
            hi[r["p"]] = min(hi.get(r["p"], 99), r["k"])
    return any(lo[p] > hi[p] for p in lo.keys() & hi.keys())


def make_instance(rng: random.Random, combo: tuple[str, str],
                  tight: int | None = None) -> Instance | None:
    if tight is None:
        tight = rng.randrange(3)
    n_days = rng.randint(3, 4)
    days = tuple(DAYS[:n_days])
    parts = rng.choice([("morning", "night"), ("morning", "afternoon"),
                        ("morning", "afternoon", "night")])
    slots = []
    for d in range(n_days):
        for part in parts:
            slots.append((d, part, None))
    slots = slots[:rng.randint(5, 7)]
    n_days = max(d for d, _, _ in slots) + 1
    days = days[:n_days]
    n_staff = (rng.randint(4, 5) if tight >= 2 else
               rng.randint(4, 6) if tight else rng.randint(5, 7))
    names = _display_names(rng, n_staff)

    pool = tuple(rng.sample(SKILLS, 3))
    # A certification requirement on a couple of shifts, held by a couple of people.
    slots = [(d, part, pool[0] if rng.random() < 0.28 else None) for d, part, _ in slots]
    needed = {s[2] for s in slots if s[2]}
    skills = []
    for p in range(n_staff):
        mine = [k for k in pool if rng.random() < 0.45]
        skills.append(tuple(mine))
    for k in needed:                      # somebody must hold every required ticket
        holders = [p for p in range(n_staff) if k in skills[p]]
        if len(holders) < 2:
            for p in rng.sample(range(n_staff), 2):
                if k not in skills[p]:
                    skills[p] = skills[p] + (k,)

    away = []
    for p in range(n_staff):
        n_away = rng.choice([1, 2, 2, 3] if tight >= 2 else
                            [1, 2, 2] if tight else [0, 1, 1, 2])
        away.append(tuple(sorted(rng.sample(range(len(slots)), n_away))))

    def recompute():
        out = []
        for s, (d, part, need) in enumerate(slots):
            ok = [p for p in range(n_staff)
                  if s not in away[p] and (need is None or need in skills[p])]
            out.append(tuple(ok))
        return out

    # The assignment space has to stay inside `MAX_DOMAIN` because the label comes from
    # enumerating it. Rejecting every instance that overshoots would have capped the
    # roster at four or five shifts, and with it the number of candidate requests -- the
    # option count this domain is meant to push up. So an oversized instance is *shaped*
    # to fit instead: leave is added to whichever shift has the widest choice, which
    # narrows the product without narrowing the roster. Unevenness is the point: one shift
    # may still be open to six people while the week as a whole enumerates cheaply.
    allowed = recompute()
    if any(len(a) < 2 for a in allowed):
        return None
    for _ in range(40):
        size = 1
        for a in allowed:
            size *= len(a)
        if size <= MAX_DOMAIN:
            break
        widest = max(range(len(slots)), key=lambda s: len(allowed[s]))
        if len(allowed[widest]) <= 2:
            return None
        p = rng.choice(allowed[widest])
        away[p] = tuple(sorted(set(away[p]) | {widest}))
        allowed = recompute()
    else:
        return None
    if any(len(a) < 2 for a in allowed):
        return None
    size = 1
    for a in allowed:
        size *= len(a)
    if size > MAX_DOMAIN:
        return None

    rules = _make_rules(rng, combo, len(slots), n_staff, tight)
    if rules is None or floor_above_availability(rules, allowed):
        return None
    return Instance(
        site=rng.choice(SITES), week=f"{rng.randint(1, 27)} {rng.choice(MONTHS)}",
        days=days, slots=tuple(slots), names=names, skills=tuple(skills),
        away=tuple(away), rules=rules, combo=combo, allowed=tuple(allowed),
        tight=tight)


# ---- the solver ------------------------------------------------------------------------

def violated(inst: Instance, a: tuple[int, ...], rules) -> list[int]:
    """Indices of the rules this complete assignment breaks. Unary facts are not rules:
    they are already baked into `inst.allowed`, so anything reaching here is locally legal."""
    counts = [0] * inst.n_staff
    days_on: list[set[int]] = [set() for _ in range(inst.n_staff)]
    slots_of: list[list[int]] = [[] for _ in range(inst.n_staff)]
    for s, p in enumerate(a):
        counts[p] += 1
        days_on[p].add(inst.day_of(s))
        slots_of[p].append(s)
    bad = []
    for i, r in enumerate(rules):
        t = r["t"]
        if t == "max_shifts":
            if counts[r["p"]] > r["k"]:
                bad.append(i)
        elif t == "min_shifts":
            if counts[r["p"]] < r["k"]:
                bad.append(i)
        elif t == "rest":
            if any(a[s] == a[s + 1] for s in range(len(a) - 1)):
                bad.append(i)
        elif t == "one_per_day":
            if any(len(slots_of[p]) > len(days_on[p]) for p in range(inst.n_staff)):
                bad.append(i)
        elif t == "pair_conflict":
            if days_on[r["a"]] & days_on[r["b"]]:
                bad.append(i)
        elif t == "handover":
            sa, sb = slots_of[r["a"]], slots_of[r["b"]]
            if sa and sb and max(sa) > min(sb):
                bad.append(i)
        elif t == "buddy":
            if days_on[r["a"]] - days_on[r["b"]]:
                bad.append(i)
    return bad


def analyse(inst: Instance) -> tuple[list[tuple[int, ...]], list[frozenset[int]]] | None:
    """Enumerate the whole locally-legal assignment space once, with the set of policy
    rules each assignment breaks. Every family below is a filter over this one pass --
    re-solving per family was the first draft and it was 30x the work for the same
    answers. None if the space would exceed `MAX_DOMAIN`."""
    size = 1
    for x in inst.allowed:
        size *= len(x)
    if size > MAX_DOMAIN:
        return None
    domain = list(itertools.product(*[list(x) for x in inst.allowed]))
    viols = [frozenset(violated(inst, a, inst.rules)) for a in domain]
    return domain, viols


def feasible_set(inst: Instance, fixed: dict[int, int] | None = None
                 ) -> list[tuple[int, ...]] | None:
    """Convenience wrapper for tests and for hand-checking: the feasible assignments,
    optionally with some shifts pinned."""
    got = analyse(inst)
    if got is None:
        return None
    domain, viols = got
    out = [a for a, v in zip(domain, viols) if not v]
    for s, p in (fixed or {}).items():
        out = [a for a in out if a[s] == p]
    return out


# ---- rendering the criteria --------------------------------------------------------------

def rule_text(inst: Instance, r: dict) -> str:
    n = inst.names
    t = r["t"]
    if t == "max_shifts":
        return f"{n[r['p']]} may cover at most {r['k']} shift{'s' if r['k'] > 1 else ''} this week."
    if t == "min_shifts":
        return f"{n[r['p']]} must cover at least {r['k']} shift{'s' if r['k'] > 1 else ''} this week."
    if t == "rest":
        return "Nobody may cover two shifts that are next to each other in the shift list."
    if t == "one_per_day":
        return "Nobody may cover more than one shift on the same day."
    if t == "pair_conflict":
        return f"{n[r['a']]} and {n[r['b']]} must not both be on duty on the same day."
    if t == "handover":
        return (f"{n[r['a']]} is handing over to {n[r['b']]}: every shift {n[r['a']]} covers "
                f"must come before every shift {n[r['b']]} covers.")
    if t == "buddy":
        return f"{n[r['a']]} may only be on duty on a day when {n[r['b']]} is also on duty."
    raise ValueError(t)


def rule_gloss(inst: Instance, r: dict) -> str:
    t = r["t"]
    if t == "max_shifts":
        return "a ceiling on one person's total, read over the whole week"
    if t == "min_shifts":
        return "a floor under one person's total, read over the whole week"
    if t == "rest":
        return "a rest rule, read over consecutive shifts"
    if t == "one_per_day":
        return "a same-day rule, read over the shifts falling on one day"
    if t == "pair_conflict":
        return "a keep-apart rule between two people, read over each day"
    if t == "handover":
        return "an ordering rule between two people's shifts"
    if t == "buddy":
        return "a cover rule that ties one person's days to another's"
    raise ValueError(t)


def criteria_block(inst: Instance) -> str:
    return "\n".join(f"- {rule_text(inst, r)}" for r in inst.rules)


# ---- rendering the facts, three ways -------------------------------------------------

def _shift_rows(inst: Instance) -> list[tuple[str, str, str]]:
    out = []
    for s in range(inst.n_slots):
        d, part, need = inst.slots[s]
        out.append((f"{s + 1}", f"{inst.days[d]} {part}", need or "-"))
    return out


def _away_text(inst: Instance, p: int) -> str:
    if not inst.away[p]:
        return "available all week"
    return "not available: " + ", ".join(
        f"shift {s + 1} ({inst.label(s)})" for s in inst.away[p])


def render(inst: Instance, shape: str, booked: dict[int, int] | None = None) -> str:
    booked = booked or {}
    if shape == "roster":
        return _render_roster(inst, booked)
    if shape == "calendar":
        return _render_calendar(inst, booked)
    if shape == "email":
        return _render_email(inst, booked)
    raise ValueError(shape)


def _render_roster(inst: Instance, booked: dict[int, int]) -> str:
    lines = [f"{inst.site} — shift roster, week of {inst.week}", "",
             "Shifts to cover", "| # | when | certification required |",
             "|---|---|---|"]
    for num, when, need in _shift_rows(inst):
        lines.append(f"| {num} | {when} | {need} |")
    lines += ["", "Staff", "| name | certifications held | availability |", "|---|---|---|"]
    for p, name in enumerate(inst.names):
        held = ", ".join(inst.skills[p]) or "none recorded"
        lines.append(f"| {name} | {held} | {_away_text(inst, p)} |")
    lines += ["", "Already booked"]
    if booked:
        for s in sorted(booked):
            lines.append(f"- shift {s + 1} ({inst.label(s)}): {inst.names[booked[s]]}")
    else:
        lines.append("- nothing booked yet; every shift above is still open")
    return "\n".join(lines)


def _render_calendar(inst: Instance, booked: dict[int, int]) -> str:
    lines = [f"{inst.site} — week planner, week of {inst.week}", ""]
    for d, day in enumerate(inst.days):
        lines.append(f"{day}")
        for s in range(inst.n_slots):
            if inst.day_of(s) != d:
                continue
            _, part, need = inst.slots[s]
            tail = f" [needs {need}]" if need else ""
            who = inst.names[booked[s]] if s in booked else "OPEN"
            lines.append(f"    shift {s + 1}  {part:<10}{tail:<32} {who}")
        # Per shift, never per day. This line used to read "off today: Ana V." for anyone
        # away from ANY shift that day, which says Ana cannot work that day at all; in
        # 84 % of listings she was away from only part of it and the label still used her
        # for the rest (domain-19 audit). The calendar then contradicted its own leave list.
        off = []
        for p in range(inst.n_staff):
            mine = [s + 1 for s in inst.away[p] if inst.day_of(s) == d]
            if mine:
                word = "shift" if len(mine) == 1 else "shifts"
                off.append(f"{inst.names[p]} ({word} {', '.join(map(str, mine))})")
        lines.append(f"    away: {', '.join(off) if off else 'nobody'}")
        lines.append("")
    lines.append("Certifications on file")
    for p, name in enumerate(inst.names):
        held = ", ".join(inst.skills[p]) or "none recorded"
        lines.append(f"    {name}: {held}")
    lines.append("")
    lines.append("Exact absences, by shift number")
    for p, name in enumerate(inst.names):
        lines.append(f"    {name}: {_away_text(inst, p)}")
    return "\n".join(lines)


def _render_email(inst: Instance, booked: dict[int, int]) -> str:
    rng = random.Random(f"{inst.site}:{inst.week}:{inst.n_slots}:{len(inst.rules)}")
    mgr, sched, hr = rng.choice(MANAGERS), rng.choice(SCHEDULERS), rng.choice(HR)
    style = rng.choice(THREAD_STYLES)
    out = [f"Subject: {style['subject']} — {inst.site}, week of {inst.week}", ""]
    out += [f"From: {mgr}", style["shifts"], ""]
    for num, when, need in _shift_rows(inst):
        out.append(f"  shift {num} — {when}"
                   + (f" — needs someone with a {need}" if need != "-" else ""))
    out += ["", f"From: {sched}", style["staff"], ""]
    for p, name in enumerate(inst.names):
        held = ", ".join(inst.skills[p]) or "nothing on file"
        out.append(f"  {name} — {held}")
    out += ["", f"From: {hr}", style["leave"], ""]
    for p, name in enumerate(inst.names):
        out.append(f"  {name} — {_away_text(inst, p)}")
    out += ["", f"From: {mgr}"]
    if booked:
        out.append(style["booked"])
        for s in sorted(booked):
            out.append(f"  shift {s + 1} ({inst.label(s)}) — {inst.names[booked[s]]}")
    else:
        # Ten of the fourteen model-written `open` lines say "every shift listed below",
        # and this is the last message of the thread, so the lines have to follow it or
        # the wording points at nothing (domain-19 audit). Restating the shifts adds
        # no fact.
        out.append(style["open"])
        for s in range(inst.n_slots):
            out.append(f"  shift {s + 1} ({inst.label(s)}) — open")
    return "\n".join(out)


# ---- the five families -------------------------------------------------------------------
# Each returns (question_text, instructions, options, descriptions, gold_index, booked, meta)
# built from the solver. Every one of them shuffles its options before returning.

def _plan_str(inst: Instance, a: tuple[int, ...]) -> str:
    return "; ".join(f"{s + 1} {inst.names[p]}" for s, p in enumerate(a))


def _plan_long(inst: Instance, a: tuple[int, ...]) -> str:
    return ", ".join(f"{inst.label(s)} {inst.names[p]}" for s, p in enumerate(a))


def _shuffle(rng: random.Random, options, descs, gold):
    order = list(range(len(options)))
    rng.shuffle(order)
    return ([options[i] for i in order], [descs[i] for i in order], order.index(gold))


def _rank(vals) -> list[int]:
    """Per value: 0 if it is the strict minimum of the list, 2 the strict maximum, else 1."""
    lo, hi = min(vals), max(vals)
    return [1 if lo == hi else 0 if v == lo else 2 if v == hi else 1 for v in vals]


# ---- answer-blind option cues, balanced across a task --------------------------------
# `grant`, `move` and `culprit` each have several ways to draw the same question (which
# request is the answer, which shift is moved, which rule set). Drawn blind, the answer
# carried surface cues a per-option scorer can learn without doing any scheduling: the
# request on the narrowest shift, the shift with the most people able to take it, the rule
# that rules out most of the week alone (shortcut audit). Each builder describes
# every option by a small tuple of such cues and, while a tally is active, takes the draw
# whose answer's cue tuple has so far been the answer least often relative to how often
# it has appeared as an option. Every cue tuple then ends up the answer about as often as
# chance says, so a scorer learns nothing from it -- and never its opposite, which picking
# "the draw the cues score worst on" would teach instead. The loader holds one tally per
# task; direct calls (tests) draw uniformly.
_TALLY: dict | None = None


def _subkeys(cue: tuple) -> list[tuple]:
    """Every single cue and every pair of cues of one option: what a scorer on one or
    two surface features would see."""
    n = len(cue)
    return ([(i, cue[i]) for i in range(n)]
            + [(i, j, cue[i], cue[j]) for i in range(n) for j in range(i + 1, n)])


def _balanced(rng: random.Random, fam: str, cands, strict: bool = False):
    """cands: [(payload, [cue tuple per option], gold index)]. Returns one payload, or
    None when `strict` and every candidate's answer carries a single cue that has already
    been the answer more than `CUE_SLACK` times as often as answers are in general (the
    week then goes to another family). Pairs of cues steer the choice but never drop a
    week: held to the same bound they cost half of `grant`."""
    if not cands:
        return None
    if _TALLY is None:
        return rng.choice(cands)[0]
    gold_n, opt_n = _TALLY.setdefault(fam, (Counter(), Counter()))
    base = sum(gold_n.values()) / sum(opt_n.values()) if opt_n else 0.0

    def ratio(c, singles=False):
        ks = _subkeys(c[1][c[2]])
        return max((gold_n[k] / opt_n[k] if opt_n[k] else 0.0)
                   for k in (ks[:len(c[1][c[2]])] if singles else ks))

    if strict and opt_n and min(ratio(c, True) for c in cands) > CUE_SLACK * base:
        return None
    scored = [(ratio(c), c) for c in cands]
    best = min(r for r, _ in scored)
    payload, keys, g = rng.choice([c for r, c in scored if r == best])
    for k in _subkeys(keys[g]):
        gold_n[k] += 1
    for cue in keys:
        for k in _subkeys(cue):
            opt_n[k] += 1
    return payload


def _type_sets(inst: Instance) -> tuple[frozenset[int], frozenset[int]]:
    """Rule indices of the combination's first and second type."""
    A, B = inst.combo
    return (frozenset(i for i, r in enumerate(inst.rules) if r["t"] == A),
            frozenset(i for i, r in enumerate(inst.rules) if r["t"] == B))


def _rule_spread(rng: random.Random, items) -> list:
    """`items` as (assignment, broken rules), ordered round-robin over the broken rules so
    that a prefix of any length is spread over as many different rules as possible."""
    by_rule: dict[int, list] = {}
    for a, v in items:
        for i in v:
            by_rule.setdefault(i, []).append(a)
    for lst in by_rule.values():
        rng.shuffle(lst)
    order = list(by_rule)
    rng.shuffle(order)
    out, seen = [], set()
    while True:
        progressed = False
        for i in order:
            while by_rule[i] and by_rule[i][-1] in seen:
                by_rule[i].pop()
            if by_rule[i]:
                a = by_rule[i].pop()
                out.append(a)
                seen.add(a)
                progressed = True
        if not progressed:
            return out


def _f_pick(inst, rng, an):
    domain, viols, feas = an
    bad = [(a, v) for a, v in zip(domain, viols) if v]
    if not feas or not bad:
        return None
    # Where the high option counts come from. The locally-legal-but-policy-breaking
    # assignments number in the thousands, so `pick` is the family that can carry a field
    # of twenty-four candidates; the corpus is 63 % binary and short of these.
    k = min(rng.choice([2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24]), len(bad) + 1)
    gold_a = rng.choice(feas)
    # Spread the distractors over as many different broken rules as possible, so that no
    # single rule separates the answer from the field -- eliminating the field one rule at
    # a time is exactly the shortcut this domain exists to deny.
    # And split them evenly between plans that break only the first rule type and plans
    # that break only the second. Spread over rules alone, most of the field broke the
    # type with more rules in it, and checking that one type found the answer 0.55 of
    # the time against 0.17 chance on the held-out combinations -- "the plan that keeps
    # the first rule listed" alone 0.40 (shortcut audit). Plans breaking both
    # types fill in only when a pure class runs out.
    tA, tB = _type_sets(inst)
    only_a = _rule_spread(rng, [(a, v) for a, v in bad if v <= tA])
    only_b = _rule_spread(rng, [(a, v) for a, v in bad if v <= tB])
    both = _rule_spread(rng, [(a, v) for a, v in bad if not v <= tA and not v <= tB])
    picked: list[tuple[int, ...]] = []
    turn = rng.randrange(2)
    while len(picked) < k - 1 and (only_a or only_b):
        src = (only_a, only_b)[turn] or (only_a, only_b)[1 - turn]
        picked.append(src.pop(0))
        turn = 1 - turn
    while len(picked) < k - 1 and both:
        picked.append(both.pop(0))
    if len(picked) < k - 1:
        return None
    rows = picked + [gold_a]
    opts = [_plan_str(inst, a) for a in rows]
    if len(set(opts)) != len(opts):
        return None
    # Above eight candidates the expanded form of every plan would cost more of the
    # prompt than the roster it refers to, and the option string already names a person
    # per shift in shift order, so it says the same thing.
    descs = ([f"cover plan: {_plan_long(inst, a)}" for a in rows] if len(rows) <= 8
             else [None] * len(rows))
    opts, descs, gold = _shuffle(rng, opts, descs, len(opts) - 1)
    broken = {i for a in picked for i in viols[domain.index(a)]}
    q = "Which of these cover plans can the depot actually run?"
    instr = ("Each plan names one person per shift, in shift-number order. Every plan "
             "already respects the certifications and the leave in the state above; what "
             "separates them is the roster policy. Pick the only plan that breaks none of "
             "these rules:\n" + criteria_block(inst))
    return q, instr, opts, descs, gold, {}, {
        "n_feasible": len(feas), "n_domain": len(domain), "rules_broken": len(broken)}


def _candidate_rules(t: str, n_staff: int) -> list[dict]:
    """Every rule of type `t` this instance could carry. Small enough to try them all."""
    if t in ("max_shifts", "min_shifts"):
        return [{"t": t, "p": p, "k": k} for p in range(n_staff) for k in (1, 2)]
    if t in ("rest", "one_per_day"):
        return [{"t": t}]
    return [{"t": t, "a": a, "b": b} for a in range(n_staff) for b in range(n_staff)
            if a != b]


def violation_matrix(inst: Instance, domain, rules) -> np.ndarray:
    """`violated`, vectorised: a bool array [assignment, rule]. Used only to *search* for
    a culprit question over ~50 candidate rules; the question that search settles on is
    re-checked with `violated` itself before it is emitted, and a test holds the two to
    agreement on every rule type."""
    D = np.asarray(domain, dtype=np.int16).reshape(len(domain), inst.n_slots)
    n = D.shape[0]
    P = inst.n_staff
    day = np.array([inst.day_of(s) for s in range(inst.n_slots)])
    n_days = int(day.max()) + 1
    on = D[:, :, None] == np.arange(P)[None, None, :]            # [a, slot, person]
    counts = on.sum(1)                                             # [a, person]
    per_day = np.zeros((n, P, n_days), dtype=np.int16)
    for s in range(inst.n_slots):
        per_day[:, :, day[s]] += on[:, s, :]
    days_on = per_day > 0
    idx = np.arange(inst.n_slots)
    cols = []
    for r in rules:
        t = r["t"]
        if t == "max_shifts":
            v = counts[:, r["p"]] > r["k"]
        elif t == "min_shifts":
            v = counts[:, r["p"]] < r["k"]
        elif t == "rest":
            v = (D[:, :-1] == D[:, 1:]).any(1)
        elif t == "one_per_day":
            v = (per_day > 1).any((1, 2))
        elif t == "pair_conflict":
            v = (days_on[:, r["a"]] & days_on[:, r["b"]]).any(1)
        elif t == "handover":
            A, B = on[:, :, r["a"]], on[:, :, r["b"]]
            last_a = np.where(A, idx, -1).max(1)
            first_b = np.where(B, idx, inst.n_slots).min(1)
            v = A.any(1) & B.any(1) & (last_a > first_b)
        elif t == "buddy":
            v = (days_on[:, r["a"]] & ~days_on[:, r["b"]]).any(1)
        else:
            raise ValueError(t)
        cols.append(v)
    return np.stack(cols, 1)


def narrow(inst: Instance, rng: random.Random, width: int | None) -> Instance:
    """The same week with more leave: each shift keeps `width` (else 2 or 3) of the people
    who could take it. Leave is a unary fact, so this changes the state and nothing about
    what kind of question can be asked of it -- but a week where most shifts are down to
    two names is one where a coupling rule actually binds, which is what `culprit` needs."""
    away = [set(a) for a in inst.away]
    allowed = [list(a) for a in inst.allowed]
    for s in range(inst.n_slots):
        w = width if width else rng.choice([2, 2, 3])
        while len(allowed[s]) > w:
            p = rng.choice(allowed[s])
            allowed[s].remove(p)
            away[p].add(s)
    return replace(inst, away=tuple(tuple(sorted(a)) for a in away),
                   allowed=tuple(tuple(a) for a in allowed))


def _clashing(rules) -> bool:
    """Two ceilings on one person, or two rules on one pair: redundant at best."""
    seen = set()
    for r in rules:
        key = ((r["t"], r["p"]) if r["t"] in ("max_shifts", "min_shifts") else
               ("pair", frozenset((r["a"], r["b"]))) if "a" in r else (r["t"],))
        if key in seen:
            return True
        seen.add(key)
    return locally_contradictory(rules)


def _culprit_wins(inst: Instance) -> list[tuple[tuple[dict, ...], int, list[float]]]:
    """Every rule set this week can carry a culprit question over, with its answer.

    A rule set qualifies if it holds both of the combination's types and nothing else,
    has at least three rules, cannot be met, and exactly one of its rules restores the
    week when lifted. Candidates are the week's own rules, with one of them optionally
    dropped and one optional rule of the combination's types added. The first version
    only ever *added* a rule to a coverable week: `rest` and `one_per_day` are single
    global rules already present, so they could never be the answer, eleven of the
    twenty-one combinations produced no culprit at all, and the family was 2.5 % of the
    row against the 15 % it asks for (domain-19 audit).

    Each win is (rules, culprit index, share of the week each rule rules out alone)."""
    domain = list(itertools.product(*[list(x) for x in inst.allowed]))
    R = list(inst.rules)
    extra = [c for t in dict.fromkeys(inst.combo) for c in _candidate_rules(t, inst.n_staff)
             if c not in R]
    pool = R + extra
    M = violation_matrix(inst, domain, pool)
    # How much of the week each rule rules out on its own, a cue `_f_culprit` balances.
    bite = np.round(M.mean(0), 2)
    wins = []
    for drop in [None] + list(range(len(R))):
        base = [i for i in range(len(R)) if i != drop]
        for add in [None] + list(range(len(R), len(pool))):
            sel = base + ([add] if add is not None else [])
            rules = tuple(pool[i] for i in sel)
            if len(rules) < 3 or {r["t"] for r in rules} != set(inst.combo):
                continue
            if _clashing(rules) or floor_above_availability(rules, inst.allowed):
                continue
            V = M[:, sel]
            k = V.sum(1)
            if not k.all():
                continue                      # the week can still be covered
            one = k == 1
            restores = [j for j in range(len(sel)) if (one & V[:, j]).any()]
            if len(restores) == 1:
                wins.append((rules, restores[0], [float(bite[i]) for i in sel]))
    return wins


def _f_culprit(inst, rng, an):
    """Which single rule makes the week impossible to cover.

    Searched, not waited for: over the week as drawn and, failing that, over the same
    week with more leave (`narrow`), for a rule set with exactly one rule whose removal
    restores it (`_culprit_wins`). The answer's rule *type* is drawn uniformly among the
    types that can be the answer here, so a prior over types -- which an earlier build
    rewarded with 0.342 against 0.246 chance -- has nothing to learn. The winning set is
    then re-checked with the plain `violated` over the whole space before it is emitted.
    """
    for attempt in range(4):
        cur = inst if attempt == 0 else narrow(inst, rng, None if attempt == 1 else 2)
        wins = _culprit_wins(cur)
        if not wins:
            continue
        kinds = sorted({rules[c]["t"] for rules, c, _ in wins})
        kind = rng.choice(kinds)
        mine = [w for w in wins if w[0][w[1]]["t"] == kind]
        # Drawn blind, the culprit was the rule that rules out most of the week on its
        # own 0.61 of the time against 0.25 chance (shortcut audit): the rule
        # that bites hardest alone is usually the one the week cannot carry, and picking
        # it needs no search over the others. Balanced over the task (`_balanced`), as
        # are two more cues of the answer: how many options share its type, and how few
        # shifts the people it names can take (0.36 with the type).
        avail = [sum(p in a for a in cur.allowed) for p in range(cur.n_staff)]

        def cues(w):
            tc = Counter(r["t"] for r in w[0])
            short = [min((avail[r[k]] for k in ("p", "a", "b") if k in r), default=99)
                     for r in w[0]]
            return list(zip(_rank(w[2]), _rank([tc[r["t"]] for r in w[0]]), _rank(short)))

        got = _balanced(rng, "culprit", [((w[0], w[1]), cues(w), w[1]) for w in mine],
                        strict=True)
        if got is None:
            continue
        rules, c = got
        domain = itertools.product(*[list(x) for x in cur.allowed])
        viol = [set(violated(cur, a, rules)) for a in domain]
        if any(not v for v in viol) or \
                [j for j in range(len(rules)) if {j} in viol] != [c]:
            raise AssertionError("culprit search disagrees with `violated`")
        opts = [rule_text(cur, r) for r in rules]
        if len(set(opts)) != len(opts):
            continue
        descs = [rule_gloss(cur, r) for r in rules]
        opts, descs, gold = _shuffle(rng, opts, descs, c)
        q = ("Which of these rules is the one that, lifted on its own with every other rule "
             "kept, would let this week be covered?")
        instr = ("The rules below were all agreed for this roster, and with the staff and "
                 "leave in the state above they cannot all be met at once. Exactly one of "
                 "them, if it were lifted and the other rules kept, would make a valid "
                 "roster possible. Which one is it?")
        return q, instr, opts, descs, gold, {}, {"n_rules": len(rules),
                                                 "culprit_type": rules[c]["t"],
                                                 "narrowed": attempt > 0}, cur
    return None


def _f_grant(inst, rng, an):
    """Which pending request survives. The option count is pushed up on purpose here:
    63 % of the corpus is binary and a rota is the natural place for twenty candidates.

    Which shifts are already confirmed decides how many requests are still open, so the
    booking is not drawn once but chosen: of several draws, the three leaving the largest
    fields of locally-legal-but-ungrantable requests are kept, and `_balanced` picks the
    question among them. Every one of them is free of any
    state-level objection -- the person is available and certified -- so the field can only
    be cut down with the policy."""
    domain, viols, feas = an
    if not feas:
        return None
    draws = {}
    for _ in range(8):
        base = rng.choice(feas)
        n_fixed = rng.randint(1, 2)
        booked = {s: base[s] for s in sorted(rng.sample(range(inst.n_slots), n_fixed))}
        live = [a for a in feas if all(a[s] == p for s, p in booked.items())]
        free = [s for s in range(inst.n_slots) if s not in booked]
        if len(free) < 2 or not live:
            continue
        grantable = {(a[s], s) for a in live for s in free}
        reqs = [(p, s) for s in free for p in inst.allowed[s]]
        good = [r for r in reqs if r in grantable]
        bad = [r for r in reqs if r not in grantable]
        if not good or not bad:
            continue
        draws[tuple(sorted(booked.items()))] = (booked, free, good, bad)
    if not draws:
        return None
    # The three bookings leaving the largest fields, not just the largest: more ways to
    # draw the question is what lets `_balanced` keep the cues level without dropping
    # the week.
    best = sorted(draws.values(), key=lambda d: -len(d[3]))[:3]
    want_k = rng.choice([2, 3, 4, 5, 6, 8, 10, 14, 18, 24, 30])
    tA, tB = _type_sets(inst)
    cands = []
    for booked, free, good, bad in best:
        k = min(want_k, len(bad) + 1)
        # The person named by the answer has to be named by a wrong request too, or the
        # answer is "the one person nobody else mentions" and no scheduling is done.
        named = {r[0] for r in bad}
        shared = [r for r in good if r[0] in named]
        if not shared:
            continue
        # Which wrong requests one rule type alone would already refuse. Drawn blind to
        # this, either type on its own cut the field down: "the request one type alone
        # still allows" found the answer 0.47-0.50 of the time against 0.26 chance on
        # the held-out combinations (shortcut audit). Tier 0: only the two
        # types together refuse it; tier 1: one type does (`side` says which); tier 2:
        # both do.
        live = [(a, v) for a, v in zip(domain, viols)
                if all(a[s] == p for s, p in booked.items())]
        passA = {(a[s], s) for a, v in live if not (v & tA) for s in free}
        passB = {(a[s], s) for a, v in live if not (v & tB) for s in free}
        tier = {r: (0 if r in passA and r in passB else
                    1 if r in passA or r in passB else 2) for r in bad}
        side = {r: int(r in passB) for r in bad}
        noise = {r: rng.random() for r in bad}

        def field(gold_r):
            """Greedy, one wrong request at a time. In order of precedence: the answer's
            person first, then its shift (a request on the one shift no wrong request
            named was the answer 0.36 of the time against 0.26); spread over people,
            the answer counting as a mention of its person (a flat sample kept
            producing a field in which every wrong request named the same person, and
            one rule about that person cut the whole field down; and the answer's
            person named most was a cue of its own); best tier; the two tier-1 sides
            kept level; chance."""
            picked: list[tuple[int, int]] = []
            left = set(bad)
            uses: Counter = Counter({gold_r[0]: 1})
            ones = [0, 0]
            while len(picked) < k - 1 and left:
                def key(r):
                    return (r[0] != gold_r[0] if not picked else 0,
                            r[1] != gold_r[1] if len(picked) == 1 else 0,
                            uses[r[0]], tier[r],
                            tier[r] == 1 and ones[side[r]] > ones[1 - side[r]], noise[r])
                r = min(left, key=key)
                picked.append(r)
                left.discard(r)
                uses[r[0]] += 1
                if tier[r] == 1:
                    ones[side[r]] += 1
            return picked

        # Several answers are tried and the surface cues of the request -- how many
        # people could take its shift, how often its person and its shift are named, how
        # early its shift is -- are balanced over the task
        # (`_balanced`). Blind, the answer sat on the narrowest shift named 0.36-0.38 of
        # the time against 0.26, and a scorer on two such cues reached 0.46.
        # "Booked beside it" is not among them: in a week with a rest rule it is the rule.
        def cues(rows):
            pc = Counter(p for p, _ in rows)
            sc = Counter(s for _, s in rows)
            return list(zip(_rank([len(inst.allowed[s]) for _, s in rows]),
                            _rank([pc[p] for p, _ in rows]),
                            _rank([sc[s] for _, s in rows]),
                            _rank([s for _, s in rows])))

        for g in rng.sample(shared, min(8, len(shared))):
            rows = field(g) + [g]
            cands.append(((rows, booked, free, good, bad), cues(rows), len(rows) - 1))
    got = _balanced(rng, "grant", cands, strict=True)
    if got is None:
        return None
    rows, booked, free, good, bad = got
    opts = [f"{inst.names[p]} on shift {s + 1}" for p, s in rows]
    if len(set(opts)) != len(opts):
        return None
    descs = [f"book {inst.names[p]} onto {inst.label(s)}, leaving the other open shifts "
             f"to be filled afterwards" for p, s in rows]
    opts, descs, gold = _shuffle(rng, opts, descs, len(opts) - 1)
    q = "Which one of these requests can still be granted?"
    instr = ("Each request asks for one named person on one still-open shift. Every one "
             "of them is allowed on its own -- that person is free then and holds any "
             "certification the shift needs. Only one of them leaves the remaining open "
             "shifts fillable under the roster policy:\n" + criteria_block(inst)
             + "\nPick the request that can be granted without making the rest of the "
               "week impossible.")
    return q, instr, opts, descs, gold, booked, {"n_open": len(free), "n_good": len(good),
                                                 "n_bad": len(bad)}


def _move_tells(inst: Instance, base, s0: int, x: int, forced: int) -> float:
    """How much two policy-blind guesses would score on this `move` question: "the other
    shift the mover already holds" and "the shift nearest the one being moved". Each is
    the chance the guess (uniform over its tied picks) lands on the answer."""
    cand = [j for j in range(inst.n_slots) if j != s0]
    held = [j for j in cand if base[j] == x]
    near = min(abs(j - s0) for j in cand)
    nearest = [j for j in cand if abs(j - s0) == near]
    return ((forced in held) / len(held) if held else 1 / len(cand)) + \
        (forced in nearest) / len(nearest)


def _move_draws(inst: Instance, rng: random.Random, an) -> list:
    """`_f_move`'s candidate draws on one week: (tell, plan, moved shift, mover, answer,
    completions left), each with exactly one shift forced to change hands and neither
    rule type alone forcing it."""
    domain, viols, feas = an
    if not feas:
        return []
    D = np.asarray(domain, dtype=np.int16).reshape(len(domain), inst.n_slots)
    ok_one = [np.fromiter((not (v & t) for v in viols), bool, len(viols))
              for t in _type_sets(inst)]

    def one_type_forces(base, s0, x, j) -> bool:
        for ok in ok_one:
            rows = D[ok & (D[:, s0] == x)]
            if len(rows) and (rows[:, j] != base[j]).all():
                return True
        return False

    draws = []
    for _ in range(MOVE_DRAWS):
        base = rng.choice(feas)
        s0 = rng.randrange(inst.n_slots)
        others = [p for p in inst.allowed[s0] if p != base[s0]]
        if not others:
            continue
        x = rng.choice(others)
        after = [a for a in feas if a[s0] == x]
        if not after:
            continue
        forced = [j for j in range(inst.n_slots)
                  if j != s0 and all(b[j] != base[j] for b in after)]
        if len(forced) != 1 or one_type_forces(base, s0, x, forced[0]):
            continue
        tell = _move_tells(inst, base, s0, x, forced[0])
        draws.append((tell, base, s0, x, forced[0], len(after)))
    return draws


def _f_move(inst, rng, an):
    """Which other shift must change hands once someone new is forced onto one.

    One draw used to be the question. Its answer was the other shift the *mover already
    held* 59 % of the time against 20 % chance, and the shift *nearest* the moved one 50 %
    of the time -- every ceiling, rest and same-day rule on the mover bites there first,
    and neither guess needs the policy read at all (domain-19 audit). So `MOVE_DRAWS` draws
    are made, and `MOVE_DEBIAS` of the time the one those two guesses score worst on is
    kept (`_move_tells`); a week whose every draw is a giveaway is kept only
    `MOVE_GIVEAWAY_KEEP` of the time and otherwise goes to another family. Inside a task
    the draw is instead chosen by `_balanced`, over those two cues and four more.

    And only draws that need both rule types are kept: one where the rules of either type
    on their own already force the answer to change hands is dropped. Unfiltered, one type
    alone decided 91 % of the held-out questions -- "the shift forced by the second rule
    type alone" scored 0.70 against 0.20 chance, 0.88 on `max_shifts+handover`
    (shortcut audit) -- so the held-out combinations measured one known rule,
    not two composed."""
    if inst.n_slots < 4:
        return None
    # Such draws are rare in a week as drawn (~5 % of weeks carry one), so, as for
    # `culprit`, the same week with more leave (`narrow`) is searched too.
    draws = []
    orig = inst
    for attempt in range(MOVE_NARROW + 1):
        if attempt:
            inst = narrow(orig, rng, None if attempt == 1 else 2)
            an = analyse(inst)
            if an is None:
                continue
            an = (an[0], an[1], [a for a, v in zip(*an) if not v])
        draws = _move_draws(inst, rng, an)
        if draws:
            break
    if not draws:
        return None
    low = min(d[0] for d in draws)
    k = inst.n_slots - 1
    if low >= MOVE_GIVEAWAY and rng.random() >= MOVE_GIVEAWAY_KEEP:
        return None                   # the instance goes to another family instead
    if _TALLY is not None:
        # In a task: every cue of the shift, the two above among them, balanced over
        # the task (`_balanced`). Kept blind, the answer was also the shift the most
        # people could take (0.31 against 0.20) once one-type draws were dropped, and
        # the one whose holder has the fewest shifts, or is named by no rule.
        named = {r.get(key) for r in inst.rules for key in ("p", "a", "b")}

        def cues(d):
            _, base, s0, x, _, _ = d
            cand = [j for j in range(inst.n_slots) if j != s0]
            dist = [abs(j - s0) for j in cand]
            return list(zip([int(base[j] == x) for j in cand],
                            [int(v == min(dist)) for v in dist],
                            _rank([len(inst.allowed[j]) for j in cand]),
                            [int(inst.day_of(j) == inst.day_of(s0)) for j in cand],
                            _rank([base.count(base[j]) for j in cand]),
                            [int(base[j] in named) for j in cand]))

        got = _balanced(
            rng, "move", [(d, cues(d), [j for j in range(inst.n_slots) if j != d[2]]
                           .index(d[4])) for d in draws], strict=True)
        if got is None:
            return None
        tell, base, s0, x, forced, n_after = got
    else:
        if rng.random() < MOVE_DEBIAS:
            draws = [d for d in draws if d[0] == low]
        tell, base, s0, x, forced, n_after = rng.choice(draws)
    cand = [j for j in range(inst.n_slots) if j != s0]
    opts = [f"shift {j + 1} ({inst.label(j)})" for j in cand]
    descs = [f"currently down to {inst.names[base[j]]}" for j in cand]
    opts, descs, gold = _shuffle(rng, opts, descs, cand.index(forced))
    q = "Which other shift has to change hands?"
    instr = (f"The plan for the week is: {_plan_long(inst, base)}. "
             f"{inst.names[x]} now has to take shift {s0 + 1} ({inst.label(s0)}) instead. "
             "Exactly one of the other shifts can no longer stay with the person it is "
             "down to, whatever else is rearranged, under this policy:\n"
             + criteria_block(inst))
    return q, instr, opts, descs, gold, {}, {"n_after": n_after,
                                             "held_by_mover": base[forced] == x,
                                             "tell": round(tell - 2 / k, 3),
                                             "narrowed": inst is not orig}, inst


def _f_feasible(inst, rng, an):
    """Can the week be covered at all -- asked of a narrowed copy of it (`narrow`).

    Drawn weeks are coverable ~96 % of the time, so `no` had to come from the
    over-constrained draws, and those are the ones with more leave and fewer staff: "few
    names per shift -> no" then scored 0.80 against a 0.58 majority (domain-19 audit).
    Asked of a narrowed week instead, `no` is ~15 % of draws, both answers come from the
    same kind of state, and the loader pairs them within bands of `width_band` and
    rule count.

    A `no` has to come from the two types together. Where the rules of one type alone
    already leave the week uncoverable, "check each type on its own, say no if either
    fails" was the whole answer: 38 % of the held-out `no`s, and a lookup on the two
    one-type checks scored 0.70 on the family (shortcut audit). Such a `no` is
    rarer, so inside a task, which says which answer it is waiting for, up to
    `FEASIBLE_TRIES` narrowings are searched for it, falling back to the first usable
    one; the loader's pairing within bands still decides what is kept."""
    want = _TALLY.get("feasible_want") if _TALLY is not None else None
    found = None
    for _ in range(FEASIBLE_TRIES if want is not None else 1):
        cur = narrow(inst, rng, None)
        if floor_above_availability(cur.rules, cur.allowed):
            continue
        got = analyse(cur)
        if got is None:
            continue
        domain, viols = got
        feas = [a for a, v in zip(domain, viols) if not v]
        if not feas and any(not any(not (v & t) for v in viols) for t in _type_sets(cur)):
            continue
        if found is None:
            found = (cur, feas)
        if want is None or int(bool(feas)) == want:
            found = (cur, feas)
            break
    if found is None:
        return None
    cur, feas = found
    opts = ["no", "yes"]
    descs = ["at least one shift cannot be covered without breaking a rule",
             "there is a way to cover every shift and break no rule"]
    q = "Can every shift this week be covered without breaking any of the rules?"
    instr = ("Every person listed may only take a shift they are free for and hold the "
             "certification for. On top of that the roster policy is:\n"
             + criteria_block(cur))
    return q, instr, opts, descs, int(bool(feas)), {}, {
        "n_feasible": len(feas), "width_band": width_band(cur), "n_rules": len(cur.rules),
        "tight": cur.tight}, cur


_BUILD = {"pick": _f_pick, "culprit": _f_culprit, "grant": _f_grant,
          "move": _f_move, "feasible": _f_feasible}


# ---- the loader ---------------------------------------------------------------------------

def build(combo: tuple[str, str], seed: int, i: int, family: str,
          tight: int | None = None) -> list[Example] | None:
    """One instance, one family, three render shapes -- or None if the solver cannot
    decide it. Identical question, options and target across the shapes."""
    rng = _rng(seed, f"{'_'.join(combo)}:{i}")
    inst = make_instance(rng, combo, tight)
    if inst is None:
        return None
    an = analyse(inst)
    if an is None:
        return None
    domain, viols = an
    return _emit(inst, rng, (domain, viols, [a for a, v in zip(domain, viols) if not v]),
                 family, i)


_BANK = None


def _phrasings():
    """The frozen phrasing bank, loaded once. Empty bank -> every template unchanged.
    Template ids and their meanings: lod/assets/phrasing_specs/d19.json."""
    global _BANK
    if _BANK is None:
        from lod.phrasings import PhrasingBank
        _BANK = PhrasingBank.load()
    return _BANK


def _emit(inst: Instance, rng: random.Random, an, family: str, i: int
          ) -> list[Example] | None:
    got = _BUILD[family](inst, rng, an)
    if got is None:
        return None
    q, instr, opts, descs, gold, booked, meta = got[:7]
    if len(got) > 7:
        inst = got[7]            # `culprit` may have searched a narrowed copy of the week
    # One wording per instance, shared by its three shapes: the shape is the controlled
    # variable, so the question text must not move with it.
    q = _phrasings().pick(f"d19.{family}", q, f"{combo_name(inst.combo)}:{family}:{i}")
    out = []
    for shape in SHAPES:
        meta_q = {"family": family, "shape": shape, "combo": "+".join(inst.combo), **meta}
        out.append(Example(
            state=render(inst, shape, booked),
            questions=[Question(id=f"{family}_{i}_{shape}", question=q, instructions=instr,
                                options=list(opts), descriptions=list(descs),
                                target=gold, meta=meta_q)]))
    return out


def width_band(inst: Instance) -> int:
    """Mean number of people who can take each shift, in half-person bands."""
    return int(2 * sum(len(a) for a in inst.allowed) / inst.n_slots)


def _loader(combo: tuple[str, str], seed: int, cap: int | None = None):
    def load(n: int) -> Iterator[Example]:
        global _TALLY
        n = min(n, MAX_PER_TASK if cap is None else cap)
        made = 0                      # examples, not instances: three shapes per instance
        counts = {f: 0.0 for f in FAMILIES}
        # `feasible` goes out in yes/no pairs that share a band of how many people each
        # shift can take, how many rules there are and how over-constrained the draw was
        # (`tight`, which sets staff numbers and leave): the first answer in a band is
        # held back until its opposite turns up in the same band. Balanced overall only,
        # "few names per shift -> no" read 0.80 against a 0.58 majority, because the
        # over-constrained draws that make `no` possible are also the ones with more
        # leave, fewer staff and more rules (domain-19 audit). Held only to within one per
        # band, the bands' leftovers summed to 0.67 on a small load once `no` also had
        # to need both rule types (shortcut audit), and a small load of every
        # task read 63-70 % `yes`.
        pending: dict[tuple[int, int, int], tuple[int, list[Example]]] = {}
        tally: dict = {}              # see `_balanced`: one cue tally per task
        i = 0
        while made < n and i < n * 40:
            i += 1
            rng = _rng(seed, f"{'_'.join(combo)}:{i}")
            inst = make_instance(rng, combo, tight=i % 3)
            if inst is None:
                continue
            got = analyse(inst)
            if got is None:
                continue
            domain, viols = got
            an = (domain, viols, [a for a, v in zip(domain, viols) if not v])
            total = sum(counts.values()) or 1.0
            jitter = random.Random(f"o:{seed}:{i}")
            order = sorted(FAMILIES,
                           key=lambda f: counts[f] / total - FAMILY_SHARE[f]
                           + jitter.random() * 0.03)
            for rank, family in enumerate(order):
                # the answer most bands are waiting for, as a hint to `_f_feasible`
                held = [g for g, _ in pending.values()]
                tally["feasible_want"] = int(2 * sum(held) < len(held))
                _TALLY = tally        # set per call: two loaders may be interleaved
                try:
                    batch = _emit(inst, rng, an, family, i)
                finally:
                    _TALLY = None
                if batch is not None and family == "feasible":
                    g = batch[0].questions[0].target
                    m = batch[0].questions[0].meta
                    band = (m["tight"], m["width_band"], m["n_rules"])
                    if made + 2 * len(batch) > n or pending.get(band, (1 - g,))[0] == g:
                        batch = None
                    elif band not in pending:
                        pending[band] = (g, batch)
                        break                 # the week is spent; nothing out yet
                    else:
                        batch = pending.pop(band)[1] + batch
                if batch is None:
                    # The scarce families (`culprit`, `feasible`) build on a minority of
                    # weeks. When the one furthest behind fails, the week is skipped
                    # `SCARCE_SKIP` of the time rather than handed to a family that never
                    # fails -- but only in a task that has shown it can carry that family,
                    # so a combination that cannot is not starved of everything else.
                    if (rank == 0 and family in SCARCE and counts[family] > 0
                            and counts[family] / total < FAMILY_SHARE[family] - 0.02
                            and jitter.random() < SCARCE_SKIP):
                        break
                    continue
                counts[family] += len(batch) // len(SHAPES)
                made += len(batch)
                for ex in batch:
                    yield ex
                break
    return load


def combo_name(combo: tuple[str, str]) -> str:
    return "_".join(SHORT[t] for t in combo)


# A trained pair's fresh-seed twin is in-distribution evaluation: devreal, never testreal.
# Left to the hash, 2 twins landed in testreal beside the 6 held-out pairs (so "sched_ in
# testreal" no longer meant held-out structure) and only 2 reached devreal, carrying 12
# culprit and 21 feasible questions between them (domain-19 audit). Same fix as rows 38
# and 42.
MAX_PER_TASK_DEV = 200


def tasks() -> list[RealTask]:
    """Trained combinations go to `train`, each with a fresh-seed twin in `devreal`;
    `DEV_COMBOS` are `devreal` and `HELDOUT_COMBOS` `testreal`, and neither is ever
    trained on. The twins share their pair's family (`family_of` strips `_eval`), so
    the devood selection keeps only the dev pairs."""
    out: list[RealTask] = []
    for combo in TRAINED_COMBOS:
        for suffix, split, seed, cap in (("", "train", 0, MAX_PER_TASK_TRAIN),
                                         ("_eval", "devreal", 5051, MAX_PER_TASK_DEV)):
            name = f"sched_{combo_name(combo)}{suffix}"
            out.append(RealTask(
                row=ROW, name=name, licence=LICENCE, url=URL,
                load=_loader(combo, seed, cap), real=False, force_split=split,
                notes=f"scheduling combo {'+'.join(combo)}; code-labelled by exhaustive solver"))
    for combo in DEV_COMBOS:
        name = f"sched_{combo_name(combo)}"
        out.append(RealTask(
            row=ROW, name=name, licence=LICENCE, url=URL,
            load=_loader(combo, 6061), real=False, force_split="devreal",
            notes=f"scheduling combo {'+'.join(combo)}; held out of train and test; "
                  "a dev structure -- selects checkpoints and fits T"))
    for combo in HELDOUT_COMBOS:
        name = f"sched_{combo_name(combo)}"
        out.append(RealTask(
            row=ROW, name=name, licence=LICENCE, url=URL,
            load=_loader(combo, 7717), real=False, force_split="testreal",
            notes=f"scheduling combo {'+'.join(combo)}; NEVER trained on"))
    return out
