"""Row 37 -- Control and sensor (domain 15).

Every other domain in this corpus answers from a snapshot. Row 1 reads a document and
names its class; row 33 reads a record and applies a rule to it; row 36 reads a page and
picks a control. In all of them the state at the moment of the question determines the
answer, and a model that learns "this reading means this label" is right.

Here it is not. **The same reading implies a different action depending on trend and
recent history.** A jacket at 78 C that is falling back toward its band is watched; the
same 78 C rising, in its second reading outside the band, gets a setpoint correction; the
same 78 C rising in its sixth gets an engineer; and a jacket at 68 C -- comfortably
*inside* its band -- gets shut down if it has gained 6 C a reading for the last three and
the critical limit is five readings away. If a reading of 78 always meant the same thing
this would be another label-recovery task and the domain would be worth nothing, so the
generator is built to make history load-bearing and `tests/test_sensors_source.py`
measures that it is: the last reading alone, given an oracle over its position in the
band, predicts the action barely better than the majority class, while the series
predicts it exactly.

**What code does and what the model does.** Code simulates the plant, computes the rate
of change, the consecutive-readings-outside count and the latched-alarm state, and
evaluates the policy. The LLM contributed the `FRAMINGS` table below -- device names,
sites, measurement nouns and unit surface forms -- and nothing else. It never sees a
series and never produces a target, and any framing that failed the validator in
the one-off generation script was dropped rather than repaired.

**Three renderings of one simulation.** `json` (a reading object), `log` (an operator's
prose log) and `table` (a series table). Same values, same question, same answer, so the
shape is a change of surface and not a harder task about parsing.

**What is held out, and why it is a structure rather than a sample.** Two families, each
paired against a trained one so the transfer question is sharp:

    plant      two plant types never simulated in training (`dryer_humidity`,
               `bearing_vibration`), built from the same direction / integrality /
               band-shape primitives as the five trained plants
    trend      `oscillating`, whose segments are `rise` and `fall` -- both trained, in
               `ramp_up` and `ramp_down` -- but whose composition is not

`sensor_action_trained_eval` is the control: trained plants and trained trends, in
`testreal`, unseen instances. A drop from it to `sensor_action_heldout_*` is a failure to
generalise over structure and not a failure on unseen vocabulary.

**Dev holds out structures of its own.** `devreal` selects checkpoints and fits the
temperature, so it has to be as novel as `testreal` -- a dev split of trained plants
measures recall and under-corrects T. It gets its own pair of held-out families, built
the same way and disjoint from the test pair, so selecting on them never touches a
structure the test split reads:

    plant      `tank_level` (low-side, like `cell_soc`) and `motor_current` (high-side,
               like `jacket_temp`) -- `DEV_PLANTS`
    trend      `plateau`, a `rise` that levels off into `flat`; both segments trained,
               the composition not -- `DEV_TRENDS`

`sensor_action_trained_dev` stays as the in-distribution dev read.
"""

from __future__ import annotations

import hashlib
import json as _json
import math
import random
from dataclasses import dataclass, replace
from typing import Iterator

from lod.phrasings import PhrasingBank
from lod.schema import Example, Question
from lod.corpus.services.sources.real.base import RealTask
from lod.corpus.services.sources.synth.grammar import soft

LICENCE = "generated by lod/corpus/services/sources/synth/sensors.py; no third-party data"
URL = "https://github.com/(this repo)/blob/main/src/lod/corpus/services/sources/synth/sensors.py"
ROW = 37
DOMAIN = 15
DEV_NOTE = "held out of train and test; a dev structure -- selects checkpoints and fits T"


# ---- the plant ----------------------------------------------------------------------

@dataclass(frozen=True)
class Plant:
    """One controlled variable, with the band a controller holds it in.

    `direction` is the side the danger is on: `high` for a temperature that runs away
    upward, `low` for a state of charge that runs down. `rmin`/`rmax` are the sensor's
    range, which is what the soft band around a threshold is a fraction of -- the same
    convention as `grammar.soft`, so a borderline reading is borderline by the same
    measure everywhere in the corpus.
    """

    key: str
    measure: str          # "jacket temperature"
    unit: str             # "C"
    lo: float             # normal band, inclusive
    hi: float
    crit: float           # critical limit, on the `direction` side of the band
    direction: str        # "high" | "low"
    rmin: float           # sensor range
    rmax: float
    step: float           # typical magnitude of one reading-to-reading change
    interval: int         # minutes between readings
    integral: bool = False

    @property
    def span(self) -> float:
        return self.rmax - self.rmin


TRAINED_PLANTS = (
    Plant("jacket_temp", "jacket temperature", "C", 58.0, 72.0, 95.0, "high",
          20.0, 120.0, 2.2, 5),
    Plant("cell_soc", "pack state of charge", "%", 35.0, 85.0, 12.0, "low",
          0.0, 100.0, 2.0, 10),
    Plant("line_pressure", "manifold pressure", "kPa", 320.0, 460.0, 610.0, "high",
          100.0, 700.0, 14.0, 2),
    Plant("queue_backlog", "queue depth", "items", 20.0, 120.0, 400.0, "high",
          0.0, 500.0, 12.0, 15, integral=True),
    Plant("reefer_temp", "compartment temperature", "C", 1.5, 6.0, 9.5, "high",
          -4.0, 14.0, 0.45, 20),
)

# Never simulated in training. Both reuse the primitives the trained plants already
# exercise -- a high-side danger direction, a non-integral reading, a band strictly
# inside the sensor range -- so a drop here is about the plant being new, not about the
# machinery being new. `test_held_out_plants_reuse_trained_primitives` asserts it.
HELDOUT_PLANTS = (
    Plant("dryer_humidity", "return-air relative humidity", "%RH", 28.0, 44.0, 62.0,
          "high", 5.0, 90.0, 2.4, 5),
    Plant("bearing_vibration", "bearing vibration velocity", "mm/s", 0.8, 3.2, 6.5,
          "high", 0.0, 10.0, 0.25, 10),
)

# Held out of train *and* test: the dev split's own unseen plants. Same rule as
# `HELDOUT_PLANTS` -- every structural primitive is a trained plant's -- and disjoint from
# them, so selecting a checkpoint on these never reads a structure test measures.
DEV_PLANTS = (
    Plant("tank_level", "storage tank level", "%", 30.0, 80.0, 12.0, "low",
          0.0, 100.0, 2.4, 15),
    Plant("motor_current", "motor phase current", "A", 40.0, 62.0, 85.0, "high",
          0.0, 120.0, 2.0, 5),
)

PLANTS = {p.key: p for p in TRAINED_PLANTS + HELDOUT_PLANTS + DEV_PLANTS}


def _resolution(p: Plant) -> float:
    return 1.0 if p.integral or p.step >= 1.0 else 0.1


def vary(p: Plant, rng: random.Random) -> Plant:
    """This example's band and critical limit: the plant's own, moved a little.

    The domain calls for "band, limit and horizon vary per example", and before the
    domain-15 audit only the horizon and the run length did -- every jacket loop in the
    corpus had the band 58 to 72 C and the limit 95 C, so for the five trained plants the
    numbers the instructions state were decoration a model could memorise per plant and
    never read. Each edge moves by up to 12 % of the band width and the limit by up to 20 %
    of its distance from the dangerous edge, rounded to the resolution the plant prints at.
    That is small enough that every installation in `FRAMINGS` still genuinely runs there
    and that the ordering `rmin < lo < hi < crit < rmax` (mirrored for a low-side plant)
    cannot break, which the domain-15 audit asserted over a sample.
    """
    res = _resolution(p)
    band = p.hi - p.lo
    gap = (p.crit - p.hi) if p.direction == "high" else (p.lo - p.crit)

    def snap(v: float) -> float:
        return round(round(v / res) * res, 6)

    lo = snap(p.lo + rng.uniform(-0.12, 0.12) * band)
    hi = snap(p.hi + rng.uniform(-0.12, 0.12) * band)
    crit = snap(p.crit + rng.uniform(-0.2, 0.2) * gap)
    return replace(p, lo=lo, hi=hi, crit=crit)


# ---- trend shapes -------------------------------------------------------------------
# A shape is a composition of segment primitives. `oscillating` is held out; its segments
# are `rise` and `fall`, which `ramp_up` and `ramp_down` train. `plateau` is the dev
# split's held-out shape: `rise` then `flat`, both trained, never composed that way.

SEGMENTS = {
    "steady": ("flat",),
    "noisy_flat": ("flat",),
    "ramp_up": ("rise",),
    "ramp_down": ("fall",),
    "step": ("flat", "jump"),
    "recovering": ("fall", "flat"),
    "spike_decay": ("jump", "fall"),
    "oscillating": ("rise", "fall"),
    "plateau": ("rise", "flat"),
}

TRAINED_TRENDS = ("steady", "noisy_flat", "ramp_up", "ramp_down", "step",
                  "recovering", "spike_decay")
HELDOUT_TRENDS = ("oscillating",)
DEV_TRENDS = ("plateau",)

ACTIONS = ("leave_the_loop_alone", "hold_and_watch", "correct_the_setpoint",
           "escalate_to_duty_engineer", "shut_down_the_loop")

# What a generator *aims* for when it draws a series. The label is never taken from the
# intent: it is derived from the series that came out, by `decide`. The intent exists
# only so the five actions are all well represented instead of the plant wandering into
# `leave_the_loop_alone` nine times in ten.
INTENTS = ("leave", "hold_in", "hold_out", "correct", "escalate", "escalate_alarm",
           "shutdown", "borderline")


# ---- framings: the LLM's whole contribution ------------------------------------------
# Generated once by a one-off script through OpenRouter and pasted here as a
# literal, so a build needs no network and no key. Each entry is (device, site, measure,
# unit label). 56 asked for, 51 kept, 5 dropped: the validator rejects a framing whose
# unit is not a surface variant of the plant's own unit, whose measure names a different
# quantity, that carries a number, or that names an action. The model may rename a
# device; it may not redefine what the device reads.
#
# The prompt carries the plant's band, because the first pass did not have it and the
# model put a paint oven and a smokehouse on the cold-chain loop -- installations that
# cannot sit at 1.5 to 6 C. A framing that contradicts the physics is not a target error,
# but it is a state no operator would ever see.

FRAMINGS: dict[str, tuple[tuple[str, str, str, str], ...]] = {
    'jacket_temp': (
        ('Reactor jacket loop alpha', 'Cinder Bay Specialty Chemicals', 'reactor jacket temperature', '°C'),
        ('Mash tun jacket circuit', 'Mistvale Brewing', 'mash tun jacket temperature', 'C'),
        ('Dye vessel jacket loop', 'Quarry Line Textiles', 'dye vessel jacket temperature', 'degC'),
        ('Solution preparation vessel jacket circuit', 'Larkspur Pharmaceutical Works', 'solution preparation vessel jacket temperature', '°C'),
        ('Emulsifier jacket loop', 'Aster Glen Cosmetics', 'emulsifier jacket temperature', 'degC'),
        ('Resin kettle jacket circuit', 'Harborlight Adhesives', 'resin kettle jacket temperature', 'C'),
    ),
    'cell_soc': (
        ('Grid storage battery pack', 'Prairie Mesa Energy Park', 'pack state of charge', '%'),
        ('Microgrid lithium battery pack', 'Sunfield Community Microgrid', 'pack state of charge', 'percent'),
        ('Forklift lithium battery pack', 'Ironworks Distribution Center', 'pack state of charge', '%'),
        ('Underground loader battery pack', 'Copper Vein Mine', 'pack state of charge', 'percent'),
        ('Ship-to-shore crane battery pack', 'Gullwing Container Terminal', 'pack state of charge', '%'),
    ),
    'line_pressure': (
        ('Digester gas engine intake manifold', 'Blackwater Reclamation Campus', 'intake manifold pressure', 'kPa'),
        ('Main engine scavenge air manifold', 'Harborline Shipyard', 'scavenge air manifold pressure', 'KPa'),
        ('Fuel gas supply manifold', 'Pine Ridge Compression Station', 'fuel gas manifold pressure', 'kpa'),
        ('Cold blast manifold', 'Ironvale Works', 'cold blast manifold pressure', 'kPa'),
        ('Mill compressed air header manifold', 'Cedar Falls Paper Mill', 'compressed air manifold pressure', 'KPa'),
        ('Process steam manifold', 'Northshore Chemicals', 'steam manifold pressure', 'kPa'),
        ('Carbon dioxide supply manifold', 'Greenfield Foods', 'carbon dioxide manifold pressure', 'kpa'),
        ('Stator cooling water manifold', 'Mesa Verde Generating Station', 'cooling water manifold pressure', 'KPa'),
    ),
    'queue_backlog': (
        ('Diffusion furnace load queue', 'Vireo Semiconductor Fab', 'queue depth', 'items'),
        ('Body shop sealer queue conveyor', 'Kestrel Ridge Assembly Plant', 'queue depth', 'items'),
        ('Parcel sorter induction queue', 'Larkspur Parcel Hub', 'queue depth', 'items'),
        ('Bottling line accumulation table', 'Juniper Falls Bottling Works', 'queue depth', 'items'),
        ('Blister pack buffer conveyor', 'Silverleaf Pharma Packaging', 'queue depth', 'items'),
        ('SMT line board queue', 'Copperfield Electronics Assembly', 'queue depth', 'items'),
        ('Put wall order queue', 'Beacon Harbor Fulfillment Center', 'queue depth', 'items'),
        ('Baggage sorter queue', 'Northgate International Airport', 'queue depth', 'items'),
    ),
    'reefer_temp': (
        ('Reefer container temperature probe', 'Frostmere Cold Logistics', 'compartment temperature', '°C'),
        ('Blood bank refrigerator compartment sensor', 'Alderpoint Blood Services', 'compartment temperature', 'C'),
        ('Vaccine refrigerator cabinet probe', 'Vireo Health Depot', 'compartment temperature', 'degC'),
        ('Walk-in cooler compartment sensor', 'Quarryside Campus Dining', 'compartment temperature', '°C'),
        ('Floral cooler compartment probe', 'Larkspur Floral Distribution', 'compartment temperature', 'C'),
        ('Cold room compartment temperature element', 'Mistvale Pharma Logistics', 'compartment temperature', 'degC'),
        ('Yeast storage compartment sensor', 'Bramblewick Brewing', 'compartment temperature', '°C'),
        ('Refrigerated incubator chamber probe', 'Thistledown Analytical Labs', 'compartment temperature', 'C'),
    ),
    'dryer_humidity': (
        ('Coating room air handler return sensor', 'Meridian Pharma Works', 'return-air relative humidity', '%RH'),
        ('Server hall return air sensor', 'Cobalt Cloud Campus', 'return-air relative humidity', '% RH'),
        ('Archive air handling unit return sensor', 'Ashgrove Museum Depository', 'return-air relative humidity', '%RH'),
        ('Tempering room air handler return sensor', 'Cocoa Vale Confections', 'return-air relative humidity', '% RH'),
        ('Surgical suite air handler return sensor', 'Lakeside Regional Hospital', 'return-air relative humidity', '%RH'),
        ('Cleanroom air handler return sensor', 'Silicon Fen Fab', 'return-air relative humidity', '% RH'),
        ('Cabinet shop air handler return sensor', 'Maple Craft Furniture', 'return-air relative humidity', '%RH'),
        ('Office tower air handler return sensor', 'Harborview Center', 'return-air relative humidity', '% RH'),
    ),
    'bearing_vibration': (
        ('Boiler feedwater pump turbine outboard bearing', 'Halcyon Reach Generating Station', 'bearing vibration velocity', 'mm/s'),
        ('Refinery hydrocracker recycle compressor inboard bearing', 'Northgate Petrochemical Works', 'compressor bearing vibration velocity', 'MM/S'),
        ('Paper machine vacuum pump drive end bearing', 'Cedar Hollow Paper Mill', 'pump bearing vibration velocity', 'mm/S'),
        ('Municipal raw water pump motor bearing', 'Blue Marsh Water Treatment Plant', 'motor bearing vibration velocity', 'Mm/s'),
        ('Mine ventilation fan shaft bearing', 'Copper Ridge Mine', 'fan bearing vibration velocity', 'mm/s'),
        ('Chiller compressor bearing', 'Summit Medical Center Central Plant', 'compressor bearing vibration velocity', 'MM/S'),
        ('Marine propulsion shaft alternator bearing', 'Port Ellery Shipyard', 'alternator bearing vibration velocity', 'mm/S'),
        ('Grain elevator blower bearing', 'Prairie Rise Grain Terminal', 'blower bearing vibration velocity', 'Mm/s'),
    ),
    # The dev split's held-out plants. Written by hand, not by the framing script, and
    # held to its validator's rules: the unit is a surface form of the plant's own, the
    # measure names the same quantity, no number and no policy word
    # (`test_framings_carry_no_policy_word` reads these too).
    'tank_level': (
        ('Potable water storage tank', 'Birchmere Water Works', 'storage tank level', '%'),
        ('Diesel day tank', 'Kestrel Point Data Centre', 'day tank level', 'percent'),
        ('Molasses storage vessel', 'Fenwick Feed Mill', 'vessel level', '%'),
        ('Fire water reservoir', 'Ashcombe Logistics Park', 'reservoir level', 'percent'),
        ('Caustic dosing tank', 'Riverside Effluent Plant', 'dosing tank level', '%'),
        ('Milk silo', 'Greenholt Creamery', 'silo level', 'percent'),
    ),
    'motor_current': (
        ('Conveyor drive motor', 'Oakridge Aggregates Quarry', 'motor phase current', 'A'),
        ('Chilled water pump motor', 'Westbury Hospital Energy Centre', 'pump motor current', 'A'),
        ('Extruder main drive', 'Tamsin Polymers', 'drive motor current', 'A'),
        ('Mixer agitator motor', 'Copperleaf Bakery', 'agitator motor current', 'A'),
        ('Cooling tower fan motor', 'Dunmore Refinery', 'fan motor current', 'A'),
        ('Ski lift bullwheel motor', 'Ptarmigan Ridge Resort', 'bullwheel motor current', 'A'),
    ),
}


# ---- simulation ----------------------------------------------------------------------

def _round(p: Plant, v: float) -> float:
    if p.integral:
        return float(int(round(v)))
    return round(v, 2 if p.step < 1.0 else 1)


def _clamp(p: Plant, v: float) -> float:
    return min(max(v, p.rmin), p.rmax)


def _sign(p: Plant) -> int:
    """+1 if an excursion in the dangerous direction raises the reading."""
    return 1 if p.direction == "high" else -1


def _series(p: Plant, trend: str, end: float, slope: float, rng: random.Random,
            n: int) -> list[float]:
    """`n` readings ending at `end` with a recent per-reading change of `slope`.

    The series is built backwards from the last reading, because the last reading and the
    recent slope are what the policy reads and what the intent wants to control; the
    earlier history is then whatever the trend shape says it was.
    """
    jitter = p.step * (0.55 if trend == "noisy_flat" else 0.12)
    out = [0.0] * n
    out[-1] = end
    if trend in ("ramp_up", "ramp_down", "recovering"):
        for i in range(n - 2, -1, -1):
            out[i] = out[i + 1] - slope + rng.gauss(0, jitter)
    elif trend in ("steady", "noisy_flat"):
        for i in range(n - 2, -1, -1):
            out[i] = end - slope * (n - 1 - i) * 0.25 + rng.gauss(0, jitter)
    elif trend == "step":
        # flat, one jump, flat. The jump sits at least three readings back so the recent
        # slope is the post-step drift and not the step itself.
        at = rng.randint(2, max(2, n - 3))
        base = end - slope * (n - 1 - at)
        prior = base - rng.uniform(1.5, 4.0) * p.step * (1 if slope >= 0 else -1)
        for i in range(n - 2, -1, -1):
            out[i] = (out[i + 1] - slope + rng.gauss(0, jitter)) if i >= at else \
                prior + rng.gauss(0, jitter)
    elif trend == "spike_decay":
        peak = rng.randint(1, max(1, n - 4))
        amp = rng.uniform(2.0, 4.5) * p.step
        for i in range(n - 2, -1, -1):
            out[i] = out[i + 1] - slope + rng.gauss(0, jitter)
        for i in range(n):
            out[i] += amp * math.exp(-abs(i - peak) / 1.6)
        out[-1] = end
    elif trend == "oscillating":
        amp = rng.uniform(1.2, 2.8) * p.step
        period = rng.uniform(3.5, 6.0)
        phase = rng.uniform(0, 2 * math.pi)
        for i in range(n):
            out[i] = end - slope * (n - 1 - i) + amp * math.sin(
                2 * math.pi * i / period + phase) + rng.gauss(0, jitter)
        # keep the requested recent slope: shift the tail so the last three readings
        # carry it, which is what the policy reads.
        out[-1] = end
        out[-2] = end - slope + rng.gauss(0, jitter * 0.5)
        out[-3] = end - 2 * slope + rng.gauss(0, jitter * 0.5)
    elif trend == "plateau":
        # a climb that levels off: before `at` the reading rose faster than it does now,
        # and the last three readings carry the requested slope, which is what the
        # policy reads. `at` stays at least four readings back so `rate` never sees the
        # knee.
        at = rng.randint(1, max(1, n - 4))
        climb = rng.uniform(0.8, 2.0) * p.step
        for i in range(n - 2, -1, -1):
            out[i] = out[i + 1] - slope - (climb if i < at else 0.0) + rng.gauss(0, jitter)
    else:                                                    # pragma: no cover
        raise ValueError(f"unknown trend {trend!r}")
    return [_round(p, _clamp(p, v)) for v in out]


def rate(values: list[float]) -> float:
    """Average change per reading over the last three readings. Stated in the criteria,
    so the model is told the definition and has to apply it."""
    if len(values) < 3:
        return values[-1] - values[0]
    return (values[-1] - values[-3]) / 2.0


def consecutive_outside(p: Plant, values: list[float]) -> int:
    n = 0
    for v in reversed(values):
        if v < p.lo or v > p.hi:
            n += 1
        else:
            break
    return n


# ---- the alarm history ---------------------------------------------------------------

def _alarms(p: Plant, values: list[float], rng: random.Random,
            allow: bool) -> list[tuple[int, str]]:
    """An alarm raised at an earlier excursion, possibly cleared later.

    This is the part of "recent history" that is not in the numbers: whether somebody has
    already been told. It is what separates `escalate_to_duty_engineer` from
    `correct_the_setpoint` on an identical reading with an identical slope.
    """
    if not allow:
        return []
    out_idx = [i for i, v in enumerate(values[:-1]) if v < p.lo or v > p.hi]
    if not out_idx or rng.random() < 0.45:
        return []
    raised = out_idx[0]
    events = [(raised, "alarm_raised")]
    back = [i for i, v in enumerate(values) if i > raised and p.lo <= v <= p.hi]
    # Cleared half the time. Before the shortcut audit a clear needed the reading to come
    # back into the band after the alarm, which the recent-excursion draws (`correct`,
    # `escalate_alarm`) never do -- so 2 % of alarms were cleared and "an alarm appears
    # anywhere, so it is an engineer" was the latch clause with the "not been cleared"
    # half of it never tested. The panel may also clear an alarm while the reading is
    # still out (acknowledged and reset); the criteria ask only whether it was cleared.
    if rng.random() < 0.5:
        at = back[0] if back else rng.randint(raised + 1, len(values) - 1)
        events.append((at, "alarm_cleared"))
    return events


def latched(events: list[tuple[int, str]]) -> bool:
    state = False
    for _, kind in events:
        state = kind == "alarm_raised"
    return state


# ---- the policy ----------------------------------------------------------------------

def _past(p: Plant, value: float, thr: float, greater: bool) -> float:
    """p(`value` is past `thr`): soft for a measurement, a step for a count.

    `grammar.soft` smooths a threshold over 3 % of the sensor's range because a reading of
    a temperature is a measurement and one sitting on an edge honestly could be either
    side. A queue depth is a count. On `queue_backlog` that band was 15 items wide, so a
    queue of 121 against a band that ends at 120 was "outside" with probability 0.58 and a
    projection of 395 against a limit of 400 "past" it with 0.16 -- 17.5 % of that
    plant's targets were soft over integers the reader can compare exactly (a finding
    of the first domain-15 audit, resolved in the second). Its projection is exact
    arithmetic on counts too, `last + h * (v[-1] - v[-3]) / 2`, so it gets the same step.
    The band is inclusive and the limit strict, which is how the criteria read: "inside the
    normal band of 20 to 120" includes 120, "above the critical limit of 400" excludes 400.
    """
    if p.integral:
        return float(value > thr) if greater else float(value < thr)
    return soft(value, thr, p.span, greater)


def decide(p: Plant, values: list[float], events: list[tuple[int, str]], k: int,
           h: int) -> tuple[list[float], dict]:
    """The controller's policy, as a distribution over `ACTIONS`.

    Ordered, first match wins, exactly as the option descriptions state it. Soft where a
    measurement is soft: the band edges and the critical limit are smoothed by
    `grammar.soft` over 3 % of the sensor's range, so a reading sitting on an edge gets
    the honest probability rather than a coin flip dressed as a certainty. A count is not
    a measurement and gets hard edges (`_past`).
    """
    last = values[-1]
    r = rate(values)
    projected = last + r * h

    # 1. critical, now or within the horizon
    high = p.direction == "high"
    p_now = _past(p, last, p.crit, high)
    p_proj = _past(p, projected, p.crit, high)
    p_crit = 1.0 - (1.0 - p_now) * (1.0 - p_proj)

    # 2-3. outside the band
    p_above = _past(p, last, p.hi, True)
    p_below = _past(p, last, p.lo, False)
    p_out = 1.0 - (1.0 - p_above) * (1.0 - p_below)

    high_side = last > (p.hi + p.lo) / 2.0
    improving = (r < 0) if high_side else (r > 0)
    runs = consecutive_outside(p, values)
    known = latched(events)

    if improving:
        out_key = "hold_and_watch"
    elif runs >= k or known:
        out_key = "escalate_to_duty_engineer"
    else:
        out_key = "correct_the_setpoint"

    # 4-5. inside the band: is it projected out within the horizon?
    if r > 0:
        p_exit = _past(p, projected, p.hi, True)
    elif r < 0:
        p_exit = _past(p, projected, p.lo, False)
    else:
        p_exit = 0.0

    dist = dict.fromkeys(ACTIONS, 0.0)
    dist["shut_down_the_loop"] = p_crit
    rest = 1.0 - p_crit
    dist[out_key] += rest * p_out
    dist["hold_and_watch"] += rest * (1.0 - p_out) * p_exit
    dist["leave_the_loop_alone"] += rest * (1.0 - p_out) * (1.0 - p_exit)

    total = sum(dist.values()) or 1.0
    probs = [dist[a] / total for a in ACTIONS]
    facts = {"rate": round(r, 3), "runs_outside": runs, "alarm_latched": known,
             "projected": round(projected, 3), "last": last}
    return probs, facts


# ---- drawing a scenario --------------------------------------------------------------

def _draw(p: Plant, trend: str, intent: str, rng: random.Random, h: int = 4):
    """(last reading, recent slope, whether an alarm may have been raised).

    Only the *aim*. `decide` still derives the action from the series that results, and
    where the draw misses -- a `correct` draw whose projection happens to cross the
    critical limit, say -- the derived action stands and the intent is discarded.
    """
    s = _sign(p)
    band = p.hi - p.lo
    edge = p.hi if s > 0 else p.lo               # the edge on the dangerous side
    gap = abs(p.crit - edge)
    if intent == "leave":
        if rng.random() < 0.5:
            # `hold_in`'s near miss: inside, drifting toward the dangerous edge, but slow
            # enough that `last + rate * h` stays inside. Without it "inside and moving
            # toward the edge" (or "the window swings across the band") meant rule 4 and
            # the projection was never computed (measured by a shortcut audit).
            # Distance and slope come from the same draw as `hold_in`'s matched half;
            # only whether `dist / (slope * h)` is under or over 1 differs.
            dist = rng.uniform(0.03, 0.45) * band
            return (edge - s * dist, s * dist / (h * rng.uniform(1.15, 3.0)), False)
        return (rng.uniform(p.lo + 0.2 * band, p.hi - 0.2 * band),
                rng.uniform(-0.15, 0.15) * p.step, False)
    if intent == "hold_in":
        # inside the band, but the ramp takes it out within the horizon
        if rng.random() < 0.5:
            dist = rng.uniform(0.03, 0.45) * band
            return (edge - s * dist, s * dist / (h * rng.uniform(0.35, 0.87)), False)
        return (edge - s * rng.uniform(0.05, 0.3) * band,
                s * rng.uniform(0.5, 1.4) * p.step, False)
    if intent == "hold_out":
        return (edge + s * rng.uniform(0.15, 0.6) * min(band, gap),
                -s * rng.uniform(0.4, 1.3) * p.step, True)
    if intent == "correct":
        # a *recent* excursion: the depth past the edge is a small multiple of the slope,
        # so only one to three readings are outside and the run-length test in rule 2
        # does not fire. This is the case that separates rule 3 from rule 2 on an
        # otherwise identical reading, and it has to be drawn deliberately or the
        # run-length test swallows it.
        sl = rng.uniform(0.6, 1.6) * p.step
        return (edge + s * min(sl * rng.uniform(0.2, 2.2), 0.8 * gap), s * sl, False)
    if intent == "escalate":
        depth = rng.uniform(0.2, 0.6) * min(band, gap)
        if rng.random() < 0.5:
            return (edge + s * depth, s * rng.uniform(0.1, 0.5) * p.step, True)
        # The slow drift above leaves every reading in the window outside, and with `k`
        # never longer than the window "the whole series is out" then answered rule 2 vs
        # 3 without counting (measured by a shortcut audit). Half the time the
        # ramp crossed the edge a few readings back instead, so the run has a start to
        # count from and `_persistence` can put `k` on either side of it.
        return (edge + s * depth, s * depth / rng.uniform(2.5, 7.5), True)
    if intent == "escalate_alarm":
        # The alarm on its own. `escalate` sits deep past the edge on a slow drift, so
        # the run-length test in rule 2 fires and the latched alarm is a second reason
        # for an answer that already held -- measured over the shipped corpus, the alarm
        # was the *only* reason in 0.6 % of examples, which is not a policy clause being
        # exercised. This draw is `correct`'s shallow, recent excursion with an alarm
        # allowed: two or three readings outside, so rule 2's run-length test cannot
        # fire, and the only thing that separates rule 2 from rule 3 is whether somebody
        # has already been told.
        sl = rng.uniform(0.6, 1.6) * p.step
        return (edge + s * min(sl * rng.uniform(0.9, 1.9), 0.8 * gap), s * sl, True)
    if intent == "shutdown":
        if rng.random() < 0.45:
            return (p.crit + s * rng.uniform(0.02, 0.25) * gap,
                    s * rng.uniform(0.0, 0.6) * p.step, True)
        # from inside or just outside the band, on a ramp steep enough to reach the limit
        start = edge - s * rng.uniform(0.0, 0.35) * band
        need = abs(p.crit - start)
        return (start, s * rng.uniform(1.05, 1.6) * need / 4.0, False)
    # borderline: sit the last reading on an edge, where the answer is genuinely a
    # probability rather than a class
    which = rng.choice(("band", "crit"))
    target = edge if which == "band" else p.crit
    return (target + rng.uniform(-1.0, 1.0) * 0.035 * p.span,
            rng.choice((-1, 1)) * rng.uniform(0.1, 0.8) * p.step, rng.random() < 0.5)


def _persistence(p: Plant, values: list[float], k: int, rng: random.Random) -> int:
    """This example's `k`, drawn against the run the series actually has.

    Rule 2 against rule 3 turns on `runs >= k`, and with `k` drawn blind from 3..6 the
    run length alone decided it: the `correct` draws put one to three readings outside
    and the `escalate` draws a dozen, so "a short run is a correction, a long run an
    engineer" agreed with the label on 0.84-0.89 of rule-2/3 examples without ever
    reading `k` (measured by a shortcut audit). Once the reading is outside, `k`
    sits either side of the run instead -- at or just under it half the time, over it
    the other half -- so the count has to be compared with the stated threshold. Where
    an earlier excursion puts more readings outside than the current run, "over" may
    land between the run and that total, so counting every outside reading rather than
    the *consecutive* ones is wrong there. `k` never drops below 2 (one reading outside
    is not "persistently" anything) and never exceeds the window, which could not show
    a run that long. Inside the band the run is 0 and `k` keeps its blind draw.
    """
    n = len(values)
    runs = consecutive_outside(p, values)
    if runs == 0:
        return k
    total = sum(1 for v in values if v < p.lo or v > p.hi)
    at = [x for x in (runs, runs - 1) if x >= 2]
    over = sorted({runs + 1, runs + 2, *range(runs + 1, total + 1)})
    over = [x for x in over if x <= n]
    if at and (not over or rng.random() < 0.5):
        return rng.choice(at)
    return rng.choice(over) if over else 2


# ---- rendering -------------------------------------------------------------------------

SHAPES = ("json", "log", "table")


def _clock(start_min: int, i: int, interval: int) -> str:
    t = (start_min + i * interval) % (24 * 60)
    return f"{t // 60:02d}:{t % 60:02d}"


def _num(p: Plant, v: float) -> str:
    return str(int(v)) if p.integral else f"{v:g}"


def _render(p: Plant, framing, values, events, start_min, shape: str) -> str:
    device, site, measure, unit = framing
    ev = dict(events)
    times = [_clock(start_min, i, p.interval) for i in range(len(values))]
    if shape == "json":
        body = {
            "device": device,
            "site": site,
            "measure": measure,
            "unit": unit,
            "sample_interval_min": p.interval,
            "readings": [{"t": times[i], "value": values[i]} for i in range(len(values))],
            "events": [{"t": times[i], "event": ev[i]} for i in sorted(ev)],
        }
        return _json.dumps(body, indent=2)
    if shape == "log":
        head = (f"Operator log -- {site}, {device}. {measure[0].upper()}{measure[1:]} "
                f"sampled every {p.interval} min, in {unit}.")
        lines = [head]
        for i, v in enumerate(values):
            lines.append(f"{times[i]}  {measure} {_num(p, v)} {unit}.")
            if i in ev:
                word = ("ALARM RAISED on this loop." if ev[i] == "alarm_raised"
                        else "Alarm on this loop cleared by the panel.")
                lines.append(f"{times[i]}  {word}")
        return "\n".join(lines)
    head = (f"device: {device} ({site})\n"
            f"measure: {measure}, in {unit}, sampled every {p.interval} min\n")
    width = max(len(measure), 12)
    rows = [f"{'time':<6} | {measure:<{width}} | note",
            f"{'-' * 6}-+-{'-' * width}-+-----"]
    for i, v in enumerate(values):
        note = "" if i not in ev else (
            "alarm raised" if ev[i] == "alarm_raised" else "alarm cleared")
        rows.append(f"{times[i]:<6} | {_num(p, v):<{width}} | {note}")
    return head + "\n".join(rows)


# ---- the question ----------------------------------------------------------------------

def _policy(p: Plant, unit: str, k: int, h: int) -> dict[str, str]:
    """The controller's policy, one clause per option.

    The order is carried by "Rule N of 5" and "no lower-numbered rule matches" rather
    than by the option's position in the list, because the list is rotated per example.
    A clause names the condition and never the action, so an option key appears nowhere
    in the example at all -- not in the state, not in the question, not in the
    instructions, and not even in its own description -- which is what keeps the question
    from being answerable by string match.
    """
    lo, hi, crit = _num(p, p.lo), _num(p, p.hi), _num(p, p.crit)
    side = "above" if p.direction == "high" else "below"
    return {
        "shut_down_the_loop":
            f"Rule 1 of 5. Choose this when the latest reading is already {side} the "
            f"critical limit of {crit} {unit}, or when the rate of change projects it "
            f"{side} that limit within {h} readings.",
        "escalate_to_duty_engineer":
            f"Rule 2 of 5. Choose this when no lower-numbered rule matches, the latest "
            f"reading is outside the normal band of {lo} to {hi} {unit}, the rate of "
            f"change is not carrying it back toward the band, and either the reading has "
            f"been outside the band for {k} or more consecutive readings or an alarm "
            f"raised earlier in this window has not been cleared.",
        "correct_the_setpoint":
            f"Rule 3 of 5. Choose this when no lower-numbered rule matches, the latest "
            f"reading is outside the normal band of {lo} to {hi} {unit}, and the rate of "
            f"change is not carrying it back toward the band.",
        "hold_and_watch":
            f"Rule 4 of 5. Choose this when no lower-numbered rule matches and either "
            f"the latest reading is outside the normal band but the rate of change is "
            f"carrying it back toward the band, or the reading is inside the band and "
            f"the rate of change projects it outside the band within {h} readings.",
        "leave_the_loop_alone":
            f"Rule 5 of 5. Choose this when no lower-numbered rule matches: the reading "
            f"is inside the normal band of {lo} to {hi} {unit} and is not projected to "
            f"leave it within {h} readings.",
    }


ORDER = ("shut_down_the_loop", "escalate_to_duty_engineer", "correct_the_setpoint",
         "hold_and_watch", "leave_the_loop_alone")

QUESTION_ID = "d15.sensor_action"
QUESTION = "Which action should the controller take on this loop now?"
_BANK: PhrasingBank | None = None


def _phrasing(key: str) -> str:
    global _BANK
    if _BANK is None:
        _BANK = PhrasingBank.load()
    return _BANK.pick(QUESTION_ID, QUESTION, key)


def _question(p: Plant, unit: str, k: int, h: int, probs: list[float], facts: dict,
              trend: str, shape: str, rng: random.Random,
              phrasing_key: str = "") -> Question:
    """Options in the policy's own order, but rotated, so position is not the answer.

    The descriptions are read in order and say "none of the above", which is the ordered
    policy itself -- so the rotation keeps the text's order while moving where each
    option sits in the list.
    """
    text = _policy(p, unit, k, h)
    roll = rng.randrange(len(ORDER))
    keys = list(ORDER[roll:]) + list(ORDER[:roll])
    # Every number the policy reads is stated here as well as in the rules. The rules are
    # option descriptions, and `lod.training.data.strip_criteria` drops descriptions from 10 %
    # of training questions: with `k` and `h` only in the rules, those questions asked for
    # an answer that turned on two numbers the example no longer contained.
    #
    # The rate is spelled out as arithmetic. "The average change per reading over the
    # last three readings" also reads as the last three *changes*, four readings, and
    # that reading changes the answer on 7.7 % of examples (domain-15 audit).
    instructions = (
        f"The normal operating band for this loop is {_num(p, p.lo)} to "
        f"{_num(p, p.hi)} {unit} and the critical limit is {_num(p, p.crit)} {unit}. "
        f"Rate of change means the average change per reading across the last three "
        f"readings: the latest reading minus the reading two before it, divided by 2. "
        f"The projection horizon is {h} readings, and a reading counts as persistently "
        f"out of band once it has been outside the band for {k} or more consecutive "
        f"readings. The option rules are numbered; apply them in that order and take the "
        f"first that matches, whatever order the options are listed in."
    )
    idx = {a: i for i, a in enumerate(ACTIONS)}
    target = [probs[idx[k_]] for k_ in keys]
    total = sum(target) or 1.0
    target = [x / total for x in target]
    # `ordered_rules`: every rule after the first is conditional on "no lower-numbered rule
    # matches", so an augmentation that removes one option's text can make the answer
    # undecidable (19 % of these questions after `lod.training.data.augment_criteria`, measured
    # by the domain-15 audit). Carried so the augmentation can recognise the case.
    meta = {"plant": p.key, "trend": trend, "shape": shape, "k": k, "h": h,
            "lo": p.lo, "hi": p.hi, "crit": p.crit, "ordered_rules": True, **facts}
    return Question("action", _phrasing(phrasing_key), keys, target, meta, instructions,
                    [text[k_] for k_ in keys])


# ---- examples ---------------------------------------------------------------------------

def make_example(plants, trends, rng: random.Random, task: str) -> Example:
    p = vary(rng.choice(list(plants)), rng)
    trend = rng.choice(list(trends))
    intent = rng.choice(INTENTS)
    framing = rng.choice(FRAMINGS[p.key])
    shape = rng.choice(SHAPES)
    k = rng.randint(3, 6)          # kept for an in-band reading; `_persistence` redraws it
    h = rng.randint(3, 6)
    n = rng.randint(9, 15)
    end, slope, allow_alarm = _draw(p, trend, intent, rng, h)
    # A steep ramp over fifteen readings runs off the bottom of the sensor's range and
    # `_clamp` then prints the same floor value five times, which is an artefact of the
    # draw and not a plant doing anything. Shorten the window instead.
    if slope:
        n = max(8, min(n, int(0.85 * p.span / abs(slope)) + 1))
    end = _round(p, _clamp(p, end))
    values = _series(p, trend, end, slope, rng, n)
    k = _persistence(p, values, k, rng)
    events = _alarms(p, values, rng, allow_alarm)
    probs, facts = decide(p, values, events, k, h)
    start_min = rng.randrange(0, 24 * 60, 5)
    state = _render(p, framing, values, events, start_min, shape)
    facts["intent"] = intent
    key = task + ":" + hashlib.sha1(state.encode("utf-8")).hexdigest()[:16]
    q = _question(p, framing[3], k, h, probs, facts, trend, shape, rng, key)
    return Example(state=state, questions=[q], task=task)


def _loader(plants, trends, task: str, seed: int):
    def load(n: int) -> Iterator[Example]:
        h = hashlib.sha256(f"sensors:{task}:{seed}".encode()).digest()
        rng = random.Random(int.from_bytes(h[:8], "big"))
        for _ in range(n):
            yield make_example(plants, trends, rng, task)
    return load


def tasks() -> list[RealTask]:
    """Two trained tasks, one devreal control and two dev holdouts, three testreal.

    The trained side is split by plant because a task is the unit of quota as well as
    the unit of the split, and one task would have put four times as much of this row
    into `testreal` as into training -- the mistake domain 4 is still paying for, where
    the model has never seen a chess puzzle it is measured on. Two tasks over disjoint
    trained plants double the training share without inventing a family.

    `devreal` holds out structures of its own, disjoint from `testreal`'s:
    `sensor_action_dev_plant` (`DEV_PLANTS`) and `sensor_action_dev_trend`
    (`DEV_TRENDS`). Checkpoint selection and the temperature read those, so they are as
    novel as the test holdouts without being them. `sensor_action_trained_dev` stays as
    the in-distribution dev read: same families as training, unseen instances.

    Family: the two trained tasks and both trained-plant twins are one family,
    `sensor_trained`, so the devood selection never counts a twin as held out.

    `sensor_action_trained_eval` is the testreal control. A gap between it and
    `sensor_action_heldout_plant` or `sensor_action_heldout_trend` is a failure to
    generalise over structure; without it a held-out number means nothing.
    """
    thermal = tuple(p for p in TRAINED_PLANTS if p.key in ("jacket_temp", "reefer_temp"))
    store = tuple(p for p in TRAINED_PLANTS if p not in thermal)
    tt = TRAINED_TRENDS
    spec = (
        ("sensor_action_train_thermal", thermal, tt, "train", 0,
         "trained trends on the two thermal loops"),
        ("sensor_action_train_store", store, tt, "train", 11,
         "trained trends on the charge, backlog and pressure loops"),
        ("sensor_action_trained_dev", TRAINED_PLANTS, tt, "devreal", 101,
         "trained families, unseen instances; the devreal control"),
        ("sensor_action_trained_eval", TRAINED_PLANTS, tt, "testreal", 202,
         "trained families, unseen instances; the testreal control for the holdouts"),
        ("sensor_action_heldout_plant", HELDOUT_PLANTS, tt, "testreal", 303,
         "plant types never simulated in training; trained trends"),
        ("sensor_action_heldout_trend", TRAINED_PLANTS, HELDOUT_TRENDS, "testreal", 404,
         "oscillation, never trained; its rise and fall segments are"),
        ("sensor_action_dev_plant", DEV_PLANTS, tt, "devreal", 505,
         "plant types never simulated in train or test; trained trends. " + DEV_NOTE),
        ("sensor_action_dev_trend", TRAINED_PLANTS, DEV_TRENDS, "devreal", 606,
         "plateau, never trained; its rise and flat segments are. " + DEV_NOTE),
    )
    trained = {"sensor_action_train_thermal", "sensor_action_train_store",
               "sensor_action_trained_dev", "sensor_action_trained_eval"}
    return [
        RealTask(row=ROW, name=name, licence=LICENCE, url=URL,
                 load=_loader(plants, trends, name, seed),
                 soft=True, real=False, force_split=split, notes=notes,
                 family="sensor_trained" if name in trained else None)
        for name, plants, trends, split, seed, notes in spec
    ]
