"""Shared plumbing for the schema sources.

A *source* is a generator family. It emits `Example`s whose `task` names the
individual schema, so distinct schemas are countable, and it declares a
provenance row that must reach the provenance manifest or its rows do not enter training.
"""

from __future__ import annotations

import gzip
import hashlib
import io
import json
import time
import urllib.error
import urllib.request
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

from lod.paths import RAW_ROOT

UA = {"User-Agent": "lod-research/1.0 (open decision-model dataset; non-commercial research)"}
CACHE = RAW_ROOT  # direct downloads land beside the raw-row store

# schema diversity axes, used for the coverage report
GROUND_TRUTH_TYPES = ("structural", "executable", "taxonomic", "outcome", "crowd")
STATE_FORMATS = ("prose", "structured", "tabular")
OPTION_TYPES = ("fixed", "per_example")


@dataclass
class SourceInfo:
    """One row of the provenance manifest. No licence, no training rows."""

    name: str
    url: str
    licence: str
    tier: int  # 1 bulk/open, 2 API/rate-limited, 3 eval-only
    ground_truth_type: str
    state_format: str
    option_type: str
    notes: str = ""

    def __post_init__(self) -> None:
        if self.ground_truth_type not in GROUND_TRUTH_TYPES:
            raise ValueError(f"{self.name}: bad ground_truth_type {self.ground_truth_type!r}")
        if self.state_format not in STATE_FORMATS:
            raise ValueError(f"{self.name}: bad state_format {self.state_format!r}")
        if self.option_type not in OPTION_TYPES:
            raise ValueError(f"{self.name}: bad option_type {self.option_type!r}")
        if not self.licence:
            raise ValueError(f"{self.name}: a source without a licence cannot enter train")


@dataclass
class SourceResult:
    info: SourceInfo
    examples: list = field(default_factory=list)
    schemas: set = field(default_factory=set)  # distinct (question, option-set) keys

    @property
    def n_schemas(self) -> int:
        return len(self.schemas)


def cache_path(url: str, suffix: str = "") -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    return CACHE / (hashlib.sha1(url.encode()).hexdigest()[:20] + suffix)


def fetch(url: str, timeout: int = 120, retries: int = 2, cache: bool = True) -> bytes:
    """GET with a User-Agent (several of these hosts 403 without one) and a disk cache."""
    p = cache_path(url)
    if cache and p.exists():
        return p.read_bytes()
    last: Exception | None = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=timeout) as r:
                body = r.read()
            if cache:
                p.write_bytes(body)
            return body
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            last = e
            if attempt < retries:
                time.sleep(1.5 * (attempt + 1))
    raise RuntimeError(f"fetch failed for {url}: {last}")


def fetch_json(url: str, **kw) -> Any:
    return json.loads(fetch(url, **kw))


def fetch_jsonl_gz(url: str, limit: int | None = None, **kw) -> Iterable[dict]:
    body = fetch(url, **kw)
    with gzip.open(io.BytesIO(body)) as f:
        for i, line in enumerate(f):
            if limit is not None and i >= limit:
                return
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def schema_key(question: str, options: list[str]) -> tuple:
    """What counts as one schema: a question plus the option set it ranges over."""
    return (question, tuple(options) if len(options) <= 40 else ("free", len(options)))


def write_manifest(path: Path, rows: list[dict]) -> None:
    """A provenance manifest: every task with its source, licence and split counts."""
    cols = ["task", "source", "url", "licence", "tier", "ground_truth_type",
            "state_format", "option_type", "n_train", "n_val", "n_heldout", "generator"]
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Provenance manifest",
        "",
        "Generated by the corpus build. A task without a licence entry",
        "does not enter `train.jsonl`. Tier 3 sources are eval-only.",
        "",
        "| " + " | ".join(cols) + " |",
        "|" + "|".join(["---"] * len(cols)) + "|",
    ]
    for r in sorted(rows, key=lambda r: (r.get("generator", ""), r.get("task", ""))):
        lines.append("| " + " | ".join(str(r.get(c, "")) for c in cols) + " |")
    path.write_text("\n".join(lines) + "\n")


def coverage_report(rows: list[dict]) -> dict[str, dict[str, int]]:
    """How many distinct train sources cover each diversity-axis value."""
    out: dict[str, dict[str, int]] = {"ground_truth_type": {}, "state_format": {}, "option_type": {}}
    for axis in out:
        for r in rows:
            if int(r.get("n_train", 0)) <= 0:
                continue
            v = r.get(axis, "")
            out[axis].setdefault(v, set())  # type: ignore[arg-type]
            out[axis][v].add(r.get("generator", r.get("source", "")))  # type: ignore[union-attr]
        out[axis] = {k: len(v) for k, v in out[axis].items()}  # type: ignore[union-attr]
    return out


def info_dict(info: SourceInfo) -> dict:
    return asdict(info)
